### DISCUSSION TITLE
Mirroring using Contour in Kubernetes

### DISCUSSION THREAD

**Discussion by mpsanj** [projectcontour/contour#4000] [Q&A]
We have a prod env(cluster-a) where we have a service running which is exposed to the public via HTTPProxy

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: aserver
  namespace: ees
  annotations:
    kubernetes.io/ingress.class: contourpub
spec:
  virtualhost:
    fqdn: "example.com"
  routes:
    - conditions:
      - prefix: /v1/app
      services:
        - name: event-serv
          port: 80
```
now we wanna mirror the traffic from example.com to another service running in another cluster lets call it cluster-b.

Added an externalname service to point event-serv2 service of cluster-b in cluster-a.

```
apiVersion: v1
kind: Service
metadata:
  name: event-serv2
  namespace: ees
spec:
  type: ExternalName
  externalName: example-stage-testing.com
  ports:
  - port: 80
```
And then added the mirroring rule in httpproxy config

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: aserver
  namespace: ees
  annotations:
    kubernetes.io/ingress.class: contourpub
spec:
  virtualhost:
    fqdn: "example.com"
  routes:
    - conditions:
      - prefix: /v1/app
      services:
        - name: event-serv
          port: 80
        - name: event-serv2
          port: 80
          mirror: true
```
event-serv2 is throwing 404 as per the grafana graph and event-serv is serving 200 as before, the problem I'm seeing in that in cluster-b for service example-stage-testing.com, the host or fqdn is different ie it is example-stage-testing.com and not example.com, i believe its cause of it, its being throwing 404. Well I maybe wrong with whole concept of mirroring using contour, please advice how to proceed to achieve mirroring in the above scenario.

Thank You !
