### DISCUSSION TITLE
HTTPProxy wildcard route priorities

### DISCUSSION THREAD

**Discussion by stasmir** [projectcontour/contour#4985] [Q&A] [answered]
Hi all,

The question is how to determine priority for wildcard routes defined for HTTPProxy.
For example, there are three paths:

1. /api/data-stores
2. /api/data-stores/@dataStoreId/data-sets
3. /api/data-stores/@dataStoreId/data-sets/@dataSetId/versions
4. and all other paths

The intention is to define the following routes:

1. Requests by the following path prefix '/api/data-stores' should be routed to QueryService
2. Requests by the following path prefix '/api/data-stores/*/data-sets' should be routed to QueryService
3. Requests by the following path prefix '/api/data-stores/*/data-sets/*/versions' should be routed to CommandService
4. Requests by other paths should be routed to UIService

So, could you please advise on how can I achieve the desired behavior?
In this case 
GET /api/data-stores should be routed to QueryService
GET /api/data-stores/123/data-sets should be routed to QueryService too
POST /api/data-stores/123/data-sets/456/versions should be routed to CommandService
GET /ui should be routed to UIService

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: ingress-route-prod-main
  namespace: 123
  annotations:
    projectcontour.io/ingress.class: contour
  labels:
    cluster: prod
spec:
  routes:
    - services:
        - name: QueryService
          port: 80
      conditions:
        - prefix: /api/data-stores  # this route will have the highest priority and below routes will be ignored. But what priority will be if the prefix is /api/data*stores

    - services:
      - name: QueryService
        port: 80
      conditions:
        - prefix: /api/data-stores/*/data-sets

    - services:
      - name: CommandService
        port: 80
      conditions:
        - prefix: /api/data-stores/*/data-sets/*/versions

    - services:
      - name: UIService
        port: 80
      conditions:
        - prefix: /

```
