### DISCUSSION TITLE
using globalExtAuth with Gateway API

### DISCUSSION THREAD

**Discussion by h-otter** [projectcontour/contour#5435] [Q&A] [answered]
I have configured ExtensionService and Gateway APIs as below.

```yaml
kind: ContourDeployment
apiVersion: projectcontour.io/v1alpha1
metadata:
  name: contour
  namespace: projectcontour
spec:
  runtimeSettings:
    globalExtAuth:
      extensionRef:
        namespace: default
        name: testserver
      failOpen: false
      responseTimeout: 1s
---
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: contour
spec:
  controllerName: projectcontour.io/gateway-controller
  parametersRef:
    kind: ContourDeployment
    group: projectcontour.io
    name: contour
    namespace: projectcontour
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: contour
spec:
  gatewayClassName: contour
  listeners:
    - name: kuard
      hostname: kuard.example.com
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: kuard-example-com-tls
            kind: Secret
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: contour
  hostnames:
  - "kuard.example.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - kind: Service
      name: kuard
      port: 80
```

However, kuard service is not protected by globalExtAuth.
I confirmed that using HTTPProxy works globalExtAuth.
Doesn't GatewayAPI support globalExtAuth?

Thank you!
