### DISCUSSION TITLE
can we use envoy filters on HTTPProxy object?

### DISCUSSION THREAD

**Discussion by themkarimi** [projectcontour/contour#5951] [Q&A] [answered]
I am curious whether it is possible using envoy filters in a httpproxy object. it would help a lot especially when it comes to using lua filter.
i mean something like this: 
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: example
spec:
  virtualhost:
    fqdn: example.com
  routes:
    - services:
        - name: my-service
          port: 80
      filters:
        - name: envoy.filters.http.lua
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
            inline_code: |
              function envoy_on_request(request_handle)
                -- Your Lua script logic for request handling
              end
```
