### DISCUSSION TITLE
How to block a path ?

### DISCUSSION THREAD

**Discussion by rgarrigue** [projectcontour/contour#6225] [Q&A] [answered]
Hi,

I'm wondering what's the best way to block a path using a httpproxy ? I've a quite basic usage, like

```yaml
spec:
  routes:
  - services:
    - name: api-analytics
      port: 8080
  virtualhost:
    fqdn: analytics.company.com
    tls:
      secretName: api-analytics-tls
```

I'd like to prevent access to (prometheus) `/metrics` . I guess I could route /metrics to a nginx proxy answering nothing, but there ought to be a better way ?

**Comment by tsaarni** [comment, marked as answer]
You could try adding "direct responses" under routes

```yaml
spec:
  routes:
    - conditions:
        - prefix: /metrics
      directResponsePolicy:
        statusCode: 404
```
