### DISCUSSION TITLE
Deploy Contour using Helm chart on AWS EKS IPv6 with a NLB

### DISCUSSION THREAD

**Discussion by rgarrigue** [projectcontour/contour#7052] [Q&A]
Hello

I've been using Contour on IPv4 EKS clusters with AWS NLB for 2 years. Niw I'm trying to deploy it on an IPv6 EKS. Using bitnami Helm chart v19.5.13. 

So far I got everything seemingly running: pods are ok, NLB is here, but can't reach my test service : nmap says port 80 & 443 are closed (on NLB's hostname as well as test-service.company.cloud)

My values are

``` yaml
contour:
  extraArgs:
    - "--stats-address=::"
    - "--envoy-service-http-address=::"
    - "--envoy-service-https-address=::"

envoy:
  logLevel: trace
  service:
      # loadBalancerClass: eks.amazonaws.com/nlb
      ipFamilyPolicy: SingleStack
      ipFamilies:
        - IPv6
```

I've been trying any combination of parameters that seemed to make sense, not better. I also manually fiddled with the NLB, to switch to DualStack, not better either.

![image](https://github.com/user-attachments/assets/f450b5bf-93ae-45da-afd6-a489eee033de)

Still closed.

![image](https://github.com/user-attachments/assets/91ef5cb7-6f5e-4e1e-af7c-e71b823e6f5a)

Anyone got a working example or something I could try please ?
