### ISSUE TITLE
Add support to add Content-Security-Policy and Strict-Transport-Security headers

### ISSUE THREAD

**Issue by SmoothMaverick** [projectcontour/contour#1064]
I would like to add response headers to satisfy our security requirements.

This is related to https://github.com/heptio/contour/issues/70

With ingress-nginx, I could add a configuration snippet:
```yaml
nginx.ingress.kubernetes.io/configuration-snippet: >-
    add_header Content-Security-Policy "default-src 'self';";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
```

I would like to do something similar in IngressRoute:
```yaml
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: example
spec:
  virtualhost:
    fqdn: example.com
  headers:
   - header: Content-Security-Policy
      value: >
        "default-src 'self'"
   - header: Strict-Transport-Security
      value:  >
        "max-age=31536000; includeSubDomains" always
  routes:
    - match: /
      services:
        - name: app
          port: 80
```

**Comment by davecheney** [comment]
Thank you for raising this issue.

I am marking this as needs a design document because the form of the IngressRoute yaml must be agreed upon before starting work.

From your use case it seems to me that HSTS is a property of the virtualhost, not any particular route. Rather than specifying this as a header, I'd like to see a parameter, something like 

```
spec:
  virtualhost:
    name: foo.example.com
    tls:
      hsts: true
```
This should probably live inside the `tls:` block because as I understand it HSTS only makes sense on TLS enabled sites and on non TLS enabled sites the headers transmitted back to the client are not trusted.

Going futher, why shouldn't we enable this for everyone by default, and make the field `hsts: false` if they do not want to send the header?

**Comment by SmoothMaverick** [comment]
Can you point me where I should look for how to provide a design document? Thank you.

**Comment by davecheney** [comment]
Please see the template in the design/ folder.  Git log will show you the PRs that added the other entries in that folder. 

Thank you

**Comment by davecheney** [comment]
Assigning to the 0.14 milestone for prioritisation tomorrow. This might get bumped to a later milestone, but i’d like to see this included for Contour 1.0

**Comment by davecheney** [comment]
I have an update on this issue. Sadly the 0.15 cycle closes next week. 0.15 is our last development cycle before the 1.0 freeze. At this point this feature will not make the 1.0 cut. I am moving it to the unplanned milestone to revisit after Contour 1.0 ships in November.

**Comment by JTarasovic** [comment]
> Going futher, why shouldn't we enable this for everyone by default, and make the field hsts: false if they do not want to send the header?

We do always set this header in this manner; however, it would mean users would have to change configs on upgrade to maintain existing behavior. Also, some organizations may not want to include subdomains or may want to use a smaller max-age.

**Comment by jpeach** [comment]
@jpeach to verify whether you can do this with header rewrite support.

**Comment by jpeach** [comment]
In Contour 1.2, you can do this:

```
apiVersion: projectcontour.io/vi
kind: HTTPProxy
metadata:
  name: example
spec:
  virtualhost:
    fqdn: example.com
  routes:
  - services:
    - name: app
      port: 80
      responseHeadersPolicy:
        set:
        - name: Content-Security-Policy
          value: "default-src 'self'"
        - name: Strict-Transport-Security
          value: max-age=31536000; includeSubDomains
```
