### ISSUE TITLE
Add support for external client certificate validation (mTLS)

### ISSUE THREAD

**Issue by uablrek** [projectcontour/contour#1090]
**Describe the solution you'd like**

Enable client certificate validation for external clients ([mTLS](https://en.wikipedia.org/wiki/Mutual_authentication))

Since mTLS is done for a virtual server, not a path, annotations in service manifests can not be used. Annotations in the `Ingress` manifest would be possible but be awkward. So the client validation configuration will only be available in the `IngressRoute` objects.

Example;
```yaml
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: www
  namespace: default
spec:
  virtualhost:
    fqdn: foo.com
    tls:
      secretName: server-secret
      clientValidation:
        secretName: client-secret
  routes:
    - match: /
      services:
        - name: s1
          port: 80
```

**Anything else you would like to add:**

See also #433 

Relevant envoy documentation; https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/auth/cert.proto.html?highlight=require_client_certificate

Example;
```yaml
      tls_context:
        require_client_certificate: true
        common_tls_context:
          validation_context:
            verify_certificate_spki: j1fFFSBuF7S/Hzk5xsIq7N7wvVm8xdMpMnt0OUsz5rs=
```

In the example Subject Public Key Information (SPKI) is used to validate the client certificate. This does not have to be secret but is generated outside the cluster without any risk of exposing the private key and can be specified in clear text in the annotation.

The spki is generated as described in the envoy doc with;
```
openssl x509 -in default/cert/kahttp.crt -noout -pubkey \
  | openssl pkey -pubin -outform DER \
  | openssl dgst -sha256 -binary \
  | openssl enc -base64
```

**Environment:**
N/A

**Comment by davecheney** [comment]
Thank you for raising this issue. At the moment there is no plan to add mTLS between Envoy and the backend pod. I am marking this issue as needs-product for input from our product managers.

**Comment by uablrek** [comment]
This is *not* about mTLS between Envoy and the backend POD.

It is about providing the possibility to require that an client outside k8s authenticate itself with a client certficate.

The "downstream" term I got from the Envoy documentation https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/terminology

**Comment by davecheney** [comment]
I'm sorry I misunderstood your request, Envoy's nomenclature is unusual.

Sadly the answer is the same, I'll have to punt this to our PM's for direction on the priority of this enhancement.

**Comment by uablrek** [comment]
Yeah, I also think the Envoy nomenclature is backwards :smiley: I even drew a picture to have in front of me when working with Envoy. I change the title to avoid further misunderstandings.

**Comment by uablrek** [comment]
The client certificate is not forwarded from Envoy to the backend POD (I got that wrong) but envoy should forward client certificate details; 

```
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
...
          forward_client_cert_details: SANITIZE_SET
```

This makes Envoy insert a header like;
```
X-Forwarded-Client-Cert: [Hash=f1a0b3b8dc14b5449cff1a81ebbf3df10078e6539ff9a2cef32c31e550b19e3c]
```

The backend POD can use this for further client validations. To generate this hash from the client certificate with `openssl` do;
```
openssl x509 -noout -fingerprint -sha256 -inform pem -in default/cert/kahttp.crt
SHA256 Fingerprint=F1:A0:B3:B8:DC:14:B5:44:9C:FF:1A:81:EB:BF:3D:F1:00:78:E6:53:9F:F9:A2:CE:F3:2C:31:E5:50:B1:9E:3C
```
