### ISSUE TITLE
config: sane defaults for envoy

### ISSUE THREAD

**Issue by glerchundi** [projectcontour/contour#1375]
I came across [this PR](https://github.com/envoyproxy/envoy/pull/8001) from @PiotrSikora and thought it would be interesting to corroborate if those 'best practices' are being followed in Contour.

**Comment by davecheney** [comment]
Thank you for this. There is some very useful information here.

Scheduling for rc1 to review and see what if any changes we should take from this document.

**Comment by ravilr** [comment]
Also, this https://github.com/envoyproxy/envoy/issues/6323 . Can we configure tcp keepalive options to tear down half open connections for both Contour grpc management server upstream cluster and also (optionally may be) for all K8s service upstream clusters in envoy config programmed by Contour.

**Comment by youngnick** [comment]
Building a todo list for this one:

For the TCP keepalive settings, that is 100% worth doing, I've made separate issue (#1744)  for that one, as it might possibly be related to another issue.

TCP Proxies

- [ ] overload manager
- [ ] listener buffer limits to 32KiB
- [ ] cluster buffer limits to 32KiB

HTTP Proxies should additionally configure

- [ ] connection maanager use_remote_address to true (see header_sanitizing for details)
- [ ] connect_timeout 15s
- [ ] per_connection_buffer_limit_byes to 32 KiB
- [ ] HTTP/2 maximum concurrent streams limit to 100
- [ ] HTTP/2 initial stream window size limit to 64KiB
- [ ] HTTP/2 initial connection window size limit to 1MiB

YAML example:
```yaml
overload_manager:
  refresh_interval: 0.25s
  resource_monitors:
  - name: "envoy.resource_monitors.fixed_heap"
    config:
      # TODO: Tune for your system.
      max_heap_size_bytes: 2147483648 # 2 GiB
  actions:
  - name: "envoy.overload_actions.shrink_heap"
    triggers:
    - name: "envoy.resource_monitors.fixed_heap"
      threshold:
        value: 0.95
  - name: "envoy.overload_actions.stop_accepting_requests"
    triggers:
    - name: "envoy.resource_monitors.fixed_heap"
      threshold:
        value: 0.98

static_resources:
  listeners:
  - address:
      socket_address: { address: 127.0.0.1, port_value: 443 }
    listener_filters:
    - name: "envoy.listener.tls_inspector"
      typed_config: {}
    per_connection_buffer_limit_bytes: 32768 # 32 KiB
    filter_chains:
    - filter_chain_match:
        server_names: ["example.com", "www.example.com"]
      tls_context:
        common_tls_context:
          tls_certificates:
          - certificate_chain: { filename: "example_com_cert.pem" }
            private_key: { filename: "example_com_key.pem" }
      filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          use_remote_address: true
          common_http_protocol_options:
            idle_timeout: 840s
          http2_protocol_options:
            max_concurrent_streams: 100
            initial_stream_window_size: 65536 # 64 KiB
            initial_connection_window_size: 1048576 # 1 MiB
          route_config:
            virtual_hosts:
            - name: default
              domains: "*"
              routes:
              - match: { prefix: "/" }
                route: { cluster: service_foo }
  clusters:
    name: service_foo
    connect_timeout: 15s
    per_connection_buffer_limit_bytes: 32768 # 32 KiB
    hosts:
      socket_address:
        address: 127.0.0.1
        port_value: 8080
    http2_protocol_options:
      max_concurrent_streams: 100
      initial_stream_window_size: 65536 # 64 KiB
      initial_connection_window_size: 1048576 # 1 MiB
```
