### ISSUE TITLE
Multiple ingresses for the same host / domain (kube-lego + company application)

### ISSUE THREAD

**Issue by cmaloney** [projectcontour/contour#144]
Lay out all the resources at the top, and then have some questions down at the bottom for what is the behavior, and what is the expected behavior in contour (Are things bugs to fix vs. implemented as designed and there is a simple workaround)

I have two different ingress specs:

1. kube-lego for handling the lets encrypt challenges
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
    kubernetes.io/ingress.class: contour
    kubernetes.io/tls-acme-challenge-endpoints: "true"
  creationTimestamp: 2018-01-12T21:38:23Z
  generation: 1
  name: kube-lego-nginx
  namespace: kube-lego
spec:
  rules:
  - host: application-smoke1.example.com
    http:
      paths:
      - backend:
          serviceName: kube-lego-nginx
          servicePort: 8080
        path: /.well-known/acme-challenge
status:
  loadBalancer: {}
```

2. One to point all traffic to my app backend using the "default backend" form of the ingress spec
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: stage-application-smoke-1-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - application-smoke1.example.com
    secretName: stage-application-smoke-1-secret
  backend:
    serviceName: stage-application-smoke-1-service
    servicePort: 5117
```

If i look at envoy's admin ui (port 9001 on the envoy container in the contour pod) I see only one route for the domain for the kube-lego ingress, and none for my default backend
```json
{"name":"application-smoke1.example.com","domains":["application-smoke1.example.com"],"routes":[{"match":{"prefix":"/.well-known/acme-challenge"},"route":{"cluster":"kube-lego/kube-lego-nginx/8080"}}]}
```

1. Is this expected behavior? My expectation was that contour would to make an http route for the domain which points the `/.well-known/acme-challenge` to the kube-lego pod, and all other paths to my default backend.
2. Would moving to specifying paths + host rules always fix this (Just making path / point to the app I want)?
3. Would SSL/SNI with contour work in the "passing to a default backend only" case if the kube-lego container didn't exist?
