### ISSUE TITLE
Trailing slash on prefix match stripped

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#1597]
```yams
spec:
- routes:
  - conditions:
     - prefix: "/a/"
```
Will be translated into a prefix match of `/a`, the trailing slash will be stripped.

**Comment by davecheney** [comment]
Thinking about this some more I think we may have to revise how prefix merging works.

I made the classic mistake of assuming URLs were directory paths when I insisted on using `path.Join`. This mistake meant the only way to delegate `prefix: /users/a`, that is all users starting with `a` is a include condition `prefix: /users/a` and no prefix condition on the included route. If the user tried to combine `prefix: /users/a` with `prefix: /` the result would be `prefix: /users/a/` not `prefix: /users/a`.

I suggest we do the following.

1. Stop using path.Join. That was my bad, I wasn't thinking.
2. merge prefix conditions by concatenation, `prefix: /foo` and `prefix: /bar` would become `prefix: foo/bar`, but `prefix: /foo` and `prefix: bar` would become `prefix: /foobar`.
3. We probably need to do some clever cleaning of the resulting url`, prefix: /` and `prefix: /foo` should not become `prefix: //foo`. However `prefix: /` and `prefix: /foo/` should merge to `prefix: /foo/`, the trailing slash should not be stripped.

**Comment by stevesloka** [comment]
What makes it difficult is if you have a path `prefix: /foo` and `prefix: /` should that become `/foo` or `/foo/`? 

The logic we have now is that if you do not specify a path condition, it defaults to "/", my thought was to make that field optional so users wouldn't have to explicitly add the "condition" field all over the place. 

I never thought of merging conditions like in your example `prefix: /foo and prefix: bar would become prefix: /foobar.` We need to be careful that we keep the delegation model working properly. 

I always thought we'd only allow full paths separated by `/`, but allowing the previous example does make it more flexible at the end given users who might need that additional complexity, but it does add to the UX problem.

**Comment by davecheney** [comment]
> What makes it difficult is if you have a path prefix: /foo and prefix: / should that become /foo or /foo/?

Good question. I think under the current logic and my proposed change `prefix: /foo` and `prefix: /` would result in `prefix: /foo/`. 

> The logic we have now is that if you do not specify a path condition, it defaults to "/", my thought was to make that field optional so users wouldn't have to explicitly add the "condition" field all over the place.

That is true. Perhaps this isn't as bad as I'm thinking. If someone wants to do `include.conditions.prefix: /users/a, namespace: a-users` then the child route should have no prefix so it can register as `prefix: /users/a`

> I never thought of merging conditions like in your example prefix: /foo and prefix: bar would become prefix: /foobar. We need to be careful that we keep the delegation model working properly.

> I always thought we'd only allow full paths separated by /, but allowing the previous example does make it more flexible at the end given users who might need that additional complexity, but it does add to the UX problem.

Maybe we need to make that more explicit -- all `prefix:` conditions _must_ start with a `/`. Something like that.

**Comment by stevesloka** [comment]
In my head having each prefix condition start with a `/` makes sense. There should probably be a way to make the condition still be specified, even if they specify the default (e.g. "/"), meaning you could either leave the field off the struct, or define it with the default value.  

So the first question to decide on is if we default a prefix condition with `/` or not. So in your example, a user would either not define a child prefix, or define it to be an empty string:

> include.conditions.prefix: /users/a, namespace: a-users then the child route should have no prefix so it can register as prefix: /users/a

**Comment by davecheney** [comment]
> So the first question to decide on is if we default a prefix condition with / or not. So in your example, a user would either not define a child prefix, or define it to be an empty string:

I think we can relax this a little.

At the moment you can write, in ingress v1:
```
spec:
  backend: ...
```
And send all traffic to the default backend. You can do the same in ingress v1 without the default backend with
```
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: test
          servicePort: 80
```
So it's totally valid to give a route, with no conditions, and one or more services to send the traffic too.

We can do this in httpproxy, just don't have any conditions.
```
spec:
  routes:
  - services:
      ...
```
At the moment we document that you need at least one condition per route

> Lines 8-9: Each HTTPProxy must have one or more routes, each of which must have a condition to match against (e.g. prefix: /) and then one or more services which will handle the HTTP traffic.

but this isn't true -- we have tests that assert that. 

So maybe the answer is to change the documentation to say something like

> Each HTTPProxy must have one or more routes, each of which may have one or more conditions to match against (e.g. prefix: /) and then one or more services which will handle the HTTP traffic.

**Comment by youngnick** [comment]
I'll update the docs to match up with the tests. Something like:
> Each HTTPProxy must have one or more routes, each of which must have one or more services which will handle the HTTP traffic. In addition, each route may have one or more conditions to match against.

If we do that, and implement #1628 including full tests, then we should be able to handle all of the cases.

**Comment by youngnick** [comment]
Blocked on #1628.

**Comment by youngnick** [comment]
Note for later: full tests should include:
- [ ] included with `prefix: /prefix`, and no prefix on the included HTTPRoute
- [ ] included with `prefix: /prefix`, and `prefix: /` on the included HTTPRoute
- [ ] included with `prefix: /prefix`, and `prefix: /other` on the included HTTPRoute
- [ ] included with `prefix: /foo` and `prefix: bar` should fail.

**Comment by youngnick** [comment]
Okay, after looking into this for a bit, here's what I've found:
- it *is* currently possible to have a HTTPProxy with no conditions.
- In the case you don't have a prefix condition specified, and your HTTPProxy is included with a prefix, the path you end up matching *must* end with a `/`, as the prefix condition defaults to `/` if not specified. 

So, if you are including a proxy with a prefix of `/foo/bar`, the service will currently always match `/foo/bar/`. We have no tests to verify this case, and changing this will be reasonably substantial.
Also note that the example in the HTTPProxy docs (`httpproxy-inclusion-samenamespace.yaml`) is incorrect, the included service with prefix `/` will be available at `/service2/`, not `/service2` currently.

Fixing the 'trailing slash stripped' problem is straightforward, I have a PR for that. But adding the ability to include a prefix and not have the included service end up with a path that starts with a `/` is a bit more work, but more importantly introduces a very unexpected possible behaviour.

Specifically, here's the yaml the new use case would entail in its basic form:

```yaml
# httpproxy-inclusion-samenamespace.yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: include-root
  namespace: default
spec:
  virtualhost:
    fqdn: root.bar.com
  includes:
  # Includes the /service2 path from service2 in the same namespace
  - name: www
    namespace: default
    conditions:
    - prefix: /service2
  routes:
    - conditions:
      - prefix: /
      services:
        - name: s1
          port: 80
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: service2
  namespace: default
spec:
  routes:
    - services: # matches /service2
        - name: s2
          port: 80
---

```

Note that this use case does have one big drawback: If there is more than one route in the included HTTPProxy, whether they work as expected will be dependent on the order they are listed in the file (I think, since we will supply the eventual routes to Envoy in that order, and Envoy does short-circuit matching, I believe).

For example, what would happen in this case?
```yaml
# httpproxy-inclusion-samenamespace.yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: include-root
  namespace: default
spec:
  virtualhost:
    fqdn: root.bar.com
  includes:
  # Includes the /service2 path from service2 in the same namespace
  - name: www
    namespace: default
    conditions:
    - prefix: /service2
  routes:
    - conditions:
      - prefix: /
      services:
        - name: s1
          port: 80
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: service2
  namespace: default
spec:
  routes:
    - services:  # matches /service2 ? what about the next route?
        - name: s2
          port: 80
    - conditions:
      - prefix: /blog # matches /service2/blog
      services:
        - name: blog
          port: 80
```
Most of the time this is not a big deal, but when it is, it will be a very big deal.

So, we have two options:
- Leave the behaviour as it is, and document that *included HTTPProxies with no conditions* will have a `/` appended to their prefix.
- Add this new use case to allow the `/` not to be added, and document the complexity around ordering in that case.

I'm kind of inclined to do the former. @davecheney and @stevesloka, thoughts?
