### ISSUE TITLE
internal/dag: Duplicate prefix conditions should be invalid

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1611]
If a set of conditions is defined in an include or route, duplicate `prefix` conditions should mark the `Proxy` status as invalid. 

Example:
```
spec:
  routes:
  - conditions:
    - prefix: /
    - prefix: /foo
    - prefix: /bar
```
