### ISSUE TITLE
no matches for kind "HTTPProxy" in version "projectcontour.io/v1"

### ISSUE THREAD

**Issue by bndw** [projectcontour/contour#1615]
**What steps did you take and what happened:**
I'm new to Contour and following the README to get stared. I'm attempting to create an `HTTPProxy` as defined in [Ingress to HTTPProxy](https://github.com/projectcontour/contour/blob/master/docs/httpproxy.md#ingress-to-httpproxy)

```yaml
# httpproxy.yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: basic
spec:
  virtualhost:
    fqdn: foo-basic.bar.com
  routes:
    - conditions:
      - prefix: /
      services:
        - name: s1
          port: 80
```

When applying this I receive the following error:
```sh
kubectl apply -f svc1.yaml
deployment.apps/svc1 created
service/svc1 created
error: unable to recognize "svc1.yaml": no matches for kind "HTTPProxy" in version "projectcontour.io/v1"
```

Here's the full `svc1.yaml` file I'm using
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc1
  labels:
    app: svc1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: svc1
  template:
    metadata:
      labels:
        app: svc1
    spec:
      containers:
      - image: nginx:alpine
        name: svc1
---
apiVersion: v1
kind: Service
metadata:
  name: svc1
  labels:
    app: svc1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: svc1
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: svc1
  labels:
    app: svc1
spec:
  virtualhost:
    fqdn: svc1.example.com
  routes:
    - conditions:
      - prefix: /
      services:
        - name: svc1
          port: 80
```

**What did you expect to happen:**
An HTTPProxy to be created

**Environment:**

- Contour version:
I used the README instructions:
```
kubectl apply -f https://projectcontour.io/quickstart/contour.yaml
```
Following that URL it looks like
```
spec:
  group: contour.heptio.com
  version: v1beta1
```

- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-19T13:59:47Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
kops version 1.13.2
- Cloud provider or hardware configuration:
AWS
- OS (e.g. from `/etc/os-release`):
