### ISSUE TITLE
Redirect: adding a redirect (301 or 302) option in ingressroute / httpproxy

### ISSUE THREAD

**Issue by vincentdeity** [projectcontour/contour#1627]
**Describe the solution you'd like**
The ingressroute / httpproxy should be able to support a match and then redirect with either a 301 or 302 to an http or https destination

Something like:
```
spec:
  routes:
  - match: /
    services:
    - name: awesome-service-01
      port: 1000
   - match: /redirectpath
    redirect:
      method: 301
      destination: https://externalawesomewebsite.com
  virtualhost:
    fqdn: awesomehost.tld
```

**Anything else you would like to add:**
The use case would be that for example if you have a website pointed to the ingress you can now also do redirects in contour. This would prevent you from having to spin up another container inside for the redirect (nginx for example).

**Environment:**

- Contour version: v1.0.0-beta.1
- Kubernetes version: (use `kubectl version`): v1.14.6-gke.1
- Kubernetes installer & version: N/A (Google)
- Cloud provider or hardware configuration: GKE
- OS (e.g. from `/etc/os-release`): GKE

**Comment by danramteke** [comment]
This would be nice for dealing with redirecting 'example.com` to `www.example.com` or vice-versa. Currently, I'm running an nginx container whose only job is to redirect all requests to `www.example.com`.

**Comment by davecheney** [comment]
Thank you for your feature request. I think I understand the use case. At the moment we're deep in feature freeze in preparation for Contour 1.0. I've assigned this to the backlog for prioritisation for a future release.

**Comment by PeopleRange** [comment]
Also needed from an SEO standpoint with the http to https or root_uri to www.root_uri

**Comment by jpeach** [comment]
> On 24 Jan 2020, at 2:59 am, PeopleRange <notifications@github.com> wrote:
> 
> Also needed from an SEO standpoint with the http to https or root_uri to www.root_uri

When TLS is enabled on a root HTTPProxy, the http -> https redirect is automatically provisioned.

https://projectcontour.io/docs/v1.1.0/httpproxy/#tls

**Comment by stevesloka** [comment]
A common use-case for this is redirecting `www.stevesloka.com` --> `stevesloka.com` which isn't the same as the tls redirect @jpeach

**Comment by PeopleRange** [comment]
@jpeach Thank You for the link to the documentation. I already have this bit implemented my experience comes from Nginx which common practice especially if using hsts headers is to 301 redirects to http then 301 redirect to the canonical domain (If Any).

**Comment by bgagnon** [comment]
We have another use case here for Intranet websites -- users often rely on the DNS search path so they type "foo" instead of "foo.company.org". A 3xx redirect from the short form to the long form is often necessary. Being able to do this as the ingress proxy layer is more convenient than implementing this code in every web app / backend service.

**Comment by jpeach** [comment]
From https://github.com/projectcontour/contour/issues/3014, some kinds of redirect will want to strip the query string. The example from that issue is:
```
spec:
  virtualhost: foo.example.com
  routes:
    - redirect:
        destination: bar.example.com  # required
        include_query_string: false      # default 
```
