### ISSUE TITLE
support for networking.k8s.io/v1beta1.Ingress

### ISSUE THREAD

**Issue by ghouscht** [projectcontour/contour#1633]
**Describe the solution you'd like**
It looks like contour currently only supports the deprecated `extensions/v1beta1.Ingress` API (or the CRD based API). See https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ for more information.

We're already in progress of migrating our resources to the new `networking.k8s.io/v1beta1.Ingress` API and have some dev. clusters where the old APIs are disabled in the api-server through the `runtime-config` flag. On these clusters contour is not working properly because of the missing API:
```
E1004 05:28:35.486715       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a/tools/cache/reflector.go:98: Failed to list *v1beta1.Ingress: the server could not find the requested resource
```

**Anything else you would like to add:**
Ingress objects which are persited through `networking.k8s.io` API can also be retrieved via the old API (if not disabled 😄) so this can be considered as "feature enhancement request".

**Environment:**

- Contour version: `master`
- Kubernetes version: (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T16:51:36Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
```
kubeadm version: &version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T16:58:27Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- relevant api-server flag:
```
--runtime-config=apps/v1beta1=false,apps/v1beta2=false,extensions/v1beta1/daemonsets=false,extensions/v1beta1/deployments=false,extensions/v1beta1/replicasets=false,extensions/v1beta1/networkpolicies=false,extensions/v1beta1/podsecuritypolicies=false,extensions/v1beta1/ingresses=false
```

Thanks in advance and let me know if you need further info and/or help.

**Comment by davecheney** [comment]
Thank you for raising this issue, is this a duplicate of #973?

**Comment by ghouscht** [comment]
Yes, this didn't pop up with my search queries - sorry.

**Comment by davecheney** [comment]
Not a problem. I'm going to close the other issue as yours better describes the problem.

**Comment by davecheney** [comment]
Marking tentatively to see if its possible to do a quick hack that will avoid duplicating all of the logic for ingress v1 and beta1

**Comment by youngnick** [comment]
Okay, I've had a look into this this afternoon, and here's where we are at:

- the `networking.k8s.io/v1beta1.Ingress` kind was introduced in Kubernetes 1.14.
- the `extensions/v1beta1.Ingress` kind is deprecated but will not be removed until Kubernetes 1.20 (unless it slips again).
- we know we have users running versions < Kubernetes 1.14

Because of that, to fix this problem, unless one of those things changes, we will need to:
1. Duplicate all the code that uses `extensions/v1beta1.Ingress` (that is, all the code that touches an Ingress), to support `networking.k9s.io/v1beta1.Ingress`.
2. Put some code in to programmatically determine what Ingress objects are available and only check those. (Theoretically possible, but no idea how hard this is).
3. Do this whole thing over again once `networking.k8s.io/v1.Ingress` is released.

Because of this, I don't think this is practical for us to do before our 1.0 milestone. My recommendation is:
- we mark this work as for post-1.0
- at that time, we check over our Kubernetes version matrix and decide what we're going to do about Ingress.

I really appreciate you bringing this up @ghouscht, it's a great forcing function for us to really look deeply into the api versioning problem.

**Comment by stevesloka** [comment]
This only matters if folks disable the `extensions/v1beta1` api groups in the API server, otherwise, everything works as-is, meaning you can apply an Ingress object of type `networking.k8s.io/v1beta1` and it all just works. 

We can get the server version easily from the client, then use that to determine which watch gets applied against which api group. I've done this before on the Elastic operator switching over from TPRs to CRDs.

The only remaining bit would be to address the internal code issues. If we could cast the code to a type that might be an easy stop-gap to not copy-pasting the code for the move from extensions/v1beta1 to networking.k8s.io/v1beta1 as the types are the same. 

The move to networking.k8s.io/v1 will need to be new code since the types will change. 

If you want to test this in kind, here's a config file that you can apply:
```
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "0.0.0.0"
  - containerPort: 443
    hostPort: 443
    listenAddress: "0.0.0.0"
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      runtime-config: "apps/v1beta1=false,apps/v1beta2=false,extensions/v1beta1/ingresses=false,extensions/v1beta1/daemonsets=false,extensions/v1beta1/deployments=false,extensions/v1beta1/replicasets=false,extensions/v1beta1/networkpolicies=false,extensions/v1beta1/podsecuritypolicies=false"
```

Then create a cluster: 
```
kind create cluster --name=gimbal --config=$HOME/.kube/kind.config.yaml  --image=stevesloka/kind-node:v1.16.1 
```

For timing, can we wait till after 1.0? 1.17 drops on December 9 and we've got kubecon in the middle + holidays. Feels bad to have Contour not work with a release of k8s.
