### ISSUE TITLE
api,internal/dag: move route.service.strategy to route

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#1668]
As part of buying insurance for #1119, similar to #1630, move route.service.strategy to route.strategy. Bonus points for calling this `route.loadbalancingStrategy`

**Comment by davecheney** [comment]
I'm working on this now and looking at renaming
```
spec:
  routes:
  - services:
     - name: foo
       port: 8080
       strategy: w00t
```
to
```
spec:
  routes:
  - loadBalancerPolicy:
       strategy: w00t
     services:
     - name: foo
        port: 8080
```
