### ISSUE TITLE
Add TCP Keepalives to Envoy -> Contour xDS comms

### ISSUE THREAD

**Issue by youngnick** [projectcontour/contour#1744]
By default, Envoy will not tear down half open TCP connections for xDS, and will believe that it's connected.
See https://github.com/envoyproxy/envoy/issues/6323 and https://github.com/envoyproxy/envoy/issues/5173 for more background.

We should configure tcp keepalives for the Envoy -> Contour connection to ensure that half-open connections are flushed.

A sample config from envoyproxy#5173:
```yaml
    static_resources:
      clusters:
      - name: {{ cluster_name }}_ads
        connect_timeout: { seconds: 1 }
        dns_refresh_rate: { seconds: 10 }
        type: STRICT_DNS
        ...
        upstream_connection_options:
          tcp_keepalive:
            keepalive_probes: 3
            keepalive_time: 30
            keepalive_interval: 5
```

Thanks to @ravilr for noting this one.

It's also possible that #1523 *might* be related to this.
