### ISSUE TITLE
Bug in `contains` header condition

### ISSUE THREAD

**Issue by ledor473** [projectcontour/contour#1751]
**What steps did you take and what happened:**
I first started to test the new HTTPProxy CRD in the release 1.0.0 rc1 because I needed to route based on HTTP Headers.

I first started to test with [`httpproxy-multiple-headers.yaml`](https://github.com/projectcontour/contour/blob/master/site/_docs_1_0/httpproxy.md#multiple-routes) because it was close to what I wanted. It worked perfectly.

I proceed to test with the real data I had by modifying the example to route by UUID in the real header but somehow that didn't work. I was only getting 404 which was pretty strange.

I decided to look at the documentation a little bit more to find that there's not only `contains` but also `exact` and [some more](https://github.com/projectcontour/contour/blob/master/site/_docs_1_0/httpproxy.md#header-conditions). Figured it would be worth a try to use `exact` and surprisingly it worked!

**What did you expect to happen:**
To get routed correctly by UUID when using `contains`

**Anything else you would like to add:**
Turns out the `contains` is implemented as a regex which would require some escaping to work with _some_ values:
https://github.com/projectcontour/contour/blob/3f664fa2b177351dc2d9c2858be50f97743c0fd4/internal/envoy/route.go#L293-L295

**Environment:**

- Contour version: 1.0.0 rc1
- Kubernetes version: (use `kubectl version`): 1.14
- Kubernetes installer & version: EKS
- Cloud provider or hardware configu

**Comment by stevesloka** [comment]
Hey @ledor473, could you provide a sample of the header condition you created to match the contains issue? I'd like to write a test around this with matching sample data.

**Comment by stevesloka** [comment]
I took another look into this and you're right, when I implemented this I overlooked escaping special characters in the regex.

**Comment by ledor473** [comment]
I just realized that I might have been tricked by something else. Seems like I picked a different UUID from when I tested the `contains` vs the `exact` and that only my last route works and not the rest of them 🤔 

I still feel there might be case where the regex will fail and it should be at least be documented but what I haven't found yet is why only my last route works, here's more details:

The HTTPRoute
```yaml
apiVersion: projectcontour.io/v1
  kind: HTTPProxy
  metadata:
    name: test-wgxyca8z
    namespace: default
  spec:
    routes:
    - conditions:
      - header:
          contains: 421bea4c-97b0-4ee4-82fa-0b806f5a695a
          name: x-test
      services:
      - name: kuard-0
        port: 80
    - conditions:
      - header:
          contains: 8c996dbb-ba31-4b29-b170-0d16b0f2c4e7
          name: x-test
      services:
      - name: kuard-1
        port: 80
    - conditions:
      - header:
          contains: 87f8178f-4c78-4029-bc96-adcceba42ff4
          name: x-test
      services:
      - name: kuard-2
        port: 80
    - conditions:
      - header:
          contains: dad6854a-2296-4c80-b4d4-89a67f2a5dd8
          name: x-test
      services:
      - name: kuard-3
        port: 80
    - conditions:
      - header:
          contains: 88819f12-45c4-4674-a0db-32b34f402c46
          name: x-test
      services:
      - name: kuard-4
        port: 80
    virtualhost:
      fqdn: test.com
```

And here's the relevant part of `/config_dump` from Envoy:
```json
    {
      "@type": "type.googleapis.com/envoy.admin.v2alpha.RoutesConfigDump",
      "static_route_configs": [ .... ],
      "dynamic_route_configs": [
        {
          "version_info": "2",
          "route_config": {
            "name": "ingress_http",
            "virtual_hosts": [
              {
                "name": "test.com",
                "domains": [
                  "test.com",
                  "test.com:*"
                ],
                "routes": [
                  {
                    "match": {
                      "prefix": "/",
                      "headers": [
                        {
                          "name": "x-test",
                          "regex_match": ".*88819f12-45c4-4674-a0db-32b34f402c46.*"
                        }
                      ]
                    },
                    "route": {
                      "cluster": "default/kuard-4/80/da39a3ee5e"
                    }
                  }
                ]
              }
            ],
            "request_headers_to_add": [
              {
                "header": {
                  "key": "x-request-start",
                  "value": "t=%START_TIME(%s.%3f)%"
                },
                "append": true
              }
            ]
          },
          "last_updated": "2019-10-21T15:59:17.817Z"
        }
      ]
    }
```
