### ISSUE TITLE
Duplicate prefix conditions included to separate proxies not enforced

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1770]
**What steps did you take and what happened:**
If I create a root proxy which delegates the same prefix to two different proxies in different namespaces, the root proxy is not set to error, but instead are `valid`.

This breaks the multi-team model since the same path is referenced in different namespaces.

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: root
  namespace: projectcontour-roots
spec:
  includes:
  - conditions:
    - prefix: /blog
    name: blogsite
    namespace: projectcontour-marketing
  - conditions:
    - prefix: /blog
    name: defaultsite
    namespace: default
```

![image](https://user-images.githubusercontent.com/1048184/67351093-9fc5b580-f51a-11e9-9b40-e92050e57761.png)
