### ISSUE TITLE
Investigate enabling overload manager for Envoy

### ISSUE THREAD

**Issue by youngnick** [projectcontour/contour#1794]
As mentioned in #1375, Envoy has an overload manager that we should investigate.

It's pretty generic by design, but currently is effectively a memory (that is, heap size) manager. You can configure a maximum heap size, and then different actions to take at different percentages of that heap size.

Sample from the Envoy PR:
```yaml
overload_manager:
  refresh_interval: 0.25s
  resource_monitors:
  - name: "envoy.resource_monitors.fixed_heap"
    config:
      # TODO: Tune for your system.
      max_heap_size_bytes: 2147483648 # 2 GiB
  actions:
  - name: "envoy.overload_actions.shrink_heap"
    triggers:
    - name: "envoy.resource_monitors.fixed_heap"
      threshold:
        value: 0.95
  - name: "envoy.overload_actions.stop_accepting_requests"
    triggers:
    - name: "envoy.resource_monitors.fixed_heap"
      threshold:
        value: 0.98
```
