### ISSUE TITLE
Investigate setting default HTTP/2 options for upstream clusters

### ISSUE THREAD

**Issue by youngnick** [projectcontour/contour#1795]
In #1375, a PR to Envoy suggested setting HTTP/2 options as follows:

```yaml
    http2_protocol_options:
      max_concurrent_streams: 100
      initial_stream_window_size: 65536 # 64 KiB
      initial_connection_window_size: 1048576 # 1 MiB
```
This ticket is to investigate setting these.
