### ISSUE TITLE
Apply standard application labels to Contour deployments

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#1821]
When you are looking at Contour deployments in a Kubernetes cluster, it's not always obvious which release you have. When we generate the deployment YAML, we could apply standard [application labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) such as `app.kubernetes.io/version` to make it more obvious.

As a bonus, Octant appears to use these labels for some kind of object grouping.

**Comment by tthebst** [comment]
I would like to give this a go.

I suppose you don't want any hardcoded values in `example/03-contour.yaml`. So is it enough if you pass `$VERSION` to the `generate-deployment.sh`. This would produce sth like "v1.6.0" or should I strip the "v"

**Comment by jpeach** [comment]
@tthebst I'd prefer to not take a dependency on yq. Maybe we can whack this with sed?

**Comment by tthebst** [comment]
@jpeach editing yaml's with CLI is painful. Especially because its labeling is inconsistent across `example/*.yaml`

My idea would be to add sth like to the examples file where appropriate.

```
  labels:
    app.kubernetes.io/name: NAME
    app.kubernetes.io/version: VERSION
    app.kubernetes.io/part-of: PARTOF
```
This would make it very easy to do `sed` and replace the values with the correct ones when creating the `contour.yaml` file. The drawback is that I would have to edit the `example/` files and I don't know if this acceptable. 
What do you think?

**Comment by jpeach** [comment]
Yeh, in the absence of something like #2088 that's the best we can do I think.

**Comment by jpeach** [comment]
> Yeh, in the absence of something like #2088 that's the best we can do I think.

One thing to try is to set the version to `master` on the main yaml, then sed that to the real version in `make generate`

**Comment by tthebst** [comment]
@jpeach Thanks for the response. Also, do you think it makes sense to use all standard labels
``` 
 labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql-abcxzy
    app.kubernetes.io/version: "5.7.2"1
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: wordpress
    app.kubernetes.io/managed-by: helm
```

Or only use a selection. For example only
```
 labels:
    app.kubernetes.io/name: MySQL
    app.kubernetes.io/version: "5.7.2"
```

**Comment by jpeach** [comment]
I think that selection makes the most sense, "name" and "version" are the most useful, "part-of" could be a useful, but not so sure about it.

**Comment by youngnick** [comment]
I like the idea of having `name` and `version` in the standard label format, it could be that `instance` may be useful down the road to help with multiple-Contours-in-one-cluster usecases, but just adding `name` and `version` is a great start.

Editing the example YAMLs for this purpose is fine. I'd also echo @jpeach and say that it's probably better to set the version to `master` on master, and sed it to the release version when we cut a release. We already do this for container image versions.

**Comment by tthebst** [comment]
@youngnick @jpeach 

I think `part-of` could be used like this. It probably also makes sense to set `app.kubernetes.io/name:` to the same value as `name`

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy
  namespace: projectcontour
  labels:
    app.kubernetes.io/name: envoy
    app.kubernetes.io/part-of: contour
    app.kubernetes.io/version: master
```
