### ISSUE TITLE
Check for Duplicate routes

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1834]
**What steps did you take and what happened:**
A user could create duplicate routes on a Proxy which could cause incorrect routing. Contour should warn the user that this has happened. 

Example proxy:

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
    name: root
  namespace: projectcontour-roots
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: rootapp
      port: 80
  - conditions:
    - prefix: /secure  # <--- dup
    services:
    - name: rootapp
      port: 80
  - conditions:
    - prefix: /secure  # <--- dup
    services:
    - name: secureapp-default
      port: 80
  - conditions:
    - prefix: /secure
    - header:
        contains: Chrome
        name: User-Agent
    services:
    - name: secureapp
      port: 80
  virtualhost:
    fqdn: local.projectcontour.io
status:
  currentStatus: valid
  description: valid HTTPProxy
```
