### ISSUE TITLE
Breaking down big list of conditions

### ISSUE THREAD

**Issue by prateekjainaa** [projectcontour/contour#1869]
I am working on a deployment where close to 70 apps will be deployed into single namespace. It is currently using Ingress objects to expose urls and things are fine because each application can come and deploy its own Ingress object. I am trying to shift from nginx based Ingress controller to Contour based ingress controller. 

  Issue which I can see here is, with contour individual application will not be coming with its own HTTPProxy object (because they are deployed under same namespace and host/url) but the root HTTPProxy file will become very large and hard to maintain, due to big list of "conditions" like,

```
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: s1
      port: 80
  - conditions:
    - prefix: /hello
    services:
    - name: kubia
      port: 80
  -  conditions:
  -  conditions:
  -  conditions:
  .
  .
  .
  virtualhost:
    fqdn: kuard.local
```

Just wanted to know if there is some feature in contour via which we can allow applications to bring their own configurations so that application developers dont have to maintain a gigantic configuration file. I have already gone through examples [here](https://github.com/projectcontour/contour/tree/master/examples/example-workload/httpproxy). 

**Note**: Feel free to correct me if I am wrong here with my understanding of contour.
