### ISSUE TITLE
Contour not showing status for Ingress with unmatched Service name

### ISSUE THREAD

**Issue by opyh** [projectcontour/contour#1886]
**What steps did you take and what happened:**

I've tried to create an `Ingress` route:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: github-webhook
  namespace: argo-events
  annotations:
    kubernetes.io/ingress.class: "contour"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - …
    secretName: github-webhook-tls
  rules:
  - host: …
    http:
      paths:
      - backend:
          serviceName: github-gateway-svc
          servicePort: 12000
        path: /
```

Unfortunately I had a typo in the `spec.rules[0].http.paths[0].backend.serviceName`, so the referenced service did not exist. There was no error in the contour logs, and no info about the ingress in http://127.0.0.1:9001/clusters. It took me very long to find why the `Ingress` was not picked up by contour as there was no visible way for me to debug this.

**What did you expect to happen:**

I expected contour to show an error in the log that the Service reference was invalid - or at least some information about the ingress in http://127.0.0.1:9001/clusters. Unfortunately, the cluster did not show up there at all, so I expected I had some configuration error in the contour configuration (e.g. a namespace filter or something).

**Anything else you would like to add:**

After changing the `serviceName` to something invalid, no further errors or changes on http://127.0.0.1:9001/clusters were visible - the cluster stats remained as they were.

**Environment:**

- Contour version: v1.0.0
- Kubernetes version: (use `kubectl version`): Client v1.16.2 / Server v1.15.5
- Cloud provider or hardware configuration: DigitalOcean
- OS (e.g. from `/etc/os-release`): CentOS Linux 7 (Core)
