### ISSUE TITLE
Instructions for presenting grpc services needs a guide

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#1894]
We need a guide that concisely describes the HTTPProxy configuration and service annotations required to proxy grpc through contour.

**Comment by twfx7758** [comment]
me too

**Comment by reagul** [comment]
I can help with this. Can i get assigned ?

**Comment by stevesloka** [comment]
Awesome all yours @reagul! 

Some work steps in my head if this helps:
- I think this would be a good "guide" where you'd add a new file here: https://github.com/projectcontour/contour/tree/master/site/_guides
- If you want to test what it looks like on your machine you can run: `make site-devel` and open up a browser to `localhost:4000`
- It would be good to link to this guide from the `annotations` page as well as the `HTTPProxy`

**Comment by JasonMorgan** [comment]
hey folks! Any progress on this? I was just looking for this exact info. Happy to help if anyone can point me at a starting point.

**Comment by jpeach** [comment]
> hey folks! Any progress on this? I was just looking for this exact info. Happy to help if anyone can point me at a starting point.

To expose gRPC services, you would need to enable TLS on the [virtual hosts](https://projectcontour.io/docs/v1.9.0/api/#projectcontour.io/v1.VirtualHost) and set the `h2` protocol on any upstream [service](https://projectcontour.io/docs/v1.9.0/api/#projectcontour.io/v1.Service) entries.

If you'd like to contribute a specific user guide, that would be great. Steve's comment above and the [site contribution doc](https://github.com/projectcontour/contour/blob/main/SITE_CONTRIBUTION.md) should help you get started with the docs.

**Comment by reagul** [comment]
@JasonMorgan i am still working on this one. I will post something soon.

**Comment by danthegoodman1** [comment]
Any update on this?

**Comment by youngnick** [comment]
Hmm, it doesn't look like there's much movement here. I'd agree that this one is prime candidate for a fresh guide. Perhaps @OrlinVasilev or @jonasrosland could raise this one at a Tech Docs WG meeting?

**Comment by OrlinVasilev** [comment]
@reagul did you make any progress on that or we can restart that topic?

**Comment by samelie** [comment]
A guide would be really helpful. Am stumbling piecing together what's required in the contour+envoy config to make this work

**Comment by OrlinVasilev** [comment]
@jpeach - are you still interested in that or if anyone else wants to take it ?

**Comment by youngnick** [comment]
I think that James has moved on and will not be interested in updating here.

**Comment by samelie** [comment]
Was able to piece it together - props to y'all and this amazing project. There were only 2 custom parts to getting grpc-web working
> envoy-config.yaml

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: adddog-envoy-config
data:
  config.yaml: |
    domain: contour
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address: { address: 0.0.0.0, port_value: 9901 }

    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address: { address: 0.0.0.0, port_value: 8080 }
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: auto
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match: { prefix: "/" }
                    route:
                      cluster: echo_service
                      timeout: 0s
                      max_stream_duration:
                        grpc_timeout_header_max: 0s
                  cors:
                    allow_origin_string_match:
                    - prefix: "*"
                    allow_methods: GET, PUT, DELETE, POST, OPTIONS
                    allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                    max_age: "1728000"
                    expose_headers: custom-header-1,grpc-status,grpc-message
              http_filters:
              - name: envoy.filters.http.grpc_web
              - name: envoy.filters.http.cors
              - name: envoy.filters.http.router
      clusters:
      - name: echo_service
        connect_timeout: 0.25s
        type: logical_dns
        http2_protocol_options: {}
        lb_policy: round_robin
        load_assignment:
          cluster_name: cluster_0
          endpoints:
            - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: node-server
                        port_value: 50051
                        
```

Then used the example project https://github.com/projectcontour/contour/tree/main/examples/contour , just changing the `loadBalancerIP` to the GKE static ip

I wrote custom `HTTPProxy` in Tanka so it's kinda hard to share, but can do if someone asks. Essentially, combined the _letsencrypt_ and _cors_ guides , also adding `protocol: 'h2c',` to the services block made it all work. Also the `timeoutPolicy` on the _route_ block has been useful for the grpc streams
