### ISSUE TITLE
Use gRPC readiness/liveness probes

### ISSUE THREAD

**Issue by bgagnon** [projectcontour/contour#1900]
The current probes used in the example deployments are rather crude:

```
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
        readinessProbe:
          tcpSocket:
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 10
```

The readiness probe only that Contour is able to open a TCP connection, while the liveness probe makes an HTTP call to `/healthz` that merely pings the Kubernetes API:

```go
healthCheckHandler := func(w http.ResponseWriter, r *http.Request) {
		// Try and lookup Kubernetes server version as a quick and dirty check
		_, err := client.ServerVersion()
		if err != nil {
			msg := fmt.Sprintf("Failed Kubernetes Check: %v", err)
			http.Error(w, msg, http.StatusServiceUnavailable)
			return
		}
		w.WriteHeader(http.StatusOK)
		fmt.Fprintln(w, "OK")
	}
```

The problem with this is that Envoy talks to Contour via gRPC, not HTTP. As a gRPC server, Contour should leverage the [grpc-health-probe](https://github.com/grpc-ecosystem/grpc-health-probe/) utility that has recently gained popularity following a [mention on the Kubernetes blog](https://kubernetes.io/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/) last year.

Since this puts Contour in full control of the probes, it could open up new opportunities for self-healing and leader election. But more importantly, it would make the probes more representative of Contour's true client, Envoy.
