### ISSUE TITLE
TLS annotation (contour.heptio.com/upstream-protocol.tls) to the service is ignored when using L4 ingressroute

### ISSUE THREAD

**Issue by vtsanghi** [projectcontour/contour#1916]
**What steps did you take and what happened:**

I configured my Service and IngressRoute as the following:
```
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    contour.heptio.com/upstream-protocol.tls: "https,443"
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  selfLink: /api/v1/namespaces/default/services/kubernetes
spec:
  clusterIP: 192.168.128.1
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: kubernetesb
  namespace: default
spec:
  virtualhost:
    fqdn: k8s.run.ubisoft.org
    tls:
      secretName: k8s-tls
  tcpproxy:
    services:
    - name: kubernetes
      port: 443
```

When accessing to the url  **k8s.run.ubisoft.org**, I got the following message :
`Client sent an HTTP request to an HTTPS server.`
It seems like the TLS annotation is ignored and Envoy doesn't consider the upstream service over tls.

**What did you expect to happen:**

Envoy should communicate with the upsteam service over tls when using the TLS annotation to the service.

`
contour.heptio.com/upstream-protocol.tls: "https,443"
`

**Anything else you would like to add:**

I have a look to the Envoy config_dump and noticed that the "tls context" config is missing in the cluster

```
...
{
     "version_info": "104",
     "cluster": {
      "name": "default/kubernetes/443/da39a3ee5e",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "api_config_source": {
         "api_type": "GRPC",
         "grpc_services": [
          {
           "envoy_grpc": {
            "cluster_name": "contour"
           }
          }
         ]
        }
       },
       "service_name": "default/kubernetes/https"
      },
      "connect_timeout": "0.250s",
      "common_lb_config": {
       "healthy_panic_threshold": {}
      },
      "alt_stat_name": "default_kubernetes_443"
     },
     "last_updated": "2019-11-18T19:45:50.457Z"
}
...
```

I would expect to see to the cluster:
```
...
"tls_context": {
    "common_tls_context": {}
},
...
```

**Environment:**

- Contour version: v0.15.3
- Envoy: v0.15.3
- Kubernetes version: 1.14
- Rancher : 2.2.3
- Cloud provider : Open Stack
- OS : 4.19.43-coreos
