### ISSUE TITLE
Multiple applications deployed in one namespace

### ISSUE THREAD

**Issue by prateekjainaa** [projectcontour/contour#1945]
We deployed one application in our k8s cluster, this application has following characteristics:

1. It handles SSL on its own.
2. It exposes multiple contexts say, /login, /dashboard etc.

We removed its Ingress object and deployed new HTTPProxy like

```
# httpproxy-tls-passthrough.yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: example
  namespace: default
spec:
  virtualhost:
    fqdn: tcp.example.com
    tls:
      passthrough: true
  tcpproxy:
    services:
    - name: loginAndDashboard
      port: 443

```
Everything worked fine till now. We are able to login and access services from this app. Now, we deployed another application (in same namespace) with similar characteristics:

1. It handles SSL on its own.
2. It exposes multiple contexts say, /configureUser, /deleteUser etc.

So, we added its service to the list under tcpProxy

```
tcpproxy:
    services:
    - name: loginAndDashboard
      port: 443
    - name: userService
      port: 443
```

We expected that new service will also be accessible in addition to previous service. But userService was not accessible. So, we thought that it is reasonable behavior as how will contour decide which request should be forwarded to which service. So, we defined explicit paths in HTTPProxy object like (routes section),

```
# httpproxy-tls-passthrough.yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: example
  namespace: default
spec:
  virtualhost:
    fqdn: tcp.example.com
    tls:
      passthrough: true
  routes:
    - conditions:
      - prefix: /login
      services:
        - name: loginAndDashboard
          port: 443
    - conditions:
      - prefix: /dashboard
      services:
        - name: loginAndDashboard
          port: 443
    - conditions:
      - prefix: /configureUser
      services:
        - name: userService
          port: 443
    - conditions:
      - prefix: /deleteUser
      services:
        - name: userService
          port: 443
 tcpproxy:
    services:
    - name: loginAndDashboard
      port: 443
    - name: userService
      port: 443
```

But now even the parts of previous service started to become inaccessible. Are we trying to do something wrong/not-supported here? Where can we look for errors because its status shows its a valid proxy.

**Comment by davecheney** [comment]
@prateekjainaa I'm sorry you are having issues. The root cause is TCP proxying cannot be combined with routing (there is one edge case where this statement is not true, but it does not apply in your scenario).

Contour should reject the configuration you provided. I'm sorry, this is a bug and it will be rectified.

For you, you should either use routing or tcpproxying, not both.

**Comment by prateekjainaa** [comment]
Because we are using ssl-passthrough feature, we have to use tcp-proxy feature. And because as soon as we add another proxy to list, it stops working. So, does it mean that we cannot use contour right now? 
Same feature is working fine currently with **Ingress** objects. Am I correct in assuming that, we cannot use contour right now in this situation. Please comment.

**Comment by stevesloka** [comment]
@davecheney can't we tie L4 to `tcp.example.com` as well as L7 to `tcp.example.com`?

**Comment by davecheney** [comment]
> @davecheney can't we tie L4 to tcp.example.com as well as L7 to tcp.example.com?

yes, but on a per port basis. port 443 is unilaterally forwarded to the services mentioned, there is no scope to do http routing on port 443 at that point

**Comment by davecheney** [comment]
> Because we are using ssl-passthrough feature, we have to use tcp-proxy feature.

yes, if you want the backend service to handle the tls handshake then envoy cannot do any http routing because the L7 HTTP traffic is not available to it.

>  And because as soon as we add another proxy to list, it stops working. So, does it mean that we cannot use contour right now?

> Same feature is working fine currently with **Ingress** objects. Am I correct in assuming that, we cannot use contour right now in this situation. Please comment.

This is probably a bug, the underlying rule that a virtual host, per port, can only be handled by envoy in L7 HTTP mode or L4 TCP mode is immutable.

**Comment by prateekjainaa** [comment]
@stevesloka @davecheney we have a line of 100 such applications waiting to be deployed in similar model. Can you guys provide us rough time frame for fixing this issue? I am asking this because it is acting as a blocker for our migration work to contour ingress controller.

**Comment by davecheney** [comment]
I'm sorry if I was not clear. Mixing L4 and L7 per vhost cannot work the
way you want. If a vhost is in L4 mode using tcpproxy then envoy cannot
apply L7 http routing.

Can you step back a few paces and tell us about the way you want to deploy
your applications then maybe we can help find a way to use contour to do
what you need.

**Comment by prateekjainaa** [comment]
sure, I will list down our requirements again here:

1. Applications needs to handle their secure connection (https) by themselves.
2. Close to 100 such applications will be deployed under same namespace.
3. All applications will have same virtual hostname/IP.

This setup is currently working with nginx-ingress-controller. I have avoided any technical details about our approach to keep things simple. I hope this will make things more clearer.

**Comment by davecheney** [comment]
Thank you for your reply. Please try this httpproxy template
```
# httpproxy-tls-passthrough.yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: app
  namespace: default
spec:
  virtualhost:
    fqdn: app.example.com
    tls:
      passthrough: true
  tcpproxy:
    services:
    - name: app
      port: 443
```
You will need to deploy one httpproxy per backend service, or more correctly one httpproxy per virtual host you want to multiplex onto one ip.

**Comment by prateekjainaa** [comment]
@davecheney As far as I remember, we did tried this and it works but as far as their is only one service is configured. As soon as I added another service to the list of services like,

tcpproxy:
    services:
```
    - name: app
      port: 443
   - name: app2
      port: 443
```

it stopped working. If you can tell me where to look for errors, I will collect error logs and try to share with with you.

**Comment by davecheney** [comment]
Yes, that will not work because it combines multiple k8s services behind a single virtualhost. This is essentially the same as saying (sorry for the yaml, on phone)

virtualhost:
  Fqdn: example.com
routes:
  - conditions:
     - prefix: /
     services:
     - name: app1
        port: 443
     - name: app2
        port: 443

**Comment by prateekjainaa** [comment]
So, should we expect this to be fixed in 1.1 release? and can you provide us some rough timeline for its release, this will ease up our planning on whether we want to wait for fix or look for alternatives.

**Comment by davecheney** [comment]
I’ve explained that if you combine multiple backend services in tcppassthrough mode envoy considers them to be one single service and shares all incoming traffic across all the services you list — this is why when you add additional services the your tcpproxy: block it breaks.

With that understanding, what solution would you like us to implement ?

**Comment by prateekjainaa** [comment]
@davecheney Thanks for explaining.

1.

>  what solution would you like us to implement ?

We are not envoy or contour expert so can't comment there.
2. Are you saying that our use case will not be supported by contour?
3. If we move HTTPS handling to Ingress controller then will rest of the use case supported by contour? As per my understanding, we have to use TLS termination in that case which will be similar to,

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: example
  namespace: default
spec:
  virtualhost:
    fqdn: tcp.example.com
    tls:
      secretName: secret
  tcpproxy:
    services:
    - name: app1
      port: 80
    - name: app2
      port: 80

```
Will it work as this also uses tcpproxy?

**Comment by davecheney** [comment]
@prateekjainaa 

> We are not envoy or contour expert so can't comment there.

I'm sorry, I did not mean to gate keep here. As I understand it your requirements are

1. Each k8s service will handle its own TLS handshaking
2. All virtualhosts (dns names) should be presented behind one external IP address
3. Each k8s service has its own virtual host; ie the k8s service foo is presented at foo.example.com, and the k8s service bar is presented as bar.example.com.

> 2. Are you saying that our use case will not be supported by contour?

Can you please confirm or correct your requirements as stated, then I can advise.

> 3. If we move HTTPS handling to Ingress controller then will rest of the use case supported by contour? As per my understanding, we have to use TLS termination in that case which will be similar to,

If you move TLS handshaking to Contour then you will be able to route at layer 7, HTTP, rather than layer 4, tcp flows

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: example
  namespace: default
spec:
  virtualhost:
    fqdn: tcp.example.com
    tls:
      secretName: secret
  tcpproxy:
    services:
    - name: app1
      port: 80
    - name: app2
      port: 80
```
This configuration will send 50% of the incoming TCP flows to the pods that represent the service app1 and 50% to app2.

**Comment by jpeach** [comment]
> sure, I will list down our requirements again here:

> Applications needs to handle their secure connection (https) by themselves.
> Close to 100 such applications will be deployed under same namespace.
> All applications will be deployed under same virtual hostname/IP.
> Requests will be routed to designated applications/services based upon request url for example,
> abc.com/userService should be routed to svc1
> abc.com/jobService should be routed to svc2

> These svc1, svc2 are k8s services. This setup is currently working with nginx-ingress-controller. I  have avoided any technical details about our approach to keep things simple. I hope this will make things more clearer.

This can't possibly work if the k8s service is doing the TLS termination. If the service terminates TLs, the proxy never sees cleartext traffic and by definition it can't route HTTP request paths to different services. The only way this could work is if the proxy is doing TLS termination.

The ingress-nginx [documentation](https://kubernetes.github.io/ingress-nginx/user-guide/tls/#ssl-passthrough) describes how SSL passthrough proxies raw TCP, without routing HTTP.

**Comment by prateekjainaa** [comment]
> Each k8s service will handle its own TLS handshaking
  Yes

> All virtualhosts (dns names) should be presented behind one external IP address
I dont understand this. There is only one virtual host/dns name for all apps for example, abc.com

> Each k8s service has its own virtual host; ie the k8s service foo is presented at foo.example.com, and the k8s service bar is presented as bar.example.com.

No, virtualhost/DNS will be same for all applications inside k8s cluster so services foo and bar both will be using same virtual host abc.com. The routing decision about which service to call is based upon whether request is for abc.com/foo or, abc.com/bar or, abc.com/anything. 

> If you move TLS handshaking to Contour then you will be able to route at layer 7, HTTP, rather than layer 4, tcp flows

 will requirements listed above fulfilled? How will sample configuration look like?

**Comment by davecheney** [comment]
> I dont understand this. There is only one virtual host/dns name for all apps for example, abc.com

Ahh, I understand now.

In Contour requests are mapped to their HTTPProxy documents by the fully qualified domain name, FQDN. This FQDN is what we call the virtual host (as the physical host is the machine running the application, an antiquated concept). An FQDN is also the long form name of DNS name. Thus one dns name, one HTTPProxy document.

With this understanding in place the decision you have to make as a HTTPProxy author is do you want to handle the traffic at layer 7, HTTP, or layer 4, tcp proxying. If you want the backend application to handle the TLS handshake then you are restricted to layer 4 proxying -- you said you wanted the backend application to handle the L4 TLS encrypted traffic, there is nothing more Envoy can add but to forward packets back and forth.

With this understanding you can see that if you use TCPProxying then the responsibility for routing requests falls to the backend application -- Envoy cannot do this routing, it isn't even able to see the decrypted traffic. 

For your application. I recommend that you do not use TCP proxying, instead let Contour handle the TLS handshaking by providing the TLS key material for abc.com, then using routes and conditions to handle the routing of requests to various services.
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: example
  namespace: default
spec:
  virtualhost:
    fqdn: abc.com
    tls:
      secretName: abc-tls-cert
 routes:
   - conditions:
      - prefix: /foo
      services:
      - name: foo-app
        port: 8080
  - conditions:
     - prefix: /bar
     services:
     - name: bar-app
        port: 8000
```

    - name: loginAndDashboard
      port: 443
