### ISSUE TITLE
Contour should reject httpproxy with a missing service unconditionally

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#1951]
Under some conditions Contour may be permitting the httpproxy with a missing backend service:
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: example
  namespace: default
spec:
  virtualhost:
    fqdn: tcp.example.com
    tls:
      passthrough: true
  routes:
      services:
        - name: missing
          port: 443
 tcpproxy:
    services:
    - name: correct
      port: 443
```
This may be a holdover from the days when kubectl schema validation required a dummy `routes:` key.
