### ISSUE TITLE
tcpproxy + upgradeHTTPS presents a valid route in ingress_https

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#1954]
When tcpproxy is combined with a non permitInsecure service on port 80:
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: example
  namespace: default
spec:
  virtualhost:
    fqdn: tcp.example.com
    tls:
      passthrough: true
  routes:
      services:
        - name: correct
          port: 8080
 tcpproxy:
    services:
    - name: correct
      port: 8080
```
Contour correctly generates the `ingress_http` upgrade 301 configuration
```
envoy.RouteConfiguration("ingress_http",
                                envoy.VirtualHost("kuard-tcp.example.com",
                                        upgradeHTTPS(routePrefix("/")),
                                ),
                        ),
```
However it also incorrectly presents a valid route on `ingress_https`
```
                        envoy.RouteConfiguration("ingress_https",
                                envoy.VirtualHost("kuard-tcp.example.com",
                                        envoy.Route(routePrefix("/"),
                                                routeCluster("default/backend/80/da39a3ee5e"),
                                        ),
                                ),
                        ),
```
This route should not be triggered because there is no http manager configured for this vhost -- it is a tcp proxy -- but the route should not be there.
