### ISSUE TITLE
Contour marks a httproxy w/ tcpproxy unconditionally valid if it does not have a TLS block

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#1958]
Contour accepts this httpproxy definition without validating if the tcpproxy service is missing because there is no tls block.
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: example
  namespace: default
spec:
  virtualhost:
    fqdn: tcp.example.com
 tcpproxy:
    services:
    - name: missing
      port: 443
```
httpproxy's with a tcpproxy block cannot be valid without a spec.virtualhost.tls stanza and one of passthrough or a valid secret.
