### ISSUE TITLE
Feature Request: Allow "protocol" Be Defined in route.services.service (Enable Upstream TLS)

### ISSUE THREAD

**Issue by ryanelian** [projectcontour/contour#1962]
**Please describe the problem you have**

Continuing discussion from https://github.com/projectcontour/contour/issues/406

Currently enabling Upstream TLS requires annotations to be added to the backend `Service` manifest:

```
  annotations:
    projectcontour.io/upstream-protocol.tls: "443,https"
```

This causes some maintainability and usability issues, because the annotation and the Contour ingress object are in two different places. (Despite the annotation sole purpose is for configuring Contour ingress!)

And since one of the goals of doing custom CRD (`HTTPProxy`) instead of using default `Ingress` Kubernetes object is to reduce [*"an explosion of annotations to express missing properties of HTTP routing"*](https://github.com/projectcontour/contour/blob/master/design/ingressroute-design.md),

The `protocol` should be able to be defined in the `route.services.service` of a `HTTPProxy`:

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kubernetes-dashboard-proxy
  namespace: kubernetes-dashboard
spec:
  virtualhost:
    fqdn: dashboard.kubernetes.com
    tls:
      secretName: kubernetes-dashboard-tls
  routes:
    - conditions:
      - prefix: /
      services:
        - name: kubernetes-dashboard
          protocol: https # <--- FEATURE REQUEST!
          port: 443
```

**Comment by davecheney** [comment]
Thank you for raising this issue. Moving to the backlog for prioritisation, /cc @michmike

**Comment by ryanelian** [comment]
Excuse me, I am having trouble using the new `protocol: https` feature.

![image](https://user-images.githubusercontent.com/8892187/73075288-2c06c080-3eee-11ea-9f5b-a6b6d2e28c77.png)

What should I do?

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kubernetes-dashboard-proxy
  namespace: kubernetes-dashboard
spec:
  virtualhost:
    fqdn: dashboard.cloud.xxx.com
    tls:
      secretName: kubernetes-dashboard-tls
  routes:
    - conditions:
      - prefix: /
      services:
        - name: kubernetes-dashboard
          # protocol: https
          port: 443
```
