### ISSUE TITLE
growing multiple paths in httpproxy

### ISSUE THREAD

**Issue by prateekjainaa** [projectcontour/contour#1966]
We are migrating from nginx Ingress controller to contour. Here is a case where we see issue.

step1: Everything is fine till we have something similar to:

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
  name: basic
  namespace: foo
spec:
  routes:
  - conditions:
    - prefix: /foo
    services:
    - name: test1
      port: 80
  virtualhost:
    fqdn: example.com
    tls:
      secretName: sslsecretthird
```
Here, contour is handling ssl connection for all apps but right now there is only one app.

step 2: We migrate another app (same namespace, same FQDN) to use contour and then everything works fine if we update same proxy object to look like,

```
 routes:
  - conditions:
    - prefix: /foo
    services:
    - name: test1
      port: 80
  - conditions:
    - prefix: /
    services:
    - name: kuard
      port: 80

```

Now, this approach has issues like every app will have dependency over this central configuration file. So, if we plan to deploy any new app then this central HTTPProxy object has to be updated. In fact, if we want to selectively deploy apps in different clusters then, that also can't be done automatically as we need to know upfront what services/apps are deployed and supply HttpProxy object accordingly. When we tried to break it down into two separate deploy-able files it threw error like:

`fqdn "example.com" is used in multiple HTTPProxies: default/basic, default/basic-foo`

We need a mechanism where applications can come and deploy their own HttpProxy objects so that applications can be deployed/removed independently from cluster. Feel free to correct me, if I am missing something here.
