### ISSUE TITLE
HTTPProxy is rejected by API server when timeoutPolicy.idle is empty

### ISSUE THREAD

**Issue by kfyharukz** [projectcontour/contour#1993]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I wrote the following `HTTPProxy` but it was rejected by APIserver (kubectl) with the message `spec.routes.timeoutPolicy.idle in body is required`.
```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  ...
spec:
  ...
  routes:
    # For static files
    - conditions:
      - prefix: /
      services:
      - name: server-https
        port: 443
      timeoutPolicy:
        response: 2m
```

**What did you expect to happen:**

In the reference document, I can omit `idle` field.
When `idle` field is omitted, it should be filled by the default value (5m).

https://projectcontour.io/docs/v1.0.0/httpproxy/#httpproxy-api-specification

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I think, each field in Timeout.Policy should be optional & omitempty.

https://github.com/projectcontour/contour/blob/768510af6486f20ed032f20515a9878db07c16b0/apis/projectcontour/v1/httpproxy.go#L226

**Environment:**

- Contour version: 1.0.0
- Kubernetes version: (use `kubectl version`): 1.15.4
