### ISSUE TITLE
guides: Cert-Manager guide should use a Certificate object

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2018]
The cert-manager guide (https://projectcontour.io/guides/cert-manager/) uses a dummy ingress object to generate the certs. It should just use a cert-manager `Certificate` object to generate the certs since the extra Ingress object sitting around with `HTTPProxy` objects to me is confusing. 

Also, the ordering of ingress objects might break the current guide's model (i.e. HTTPProxy takes precedence over anything). 

Example cert object: 

```
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tlscert
  namespace: projectcontour-roots
spec:
  secretName: containersteve-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: containersteve.com
  dnsNames:
  - containersteve.com
  - www.containersteve.com
  acme:
    config:
    - http01:
        ingressClass: contour
      domains:
      - containersteve.com
      - www.containersteve.com
```
