### ISSUE TITLE
guides: Update cert manager annotation to work with HTTPProxy

### ISSUE THREAD

**Issue by Javlopez** [projectcontour/contour#2053]
The guide to work cert-manager with HTTPProxy (https://projectcontour.io/guides/cert-manager/) in the section **Making cert-manager work with HTTPProxy** indicates that we should to create a dummy Ingress object like this

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
  name: httpbinproxy
  namespace: default
spec:
  rules:
  - host: httpbinproxy.davecheney.com
    http:
      paths:
      - backend:
          serviceName: httpbin
          servicePort: 8080
  tls:
  - hosts:
    - httpbinproxy.davecheney.com
    secretName: httpbinproxy 
```
But this is wrong due the line 5 is incorrect, that annotation needs to be updated by the right one, which is **certmanager.k8s.io/cluster-issuer**

The code should be the following

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
  name: httpbinproxy
  namespace: default
spec:
  rules:
  - host: httpbinproxy.davecheney.com
    http:
      paths:
      - backend:
          serviceName: httpbin
          servicePort: 8080
  tls:
  - hosts:
    - httpbinproxy.davecheney.com
    secretName: httpbinproxy 
```
