### ISSUE TITLE
Consider the use of port name to guide protocol selection. 

### ISSUE THREAD

**Issue by mattmoor** [projectcontour/contour#2056]
To support http/2 delivery today the service referenced from Contour's HTTPProxy must be annotated with something like:
```yaml
annotations:
  contour.heptio.com/upstream-protocol.h2c: "80,http"
```

This style of annotation-based configuration unfortunately requires us (Knative) to bake in knowledge of how to configure this for every networking implementation with which we integrate.

Istio [developed a convention](https://istio.io/docs/ops/configuration/traffic-management/protocol-selection/) for avoiding this that we adopted, which isn't tied to one implementation and a few others have adopted.

Essentially by naming the port a certain way, it determines what protocol should be used by default to speak to that port.  In our case, when we synthesize http/1.1 services we have:
```yaml
  ports:
  - name: http   # I am http/1.1
    port: 80
    protocol: TCP
    targetPort: 8012
```

When we synthesize http/2 services we have:
```yaml
  ports:
  - name: http2  # I am http/2
    port: 81
    protocol: TCP
    targetPort: 8013
```

At least so far, this has proven to be a relatively uncontentious middle ground, but I wanted to open this issue to start a conversation about whether adopting this (or something similar) in Contour might be feasible, and if not what other alternatives might be possible.

**Comment by stevesloka** [comment]
Back when we were designing IngressRoute/v2 I thought it would be interesting to change the `name` field to the protocol. So you'd have something like this:

```
  ports:
  - http: serviceName   # I am http/1.1
    port: 80
    protocol: TCP
    targetPort: 8012
```


```
  ports:
  - http2: serviceName   # I am http/2 (This might also be h2)
    port: 80
    protocol: TCP
    targetPort: 8012
```

**Comment by mattmoor** [comment]
I could also see the `Service` section of the `HTTPProxy` being used to direct the protocol semantics as well and this would allow the controller that reconciles the Knative networking abstraction => `HTTPProxy` to be what's sensitive to the convention and direct the `HTTPProxy` on when to use `http` vs. `http2`.  I biased towards this approach because I recall seeing a comment from Dave on wanting this configuration to live K8s `Service`-side.

Part of the problem here is that the networking controller that produces `HTTPProxy` _has_ to be Contour-specific / -aware, but at least today the controller that produces the K8s services that we route to encodes no real knowledge of Istio / Gloo / Ambassador / Contour / Kourier / ...

If facilities for doing this within HTTPProxy itself are preferable, then I could probably make that work as well.  Something like:
```yaml
spec:
  routes:
  - enableWebsockets: true
    retryPolicy:
      count: 3
      perTryTimeout: 10m0s
    services:
    - name: foo-v2
      protocol: http2    # http/2
      port: 80
      requestHeadersPolicy:
        set:
        - name: K-Network-Hash
          value: f7d5526e584b2c085465b57adf5c7d65
        - name: Knative-Serving-Namespace
          value: default
        - name: Knative-Serving-Revision
          value: foo-v2
      weight: 49
    - name: foo-v1
      protocol: http1    # http/1
      port: 80
      requestHeadersPolicy:
        set:
        - name: K-Network-Hash
          value: f7d5526e584b2c085465b57adf5c7d65
        - name: Knative-Serving-Namespace
          value: default
        - name: Knative-Serving-Revision
          value: foo-v1
      weight: 51
    timeoutPolicy:
      response: 10m0s
  virtualhost:
    fqdn: foo.default.mattmoor.io
```
