### ISSUE TITLE
Document how to integrate with Linkerd

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2089]
Now that Contour supports injecting HTTP headers, it should be possible to configure Contour as a [Linkerd Ingress](https://linkerd.io/2/tasks/using-ingress/). We should verify and document how to do this.

**Comment by stefanprodan** [comment]
Linkerd blocks the proxy injection into Envoy pods see https://github.com/linkerd/linkerd2/issues/3910

**Comment by arminbuerkle** [comment]
With [linkerd edge-20.3.1](https://github.com/linkerd/linkerd2/releases/tag/edge-20.3.1) linkerd no longer blocks the proxy injection into envoy / contour pods.

Using [linkerd with contour/envoy works](https://linkerd.io/2/tasks/using-ingress/#contour) but a lot of configuration is required since you need to set the `l5d-dst-override` header explicitly for every route split.

Is it somehow possible to automatically add those headers? Either by adding a config flag to contour, similar to ambassador (`add_linkerd_headers: true` ) or by having variables when editing headers:
```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: test
spec:
  routes:
  - requestHeadersPolicy:
      set:
      - name: l5d-dst-override
        value: ${SVC_NAME}.${SVC_NAMESPACE}.svc.cluster.local:${SVC_PORT}
    services:
    - name: test
      namespace: default
      port: 80
```
