### ISSUE TITLE
Using the new field protocol in the Service spec is ignored when using a tcpproxy

### ISSUE THREAD

**Issue by vtsanghi** [projectcontour/contour#2188]
**What steps did you take and what happened:**
I have a httpProxy configured with a TCP proxy and the new field **protocol**:
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kubernetes
  namespace: default
spec:
  tcpproxy:
    services:
    - name: kubernetes
      port: 443
      protocol: tls
  virtualhost:
    fqdn: k8s.run.ubisoft.org
    tls:
      secretName: kubernetes-tls
```
When accessing to the url k8s.run.ubisoft.org, I got the following message :
`Client sent an HTTP request to an HTTPS server.`
It seems like the **protocol** field is ignored and Envoy doesn't consider the upstream service over tls.
But if I put the annotation `projectcontour.io/upstream-protocol.tls` in the service, it is working.
From my understanding the **protocol** field should replace the annotation.

**What did you expect to happen:**

Envoy should communicate with the upsteam service over tls when using the **protocol** field without the annotation `projectcontour.io/upstream-protocol.tls` on the service.

**Environment:**

- Contour version: v1.1.0
- Envoy version: v1.12.2
- Kubernetes version: 1.14
- Rancher : 2.2.9
- Cloud provider : Open Stack
- OS : 4.19.43-coreos
