### ISSUE TITLE
When started with --ingress-class-name flag, contour still considers IngressRoutes objects without a matching ingress.class annotation

### ISSUE THREAD

**Issue by clmssz** [projectcontour/contour#2199]
**What steps did you take and what happened:**

My contour deployment is started with a ` --ingress-class-name=test` flag. It however still feeds envoy configuration for some `IngressRoute` objects which don't have an annotation. 

Those objects are the one currently used by the "old" (current production deployment) contour. They don't have `*/ingress.class` annotations. 

Example (stripped from personnal infos / kubernetes runtime infos)

```
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: xxx.com
spec:
  routes:
  - match: /
    services:
    - name: xxx-some-backend
      port: xxx
  virtualhost:
    fqdn: xxx.com
    tls:
      secretName: xxxSSL
status:
  currentStatus: valid
  description: valid IngressRoute
```

Envoy config excerpt :

```
        "name": "xxx.com",
        "domains": [
         "xxx.com",
         "xxx.com:*"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/"
          },
          "route": {
           "cluster": "namespace/xxx-some-backend/xxx/da39a3ee5e"
          }
         }
        ]
```
 

**What did you expect to happen:**
I'm in the process of upgrading contour from a <= 0.13.0 (I know ... :)) version and it's the opportunity to migrate `IngressRoute` objects to `HTTPProxy` at the same time. 
I'm not sure about potential side-effects with having both objects in // for the same virtualhosts/fqdn so I would like my new contour deployment to only consider `HTTPProxy` objects and ignore my current `IngressRoute` ones.

**Environment:**
- Contour version: v1.1.0, official docker image
- Kubernetes version: v1.12.10-gke.17
- Cloud provider or hardware configuration: GKE
- OS (e.g. from `/etc/os-release`): cos
