### ISSUE TITLE
Websockets with ingress 

### ISSUE THREAD

**Issue by seangaffey** [projectcontour/contour#2210]
Hi all,

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I'm trying to open a websocket session using contour.
I suspect I am not using the annotation properly but I haven't found any example.
Here is my ingress, deployment and service yamls:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress-ws
  namespace: poc
  annotations:
    kubernetes.io/ingress.class: "contour"
    projectcontour.io/websocket-routes: "ws"
spec:
  tls:
    - hosts:
        - com.example.host
      secretName: example-tls-certificate
  rules:
    - host: com.example.host
      http:
        paths:
          - path: /ws1
            backend:
              serviceName: ws-svc
              servicePort: 80
          - path: /ws
            backend:
              serviceName: ws-svc
              servicePort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ws
  template:
    metadata:
      labels:
        app: ws
    spec:
      containers:
        - name: ws
          image: someregistry:ws
          ports:
            - containerPort: 8080
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ws-svc
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: ws
  selector:
    app: ws
---
```
There is a static web page that gets served on port 80 which works. This page then tries to open a websocket e.g. ws = new WebSocket('ws://com.example.host:8080');
but it just times out.

**What did you expect to happen:**
I expected a websocket connection to be made.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: 1.1
- Kubernetes version: (use `kubectl version`): 1.16
- Kubernetes installer & version: 
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):
