### ISSUE TITLE
api: json field for TCPDelegation is plural when it should be singular

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2218]
The json field for `HTTPProxy.TCPProxy.Include` is plural (i.e. `includes`) when it should be singular: https://github.com/projectcontour/contour/blob/master/apis/projectcontour/v1/httpproxy.go#L179

The docs match this (https://projectcontour.io/docs/v1.1.0/httpproxy/#tcpproxy-delegation) where it shows the singular version. 

If a user follows the examples in the docs, the delegation won't work properly since when the yaml is parsed, the field is ignored because it doesn't match the struct. 

I opened #2201 to fix the docs to at least allow users to follow along properly, however, the real fix is to set the name to be singular.

**Comment by davecheney** [comment]
> The request from you and Pere to decompose a service mesh using contour components is super clear, but the more people I talk to in the BU, the less I can find anyone would actually use that — their requirements are just too far removed from a toolkit of components that we discussed with Pere and Avi.

**Comment by davecheney** [comment]
> I opened #2201 to fix the docs to at least allow users to follow along properly, however, the real fix is to set the name to be singular.

I agree, the name of the tag should be `include`, but it looks like this will be a compatibility break as the validations enforce is as the plural.
```
includes:
                  description: Include specifies that this tcpproxy should be delegated
                    to another HTTPProxy.
                  properties:
                    name:
                      description: Name of the child HTTPProxy
                      type: string
                    namespace:
                      description: Namespace of the HTTPProxy to include. Defaults
                        to the current namespace if not supplied.
                      type: string
```
:(
