### ISSUE TITLE
I can't understand how to configure path rewriting/redirection in HTTPProxy

### ISSUE THREAD

**Issue by torquemada163** [projectcontour/contour#2411]
### Background:
---
I have service in Kubernetes on port 8804 (Java application in container), it response on URL ends with /dashboards I'm publish this service with Contour HTTPProxy:

```
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: demo-dashboards-route
  namespace: demo-dashboards
spec:
  virtualhost:
    fqdn: demos.cuba-labs.com
  routes:
  - services:
    - name: demo-dashboards-app
      port: 8804
    loadBalancerPolicy:
      strategy: Cookie
```

My application work well with URL `http://demos.cuba-labs.com/dashboards`
https://i.stack.imgur.com/zkFE6.png

### Problem:
---
The next step I want to do is automatically redirect from the URL `http://demos.cuba-labs.com` to `http://demos.cuba-labs.com/dashboards`
To do this, rewrite it like this:

```
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: demo-dashboards-route
  namespace: demo-dashboards
spec:
  virtualhost:
    fqdn: demos.cuba-labs.com
  routes:
  - services:
    - name: demo-dashboards-app
      port: 8804
    loadBalancerPolicy:
      strategy: Cookie
    pathRewritePolicy:
      replacePrefix:
      - prefix: /
        replacement: /dashboards
```

I go to root URL - `http://demos.cuba-labs.com` and see the following situation:
https://i.stack.imgur.com/2UM6k.png

In the address bar, the URL has been replaced and written correctly - `http://demos.cuba-labs.com/dashboards` but in the browser window the doubled URL `/dashboardsdashboards` is displayed. And I see 404 error...

What am I doing wrong?

**Comment by jpeach** [comment]
To use the prefix replace like this, you could try:

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: demo-dashboards-route
  namespace: demo-dashboards
spec:
  virtualhost:
    fqdn: demos.cuba-labs.com
  routes:
  - services:
    - name: demo-dashboards-app
      port: 8804
    loadBalancerPolicy:
      strategy: Cookie
    conditions:
      - prefix: /
    pathRewritePolicy:
      replacePrefix:
      - prefix: /
        replacement: /dashboards/
  - services:
    - name: demo-dashboards-app
      port: 8804
    loadBalancerPolicy:
      strategy: Cookie
    conditions:
      - prefix: /dashboards
```

In this example, we match separately on "/" and on "/dashboards", but sends both paths to the same backend service. On the "/" match, we insert the "/dashboards/" prefix, but that won't happen on the "/dashboards" match.
