### ISSUE TITLE
SSL Termination on AWS NLB to avoid managing certs in contour

### ISSUE THREAD

**Issue by farshad-hobsons** [projectcontour/contour#2441]
AWS came out with [TLS Termination for Network Load Balancers](https://aws.amazon.com/blogs/aws/new-tls-termination-for-network-load-balancers/) on Jan 24, 2019. In order to avoid managing ssl certs manually or through cert-manager, I would prefet to use ssl termination on aws-nlb while leveraging the other nice contour features. So basically, I am looking whether this sort of architecture is possible:
```
https-traffic -> aws-nlb -> http-traffic-to-envoy
```
I have successfully tested this same type of functionality in nginx-controller using the following annotations with aws-nlb:
```
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "ssl"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "mycertARN"
```

Unfortunately, following the [deploy-aws-nlb.md](https://github.com/projectcontour/contour/blob/master/site/_guides/deploy-aws-nlb.md) with the above annotations did not work (traffic does not make it to envoy) for contour. I also tried testing by  setting: `hostNetwork: true` and `dnsPolicy: ClusterFirstWithHostNet` on my Envoy pod definition as per [contour's Host Networking docs](https://projectcontour.io/docs/master/deploy-options/)

If the above architecture is possible, it would be help the community if we can update the aws nlb docs. If its not possible, it would be good to know the technical reasons and if this would be possible in future contour releases.

**Comment by stevesloka** [comment]
Hey @farshad-hobsons I took some time this morning to setup your scenario. I did get it working, the TLDR is that I changed the TLS Listener on port 443 for the NLB to the same that used on port 80. 

The reason for this change is that Contour only sets up a TLS listener on Envoy when a TLS secret exists. Since there's no secret (i.e. you're not terminating TLS at Envoy), the default group in AWS sends traffic to the port 443 nodePort which isn't listening. 

Here's a sample of my setup:
![image](https://user-images.githubusercontent.com/1048184/81417867-d6ab9380-9119-11ea-99c2-2513bed58522.png)

This would also be great to add to the docs on how to configure this properly from the start. I'll pop open a new issue for that.

**Comment by farshad-hobsons** [comment]
thanks @stevesloka for providing this workaround.

**Comment by psehgal** [comment]
This is a great workaround. But is there any way to manage this through the manifests for contour?

**Comment by WKuipers** [comment]
I've run into this issue too while deploying through Helm. If that chart would allow customizing targetPort for https on the envoy service it would be awesome.

**Comment by psehgal** [comment]
@WKuipers I had no idea there was a helm chart for install this. Thank you for sharing. It looks like this value might actually be driven by a variable you can configure in your `values.yaml`

```
  ports:
    - name: http
      port: {{ .Values.envoy.service.ports.http }}
      protocol: TCP
      targetPort: http
      {{- if and (or (eq .Values.envoy.service.type "NodePort") (eq .Values.envoy.service.type "LoadBalancer")) (not (empty .Values.envoy.service.nodePorts.http)) }}
      nodePort: {{ .Values.envoy.service.nodePorts.http }}
      {{- else if eq .Values.envoy.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    - name: https
      port: {{ .Values.envoy.service.ports.https }}
      protocol: TCP
      targetPort: https
      {{- if and (or (eq .Values.envoy.service.type "NodePort") (eq .Values.envoy.service.type "LoadBalancer")) (not (empty .Values.envoy.service.nodePorts.https)) }}
      nodePort: {{ .Values.envoy.service.nodePorts.https }}
      {{- else if eq .Values.envoy.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
```

**Comment by youngnick** [comment]
I see this request, maybe @georgegoh could comment on how to log an issue for the Helm chart?

**Comment by ectogon** [comment]
Has anyone tried this in combination with `nginx.ingress.kubernetes.io/force-ssl-redirect: "true"`?

**Comment by abhinavk07** [comment]
```
apiVersion: v1
kind: Service
metadata:
  name: elm-nlb
  namespace: demo
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ***
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: demo-elm
```

Above config for NLB isn't working for me. I'm able to reach the application but the SSL cert doesn't work. I'm using kubernetes 1.14, can anyone suggest a workaround?

**Comment by abhinavk07** [comment]
```
apiVersion: v1
kind: Service
metadata:
  name: **
  namespace: demo
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: *****
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: **
```

Above config for NLB isn't working for me. I'm able to reach the application but the SSL cert doesn't work. I'm using kubernetes 1.14, can anyone suggest a workaround?
