### ISSUE TITLE
Path based routing isn't working with Contour 

### ISSUE THREAD

**Issue by gourav-goutam** [projectcontour/contour#2450]
I tried with HTTPProxy,
https://github.com/projectcontour/contour/blob/master/examples/example-workload/httpproxy/03-routes/httpproxy-multiple-paths.yaml

Also with Ingressroute,
https://github.com/projectcontour/contour/tree/master/examples/example-workload/ingressroute/06-multiple-roots

But path based routing is not working with contour.
I am able to achieve it with nginx. But I want to use contour.

Any help would be appreciated.
I used below yaml,

# httpproxy-multiple-paths.yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: multiple-paths
  namespace: default
spec:
  virtualhost:
    fqdn: nginx.example.com
  routes:
    - conditions:
      - prefix: / 
      services:
        - name: nginx-main
          port: 80
    - conditions:
      - prefix: /blue  
      services:
        - name: nginx-blue
          port: 80

I'm able to access nginx.example.com.
but nginx.example.com/blue is not accessible -> 404 Not Found

**Environment:**

- Contour version:  1.0.0
- Kubernetes version: (use `kubectl version`): Client Version: v1.18.0, Server Version: v1.18.1
- Kubernetes installer & version:  kubeadm
- Cloud provider or hardware configuration:  This is on-prem cluster
- OS (e.g. from `/etc/os-release`): NAME="Red Hat Enterprise Linux Server", VERSION="7.5 (Maipo)", ID="rhel", ID_LIKE="fedora"

**Comment by stevesloka** [comment]
Hey @gourav-goutam! Not sure if it's a copy/paste error, but looks like you've got some spacing issues on your yaml.

I fixed them up so you could try again:

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: multiple-paths
  namespace: default
spec:
  virtualhost:
    fqdn: nginx.example.com
  routes:
    - conditions:
      - prefix: / 
      services:
        - name: nginx-main
           port: 80
    - conditions:
      - prefix: /blue
      services:
        - name: nginx-blue
           port: 80
``` 

Let me know how this one works out!

**Comment by gourav-goutam** [comment]
Hi @stevesloka , That is copy/paste error. Still, I tried with your yaml and it isn't working.

**Comment by jpeach** [comment]
> Hi @stevesloka , That is copy/paste error. Still, I tried with your yaml and it isn't working.

If the route to `/` is working but the route to `/blue` is not, then the most likely explanation is that the `nginx-blue` service doesn't have any healthy endpoints or isn't available. If the prefix routing wasn't working, then the request would have been forwarded to `nginx-main` which is working according to your tests.

So, the next step is to check that `nginx-blue` is healthy and has endpoints.

**Comment by stevesloka** [comment]
Thanks for the reminder on this @jpeach. =)

The other thing to add @gourav-goutam is that nginx by default will serve a 404 for any path other than `/`. Can you share the output of `curl -i http://nginx.example.com/blue`? So if you are getting a 404, it's possible that everything is working.

**Comment by gourav-goutam** [comment]
Hi @stevesloka ,
I'm getting a 404 error as you said. Based on your above comment, you meant that there is a problem with nginx pod (deployment).
In my scenario, I have two deployments with nginx image where I am displaying everything in different color. For each deployment, I've exposed a service.
If needed, I can share all yaml's that I've used.

Could you share me the yaml for creating deployment that uses image of any other type (not nginx).

**Comment by stevesloka** [comment]
Hey @gourav-goutam, my gut guess is everything is working, but let's try one more thing to validate. 

Can you update your `nginx-blue` deployment to use a sample image I demo with? Here's a sample deployment + service. Just deploy this then update your `HTTPProxy` to use the service `rootapp` instead of `nginx-blue`. 

What this sample app does is echo back pieces of your request to the screen. It should tell you the path that was requested along with all the header bits.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rootapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rootapp
  template:
    metadata:
      labels:
        app: rootapp
    spec:
      containers:
      - name: echo
        image: stevesloka/echo-server
        command: ["echo-server"]
        args:
          - --echotext=This is the default app site!
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rootapp
  name: rootapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rootapp
  type: ClusterIP
---
```
