### ISSUE TITLE
gRPC HTTP/1.1 reverse bridge support

### ISSUE THREAD

**Issue by sp-manuel-jurado** [projectcontour/contour#2456]
**gRPC HTTP/1.1 reverse bridge support**

Hi contour team, I have a question:

In the company I’m working in nowadays, we are evaluating using contour as the main ingress-controller.

We have services running in http1.1 and others in gRPC using golang natively. As we have been able to read in the documentation the protocols http1.1, h2 and h2c are supported, so we have successfully integrated them using contour.

But also, we have an upstream that does not understand any gRPC semantics, due to we’re using envoy v1.12.2 with the HTTP filter ‘gRPC HTTP/1.1 reverse bridge’ because we want to establish gRPC as the main protocol with the client-side. By setting the withhold_grpc_frame option, the filter will assume that the upstream does not understand any gRPC semantics and will convert the request body into a simple binary encoding of the request body and perform the reverse conversion on the response body.

We have tried to integrate this service with contour 1.1.0, but we have not been able.
I guess, by design or philosophy reasons, it is not supported currently… or is it possible to integrate it with contour and we have forgotten some contour annotations or configs?
This is our current envoy configuration related to the filter (sp.rpc.PingService was implemented using golang and gRPC natively within 'envoy.filters.http.grpc_http1_reverse_bridge' disabled and enabled for the other services):

```
    ...
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/sp.rpc.PingService/"
                route:
                  cluster: ping
                per_filter_config:
                  envoy.filters.http.grpc_http1_reverse_bridge:
                    disabled: true
              - match:
                  prefix: "/"
                route:
                  cluster: backend
          http_filters:
            - name: envoy.filters.http.grpc_http1_reverse_bridge
              config:
                content_type: application/grpc+proto
                withhold_grpc_frames: true
    ...
```

Thanks in advance.
