### ISSUE TITLE
Possible envoy regression causes HTTP 404

### ISSUE THREAD

**Issue by alex1989hu** [projectcontour/contour#2468]
**What steps did you take and what happened:**
I have upgraded `contour` to `1.4.0` from `1.3.0`. I see many `404` errors in `envoy` pod log. The services behind `HTTPProxy` can not be loaded, I got `404` error  in browser, too. Constantly hitting refresh button in my browser temporary solves the issue: it can load the page. I thought it is a network issue: after downgraded to `1.3.0` the services behind `HTTPProxy`  instantly loaded, no error log in `envoy`. Reinstalled the whole cluster from scratch with `1.4.0`, the same symptom can be seen. Downgraded back to `1.3.0` solves the issue again.

**UPDATE**: actually it is `404`, not `401`.

**What did you expect to happen:**
No  `404` error.

**Anything else you would like to add:**
- 100% reproducible
- Using GitOps for all the Kubernetes related configuration, no external change occured

**Environment:**

- Contour version:
```
1.4.0
```
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
```
v1.18.0
```
- Cloud provider or hardware configuration:
```
external: cloud-provider-vsphere
```
- OS (e.g. from `/etc/os-release`):
```
Talos (v0.4.1)
```

**Comment by youngnick** [comment]
Thanks for the report @alex1989hu. Can you give us a sample HTTPProxy, so we can attempt to replicate please?

**Comment by alex1989hu** [comment]
Having `A` record and several `CNAME`; Contour does `TLSCertificateDelegation`.

I installed `1.4.0` it again today to ensure that is the problem. I found that the error code is `404`, not `401`. It is my bad, sorry.

Let me share the simplest service where `nginx` is running, but a more complex service also has the same defect.

**Extra:**
I see drops and missing TCPv4 SYN-ACKs alert in `Grafana`, inspected by `hubble` after installing `1.4.0`. Using `1.3.0` does not cause any of them. 

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: knowledgebase-proxy
  namespace: knowledgebase
  labels:
    app.kubernetes.io/name: knowledgebase
spec:
  virtualhost:
    fqdn: kb.foo.bar.acme.com
    tls:
      secretName: projectcontour/wildcard-foobar-cert
  routes:
    - conditions:
      - prefix: /
      services:
        - name: knowledgebase-service
          port: 8080
          responseHeadersPolicy:
            set:
              - name: Strict-Transport-Security
                value: "max-age=31536000; includeSubdomains"
              - name: X-Content-Type-Options
                value: nosniff
              - name: X-Frame-Options
                value: DENY
              - name: X-XSS-Protection
                value: "1; mode=block"
```
