### ISSUE TITLE
guides: Document "default cert" for Ingress with TLS Certificate Delegation

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2488]
Contour has had `TLS Certificate Delegation` for some time now. Folks will ask about the "default" certificate pattern that exists in other ingress controller and if Contour supports that. 

Contour does support this today via the Cert Delegation feature. This works by telling Contour what cert you would like delegated to which namespace. Internally Contour keeps track of the certs and where they should exist. 

Users can then reference a cert from their namespace without actually having it exist physically.  

Here's an example of how this might work. We should write this up into a guide or docs somehow to make it clear how this could work:

```
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: example-com-wildcard
  namespace: projectcontour-roots
spec:
  delegations:
    - secretName: containerstevecom-tls-wild 
      targetNamespaces:
      - "*"
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tls-example-ingress
  namespace: default
spec:
  tls:
  - hosts:
    - containersteve.com
    secretName: projectcontour-roots/containerstevecom-tls-wild 
  rules:
    - host: containersteve.com
      http:
        paths:
        - path: /
          backend:
            serviceName: nginx
            servicePort: 80
```

**Comment by plod** [comment]
I've just come up against this issue and was looking for a guide. I'm fairly interested in picking this up if it's okay. Is it worth creating a guide setting up cert-manager with a wildcard domain like the guide that exists currently for cert-manager?

**Comment by stevesloka** [comment]
Hey @plod feel free to send over updates. Let me know if you have any questions and happy to review. =)

**Comment by marcelo-devsres** [comment]
Hey folks. 

I know this is probably not the best place, but it's basically the only reference on the Internet I found about the mention of a "default cert" for Contour.

> Contour has had TLS Certificate Delegation for some time now. Folks will ask about the "default" certificate pattern that exists in other ingress controller and if Contour supports that.

So, in Nginx Ingress Controller, we have this config flag:

```
--default-ssl-certificate: Secret containing a SSL certificate to be used by the default HTTPS server (catch-all). Takes the form "namespace/name".
```

So, if we have, lets say, 10.000 Ingress objects, all served from a wildcard domain with the same cert, we can basically trust Nginx to use the default-ssl-certificate.

In case we migrate to Contour, all 10.000 httpproxy objects would have to be configured with virtualhosts which point to the delegated secret on a specific namespace.

Did I get it right?

**Comment by youngnick** [comment]
Yes, that's correct, currently. We do have a "fallback" certificate option, but that's for use for TLS *clients* that don't supply an SNI. In the past we've generally preferred the objects to be explicit about this, and encouraged people to have other ways to simplify this, like a mutating admission webhook or something. But I can see it's a nice-to-have for large installs, and it seems worth discussing the tradeoffs in a more clear way.

I think that any design that addressed adding this would need to address questions like:
- How do you pick what HTTPProxy/Ingress objects to add the default to?
- How do you tell people that their HTTPProxy has a default cert overlaid (Ingress has no status, so you're out of luck there anyway)?
- How does this interact with the Gateway Policy construct? Is it worth  spending this effort when Gateway has a better solution?

I'd love to see an issue logged requesting this feature, so that we can discuss it there.

**Comment by jordo** [comment]
This has been quite helpful

**Comment by DanPhonovation** [comment]
When I try this I cannot create a regular ingress object with a slash in it (forcing me to recreate the cert in my apps namespace):

```
Failed to save resource: {"error":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Ingress.extensions \"devtron-app-v1-devtron-app-ingress\" is invalid: spec.tls[0].secretName: Invalid value: \"contour-ef6b6d59/comodo-wildcard-tls2023\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","reason":"Invalid","details":{"name":"devtron-app-v1-devtron-app-ingress","group":"extensions","kind":"Ingress","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"contour-ef6b6d59/comodo-wildcard-tls2023\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","field":"spec.tls[0].secretName"}]},"code":422},"messages":["Ingress.extensions \"devtron-app-v1-devtron-app-ingress\" is invalid: spec.tls[0].secretName: Invalid value: \"contour-ef6b6d59/comodo-wildcard-tls2023\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"],"isUsedForNotification":false}
```

My spec is simply:

```
spec:
  ingressClassName: contour
  tls:
     - hosts:
       - phonosimcheck-devtron.iaas.phonovation.com
       secretName: "contour-ef6b6d59/comodo-wildcard-tls2023"
```

if I take out the contour-ef6b6d59/ portion, I can apply the ingress. Otherwise, I get the error.
