### ISSUE TITLE
Add a "route destination" to directly return a status code with body , for example "403/forbidden"

### ISSUE THREAD

**Issue by primeroz** [projectcontour/contour#2515]
**Please describe the problem you have**
Most of my workloads expose a `/healthz` , `/readiness` , `/metrics` endpoint on the same port as the main service ( Which i understand is not great but i have no way of changing ) 

This causes every publicly exposed workload to also expose those internal endpoint to the internet, I would like a way to specify a way to return `403 forbidden` directly as a route destination ( similar to what [gloo does](https://docs.solo.io/gloo/latest/guides/traffic_management/request_processing/direct_response_action/) ) 

probably related to https://github.com/projectcontour/contour/issues/1627

a syntax like :
```
routes:
     - conditions:
      - prefix: /readiness
      directRouteAction:
          status: 403
          body: "forbidden"
```

At the moment my *workaround* is to run an httpbin service and use `httproxy inclusion` and `pathrewrite` to achieve this 
```
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: forbid-generic-403
  namespace: httpbin
  annotations:
    projectcontour.io/ingress.class: contour
spec:
  routes:
    - services:
        - name: httpbin
          port: 8080
      pathRewritePolicy:
        replacePrefix:
        - replacement: /status/403
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: podinfo-tls
  annotations:
    projectcontour.io/ingress.class: contour
spec:
  virtualhost:
    fqdn: podinfo-tls.example.com
    tls:
      secretName: wildcard
  includes:
    - name: forbid-generic-403
      namespace: httpbin
      conditions:
      - prefix: /metrics
    - name: forbid-generic-403
      namespace: httpbin
      conditions:
      - prefix: /healthz
    - name: forbid-generic-403
      namespace: httpbin
      conditions:
      - prefix: /readiness
    #- name: forbid
    #  namespace: httpbin
  routes:
    - services:
        - name: podinfo
          port: 8443
```
