### ISSUE TITLE
Add support to set Header value from another header

### ISSUE THREAD

**Issue by primeroz** [projectcontour/contour#2516]
**Please describe the problem you have**
I have some Third Party LoadBalancers, on which i don't have any Control, setting the `Real IP` header to a custom header like `x-real-client-ip` rather than the usual `x-forwarded-for` 

In my current `haproxy ingress` , which i am trying to replace with contour , i simply have a frontend snippet like 

```
acl acl_real_client_ip_header_exists req.hdr(X-Real-Client-IP) -m found
http-request set-header X-Forwarded-For %[req.hdr(X-Real-Client-IP)] if acl_real_client_ip_header_exists
http-request set-header X-Forwarded-For %[src] if !acl_real_client_ip_header_exists
```

* If the `header X-Real-Client-IP` exist then set `x-forwarded-for` to the value of `x-real-client-ip`
* else set `x-forwarded-for` to the `src ip` 

Ideally i would expect something like 
```
  routes:
    - services:
      - name: podinfo
        port: 8443
        responseHeadersPolicy:
          set:
              - name: x-forwarded-for
                valueFromHeader: x-real-client-ip
                fallback: ignore
```

To copy the value if present and `ignore` if not present ( and hopefully still get the standard `x-forwarded-for` behavior from contour
