### ISSUE TITLE
Ability to define the same endpoint multiple times in envoy.

### ISSUE THREAD

**Issue by prahaladramji** [projectcontour/contour#2541]
Using a cluster of envoy proxy as an edge proxy for upstreams in a different region with longer latency. (~300ms) Sydney ~ Europe.

We are able to mitigate the issues of bandwidth delay due to a [long fat network](https://en.wikipedia.org/wiki/Bandwidth-delay_product) by specifing the upstream multiple times in the cluster config as described below.
```yaml
clusters:
  - name: origin_eu
    connect_timeout: 15s
    per_connection_buffer_limit_bytes: 32768 # 32 KiB
    max_requests_per_connection: 500
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: origin_eu
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: origin-eu.private.foobar.com
                    port_value: 443
                    protocol: TCP
            - endpoint:
                address:
                  socket_address:
                    address: origin-eu.private.foobar.com
                    port_value: 443
                    protocol: TCP
            - endpoint:
                address:
                  socket_address:
                    address: origin-eu.private.foobar.com
                    port_value: 443
                    protocol: TCP
    http2_protocol_options:
      initial_stream_window_size: 65536 # 64 KiB
      initial_connection_window_size: 8388608 # 8 MiB
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: origin-eu.private.foobar.com
        common_tls_context:
          alpn_protocols:
            - h2
```

### Tuning currently done:
* envoy's [concurrency](https://www.envoyproxy.io/docs/envoy/v1.13.1/operations/cli.html?highlight=concurrency#cmdoption-concurrency) is set to 4 to match the number of cpu's on the host/pod. Increasing this causes the latency to spike.
* This does help increase the number of parallel connections made to the upstream. But is limited to the number of concurrency threads.
* The workaround done is adding more endpoints (same endpoint multiple times). This let's envoy open more parallel connections since each endpoint creates a few active connections to the upstream on start up based on the concurrency set.

> This workaround was taken from https://github.com/envoyproxy/envoy/issues/9112 and based on a talk by Dylan Carney, Stripe https://www.youtube.com/watch?v=QYCsd4Ptwzo&feature=youtu.be&t=1274 (timestamp 21:18).

Since contour seems like the best candidate for our use case where we want to use envoy as an edge proxy. It would make the configuration of the cluster more streamlined if all the configurations were managed via contour instead of statically typed (current situation).

Other suggestion welcome if there's a different way to solve this situation.

### Requirements that contour is solving
* Ingress controller for the kubernetes cluster, for workloads running inside kubernetes and also to proxy back to the upstreams in a different region outside kubernetes.
* The cluster of envoy that contour manages is an independent cluster and not side cars, which only manages routing decision to workloads from the edge (North to South).
* These envoy's are not use for service to service communication.
