### ISSUE TITLE
Traffic mirroring does not work with Envoy host networking

### ISSUE THREAD

**Issue by c3mb0** [projectcontour/contour#2557]
Here's a very simple example I've copied from the docs:

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: contour-internal
  namespace: some-namespace
spec:
  virtualhost:
    fqdn: some.internal.domain
  routes:
    - timeoutPolicy:
        response: 90s
      conditions:
        - prefix: /api/someapi
      services:
        - name: someservice
          port: 80
        - name: someservice-mirror
          port: 80
          mirror: true
```

The traffic is only received by `someservice`. I do not have an Envoy Service, instead I'm running my Envoy pods directly on hosts. I'm assuming this lack of service is the reason why mirroring does not work, since there are no complaints about this anywhere else. Any pointers for getting it to work?

- Contour version: 1.4.0 (had the same problem with 1.2.1)
- Kubernetes version: 1.16.8
- Cloud provider: AWS EKS
- OS: Amazon Linux 2
