### ISSUE TITLE
Exposed url using Countour httpproxy not working for include.

### ISSUE THREAD

**Issue by zeroone-shreeram** [projectcontour/contour#2561]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
 

  name: root-ingress
  namespace: default
spec:
  includes:
  - conditions:
    - prefix: /
    name: app-ingress
    namespace: app
  - conditions:
    - prefix: /phpmyadmin
    name: phpmyadmin-ingress
    namespace: app
  virtualhost:
    fqdn: test.example.com
    tls:
      secretName: tlssecret`

```

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: phpmyadmin-ingress
  namespace: app
spec:
  routes:
     - services:
           - name: phpmyadmin
             port: 80

```
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: app-ingress
  namespace: app
spec:
  routes:
    - services:
        - name: app
          port: 80
    
```

**What did you expect to happen:**
`Working both the url i.e 
test.example.com and test.example.com/phpmyadmin

but only the test.example.com works  

url not found error fo /phpmyadin url.`

- Contour version:  contour:v1.4.0
- Kubernetes version: (use `kubectl version`):  `Client Version: v1.17.3
Server Version: v1.17.5
`
- Cloud provider or hardware configuration: DigitalOcean managed k8s cluster not worked for gcp managed cluster as well
- OS (e.g. from `/etc/os-release`): Debian GNU/Linux 9 (stretch)
