### ISSUE TITLE
Envoy cluster not created for a service when mirror: true

### ISSUE THREAD

**Issue by jason-magnetic-io** [projectcontour/contour#2581]
This HTTPProxy def based on the mirroring example in the docs doesn't work
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: podinfo-ingress
  namespace: mirror-test
spec:
  virtualhost:
    fqdn: some.public.domain
  routes:
    - conditions:
      - prefix: /
      services:
        - name: podinfo-331
          port: 9898
        - name: podinfo-331-mirror
          port: 9898
          mirror: true
```
The Pod serving `podinfo-331` responds to requests as expected
The Pod serving `podinfo-331-mirror` doesn't receive the requests

**Anything else you would like to add:**
The cluster for `podinfo-331-mirror` isn't created in envoy.
The `dynamic_route_configs` looks correct but the `mirror-test/podinfo-331-mirror/9898/da39a3ee5e` cluster is missing.
```
   "dynamic_route_configs": [
    {
     "version_info": "3",
     "route_config": {
      "@type": "type.googleapis.com/envoy.api.v2.RouteConfiguration",
      "name": "ingress_http",
      "virtual_hosts": [
       {
        "name": "some.public.domain",
        "domains": [
         "sr-test.customer-a.magnetic.io",
         "sr-test.customer-a.magnetic.io:*"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/"
          },
          "route": {
           "cluster": "mirror-test/podinfo-331/9898/da39a3ee5e",
           "request_mirror_policies": [
            {
             "cluster": "mirror-test/podinfo-331-mirror/9898/da39a3ee5e"
            }
           ]
          }
         }
        ]
       }
      ],
      "request_headers_to_add": [
       {
        "header": {
         "key": "x-request-start",
         "value": "t=%START_TIME(%s.%3f)%"
        },
        "append": true
       }
      ]
     },
     "last_updated": "2020-06-12T22:29:25.688Z"
    }
   ]
```
```
service-stats::default_priority::max_connections::1024
service-stats::default_priority::max_pending_requests::1024
service-stats::default_priority::max_requests::1024
service-stats::default_priority::max_retries::3
service-stats::high_priority::max_connections::1024
service-stats::high_priority::max_pending_requests::1024
service-stats::high_priority::max_requests::1024
service-stats::high_priority::max_retries::3
service-stats::added_via_api::false
service-stats::127.0.0.1:9001::cx_active::1
service-stats::127.0.0.1:9001::cx_connect_fail::0
service-stats::127.0.0.1:9001::cx_total::1
service-stats::127.0.0.1:9001::rq_active::0
service-stats::127.0.0.1:9001::rq_error::0
service-stats::127.0.0.1:9001::rq_success::356
service-stats::127.0.0.1:9001::rq_timeout::0
service-stats::127.0.0.1:9001::rq_total::356
service-stats::127.0.0.1:9001::hostname::127.0.0.1
service-stats::127.0.0.1:9001::health_flags::healthy
service-stats::127.0.0.1:9001::weight::1
service-stats::127.0.0.1:9001::region::
service-stats::127.0.0.1:9001::zone::
service-stats::127.0.0.1:9001::sub_zone::
service-stats::127.0.0.1:9001::canary::false
service-stats::127.0.0.1:9001::priority::0
service-stats::127.0.0.1:9001::success_rate::-1.0
service-stats::127.0.0.1:9001::local_origin_success_rate::-1.0
mirror-test/podinfo-331/9898/da39a3ee5e::default_priority::max_connections::1024
mirror-test/podinfo-331/9898/da39a3ee5e::default_priority::max_pending_requests::1024
mirror-test/podinfo-331/9898/da39a3ee5e::default_priority::max_requests::1024
mirror-test/podinfo-331/9898/da39a3ee5e::default_priority::max_retries::3
mirror-test/podinfo-331/9898/da39a3ee5e::high_priority::max_connections::1024
mirror-test/podinfo-331/9898/da39a3ee5e::high_priority::max_pending_requests::1024
mirror-test/podinfo-331/9898/da39a3ee5e::high_priority::max_requests::1024
mirror-test/podinfo-331/9898/da39a3ee5e::high_priority::max_retries::3
mirror-test/podinfo-331/9898/da39a3ee5e::added_via_api::true
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::cx_active::0
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::cx_connect_fail::0
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::cx_total::1
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::rq_active::0
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::rq_error::0
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::rq_success::8
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::rq_timeout::0
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::rq_total::8
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::hostname::
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::health_flags::healthy
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::weight::1
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::region::
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::zone::
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::sub_zone::
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::canary::false
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::priority::0
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::success_rate::-1.0
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::local_origin_success_rate::-1.0
contour::default_priority::max_connections::100000
contour::default_priority::max_pending_requests::100000
contour::default_priority::max_requests::60000000
contour::default_priority::max_retries::50
contour::high_priority::max_connections::100000
contour::high_priority::max_pending_requests::100000
contour::high_priority::max_requests::60000000
contour::high_priority::max_retries::50
contour::added_via_api::false
contour::10.86.11.149:8001::cx_active::1
contour::10.86.11.149:8001::cx_connect_fail::7
contour::10.86.11.149:8001::cx_total::8
contour::10.86.11.149:8001::rq_active::4
contour::10.86.11.149:8001::rq_error::7
contour::10.86.11.149:8001::rq_success::0
contour::10.86.11.149:8001::rq_timeout::0
contour::10.86.11.149:8001::rq_total::5
contour::10.86.11.149:8001::hostname::contour
contour::10.86.11.149:8001::health_flags::healthy
contour::10.86.11.149:8001::weight::1
contour::10.86.11.149:8001::region::
contour::10.86.11.149:8001::zone::
contour::10.86.11.149:8001::sub_zone::
contour::10.86.11.149:8001::canary::false
contour::10.86.11.149:8001::priority::0
contour::10.86.11.149:8001::success_rate::-1.0
contour::10.86.11.149:8001::local_origin_success_rate::-1.0
```
As a workaround, adding an additional route that uses `podinfo-331-mirror` results in the `mirror-test/podinfo-331-mirror/9898/da39a3ee5e` cluster being created.
The mirroring then works as expected.
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: podinfo-ingress
  namespace: mirror-test
spec:
  virtualhost:
    fqdn: some.public.domain
  routes:
    - conditions:
      - prefix: /
      services:
        - name: podinfo-331
          port: 9898
        - name: podinfo-331-mirror
          port: 9898
          mirror: true
    - conditions:
      - prefix: /
      - header:
          name: a-dummy-header
          exact: some-value-34a615f32e9a0c9e
      services:
        - name: podinfo-331-mirror
          port: 9898
```

**Environment:**
- Contour version: 1.5.0
- Kubernetes version: v1.14.10-gke.36
- Cloud provider: GKE
