### ISSUE TITLE
HTTPProxy: some routes are ignored when they differ only on header condition operator or value

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#2597]
**What steps did you take and what happened:**
Define an HTTPProxy with several routes that all have the same prefix and all have a condition on the same header, but different operators or values (some examples below).

Observe that Envoy is only configured with the last route; the other ones are dropped.

```yaml
# two routes that both have a 'contains' condition on the
# same header, with two different values.
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: dropped-routes-1
spec:
  virtualhost:
    fqdn: stevek.com
  routes:
    - conditions:
        - header:
            name: x-stevek
            contains: foo
      services:
        - name: svc1
          port: 80
    - conditions:
        - header:
            name: x-stevek
            contains: bar
      services:
        - name: svc2
          port: 80
---
# two routes that both have a condition on the
# same header -- one using 'contains' and one
# using 'notcontains'.
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: dropped-routes
spec:
  virtualhost:
    fqdn: stevek.com
  routes:
    - conditions:
        - header:
            name: x-stevek
            contains: foo
      services:
        - name: svc1
          port: 80
    - conditions:
        - header:
            name: x-stevek
            notcontains: foo
      services:
        - name: svc2
          port: 80
```

**What did you expect to happen:**
All of the routes to be configured with Envoy.
