### ISSUE TITLE
Multiple HttpProxy object for each path prefix and single virtual host

### ISSUE THREAD

**Issue by arunramachandran15** [projectcontour/contour#2645]
Hi Team,

I have single **virtualhost** (portal.example.net) but want to add **new prefix for each tenant** when there is a new tenant signup. Is there anyway I can create **multiple HttpProxy object for each prefix** but same virtual host which envoy will club together. Usage of includes is not decoupling the root from child prefix files. 

Objective here is to decouple root HttpProxy object and any number of child HttpProxy objects. I don't want to touch the root object to add includes.

**california-store.yaml**
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: california-store
spec:
  virtualhost:
    fqdn: portal.example.net
  routes:
    - services:
      - name: california-store
        port: 80
      conditions:
      - prefix: /california
      pathRewritePolicy:
        replacePrefix:
        - prefix: /california
          replacement: /
```
**washington-store.yaml**
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: washington-store
spec:
  virtualhost:
    fqdn: portal.example.net
  routes:
    - services:
      - name: washington-store
        port: 80
      conditions:
      - prefix: /washington
      pathRewritePolicy:
        replacePrefix:
        - prefix: /washington
          replacement: /
```
Maintaining all new prefix in single HttpProxy object will be very difficult. Any suggestions to solve this ?
Note :  Creating new subdomain for each tenant is not possible in our case.

**Comment by rfletcher** [comment]
I'm a new Contour user and have the same need. After finding the "inclusion" docs I was hoping HTTPProxy had support for selector-based inclusion, but I don't see anything like that in the current version. Assuming there isn't already another way to do the kind of dynamic inclusion we're looking for, something like this would be very welcome:

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: portal-root
spec:
  virtualhost:
    fqdn: portal.example.net
  routes:
    - services:
      - name: my-default-service
        port: 80
  includes:
    - selector:
        app.kubernetes.io/part-of: portal
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: california-store
  labels:
    app.kubernetes.io/part-of: portal
spec:
  routes:
    - services:
      - name: california-store
        port: 80
      conditions:
      - prefix: /california
      # ...
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: washington-store
  labels:
    app.kubernetes.io/part-of: portal
spec:
  routes:
    - services:
      - name: washington-store
        port: 80
      conditions:
      - prefix: /washington
      # ...

```
