### ISSUE TITLE
Inclusion in same namespace doesn't seem to work without specifying namespace.

### ISSUE THREAD

**Issue by josephglanville** [projectcontour/contour#2667]
When attempting to include a child HTTPProxy object in the same namespace without specifying the namespace Contour appears to fail to find the child HTTPProxy.
i.e I get invalid status, can't find <namespace>/<child_name> (where namespace is actually correct, so it should be looking in the right place)
However adding the namespace to the inclusion spec seems to correct this.

I found this while testing inclusion along with #2666 so I haven't had a chance to debug further yet because the workaround is simple, just include namespace for now.

- Contour version: v.1.5.0

**Comment by stevesloka** [comment]
Hey @josephglanville can you share your yaml used to create these?

 I just tested with the following and it all worked ok:

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
name: child
namespace: projectcontour-roots
spec:
routes:
- services:
    - name: rootapp
    port: 80
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
name: root
namespace: projectcontour-roots
spec:
includes:
- conditions:
    - prefix: /
    name: child
routes:
- conditions:
    - prefix: /secure
    services:
    - name: secureapp-default
      port: 80
virtualhost:
    fqdn: app.slokalabs.io
```
