### ISSUE TITLE
Added routing based on request method

### ISSUE THREAD

**Issue by dsvetl** [projectcontour/contour#2679]
Hi, can you add routing based on request methods?

https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/base.proto#envoy-api-enum-core-requestmethod

**Comment by youngnick** [comment]
Hi @dsvetl, thanks for logging an issue. We need a little more information to be able to answer.

How do you want routing on request methods to work, in an ideal world? What do you want to achieve with it?

**Comment by dsvetl** [comment]
Hi @youngnick

In an ideal world, all envoy dynamic parameters can be configured through the xDS API and we have such an xDS provider.

What i'll glad to see? Something like this:
* https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPMatchRequest
* https://docs.solo.io/gloo/1.0.0/gloo_routing/virtual_services/routes/matching_rules/http_method_matching/

What will the routing based on the request method give us?
* additional traffic distribution features
* ability to restrict request methods

**Comment by youngnick** [comment]
Thanks @dsvetl. In Contour, we try to be deliberate about what Envoy parameters we expose. See our [philosophy document](https://projectcontour.io/resources/philosophy/) for more, although it needs an update since we're in the process of [tweaking it a little](https://projectcontour.io/contours-landscape-jul-2020/).

It sounds like what you're asking for would be met by us adding a `method` option to the [HTTPProxy `conditions` block](https://projectcontour.io/docs/v1.6.1/httpproxy/#conditions). This is used in both the `routes` and `includes` sections, and would allow the method to be used for routing and HTTPProxy inclusion.

The current conflict resolution behavior for this is that, if there are two identical sets of condtions on different routes or includes, then both of them are rendered invalid. This would mean that you cannot specify the same method in combination with any other conditions multiple times. I don't believe this is a problem, but wanted to be clear.

Would that meet your requirement @dsvetl?

**Comment by dsvetl** [comment]
```yaml

  routes:
    - conditions:
      - prefix: /s1
      services:
        - name: s1
          port: 80
    - conditions:
      - prefix: /s1
      services:
        - name: s1
          port: 80
```

**Comment by dsvetl** [comment]
@youngnick, thanks for detail answer.

f.e. this is will be HTTPProxy block correct?

```yaml

    - conditions:
      - prefix: /foobar
        method:
        - GET
        - HEAD
        - OPTIONS
      services:
        - name: foobar
          port: 80
    - conditions:
      - prefix: /foobar
        method:
        - PUT
        - POST
      services:
        - name: bazbuz
          port: 80
    - conditions:
      - prefix: /not-foobar
        method:
        - GET
        - HEAD
        - OPTIONS
      services:
        - name: fuzboo
          port: 80
```

**Comment by dsvetl** [comment]
sup,

how it's going?

maybe remove label need-info .. or you really need more info?

**Comment by youngnick** [comment]
Sorry about this @dsvetl! To answer your question, yes that looks like what the HTTPProxy block would be, and the `/foobar` route doesn't conflict, so everything would work.

Technically, I think this would have to be implemented that you can't share _any_ methods between `method` conditions when the other conditions are the same. This is important because you don't _have_ to have a `prefix`, you can have only  `method`, only headers, or some combination of the two.

With that agreed on, I think we have something implementable.

**Comment by youngnick** [comment]
Following up on this issue, looks like the ask here is:
- add `method` as a match condition for HTTPProxy routes
- Write clear rules about how unique the set of methods needs to be, keeping in mind that the `conditions` stanza is reused between Routes and Includes.

This definitely needs a design writeup, which would be best in a design document. I'll leave this TODO here for prioritization @xaleeks, and move the issue out of "Needs Investigation".

**Comment by skriss** [comment]
FYI, I bumped into this before, but I believe it's already possible to route based on request method via the `:method` pseudo-header -- see https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html#config-route-v3-headermatcher. So you'd add a header match condition on `:method`. I haven't tested this myself yet but can try it out soon and confirm whether it works.

**Comment by skriss** [comment]
OK, I was able to verify this worked, see the following HTTPProxy:

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: default
spec:
  virtualhost:
    fqdn: local.projectcontour.io
  routes:
    - services:
      - name: s1
        port: 80
    - conditions:
      - header:
          name: ":method"
          exact: POST
      services:
      - name: s2
        port: 80
```

This properly routes to `s2` if a `POST`, and `s1` otherwise.

If this functionality is sufficient for folks, then it's probably just a matter of documenting explicitly. I could also see an argument for adding syntactic sugar to the HTTPProxy API along the lines of https://github.com/projectcontour/contour/issues/2679#issuecomment-658610060.
