### ISSUE TITLE
site/guides: Review cert-manager guide

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2709]
The cert-manager guide has a statement that Contour won't see the resource since it doesn't have the `ingress-class` annotation. Contour will "see" this resource and use it to make the HTTP01 challenge work to generate the certificate unless a specific ingress class is configured for Contour.

Also the annotation referenced earlier is: `kubernetes.io/ingress.class: contour` which I think is what the `ingress-class: contour` statement is referring to.

We should fix-up this statement and/or move to the Certificate CRD which would simply just replace the dummy ingress resource with something like this:

```
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: containersteve-tls
  namespace: projectcontour-roots
spec:
   commonName: upstream.containersteve.com
  dnsNames:
  - upstream.containersteve.com
  issuerRef:
    name: letsencrypt-prod-dns
  secretName: demoprojectcontourio-tls-upstream
```

_Originally posted by @stevesloka in https://github.com/projectcontour/contour/pull/2708#discussion_r458256070_
