### ISSUE TITLE
Add Header "Replace" Function

### ISSUE THREAD

**Issue by ccravens** [projectcontour/contour#2776]
**Please describe the problem you have**

**TL;DR**
Proposing adding a "replace" function to responseHeaderPolicy and requestHeaderPolicy with the following manifest format:
```yaml
          responseHeaderPolicy:
            replace:
              - header: <header name>
                regex: <regex search pattern>
                value: <value to replace>
```
**END TL;DR**

We are embedding some of our services hosted behind a contour proxy in an <iframe>. Some of these services respond with a 302 redirect to a url with insecure "http", which causes the browser not to load the content due to protocol mismatch because the parent frame is served over https (https://stackoverflow.com/questions/38072510/blocked-iframe-due-to-mismatch-protocols). This is due to the application in the pod not being configured for TLS (cert-manager and contour handle the SSL termination), so the the application thinks it must respond with "http" rather than "https".

![image](https://user-images.githubusercontent.com/1319049/89602331-7a4d3280-d834-11ea-9906-7b24669074a6.png)

The following is the desired behavior:

![image](https://user-images.githubusercontent.com/1319049/89602492-d57f2500-d834-11ea-8127-d698ada658c2.png)

We tried to invoke x-forwarded-proto with PROXY support settings (https://projectcontour.io/guides/proxy-proto/), but this did not cause the applications to respond with the proper https protocol.

Currently Contour supports both "set" and "remove" functions for both request and response HTTP headers (VERY useful: https://projectcontour.io/announcing-contour-1.1/), however the "set" function will not work in this use case for 2 reasons:

1) "set" would add the location header to all HTTP responses, we only want this to be applied when the "Location" header already exists (ie - for a 302 redirect response). By adding it to all responses it causes an infinite loop where all requests redirect back to the application, which responds again with a redirect and on and on. This causes Chrome to crash with the following screen:

![image](https://user-images.githubusercontent.com/1319049/89602823-943b4500-d835-11ea-9d32-40ba281659ae.png)

2) The "set" function sets an HTTP header to static content, we are only looking to replace a portion of the pre-existing header rather than setting it to a static value.

**Proposed Feature Enhancement**
We are proposing the addition of a "replace" header function, in addition to "set" and "remove" that we believe gives the most optimal resolution to this particular problem, as well as giving any developer full control to manipulate HTTP headers as they need without adding complicated templating logic to the manifests. This new function will take 3 parameters 1) the header to apply the replace 2) a regex of what to replace and 3) the value to replace. For example, this is a sample manifest with the proposed solution that would resolve the problem described above:

```yaml
          responseHeaderPolicy:
            set:
              - name: X-Service-Name
                value: s1
            remove:
              - X-Internal-Secret
            replace:
              - header: location
                regex: \http:\
                value: https:
```

This is an example of the header as it passes back through contour:

![image](https://user-images.githubusercontent.com/1319049/89604772-f5651780-d839-11ea-89b2-799dda1b78a4.png)

This would cause the location header to only exist if it had already been originally set by the application (resolves issue 1).

Additionally, this method would also allow the header value to stay correct, even if the location header is changed by the application (resolves issue 2) without complicated templating logic in the manifest. For example, if the application ever returned a different 302 redirect URL, it would still provide completely valid functionality:

![image](https://user-images.githubusercontent.com/1319049/89604629-a15a3300-d839-11ea-975f-04a7d0075402.png)

**Comment by jpeach** [comment]
Similar to https://github.com/projectcontour/contour/issues/2516 - use the value of a header to set the value of another header (in this case the source and destination headers are both `Location`).

**Comment by ccravens** [comment]
In regards to #2516, we may be able to include that in this update as well. Maybe instead of calling the function "replace" we call it "modify" and include both a regex replace (my proposal) as well as a copyFrom and copyTo (#2516 proposal). So for example:

```yaml
          responseHeaderPolicy:
            set:
              - name: X-Service-Name
                value: s1
            remove:
              - X-Internal-Secret
            modify:
              - header: location
                regex: \http:\
                replace: https:
```

and for #2516 it would be something like:
```yaml
          responseHeaderPolicy:
            set:
              - name: X-Service-Name
                value: s1
            remove:
              - X-Internal-Secret
            modify:
              - copyFrom: x-forwarded-for
                copyTo: x-real-client-ip
                default: {src.ip} <<--- Not sure about this?
```

I'm not sure about the "else set x-forwarded-for to the src ip" requirement, as that would require templating logic and from my conversations with @stevesloka he seemed to want to avoid that. If this has been brought up before maybe it's something to start looking into?
