### ISSUE TITLE
Support ExternalName without ports

### ISSUE THREAD

**Issue by mattmoor** [projectcontour/contour#2821]
ExternalName kubernetes services are not required to specify ports, in Knative (today) we use a spec that looks like:
```
spec:
  externalName: envoy.contour-internal.svc.cluster.local
  sessionAffinity: None
  type: ExternalName
```

However, when this is the target of an HTTPProxy we get the following error message with 1.7:

```
Spec.Routes unresolved service reference: port "80" on service "serving-tests/ingress-conformance-host-rewrite-rwapqodg" not matched
```

My understanding is that the semantics of ExternalName (without ports) is that of a CNAME record, so port-in = port-out.  Furthermore, it is worth confirming that ExternalName supports port-translation (or if the ports block is simply ignored) because if not then there may be a latent bug.
