### ISSUE TITLE
Support for Envoy Filters (Particularly Lua)

### ISSUE THREAD

**Issue by ccravens** [projectcontour/contour#3006]
I'm requesting the support of Envoy Lua filters with Contour. Lua filters provide developers the ability to apply sometimes complex and necessary modifications to headers for security or functional purposes that may not be supported via Contour YAML-based declarative manifests.

## Use Cases
I have 2 use cases in which Lua filters would solve my problem that is currently not possible with the current Contour manifests:

### Location Header Re-Write
While Contour offers the ability to set or remove headers, there is currently no functionality to modify headers. In my case, I need to guarantee that any `Location` header redirects to `https` rather than `http`. This problem is well described and documented in this issue: https://github.com/projectcontour/contour/issues/2776

The following inline Lua code applied as a filter would solve this problem:
```lua
function envoy_on_response(response_handle)
   local locationHeader = response_handle:headers():get("location")
   if locationHeader ~= nil then
      modified = string.gsub(locationHeader, "http://", "https://")
      response_handle:headers():replace("location", modified)
   end
end
```

### SameSite Cookie Attribute
Even more complex than header modification, updated security constraints in the Chrome browser do not allow setting iframe cookies without the proper SameSite attribute. While a lot of applications are working to apply this, it would be best to enforce this requirement at the proxy level to guarantee that this works across all applications (https://github.com/envoyproxy/envoy/issues/12970).

The following inline Lua code applied as a filter would solve this problem:
```lua
         function envoy_on_response(response_handle)
            function set_cookie_header(rh)
              s = rh:headers():get("Set-Cookie")
              if string.find(s, "mycookie=" ) and not string.find(s, "SameSite") then
                s = s.."; SameSite=None; Secure"
              end
              return s
            end
            if response_handle:headers():get("Set-Cookie") then
              secure_cookie_header = set_cookie_header(response_handle)
              response_handle:headers():replace("Set-Cookie",secure_cookie_header)
            end
          end
```

## Workaround
Initially, I was working to inject a separate XDS configuration service that would apply Lua filters to the configuration objects that Contour creates in envoy. However, due to Contour regenerating the DAG everytime a configuration update is made and re-applying the entire DAG to envoy, it would over-write any manual configurations that were applied. Therefore, the only way that we can truly get Lua filters properly supported is if they are managed by Contour.

## Sample Solutions
Istio supports an `EnvoyFilter` CRD which supports Lua inline code as well (https://istio.io/latest/docs/reference/config/networking/envoy-filter/). The following is a sample of an Istio CRD with inline Lua code:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: secure-session-cookie-filter
  namespace: istio-system
spec:
  workloadLabels:
    app: myingressgateway
  filters:
    - listenerMatch:
        listenerType: GATEWAY
      filterType: HTTP
      filterName: envoy.lua
      filterConfig:
        inlineCode: |
          function envoy_on_response(response_handle)
            function set_cookie_header(rh)
              s = rh:headers():get("Set-Cookie")
              if string.find(s, "mycookie=" ) and not string.find(s, "SameSite") then
                s = s.."; SameSite=None; Secure"
              end
              return s
            end
            if response_handle:headers():get("Set-Cookie") then
              secure_cookie_header = set_cookie_header(response_handle)
              response_handle:headers():replace("Set-Cookie",secure_cookie_header)
            end
          end
```
