### ISSUE TITLE
Support custom JSON fields for Envoy access logs

### ISSUE THREAD

**Issue by mike1808** [projectcontour/contour#3032]
We want to be able to configure Contour to have custom JSON access log fields, such as `custom_field: %REQ(OUR-CUSTOM-HEADER)%`. 

We are thinking that this can be achieved by having a new property with the JSON fields mapping like for [DefaultField](https://godoc.org/github.com/projectcontour/contour/internal/envoy#DefaultFields) in the Contour config. For example:

```yaml
accesslog-format: json
json-fields:
  - "@timestamp"
  - custom_field
extra-json-fields:
  custom_field:  "%REQ(X-CUSTOM-HEADER)%",
```

We [@cloudfoundry/cf-for-k8s-networking](https://github.com/orgs/cloudfoundry/teams/cf-for-k8s-networking) are happy to contribute this feature to upstream.
