### ISSUE TITLE
Incorrect Port Name in Contour Deployment

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour#3058]
**What steps did you take and what happened:**
The example Contour [deployment](https://github.com/projectcontour/contour/blob/main/examples/contour/03-contour.yaml) names the metrics port as `debug`:

```
kind: Deployment
metadata:
  labels:
    app: contour
  name: contour
  namespace: projectcontour
...
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
...
- containerPort: 8000
    name: debug
    protocol: TCP
...
```

Contour logs confirm that the metrics service listens on `8000` and the debug service listens on 6060:
```
time="2020-10-23T18:38:20Z" level=info msg="started HTTP server" address="0.0.0.0:8000" context=metricsvc
time="2020-10-23T18:38:20Z" level=info msg="started HTTP server" address="127.0.0.1:6060" context=debugsvc
```
Contour's metric service is listening on 
**What did you expect to happen:**
The metrics service to listen on `8000`

**Anything else you would like to add:**
xref: https://github.com/projectcontour/contour-operator/issues/46

**Environment:**

- Contour version: v1.9

/cc @Miciah @jpeach @stevesloka
