### ISSUE TITLE
Contour + envoy with force ssl redirect  and proxied cloudflare leads to infinite redirects

### ISSUE THREAD

**Issue by jaysonsantos** [projectcontour/contour#3149]
**What steps did you take and what happened:**
When configuring an ingress with `ingress.kubernetes.io/force-ssl-redirect: "true"` and pointing cloudflare proxy to the load balancer, it will keep redirecting **already https** calls to the same address leading to an infinite loop.

**What did you expect to happen:**
It should just render the page as it is already https

**Anything else you would like to add:**
The fix was to put the force-ssl-redirect to false and let cloudflare handle the redirects by itself.
The only difference on my setup from the original was by setting envoy as a daemonset with the following config.
```yaml
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: envoy
  name: envoy
  namespace: projectcontour
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8002"
        prometheus.io/path: "/stats/prometheus"
      labels:
        app: envoy
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - command:
            - /bin/contour
          args:
            - envoy
            - shutdown-manager
          image: docker.io/projectcontour/contour:v1.10.0
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/contour
                  - envoy
                  - shutdown
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8090
            initialDelaySeconds: 3
            periodSeconds: 10
          name: shutdown-manager
        - args:
            - -c
            - /config/envoy.json
            - --service-cluster $(CONTOUR_NAMESPACE)
            - --service-node $(ENVOY_POD_NAME)
            - --log-level info
          command:
            - envoy
          image: docker.io/envoyproxy/envoy:v1.16.0
          imagePullPolicy: IfNotPresent
          name: envoy
          env:
            - name: CONTOUR_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: ENVOY_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          ports:
            - containerPort: 80
              hostPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              hostPort: 443
              name: https
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ready
              port: 8002
            initialDelaySeconds: 3
            periodSeconds: 4
          volumeMounts:
            - name: envoy-config
              mountPath: /config
            - name: envoycert
              mountPath: /certs
          lifecycle:
            preStop:
              httpGet:
                path: /shutdown
                port: 8090
                scheme: HTTP
      initContainers:
        - args:
            - bootstrap
            - /config/envoy.json
            - --xds-address=contour
            - --xds-port=8001
            - --resources-dir=/config/resources
            - --envoy-cafile=/certs/ca.crt
            - --envoy-cert-file=/certs/tls.crt
            - --envoy-key-file=/certs/tls.key
          command:
            - contour
          image: docker.io/projectcontour/contour:v1.10.0
          imagePullPolicy: IfNotPresent
          name: envoy-initconfig
          volumeMounts:
            - name: envoy-config
              mountPath: /config
            - name: envoycert
              mountPath: /certs
              readOnly: true
          env:
            - name: CONTOUR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      automountServiceAccountToken: false
      serviceAccountName: envoy
      terminationGracePeriodSeconds: 10
      volumes:
        - name: envoy-config
          emptyDir: {}
        - name: envoycert
          secret:
            secretName: envoycert
      restartPolicy: Always

```
**Environment:**

- Contour version: 1.10.0
- Kubernetes version: (use `kubectl version`): v1.19.3+k3s3
- Kubernetes installer & version:k3s
- Cloud provider or hardware configuration: k3s on a bare machine
- OS (e.g. from `/etc/os-release`): ubuntu 20.04.1
