### ISSUE TITLE
Add SSL Redirect to HTTPProxy TLS Passthrough

### ISSUE THREAD

**Issue by doddatpivotal** [projectcontour/contour#3150]
I am familiar and comfortable using the annotation on Ingress object to force a redirect.  I would like to see the same option available on HTTPProxy that leverages tls-passthrough.

```
ingress.kubernetes.io/ssl-redirect: "true"
```

**Comment by stevesloka** [comment]
We might need to put an HTTP listener to handle the redirect bits, I'm not sure how to make that happen with TCP Filters in Envoy. 

However we look to solve this, however, it should be the default (meaning no annotations or other settings) since Contour doesn't accept TCP connections over insecure listeners.

**Comment by youngnick** [comment]
I updated the title a bit, because HTTPProxy already has SSL redirect for HTTPS traffic, and it's on by default.

Could I understand a little more @doddatpivotal ? You just want to be able to  do a redirect for a domain name from HTTP to HTTPS, and then have the connection TLS forwarded to the backend service? That seems like a reasonable request.

As @stevesloka says though, the tricky part will be in the details of how you ask for this, and how it's configured. We just need to make sure we're not interacting with any other features when we implement it.

**Comment by doddatpivotal** [comment]
@youngnick that is right.  I'm using this approach for dex and gangway.  I have an HTTPProxy set to tls-passthrough so that I can terminate SSL at the pod.  However, if a user accesses via http on the domain, it would be friendly to redirect them to https://.

**Comment by reddog335** [comment]
@stevesloka @doddatpivotal  Hi fellas.  I have the same exact use case.  Is this functionality available yet?

**Comment by stevesloka** [comment]
No we haven't completed this yet @reddog335. 

I just did some playing around with this and if you create a HTTPProxy with both a route & tcpproxy you can get the 301 redirect from HTTP-HTTPS. This might only work with HTTP connections, your TCP probably won't follow the HTTP redirect. 

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: echocluster
  name: tcptest
  namespace: projectcontour-roots
spec:
  routes:
  - services:
    - name: rootapp
      port: 80
    conditions:
    - prefix: /
  tcpproxy:
    services:
    - name: secureapp
      port: 80
  virtualhost:
    fqdn: local.projectcontour.io
    tls:
      passthrough: true
```

A request to: `http://local.projectcontour.io` --> 301 redirect
A request to: `https://local.projectcontour.io` --> secureapp`
