### ISSUE TITLE
Fallback and passthrough HTTPProxy directive should emit a config error.

### ISSUE THREAD

**Issue by nmathew** [projectcontour/contour#3197]
Here is the diagram:

legacy client (no SNI) <--> Contour/envoy Ingress(HttPProxy with pass-through enabled) <--> dex pod (with TLS secret configured, port 443)

Here legacy application simulates the actual application's auth & other requests to dex. that is why legacy application is directly talking to dex through contour ingress. legacy application is a robot test script.

1) HttpProxy rule:
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: dex
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: "contour"
spec:
  virtualhost:
    fqdn: auth.test.local
    tls:
      passthrough: true
      enableFallbackCertificate: true
  tcpproxy:
    services:
      - name: dex
        port: 443
        protocol: tls
```

2) TLS delegation:

```
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: delegate
  namespace: ingress-namespace                    //fallback(wildcard) certificate is in "ingress-namespace" namespace
spec:
  delegations:
    - secretName: tls-ingress
      targetNamespaces:
      - "*"
```

3) Fallback/wildcard secret configured in contour config map
from contour pod log
```
time="2020-12-11T10:11:48Z" level=info msg="enabled fallback certificate with secret: 
```

With this configuration we tested the setup.

4) with openssl tool:

> a) openssl s_client -showcerts -noservername -connect auth.test.local:443
>     this returns no certificate, ideally it should give fallback/wildcard certificate
> 
> b) openssl s_client -showcerts  -connect auth.test.local:443
>  this returns certificate for CN=auth.test.local, which is correct.
> 

5) Legacy client gives (no support for SNI )
ConnectionError:  (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))).

This error is expected because from first openssl command we were not getting any certificate.
The real question is why contour is not serving fallback certificate in pass-though ingress configuration???

In non pass-through mode, contour is serving fallback certificate for wild* domains.
