### ISSUE TITLE
gRPC route resulting in "Missing Trailers"

### ISSUE THREAD

**Issue by enyo** [projectcontour/contour#3233]
I have a contour `HTTProxy`, that I have setup to route to my gRPC server pod, that is running a gRPC server with an envoy sidecar proxy to do the translation from http -> http2.

When I expose this pod directly, my web client works perfectly.

But when I use contour as an ingress proxy, my client fails with the error message: "**Missing Trailers**".

When I inspect the responses in my browser, I can actually see that there are no trailers in the response proxied by contour:

Response With Contour ☹️ | Response Without Contour 👍
----- | -------
![image](https://user-images.githubusercontent.com/133277/103273940-c013be80-49c0-11eb-9a9a-c89e4abb39db.png) | ![image](https://user-images.githubusercontent.com/133277/103273999-e8032200-49c0-11eb-8e9e-621a8c3aec03.png)

I'm a bit lost now on how to continue debugging this, and would be very grateful for any pointers on how to fix this issue.

(On a side note, I was wondering whether still using envoy sidecars is the recommended approach with contour.)

<details>
<summary><strong>Environment</strong></summary>

- Contour version: `3.2.0`
- Kubernetes version: (use `kubectl version`):
  ```
  Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Cloud provider or hardware configuration: Same problem on digital ocean as on docker-desktop
</details>

**Comment by jpeach** [comment]
Are you trying to do GRCP over HTTP/1.1? Seems envoy's `enable_trailers` protocol option is probably needed here.

If you just want to expose a GRPC service, you need to enable TLS on the virtual host, and set the `h2` protocol on the backend [service](https://projectcontour.io/docs/v1.11.0/config/api/#projectcontour.io/v1.Service).

**Comment by enyo** [comment]
`enable_trailers` sounds like a good guess! How can I pass this option to the contour envoy proxy?

Yes I'm exposing the grpc server via http1 so that my web client can connect to it. My envoy sidecar proxy does the translation from h2 to http1 and it works fine. I've also had an envoy edge-proxy setup before I used contour, that rerouted the http1 request and that also worked fine. Only the contour proxy is failing at the moment.

**Comment by enyo** [comment]
This is the working "edge-proxy" envoy configuration that I have used before:

```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
    - name: api_listener
      address:
        socket_address: { address: 0.0.0.0, port_value: 8090 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: api_service
                            max_grpc_timeout: 0s
                http_filters:
                  - name: envoy.filters.http.router
  clusters:
    - name: api_service
      connect_timeout: 0.25s
      type: logical_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: api_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: my-deployment-api
                      port_value: 8777
```

It's simply using the `envoy.filters.http.router` filter.

So in that scenario it was `envoy (edge-proxy)` `=>` `envoy (sidecar) http1→http2` `=>` `gRPC http2 API`

This setup works completely fine, with and without the edge-proxy.

**Comment by jpeach** [comment]
> So in that scenario it was `envoy (edge-proxy)` `=>` `envoy (sidecar) http1→http2` `=>` `gRPC http2 API`

I think you'll be better off without all the conversions

`client == (http/1.1+tls) ==> contour (envoy proxy) == (http/2) ==> gRPC http2 API`

The envoy config you posted looks like what contour would generate (esp. the grpc_web) filter is there.

**Comment by enyo** [comment]
@jpeach you're a hero! That worked.

So in case anyone is experiencing this problem as well:

1. I removed the envoy sidecar proxy
2. I changed the `HTTPProxy` config to also contain the `h2c` protocol:
    ```yaml
      services:
        - name: {{ include "mylib.api.fullname" . }}
          port: {{ .Values.api.gRPC.port }}
          protocol: h2c
    ```

* * *

@jpeach so does this mean, that the envoy sidecar pattern does not work well with the convoy proxy? The reason I added it, is to have good service mesh metrics later on, although I haven't done any work in that regard. I followed the advice of a lyft talk from a few years back.

I also have other gRPC services that I only use internally (inside the kubernetes cluster), so they aren't proxied through contour. Would I then only use envoy proxies for these services and expose the other ones directly?

Thanks a lot!
