### ISSUE TITLE
default answer when trying external IP

### ISSUE THREAD

**Issue by net-brain** [projectcontour/contour#3238]
**What steps did you take and what happened:**
When I call the external IP of the envoy proxy I get my first defined http site back. I'm wondering why this happens

**What did you expect to happen:**
I expect a not found answer in my browser 

**Environment:**

- Contour version: 1.11
- Kubernetes version: (use `kubectl version`): 1.19.6
- Kubernetes installer & version: kubeadm 1.19.6
- Cloud provider or hardware configuration: bare metal with metallb load balancer
- OS (e.g. from `/etc/os-release`): ubuntu 20.04

**Comment by sunjayBhatia** [comment]
Could you give us some more information on your Ingress/HTTPProxy resources look like?

**Comment by erwbgy** [comment]
Normally when you create an Ingress/HTTPProxy and the Service doesn't exist you get a 404 Not Found error back.

But there is an odd quirk if an Ingress object without an FQDN exists - like this:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: clark
  annotations:
    kubernetes.io/ingress.class: contour
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: echo
          servicePort: 80
```
where instead of getting 404's back the service defined in this ingress (echo in this case) is called instead.  Perhaps this is what you're seeing.

This caused us several weeks of head scratching and confusion for lots of our users :-)
