### ISSUE TITLE
How to TCP Proxy?

### ISSUE THREAD

**Issue by chriscardillo** [projectcontour/contour#3247]
Hello and thanks for making this awesome product!

I have been learning k8s locally using kind, and I would like to be able to access a service from `localhost:5678`. I have tried looking over some tutorials and the docs, but I cannot figure out how to do it.

I have a basic HTTPProxy working with the virtual host `local.projectcontour.io`, but I am unsure how to:

1. Use `localhost` instead of `local.projectcontour.io`
2. Use `tcproxy` instead of `routes` to get the proxy listening on :5678

I am also having trouble understanding what my `virtualhost` would have to become if I were to move to a service like AWS EKS?

Thanks in advance for your help here, please see my manifest below:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:0.2.3
        args:
        - "-text=heyguys"
        livenessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5678
  selector:
    app: app
  type: ClusterIP
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: root
spec:
  virtualhost:
    fqdn: local.projectcontour.io
  routes:
  - services:
    - name: app
      port: 80
    conditions:
      - prefix: /
---
```

I was trying something along the lines of:

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: tcpprox
spec:
  virtualhost:
    fqdn: local.projectcontour.io
  tcpproxy:
    services:
      - name: app
        port: 5678
```

but no luck.

Thanks again!

**Comment by youngnick** [comment]
Thanks for checking Contour out @chriscardillo, and thanks for the issue.

So, `local.projectcontour.io` is just a convenience DNS record that just resolves to `127.0.0.1` - that is, the same address as `localhost`. So you can use those two names totally interchangeably.

Your config looks good, for exposing your app that's running on `5678` on the HTTP port `80`, that's in your Service definition. So the TCPProxy won't work like you expect, I think.

What are you looking to do with TCPProxy? Note that we named that wrong when we built it, really it should be called `TLSProxy`, as its main use is for forwarding sessions to services that need to terminate their own TLS.

**Comment by chriscardillo** [comment]
My overall goal is to have control over http/https ingress, as well as the ability to expose additional port services. So in sticking with the example above, I want to be able to:

- Expose the `app` service at `localhost/` (currently achieved, though I can only get it working with `127.0.0.1/`, not `localhost/`)
- Expose the `app` service at `localhost:5678` (or `127.0.0.1:5678`)

Over time, the goal would be that the `app` service would be exposed via ingress at `127.0.0.1/app` and a `db`  service would be available at a port, e.g. `127.0.0.1:5432`.

Also in general trying to understand when to use Kubernetes' `networking.k8s.io/v1 Ingress` vs Contour's `projectcontour.io/v1 HTTPProxy`.

I also realized it may be beneficial if I shared my kind config with you, as well!

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  - containerPort: 5678
    hostPort: 5678
    protocol: TCP
- role: worker
```

Thanks again! I realize this is maybe a broader help-desk type question, so I appreciate you taking the time out to help.
