### ISSUE TITLE
LoadBalancerService Network Publishing e2e Test Coverage

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour#3306]
**Please describe the problem you have**
Expand e2e test coverage to support the LoadBalancerService network publishing type. Currently, e2e tests only cover the NodePortService type because [kind](https://kind.sigs.k8s.io/) is being used to expose the Envoy service via host ports:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 30080
    hostPort: 80
    listenAddress: "0.0.0.0"
  - containerPort: 30443
    hostPort: 443
    listenAddress: "0.0.0.0"
```

The following references indicate that kind can be used in conjunction with [MetalLB](https://metallb.universe.tf/) to support LoadBalancer services:
- https://mauilion.dev/posts/kind-metallb/
- https://www.thehumblelab.com/kind-and-metallb-on-mac/

xref: https://github.com/projectcontour/contour-operator/pull/190
