### ISSUE TITLE
[bug/documentation] Rate limiting docs have invalid resource yaml

### ISSUE THREAD

**Issue by paulczar** [projectcontour/contour#3318]
**What steps did you take and what happened:**

In https://projectcontour.io/docs/v1.12.0/config/rate-limiting/#headers, the rate limit policy is:

```yaml
    rateLimitPolicy:
      local:
        requests: 20
        unit: minute
        responseHeadersToAdd:
        - name: x-contour-ratelimited
          value: true
```

when applied it gets the following error:  `The HTTPProxy "rate" is invalid: spec.routes.rateLimitPolicy.local.responseHeadersToAdd.value: Invalid value: "boolean": spec.routes.rateLimitPolicy.local.responseHeadersToAdd.value in body must be of type string: "boolean"`

it should be:

```yaml
    rateLimitPolicy:
      local:
        requests: 20
        unit: minute
        responseHeadersToAdd:
        - name: x-contour-ratelimited
          value: "true"
```
