### ISSUE TITLE
[Bug/Documentation] - bug in contour operator quickstart

### ISSUE THREAD

**Issue by paulczar** [projectcontour/contour#3319]
**What steps did you take and what happened:**

in the https://projectcontour.io/getting-started/ it gives instructions for using the Operator

```
kubectl apply -f https://projectcontour.io/quickstart/operator.yaml
```

and 

```
kubectl apply -f https://projectcontour.io/quickstart/contour-custom-resource.yaml
```

and specifies:

```
Deploying Contour using either option creates:
A Service of type: LoadBalancer that points to the Contour’s Envoy instances
```

This is inaccurate as the custom resource spec asks for a nodeport

```
apiVersion: operator.projectcontour.io/v1alpha1
kind: Contour
metadata:
  name: contour-sample
spec:
  networkPublishing:
    envoy:
      type: NodePortService
```

The documentation should be updated to reflect that its a nodeport, or the example should be changed to:

```
apiVersion: operator.projectcontour.io/v1alpha1
kind: Contour
metadata:
  name: contour-sample
spec:
  networkPublishing:
    envoy:
      type: LoadBalancerService
```
