### ISSUE TITLE
Contour ignores key field of genericKey for global rateLimitPolicy

### ISSUE THREAD

**Issue by SimonVHB** [projectcontour/contour#3443]
**What steps did you take and what happened:**
When applying a rateLimitPolicy on an HTTPProxy using a `genericKey` entry, the `key` field of the `genericKey` is ignored and the default value (`generic_key`) is passed on to the RLS.

Example configuration (using a kuard deployment as example and the envoy ratelimit service).

*HTTPProxy*
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  virtualhost:
    fqdn: local.projectcontour.io
    rateLimitPolicy:
      global:
        descriptors:
          - entries:
            - genericKey:
                key: foo
                value: bar
  routes:
  - services:
    - name: kuard
      port: 80
```

*Envoy ratelimit config*
```
domain: contour
descriptors:
  - key: foo
    value: bar
    rate_limit:
      unit: minute
      requests_per_unit: 100
```

*Envoy ratelimit debug logs*
```
level=debug msg="starting cache lookup"
level=debug msg="returning normal response"
level=debug msg="got descriptor: (generic_key=bar)"
level=debug msg="starting get limit lookup"
level=debug msg="looking up key: generic_key_bar"
level=debug msg="looking up key: generic_key"
level=debug msg="descriptor does not match any limit, no limits applied"
```

**What did you expect to happen:**
Contour should set the genericKey key value properly and pass that value on to the RLS.
The RLS should get the following descriptor:
```
descriptor: (foo=bar)
```
instead of
```
descriptor: (generic_key=bar)
```

**Anything else you would like to add:**
This happens for a RL policy defined on the virtualhost as well for a RL policy defined at the route.

**Environment:**

- Contour version: v1.13.1
- Kubernetes version: (use `kubectl version`): v1.19.4+k3s1
- Kubernetes installer & version: k3d
- Cloud provider or hardware configuration: k3d local test cluster
- OS (e.g. from `/etc/os-release`): /
