### ISSUE TITLE
Ingress: Should default backend be merged with or overridden by Ingress rules

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#3461]
Ingress resources have the ability to configure set a default backend: https://kubernetes.io/docs/concepts/services-networking/ingress/#default-backend

You can also choose to not configure a host on an Ingress rule and use a prefix path of `/` to match all requests: https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-rules

These two concepts technically conflict and need proper resolution logic

Open questions:
- Does the default backend "win"?
- Does the ingress rule "win"? - *seems like this should be the correct answer to me*
- If multiple Ingresses are present, which configuration wins? - currently the Ingress that is processed last "wins"
- Should these backends/rules be merged?

**Comment by sunjayBhatia** [comment]
See https://github.com/projectcontour/contour/pull/3468

**Comment by youngnick** [comment]
So, I think the general rules should be:
- when there's no conflict, merge.
- when there is a conflict, more specific beats less specific. So a specifically configured item would beat a default backend.
- When two things that are equally specific match, the referred services should be load balanced across (this is the nginx-ingress behavior, and I don't think it's great, but it's either this or drop them both.)

**Comment by sunjayBhatia** [comment]
> So, I think the general rules should be:
> 
> * when there's no conflict, merge.
> * when there is a conflict, more specific beats less specific. So a specifically configured item would beat a default backend.
> * When two things that are equally specific match, the referred services should be load balanced across (this is the nginx-ingress behavior, and I don't think it's great, but it's either this or drop them both.)

Playing around with this a bit, its easy to get the simple parts of some of these rules working in isolation but when you combine them and the various possible other fields that are set on an Ingress and route within that, and then put HTTPProxy resources on top (and then eventually HTTPRoutes) it becomes much more complicated (which is also seemingly why Gateway API has some concept of oldest-wins as well).

e.g. How do we treat two Ingresses like below:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foo1
  namespace: bar
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: true
spec:
  rules:
  - http:
      paths:
      - path: "/foo"
         pathType: Prefix
         backend:
         ...
```

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foo2
  namespace: bar
  annotations:
    projectcontour.io/websocket-routes: "/foo"
    projectcontour.io/response-timeout: ....
    ingress.kubernetes.io/force-ssl-redirect: false
spec:
  rules:
  - http:
      paths:
      - path: "/foo"
         pathType: Prefix
         backend:
         ...
```

Depending on the order these two are processed, a different one may win now. Merging them doesn't really make sense since different backends might need different timeouts, might not want to websocket upgrade on one backend, TLS redirect, etc. It wouldn't be impossible to figure out some sort of reconciliation here but its a lot of complexity.

So open questions/implementation comments from me:
- We can't just merge any two Ingress path rules (see example above), but in the case we have two that are for the same path + header condition match, which one wins?
  - Is it worth trying to merge two such rules given the complexity? Can we just have one win?
  - Gateway API has the one from the resource created first as winning, currently the one that is processed last wins for us
- Implementation note: To make sure default backends do not override regular rules in previously processed Ingresses, we will have to stop combining them with the regular list of rules
  - Default backends should use a variant of `vhost.addRoute()` that does not add or merge if already exists for the same path and header match
- We are explicitly testing that HTTPProxy routes override Ingress routes if both are present for the same path/header match. Do we want to keep this as the truth?
  - Makes the most sense to me to do so
  - Would be easy to keep this, we can implement `vhost.addRoute()` with a variant to override and a variant to merge, the former would be used always in HTTPProxy etc.
