### ISSUE TITLE
Ingress: Secure GRPC Backend

### ISSUE THREAD

**Issue by juanvasquezreyes** [projectcontour/contour#3470]
I'm trying to expose a grpc port using ingress contour the grpc app it has tls enabled and it uses ca to validate the access
when I disable tls and use h2c works fine, but when I tried to expose it through httpproxy it doesnt work as expected using h2

At the service I added the annotation
projectcontour.io/upstream-protocol.h2: "14250"

my httpproxy is the following, where secretName is for the user to provide a valid ca to just connect to HTTPProxy and validation  secret is for the httpproxy to connect correctly to my backend service
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations: 
    projectcontour.io/upstream-protocol.h2: "14250"
  name: grpc-httpproxy
  namespace: observability
spec:
  virtualhost:
    fqdn: test.com
    tls:
      secretName: ingress-default-cert
  routes:  
    - services:
      - name: jaeger-collector
        port: 14250
        protocol: h2
        validation:
            caSecret: ca-tls
            subjectName: test.com
```

when I try to access from outside I got this error, but the certificate it is valid and the subjectname too
`{"level":"error","ts":1615479755.5649254,"caller":"grpc/reporter.go:74","msg":"Could not send spans over gRPC","error":"rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268436498:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_CERTIFICATE","stacktrace":"github.com/jaegertracing/jaeger/cmd/agent/app/reporter/grpc.(*Reporter).send\n\tgithub.com/jaegertracing/jaeger/cmd/agent/app/reporter/grpc/reporter.go:74\ngithub.com/jaegertracing/jaeger/cmd/agent/app/reporter/grpc.(*Reporter).EmitBatch\n\tgithub.com/jaegertracing/jaeger/cmd/agent/app/reporter/grpc/reporter.go:53\ngithub.com/jaegertracing/jaeger/cmd/agent/app/reporter.(*MetricsReporter).EmitBatch\n\tgithub.com/jaegertracing/jaeger/cmd/agent/app/reporter/metrics.go:85\ngithub.com/jaegertracing/jaeger/cmd/agent/app/reporter.(*ClientMetricsReporter).EmitBatch\n\tgithub.com/jaegertracing/jaeger/cmd/agent/app/reporter/client_metrics.go:121\ngithub.com/jaegertracing/jaeger/thrift-gen/agent.(*agentProcessorEmitBatch).Process\n\tgithub.com/jaegertracing/jaeger/thrift-gen/agent/agent.go:157\ngithub.com/jaegertracing/jaeger/thrift-gen/agent.(*AgentProcessor).Process\n\tgithub.com/jaegertracing/jaeger/thrift-gen/agent/agent.go:112\ngithub.com/jaegertracing/jaeger/cmd/agent/app/processors.(*ThriftProcessor).processBuffer\n\tgithub.com/jaegertracing/jaeger/cmd/agent/app/processors/thrift_processor.go:122\ngithub.com/jaegertracing/jaeger/cmd/agent/app/processors.NewThriftProcessor.func2\n\tgithub.com/jaegertracing/jaeger/cmd/agent/app/processors/thrift_processor.go:87"}`

If I disable the tls on the grpc app and start using h2c it works fine and even using ingress

Do you know what I'm missing here? is there an annotation missing?

contour version: contour-3.3.2 helm chart
Kubernetes: v1.19.4
