### ISSUE TITLE
HTTPRoute is not reconciled when backend service is updated

### ISSUE THREAD

**Issue by nak3** [projectcontour/contour#3476]
**What steps did you take and what happened:**

#### step-1. Create HTTPRoute before kuard service

```
cat <<EOF | kubectl apply -f -
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: kuard
  namespace: projectcontour
  labels:
    app: kuard
spec:
  hostnames:
    - "local.projectcontour.io"
  rules:
    - matches:
        - path:
            type: Prefix
            value: /
      forwardTo:
        - serviceName: kuard
          port: 80
EOF
```

__As expected__, contour produces the error at this moment:

```
time="2021-03-13T05:05:44Z" level=error msg="Service \"kuard\" does not exist in namespace \"projectcontour\"" context=GatewayAPIProcessor
```

#### step-2. Deploy kuard service

```
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kuard
  name: kuard
  namespace: projectcontour
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:1
        name: kuard
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuard
  name: kuard
  namespace: projectcontour
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard
  sessionAffinity: None
  type: ClusterIP
```

#### step-4. Access to the service (and curl hangs)

```
$ export GATEWAY=$(kubectl -n projectcontour get svc/envoy -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
$ curl -H "Host: local.projectcontour.io" -s -o /dev/null -w "%{http_code}" "http://$GATEWAY/"
(command hangs)
```

**What did you expect to happen:**

- In above scenario, HTTPRoute should be available automatically when backend service is ready.
- The error could be fixed if we update the HTTPRoute manually and trigger the controller.

**Anything else you would like to add:**

- The root cause is that controller does not watch event of k8s service so it does not trigger the reconcile event.

**Environment:**

- Contour version:

Build contour operator on main branch

```
$ kubectl get deploy -n projectcontour  contour -o yaml | grep image:
        image: docker.io/projectcontour/contour:main
```
