### ISSUE TITLE
Make gateway config optional

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3479]
Currently with GatewayAPI Contour can be configured to watch a single gateway (default: `contour/projectcontour`). 

The problem I've run into is that we have two places to configure listeners, we need to decide which parameter takes precedence if they differ.  

I propose we make the gateway config in the configuration file optional (which what @skriss said in the beginning 😁 ). If Contour finds a Gateway configured then that takes precedence and ignores the listener config flags that might be passed. If not defined then Contour does what it does today since gateway api is not in the mix.  

Contour listener config:
- `--envoy-service-http-address`
- `--envoy-service-https-address`
- `--envoy-service-http-port`
- `--envoy-service-https-port`
 
Gateway listener config:
```
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: prod-web
spec:
  gatewayClassName: acme-lb
  listeners:  
  - protocol: HTTP
    port: 80 # <----- port
  - protocol: HTTPS
    port: 443 # <----- port
```
