### ISSUE TITLE
"help wanted" - Contour behind L7 LB

### ISSUE THREAD

**Issue by Berndinox** [projectcontour/contour#3489]
I'm sarching for an equivalent of: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-forwarded-headers

--- HTTPS ---> Cloud L7 LB (SSL Offload) ------> Contour Ingress Controller ---> WordPress

I got a mixed Content Error on Wordpress, i think because HTTP_X_FORWARDED_PROTO Header is missed.
Any suggestions?
Thanks!

**Comment by patrickshan** [comment]
@Berndinox using [requestHeadersPolicy](https://projectcontour.io/docs/main/config/request-rewriting/) to rewrite that header might solve your problem ?

**Comment by Berndinox** [comment]
Yeah that's it - thanks @patrickshan 

If someone else is coming here.
_Tags: Wordpress, Contour, Mixed-Content, SSL-Termination_

Bitnami/Wordpress: value.yaml
`wordpressScheme: http`

HTTPPROXY:
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: wp-test-ing
  namespace: wp-test
spec:
  virtualhost:
    fqdn: test.berndklaus.at
  routes:
   - services:
     - name: wp-test-wordpress
       port: 80
       requestHeadersPolicy:
         set:
         - name: X-Forwarded-Proto
           value: https
```
