### ISSUE TITLE
net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)

### ISSUE THREAD

**Issue by vacheli** [projectcontour/contour#3514]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: 1.131.
- Kubernetes version: (use `kubectl version`): v1.20.4
- Kubernetes installer & version: v1.20.4
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):  Ubuntu 20.04.2 LTS

Ingress config:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: test
  name: hubble-ui
  namespace: kube-system
spec:
  rules:
  - host: hubble-ui.tt.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: hubble-ui
            port:
              number: 80
```

**Comment by youngnick** [comment]
Thanks for this issue @vacheli, I think we'll need a little more than that though. Where is this error found?

**Comment by vacheli** [comment]
> Thanks for this issue @vacheli, I think we'll need a little more than that though. Where is this error found?

![image](https://user-images.githubusercontent.com/5040231/112457705-f9c54d00-8d96-11eb-9dc5-a105b679c53f.png)

Using chrome access this web.

**Comment by youngnick** [comment]
Okay, thanks for that. That error says that the transfer is being cut off partway through. Really, the only way I'd see that happening is if the transfer is taking a long time, the Envoy timeouts don't match your usage profile, or there's an issue with the underlying CNI.

I've never seen anything like this before, so I'm not sure where to go from here. Could you tell me more about your install? How is Envoy installed? Your screenshot mentions Cilium, do you have any network policies that might affect the traffic?

**Comment by vacheli** [comment]
> Okay, thanks for that. That error says that the transfer is being cut off partway through. Really, the only way I'd see that happening is if the transfer is taking a long time, the Envoy timeouts don't match your usage profile, or there's an issue with the underlying CNI.
> 
> I've never seen anything like this before, so I'm not sure where to go from here. Could you tell me more about your install? How is Envoy installed? Your screenshot mentions Cilium, do you have any network policies that might affect the traffic?

helm -n ingress-contour install contour bitnami/contour \
--set ingressClass=test

**Comment by vacheli** [comment]
The issue was resolved. Because of duration timeout
```
[2021-03-26T06:09:22.613Z] "POST /api/ui.UI/GetEvents HTTP/1.1" 200 UT 500 1089144 14999 10 "172.17.36.201" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "b5e0ddcc-0442-4400-b1c2-7700af15722e" "hubble-ui.tt.com" "10.0.0.51:8081"
```

Change timeoutPolicy's response and idle to infinity
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    kubernetes.io/ingress.class: test
  name: hubble-ui
  namespace: kube-system
spec:
  virtualhost:
    fqdn: hubble-ui.cowelltech.com
  routes:
    - conditions:
      - prefix: /
      timeoutPolicy:
        response: infinity
        idle: infinity
      services:
        - name: hubble-ui
          port: 80
```
