### ISSUE TITLE
Add more UX around TCP/HTTP interaction with HTTPProxy

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3542]
It's possible to mix HTTP & TCP routes in a single HTTPProxy object, but the TCPProxy bits take precedence since I think it matches the Envoy filters first leaving any HTTP configurations to be ignored. 

We should look at adding more validation logic to make sure that if someone configures a single fqdn with both http & tcp connections, that the http one's are going to be ignored. 

Example of `/` & `/foo` won't get routed, all tls requests will go to the `secureapp` service.

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: echocluster
  name: tcptest
  namespace: projectcontour-roots
spec:
  routes:
  - services:
    - name: rootapp
      port: 80
    conditions:
    - prefix: /
  - services:
    - name: rootapp
      port: 80
    conditions:
    - prefix: /foo
  tcpproxy:
    services:
    - name: secureapp
      port: 80
  virtualhost:
    fqdn: local.projectcontour.io
    tls:
      secretName: tlssecret
```
