### ISSUE TITLE
unable to write secrets with certgen

### ISSUE THREAD

**Issue by vinzo99** [projectcontour/contour#3547]
Hello,

trying to deploy new Contour 1.14 along with Envoy 1.17.1, in my namespace `vbertell`, using template yaml charts from https://raw.githubusercontent.com/projectcontour/contour/release-1.14/examples/render/contour.yaml

Installation fails because certgen Job fails to write certificates in namespace :  
```
# kubectl -n vbertell get pod
NAME                                      READY   STATUS              RESTARTS   AGE
contour-6ff6ccc699-45pgj                  0/1     ContainerCreating   0          16m
contour-6ff6ccc699-vlfpf                  0/1     ContainerCreating   0          16m
contour-certgen-v1.14.0-ddjkz             0/1     Error               0          16m
contour-certgen-v1.14.0-jvmnm             0/1     Error               0          16m

# kubectl -n vbertell logs contour-certgen-v1.14.0-jvmnm
Writing "compact" format Secrets to namespace "vbertell"
time="2021-04-06T14:17:47Z" level=fatal msg="failed output certificates" error="failed to write certificates to \"vbertell\": secrets \"contourcert\" is forbidden: User \"system:serviceaccount:vbertell:contour-certgen\" cannot update resource \"secrets\" in API group \"\" in the namespace \"vbertell\""

```
I had a look at the RBAC section in the yaml files (ServiceAccount, RoleBinding and Role), everything seems fine to me since `secrets` resources are allowed for `create` and `update` verbs : 

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contour-certgen
#  namespace: projectcontour
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: contour
#  namespace: projectcontour
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: contour-certgen
subjects:
- kind: ServiceAccount
  name: contour-certgen
  namespace: projectcontour
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: contour-certgen
#  namespace: projectcontour
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
---
```

Can you please advise ?

Thanks !

**Comment by sunjayBhatia** [comment]
Looks like the `RoleBinding` was not applied to the `ServiceAccount` in the correct namespace? Given this:

```
subjects:
- kind: ServiceAccount
  name: contour-certgen
  namespace: projectcontour
```

Is not:

```
subjects:
- kind: ServiceAccount
  name: contour-certgen
#  namespace: projectcontour
  namespace: {{ .Release.Namespace }}
```
