### ISSUE TITLE
requestHeadersPolicy to rewrite host per service does not work

### ISSUE THREAD

**Issue by nak3** [projectcontour/contour#3565]
**What steps did you take and what happened:**

- Setting requestHeadersPolicy to rewrite host per service does not work.
- For example, if you replace HTTPProxy in `017-host-header-rewrite.yaml` with the following config, the CI fails.

In `_integration/testsuite/httpproxy/017-host-header-rewrite.yaml`, change HTTPProxy to:

#### Work
```
kind: HTTPProxy
metadata:
  name: hostrewrite
spec:
  virtualhost:
    fqdn: hostrewrite.projectcontour.io
  routes:
  - services:
    - name: ingress-conformance-echo
      port: 80
    requestHeadersPolicy:
      set:
      - name: Host
        value: rewritten.com
```

#### Not work
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: hostrewrite
spec:
  virtualhost:
    fqdn: hostrewrite.projectcontour.io
  routes:
  - services:
    - name: ingress-conformance-echo
      port: 80
      requestHeadersPolicy:
        set:
        - name: Host
          value: rewritten.com
```

**What did you expect to happen:**

- Setting requestHeadersPolicy to rewrite host per service works.

**Anything else you would like to add:**

- https://github.com/projectcontour/contour/pull/3539 is trying to add HostRewrite for GatewayAPI, but the rewrite host per service does not work for it as well.
