### ISSUE TITLE
Is there a way to create NLB with target type as IP instead of Instance

### ISSUE THREAD

**Issue by ashwanth1109** [projectcontour/contour#3580]
Hi, I have an EKS cluster where I create a contour load balancer with the following yml:
```
apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: contour-external
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3999"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "false"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "6"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: XXX
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-2016-08
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    networking.knative.dev/ingress-provider: contour
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
    - port: 443
      name: https
      protocol: TCP
      targetPort: 80
  selector:
    app: envoy
  type: LoadBalancer
```

The target group created for the load balancer on AWS has a target type of `Instance`. I am looking to create a load balancer which has target group with type `IP` mode instead. Is there any annotation that I can set to switch the mode?

For additional reference, AWS Load Balancer Controller allows you to set the option: `service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"`. I dont see any reference for setting this option nor does it work when I try it.

https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/service/nlb_ip_mode/
https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/how-it-works/#ingress-traffic

Appreciate the help!
