### ISSUE TITLE
Deploying two HTTPRoutes gets 404 from one of them

### ISSUE THREAD

**Issue by nak3** [projectcontour/contour#3591]
**What steps did you take and what happened:**

#### 1. Deploy operator and gateway(node port)

```
$ kubectl apply -f examples/operator/operator.yaml 
$ kubectl apply -f examples/gateway/gateway-nodeport.yaml 
```

#### 2. Create two Kuard svc&deploy (Kuard1 and Kuard2)

kuard1

```
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kuard1
  name: kuard1
  namespace: projectcontour
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuard1
  template:
    metadata:
      labels:
        app: kuard1
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:1
        name: kuard
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuard1
  name: kuard1
  namespace: projectcontour
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard1
  sessionAffinity: None
  type: ClusterIP
EOF
```

kuard2

```
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kuard2
  name: kuard2
  namespace: projectcontour
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuard2
  template:
    metadata:
      labels:
        app: kuard2
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:1
        name: kuard
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuard2
  name: kuard2
  namespace: projectcontour
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard2
  sessionAffinity: None
  type: ClusterIP
EOF
```

#### 3. Deploy two HTTPRoute for kuard1 and kuard2

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.x-k8s.io/v1alpha1
kind: HTTPRoute
metadata:
  labels:
    app: kuard
  name: kuard1
  namespace: projectcontour
spec:
  gateways:
    allow: SameNamespace
  hostnames:
  - kuard1.projectcontour.io
  rules:
  - forwardTo:
    - port: 80
      serviceName: kuard1
---
apiVersion: networking.x-k8s.io/v1alpha1
kind: HTTPRoute
metadata:
  labels:
    app: kuard
  name: kuard2
  namespace: projectcontour
spec:
  gateways:
    allow: SameNamespace
  hostnames:
  - kuard2.projectcontour.io
  rules:
  - forwardTo:
    - port: 80
      serviceName: kuard2
EOF
```

#### 4. Access to the URL. (kuard1 or kuar2 gets `404`).

```
$ curl -H "Host: kuard1.projectcontour.io" 172.20.0.3:30080 -o /dev/null -w '%{http_code}\n' -s
200
$ curl -H "Host: kuard2.projectcontour.io" 172.20.0.3:30080 -o /dev/null -w '%{http_code}\n' -s
404
```

__NOTE__ Sometimes (it's very rare on my end though) it works, so you can remove HTTPRoutes and retry step-3.

#### 5. If working HTTPRoute (kuard1 above case), curl to kuard2 started working.

```
$ kubectl delete httproute -n projectcontour kuard1
httproute.networking.x-k8s.io "kuard1" deleted

$ curl -H "Host: kuard2.projectcontour.io" 172.20.0.3:30080 -o /dev/null -w '%{http_code}\n' -s
200
```

**What did you expect to happen:**

In step-4, both get 200.

**Environment:**

Contour version: HEAD (deployed by https://github.com/projectcontour/contour-operator/commit/420981165fafe9d6fd8ff3076643e5af93f8af68)
