### ISSUE TITLE
Move away from Gateway Configuration in Contour Config File

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3617]
Currently, Contour requires a name/namespace of a Gateway to be [configured](https://github.com/projectcontour/contour/blob/main/examples/contour/01-contour-config.yaml#L15-L17) in the Contour configuration file. Today if this isn't configured and a user wants to use GatewayAPI, then they must set the value in the file, then restart Contour. 

We could move to use the `controller` field of the `GatewayClass` or a specific field in the `parametersRef`. This would allow the Gateway to be specified easily without needing a configuration file change / management.

**Comment by youngnick** [comment]
I think using the `controller` field in the GatewayClass is a better idea, and allows for more dynamic configuration. It's also the most Kube-y way to do it.

**Comment by stevesloka** [comment]
What would you use to specify the name/namespace? Something like: `projectcontour.io/name/namespace`? So for a gateway in the `projectcontour` namespace named `contour`, you'd have a GatewayClass like this:

```
kind: GatewayClass
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: contour-class
spec: 
  controller: projectcontour.io/contour/projectcontour
```
