### ISSUE TITLE
External TLS Upstream Returns `connection failure...BAD_ECC_CERT`

### ISSUE THREAD

**Issue by alexanderturner** [projectcontour/contour#3637]
**What steps did you take and what happened:**
I'm using contour to reverse proxy a number of external services such that it handles domain routing and certificate generation. I've been using the following manifest:
```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: vpn
  namespace: default
spec:
  routes:
    - services:
      - name: vpn
        port: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: vpn
subsets:
- addresses:
  - ip: 192.168.2.249
  ports:
  - name: app
    port: 443
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: vpn
  name: vpn
  namespace: default
  annotations:
    projectcontour.io/upstream-protocol.tls: "443"
spec:
  ports:
  - name: app
    port: 443
    protocol: TCP
    targetPort: 443
  type: ClusterIP
  clusterIP: None
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: vpn
  namespace: projectcontour
spec:
  virtualhost:
    fqdn: vpn.mydomain.com
    tls:
      secretName: wildcard
  includes:
    - name: vpn
      namespace: default
```
However most recently I've tried this with a new service with no luck. I receive the following error (in the response):
```
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435563:SSL routines:OPENSSL_internal:BAD_ECC_CERT
```

I've tried the new `spec.virtualhost.tls.clientValidation.skipClientCertValidation` field however all that does is cause the browser to request a client cert and doesn't fix the issue. Any idea? 

**What did you expect to happen:**
I would be graciously met by my VPNs login screen 

**Environment:**

- Contour version: 1.15
- Kubernetes version: (use `kubectl version`): v1.20.4+k3s1
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

**Comment by stevesloka** [comment]
Quick question @alexanderturner, does your upstream external endpoint handle the fqdn `vpn.mydomain.com`? We've had issues in the past where the host/sni doesn't get rewritten on the outgoing request and fails. You can rewrite this with the headers policy bit.

**Comment by alexanderturner** [comment]
Thanks @stevesloka, yeah it should

**Comment by alexanderturner** [comment]
Hey guys, and update with this one?

**Comment by youngnick** [comment]
Hi @alexanderturner, sorry for the delay in getting back to you. I'm sorry that I can't offer more concrete advice, we haven't seen much like this before.

From the look of the error message, it seems like OpenSSL is rejecting a certificate for some reason. Taking a look at issues I've seen in other repos, it looks like this BAD_ECC_CERT error is caused by something about the certificate itself being off.

In your setup though, you've got an SSL connection to Contour's Envoy, and then another from Envoy to the ExternalName service (this is why Steve suggested you check the hostname, as not having the backend app's certificate accept `vpn.example.com` is a common mistake we've seen).

Assuming that the hostnames are all good, it may be that you'll need to check the ciphersuites on everything, and check that the ECC variants match on entropy bits (grpc/grpc#6722 mentions P-384 can be a problem and P-256 can work for interacting between OpenSSL and BoringSSL-based implementations, which seems like it would be worth checking). Could you check what ciphers the serving certificate is using? I'm wondering if the newer certificate is using some newer ciphersuite that doesn't match up with something.

**Comment by alex1989hu** [comment]
Hello, I have just faced with this error:
>TLS error: 268435563:SSL routines:OPENSSL_internal:BAD_ECC_CERT

The certificate was issued by `cert-manager.io v1.4.0` with this configuration (snippet):

```yaml
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
    size: 384
```

The certificate key pair was loaded into application which was built with `Go v1.16.6`, HTTPS traffic served/handled by `Echo v4.4.0`.

The traffic is routed via `HTTPProxy` provided by `contour v1.17.0`.

The only working solution is to reduce key size from `384` to `256`. Once certificate has been replaced, `envoy`/`contour` no longer reports what I shared above.

Finally, I was able to load/post content from/to `Pod` behind `HTTPProxy`. I need to add that I tried `kubectl port-forward`: I can interact with `Pod` even with `384` key size.
