### ISSUE TITLE
Can Envoy connect to non-leader Contour instances and receive staled Envoy configurations?

### ISSUE THREAD

**Issue by owenthereal** [projectcontour/contour#3653]
**What steps did you take and what happened:**

Install Coutour with `kubectl apply -f https://projectcontour.io/quickstart/contour.yaml`, and add an Ingress like:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
```

Sometimes Envoy does not respond to traffic defined in `Ingress`. Deleting all `contour` pods in the `projectcontour` ns sometimes helped fix the issue.

**What did you expect to happen:**

Envoy can serve traffic as I define in Ingress.

**Anything else you would like to add:**

I have seen issues that Envoy does not always receive up-to-date configurations from the Contour controller and I am wondering whether it's due to a possibility that Envoy can connect to non-leader Contour instances for configurations. From [this blog post](https://projectcontour.io/contour-v015/#:~:text=In%20leader%20election%20mode%2C%20only,will%20not%20serve%20gRPC%20requests.), Envoy is supposed to only connect to the leader Contour instance for configurations but in the [implementation](https://github.com/projectcontour/contour/blob/f0b2a22ecc96c9f06ce6ed75f1243e49a0be6dc6/cmd/contour/serve.go#L620) non-leader Coutour instances can serve xds traffic as well. This is just my theory why sometimes the Envoy configuration is staled because Envoy connected to non-leader Contour instances for configurations that these instances do not have the latest Ingress information.

**Environment:**

- Contour version: 1.15.0
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e", GitCommit:"96780e1b30acbf0a52c38b6030d7853e575bcdf3", GitTreeState:"clean", BuildDate:"2021-03-10T21:32:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```
- Kubernetes installer & version:
See above
- Cloud provider or hardware configuration:
EKS
- OS (e.g. from `/etc/os-release`):
N/A
