### ISSUE TITLE
Websocket Timeout

### ISSUE THREAD

**Issue by ccravens** [projectcontour/contour#3692]
Websocket connections seem to be timing-out every 16s:

![image](https://user-images.githubusercontent.com/1319049/118751991-4b86d280-b830-11eb-8892-f16e6cfb751a.png)

Expected behavior is that the websocket connection maintains Pending status indefinitely and does not timeout:

![image](https://user-images.githubusercontent.com/1319049/118752059-6eb18200-b830-11eb-97a2-eba29207715b.png)

It seems this issue occurs after upgrading to Contour `1.15.0`

- Contour version: 1.15.0
- Kubernetes version: (use `kubectl version`): 1.20.4
- Kubernetes installer & version: kubeadm
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): CentOS 8

**Comment by ccravens** [comment]
May be related to this: https://github.com/envoyproxy/envoy/issues/16129

**Comment by youngnick** [comment]
Hmm, interestingly, I can't reproduce when using the following HTTPProxy:
```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: wstest
  namespace: wstest
  annotations:
    kubernetes.io/ingress.class: contour
spec:
  virtualhost:
    fqdn: wstest.youngnick.dev
    tls:
      secretName: wstestcert
  routes:
    - conditions:
      - prefix: /
      enableWebsockets: true
      services:
        - name: wstest
          port: 8010
```

If this is related to envoyproxy/envoy#16129, this would make sense, as it needs to be on a sub-path. I'll try that next.

**Comment by youngnick** [comment]
Okay, I changed the HTTPProxy as follows:
```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: wstest
  namespace: wstest
  annotations:
    kubernetes.io/ingress.class: contour
spec:
  virtualhost:
    fqdn: wstest.youngnick.dev
    tls:
      secretName: wstestcert
  routes:
    - conditions:
      - prefix: /
      enableWebsockets: true
      services:
        - name: echoserver
          port: 80
    - conditions:
      - prefix: /websocket
      enableWebsockets: true
      services:
        - name: wstest
          port: 8010
```
And I still can't get this to reproduce. @ccravens, could you try your client against this setup? I'll leave `wss://wstest.youngnick.dev/websocket` running overnight my time so you should have a chance to have a go. I think it's very unlikely, but then that rules out any issues between your client and your server. Then we can try and figure out what's different between your HTTPProxy and mine. Any chance you could post it here (or message it to me on Slack or something?)

**Comment by ccravens** [comment]
Thanks @youngnick! What I'm seeing on my end is there are essentially 2 services using 2 different HTTPProxy on 2 different pods in 2 different namespaces that are experiencing this exact behavior described in the issue. Service names are 1) app and 2) IDE. Please find below the specifics of the configurations for each.

Screenshot of the 2 services both experiencing a 16s reconnect (`ws` is app, and `services` is IDE):
![image](https://user-images.githubusercontent.com/1319049/118817616-67ff2b00-b881-11eb-9de6-870d019d908a.png)

**Service 1 - App**
----------------------
```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: app
  namespace: app
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: app
      port: 80
  - conditions:
    - prefix: /api
    services:
    - name: app
      port: 3000
  - conditions:
    - prefix: /ws
    enableWebsockets: true
    services:
    - name: app
      port: 3000
  virtualhost:
    fqdn: app.example.com
    tls:
      secretName: app-certificate
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: app
spec:
  ports:
  - name: frontend
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: api
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: app
  type: ClusterIP
```



**Service 2 - IDE**
----------------------
```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: ide
  namespace: ide
spec:
  routes:
  - conditions:
    - prefix: /
    enableWebsockets: true
    services:
    - name: ide
      port: 8080
  virtualhost:
    fqdn: ide.example.com
    tls:
      secretName: ide-wildcard-certificate
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: ide
  namespace: ide
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ide
  sessionAffinity: None
  type: ClusterIP
```

**Comment by sunjayBhatia** [comment]
in office hours we were able to find this Envoy commit: https://github.com/envoyproxy/envoy/pull/15585

if there is no `max_stream_duration` set, the route response timeout from the upstream is used, which defaults to 15s

we had @ccravens deploy Envoy 1.17 and saw the reconnects go away, with 1.18 we were able to change the https://projectcontour.io/docs/v1.15.1/config/api/#projectcontour.io/v1.TimeoutPolicy `response` timeout field to something larger than `15s` and see it reflected in the reconnects (setting to `infinity` of course made the reconnects go away entirely)

so action items and things to discuss:
- `max_stream_duration` is an HTTPConnectionManager.CommonHttpProtocolOptions field (so it is not unique to a route), do we allow this to be configured?
- Do we instead set a default request timeout when we know we have a websocket route?
- Do just we make users configure their request timeout explicitly when using websockets (the case after Envoy 1.18, because of the above change)?

**Comment by sunjayBhatia** [comment]
we still are a little confused why @youngnick was not able to repro the issue, we may need to do some checks between environments potentially

**Comment by youngnick** [comment]
Just came back to this one:
- I think we can allow configuration of `max_stream_duration`, and we should especially note its usefulness for websockets in both its docstring and the docstring field.
- Setting a default request timeout _sounds_ reasonable when we have a websocket route, but I am not sure what it should be. @ccravens, do you have any thoughts here?
- This is where we are at right now, I hope we can do better somehow. I think that at least having some note in the websocket field docs that it's important to tune some timeouts would be helpful.

**Comment by echupriyanov** [comment]
> Just came back to this one:
> 
> * I think we can allow configuration of `max_stream_duration`, and we should especially note its usefulness for websockets in both its docstring and the docstring field.

Looks like `max_stream_duration` is also useful not only for Websockets, but for gRPC streams too.
I'm trying to setup HTTPProxy for gRPC streaming service, and notice, that my service receives stream reset approximately after 15secs. Is there a way right now to tweak `max_stream_duration` for particular service/route in HTTPProxy

**Comment by skriss** [comment]
@echupriyanov I believe that per https://github.com/projectcontour/contour/issues/3692#issuecomment-845351552, as a workaround right now if you set the route's [response timeout](https://projectcontour.io/docs/v1.15.1/config/api/#projectcontour.io/v1.TimeoutPolicy) to something larger than `15s`, that will effectively be the stream timeout value for that particular route. So something like:

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: foo
  namespace: default
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: foo
      port: 8080
    timeoutPolicy:
      response: 1h
  ...
```

Note that using `response: infinity` would completely disable the timeout, though you may want something large but non-infinite in practice.

Let us know if that works for you.
