### ISSUE TITLE
HTTPProxy healthCheck does not work correctly

### ISSUE THREAD

**Issue by tannevaled** [projectcontour/contour#3779]
**What steps did you take and what happened:**
When i define an HTTPproxy pointing to a working HTTPS external service using ExternalName, it works.
As soon as i add HTTPS services for down external endpoints to simulate failure or broken region even the healthy endpoint stops working with 'no healthy upstream'.

```yaml
kind: HTTPProxy
apiVersion: projectcontour.io/v1
metadata:
  namespace: www-admin
  name: test-failure
spec:
  virtualhost:
    fqdn: test.fake-domain.local
    tls:
      secretName: test-fake-domain-local
  routes:
  - services:
    - name: apps-okd1
      port: 443
      protocol: tls
    - name: k0s-down
      port: 443
      protocol: tls
    - name: k3s-broken-pod
      port: 443
      protocol: tls
    requestHeadersPolicy:
      set:
      - name: Host
        value: test.fake-domain.local
    healthCheckPolicy:
      host: test.fake-domain.local
      path: /WAYF/style.css
      intervalSeconds: 5
      timeoutSeconds: 2
      unhealthyThresholdCount: 2
      healthyThresholdCount: 2
```
```bash
[2021-06-07 16:38:30.604][16][debug][router] [source/common/router/router.cc:425] [C1995][S16495838167004346106] cluster 'www-admin/iaas-mat-073729/443/17415fc216' match for URL '/WAYF'
[2021-06-07 16:38:30.604][16][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:1360] no healthy host for HTTP connection pool
```

**What did you expect to happen:**
I expect contour to forward the traffic to the working service and place the others (unresponsive services) in the unhealthy list.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
contour have been installed using the 4.3.6 bitnami helm chart in hostNetwork mode.
```bash
$ cat ~/helm-values/contour-ingress.yaml
envoy:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  service:
    type: ''
    externalTrafficPolicy: ''
  logLevel: debug
```
**Environment:**

- Contour version: docker.io/bitnami/contour:1.16.0-debian-10-r0
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-13T02:40:46Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s1", GitCommit:"75dba57f9b1de3ec0403b148c52c348e1dee2a5e", GitTreeState:"clean", BuildDate:"2021-05-21T16:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version: k3s-installer.sh,  kubeletVersion v1.21.1+k3s1
- Cloud provider or hardware configuration: no cloud provider. VM
- OS (e.g. from `/etc/os-release`):

$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by stevesloka** [comment]
Hey @tannevaled! I think this is the same issue described here (https://github.com/projectcontour/contour/issues/1119).

The problem is that Envoy doesn't treat an entire unhealthy cluster as bad and still tried to route to it. I have some ideas on how to solve (https://github.com/projectcontour/contour/issues/1119#issuecomment-503149684), but we need to just get together a design and implement that to fix this up.

I agree that this is confusing and should have at least been better documented. Let me look into this a bit to see if Envoy has a better way to solve this today or if we need to implement one of the other solutions described in #1119.

**Comment by stevesloka** [comment]
Hey @tannevaled! 

The problem is that when you have multiple clusters in Envoy with weights and active health checks for a cluster. If all instances of that cluster go unhealthy, Envoy still tries to route to them.  In Contour, a Kubernetes service maps more-or-less to a cluster in Envoy. To fully solve this, we need to rework how Contour manages clusters in Envoy, by making a set of endpoints that match a route end up being a cluster in Envoy. 

I'd expect a weight of zero would not route to the service. That should work without healthchecks enabled. If not, could you share your HTTPProxy config so I can try and recreate it?

**Comment by tannevaled** [comment]
Here it is:
```yaml
kind: HTTPProxy
apiVersion: projectcontour.io/v1
metadata:
  namespace: www-admin
  name: test-failure
spec:
  virtualhost:
    fqdn: test.fake-domain.local
    tls:
      secretName: test-fake-domain-local
  routes:
  - services:
    - name: apps-okd1
      port: 443
      protocol: tls
    - name: k0s-down
      port: 443
      protocol: tls
      weight: 0
    - name: k3s-broken-pod
      port: 443
      protocol: tls
      weight: 0
    requestHeadersPolicy:
      set:
      - name: Host
        value:  test.fake-domain.local
        #    healthCheckPolicy:
        #      host: test.fake-domain.local
        #      path: /WAYF/style.css
        #      intervalSeconds: 5
        #      timeoutSeconds: 2
        #      unhealthyThresholdCount: 2
        #      healthyThresholdCount: 2
```
