### ISSUE TITLE
HTTPProxy with tcpproxy and routes results in 301 moved permanently

### ISSUE THREAD

**Issue by tsaarni** [projectcontour/contour#3800]
The description of `HTTPProxy.spec.routes` says

> If TCPProxy is present, Routes is ignored.

But this is not fully true currently.  The code processes routes regardless, and it can be even observed externally.  If I define `HTTPProxy` with `tcpproxy` and `routes`

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: protected
spec:
  virtualhost:
    fqdn: protected.127-0-0-101.nip.io
    tls:
      secretName: ingress
  routes:
    - services:
        - name: echoserver-1
          port: 80
  tcpproxy:
    services:
      - name: echoserver-2
        port: 80
```

and I make request to `http://protected.127-0-0-101.nip.io/` the result is `HTTP/1.1 301 Moved Permanently`
with `location: https://protected.127-0-0-101.nip.io/` header set in the response.  On the other hand, if I remove the `routes` from the spec, then the result is `HTTP/1.1 404 Not Found`  (or if this was the only `HTTPProxy`, then HTTP listener is removed completely).

I looked up the code and found that [computeHTTPProxy()](https://github.com/projectcontour/contour/blob/caedf100b83d37b83650a4322f62da6d115a2843/internal/dag/httpproxy_processor.go#L304) does continue to proces `routes`, even after `tcpproxy` was recognized - it does not ignore routes.   The resulting routes will not be added to secure virtualhost, but they are added to insecure virtualhost, which will result in the HTTPS upgrade as shown above.  The redirect is of course not working.

The above behavior seems unintentional to me. Couldn't we just stop processing routes completely in this case? On the other hand, there are some signs in [tcpproxy_test.go](https://github.com/projectcontour/contour/blob/caedf100b83d37b83650a4322f62da6d115a2843/internal/featuretests/v3/tcpproxy_test.go#L346) that seem to suggest otherwise, though I did not fully understand that test. So maybe there is something I missed.

**Comment by tsaarni** [comment]
I bumped in the above since I wanted to come back to implement the easiest parts of [httpproxy-conflict.md](https://github.com/projectcontour/contour/blob/main/design/httpproxy-conflict.md) (missing include, missing service). While looking impacts to tests, I've found this issue.

**Comment by skriss** [comment]
Would be good to get @youngnick or @stevesloka's input here, I'm not 100% sure if this is intentional or not.

**Comment by youngnick** [comment]
I think this is a great example of where we've assumed that `TCPProxy` was really `TLSProxy`, intended for passing through HTTPS traffic to the backend service. The fact that it's *named* `TCPProxy` rather than `TLSProxy` really contributes to this misunderstanding.

For that use case, it definitely makes sense for the automatic redirect to be present. I think that, given that TCPProxy is explicitly designed for forwarded-HTTPS use cases, we should keep it, and document turning it off for non-HTTP TCPProxies.

So, I think that means the rules should be:
- unless disabled, TCPProxy routes will generate a HTTP 301 redirect by default on the insecure port for HTTP requests matching that `Host` header.
- When a `tcpproxy` stanza is present, no further routes should be processed (as documented originally)
- All tests should be updated to lock in this behavior.

**Comment by tsaarni** [comment]
> So, I think that means the rules should be:

Thanks @youngnick. Here is a summary of changes that I see would result from this. Please correct me if misunderstood.

**(1)** Given following spec, `301 Moved Permanently` redirect shall be generated.  The response shall be given to any request with `Host` header matching with the FQDN.

Change to current behavior:
* currently `404 Not Found` is returned

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: protected
spec:
  virtualhost:
    fqdn: protected.127-0-0-101.nip.io
    tls:
      secretName: ingress
  tcpproxy:
    services:
      - name: echoserver-2
        port: 80
```



**(2)** Given following spec (with both `spec.tcpproxy` and  `spec.routes`) the `routes` section shall not be processed, like documented currently.  

Changes to the current behavior:
* Redirects are not anymore programmed according to `routes[].conditions`. We will still have `301 Moved Permanently` response but it will be result of (1) - there will be no means to set conditions anymore.
* It will not be possible to "poke a hole" anymore by using `permitInsecure: true` when `spec.tcpproxy` is present

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: protected
spec:
  virtualhost:
    fqdn: protected.127-0-0-101.nip.io
    tls:
      secretName: ingress
  routes:
    - conditions:
      - prefix: /foo
      services:
        - name: echoserver-1
          port: 80
      permitInsecure: true
  tcpproxy:
    services:
      - name: echoserver-2
        port: 80
```


> unless disabled, TCPProxy routes will generate a HTTP 301 redirect by default on the insecure port for HTTP requests matching that Host header.

How would it be disabled?  I did find any switch currently for that, so I feel I missed something :)

**Comment by youngnick** [comment]
Yes, you're right, there's no way to disable the automatic redirect at the moment for tcpproxy services, without using `permitInsecure`. I must have been thinking of that workaround when I wrote that, sorry.

Maybe we should consider adding a field to tcpproxy that controls whether a 301 for the base domain should be generated for it?

**Comment by stevesloka** [comment]
I think we need to do the following:

1. Generate the 301 to be consistent automatically without defining anything in `routes`. If folks have HTTP services then that will work, otherwise, they can just hit the TLS listener.
2. Disable the ability to define anything in the `routes` section with a TCPProxy. If you define something there, then raise an error. 
3. Update the tests to describe this behavior. 
4. (BONUS) Look at some of the issues where folks want to disable the insecure listener and allow that so that folks who have TCP requests to a TCPProxy won't have the surface area of an insecure listener at all in Envoy.

**Comment by youngnick** [comment]
Agreed. That seems like a good set of deliverables. Your thoughts @tsaarni?

**Comment by tsaarni** [comment]
Sounds good to me as well!  

Just one question: Implementing (2) can potentially cause currently working proxies to fail. Since `routes` have been documented to be ignored when `tcpproxy` is defined, we should assume there would not be users that will be impacted by this. So implementing (2) is OK without any kind of deprecation period?

**Comment by tsaarni** [comment]
It just occurred to me that implementing (2) would rather mean we raise an error but still continue traffic. According to the goals set in [httpproxy-conflict.md](https://github.com/projectcontour/contour/blob/main/design/httpproxy-conflict.md) we will serve traffic for portions of the spec that are valid. So no backwards compatibility concerns here.   Is this correct interpretation?

**Comment by youngnick** [comment]
I don't know if we'll be able to do that; I think we should do this as a warning first when we deprecate that functionality, then remove in the next version, with big callouts in the release notes.

**Comment by tsaarni** [comment]
There seems to be also conflict between Ingress and HTTPProxy in tcpproxy mode.  How should this one work?


```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: overlapping-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echoserver-1
                port:
                  number: 80
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: tcpproxy
spec:
  virtualhost:
    fqdn: host1.127-0-0-101.nip.io
    tls:
      secretName: ingress
  tcpproxy:
    services:
      - name: echoserver-2
        port: 80
```

currently it will create following listeners
* HTTP listener that routes to `echoserver-1`  (from Ingress)
* HTTPS listener that forwards to `echoserver-2` (from HTTPProxy)


There was actually an existing test case that covered this but it had an [error](  https://github.com/projectcontour/contour/blob/71c4cb8412cc1e61f82cde2cc7ddd7c656093ee2/internal/dag/builder_test.go#L8594) which has made the test case pass.  `SecretName`should be `sec1.Name`, not `s1.Name`.
