### ISSUE TITLE
Canary deployments with Gateway API between namespaces is not working

### ISSUE THREAD

**Issue by arapulido** [projectcontour/contour#3806]
**What steps did you take and what happened:**

Sometimes is very useful to have canary deployments by deploying the new version in a different namespace, as it allows to have the same service names (first dot) in both deployments. Something like this:

<img width="933" alt="image" src="https://user-images.githubusercontent.com/925437/121881208-3b6af180-cd0f-11eb-8b19-da66ab6b94a3.png">

This is possible to do using Nginx ingress controller with annotations. I created the following two Ingress objects in each of the namespaces:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: ns1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: www.example.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service1
            port:
              number: 80
```
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: ns2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "50"
spec:
  rules:
  - host: www.example.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service1
            port:
              number: 80
```

This worked well, and 50% of the traffic was sent to the services in `ns2`.

I tried to do something similar with Contour and the new Gateway API, but this doesn't seem to work.

I tried two different things:

## Two HTTPRoute objects, each one in each of the namespaces

I created two HTTPRoute objects:

```yaml
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: httproute1
  namespace: ns1
  labels:
    app: ecommerce
spec:
  gateways:
    allow: "All"
  hostnames:
    - "www.example.org"
  rules:
    - matches:
        - path:
            type: Prefix
            value: /
      forwardTo:
        - serviceName: service1
          port: 80
          weight: 50
```

```yaml
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: httproute2
  namespace: ns2
  labels:
    app: ecommerce
spec:
  gateways:
    allow: "All"
  hostnames:
    - "www.example.org"
  rules:
    - matches:
        - path:
            type: Prefix
            value: /
      forwardTo:
        - serviceName: service1
          port: 80
          weight: 50
```

When I apply the first configuration, I get 100% of the traffic to the app running on `ns1`,  but once I apply the second configuration, then I get 100% of the traffic to the app running on `ns2`.

## Creating an external service

The second thing I tried was creating an External service for the service in `ns2`  and create a single HTTPRoute object in `ns1` that points to this external service, something like:

<img width="890" alt="image" src="https://user-images.githubusercontent.com/925437/121890411-9b1aca00-cd1a-11eb-92ec-04a1c6b9ce4c.png">

I created the following `HTTPRoute` object:

```yaml
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: httproute-external
  namespace: ns1
  labels:
    app: ecommerce
spec:
  gateways:
    allow: "All"
  hostnames:
    - "www.example.org"
  rules:
    - matches:
        - path:
            type: Prefix
            value: /
      forwardTo:
        - serviceName: service1
          port: 80
          weight: 50
        - serviceName: service1-external
          port: 80
          weight: 50
```

My external service looks like this:

```yaml
kind: Service
apiVersion: v1
metadata:
  name: service1-external
spec:
  type: ExternalName
  externalName: service1.ns2.svc.cluster.local
```

When I apply it, I get the following error:

```
  Gateways:
    Conditions:
      Last Transition Time:  2021-06-14T12:52:56Z
      Message:               service "service1-external" does not exist
      Observed Generation:   1
      Reason:                Degraded
      Status:                False
      Type:                  ResolvedRefs
      Last Transition Time:  2021-06-14T12:52:56Z
      Message:               Errors found, check other Conditions for details.
      Observed Generation:   1
      Reason:                ErrorsExist
      Status:                False
      Type:                  Admitted
```

But the service exists and it works correctly:

```sh
$ kubectl get svc service1-external

NAME                     TYPE           CLUSTER-IP   EXTERNAL-IP                         PORT(S)   AGE
service1-external   ExternalName   <none>       service1.ns2.svc.cluster.local   <none>    19h
```

This doesn't work either

**What did you expect to happen:**

To be able to split traffic between different namespaces, to ease canary deployments. Is there a way to do this? If not, should this be implemented?

**Environment:**

- Contour version: 1.16
- Kubernetes version: (use `kubectl version`): 1.20
- Kubernetes installer & version: minikube
