### ISSUE TITLE
Unable to kubectl exec into docker.io/projectcontour/contour:v1.16.0

### ISSUE THREAD

**Issue by JCzz** [projectcontour/contour#3856]
I am trying to debug Ingress returning empty reply - and would try curl from within the ingress:

Installed on KinD:
https://kind.sigs.k8s.io/docs/user/ingress/#contour

I have tried:
`kubectl exec contour-5777747db9-2bxtn -n projectcontour -it -- /bin/sh`

but ig gives:
```
kubectl exec contour-5777747db9-2bxtn -n projectcontour -it -- /bin/sh
error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "703db6ba9712dfccf21ea0d5c0cc014ecb0ae72eae23ce9cbf35df79f21ff0d5": OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown

```

Tried -- bash, ls etc. nothing - how do you get in?

You can also try:
`docker run --rm -ti docker.io/projectcontour/contour:v1.16.0 sh`

Side question: have you made contour working with Knative on KinD local [cluster?](https://knative.dev/docs/install/install-serving-with-yaml/#serving_networking-1)

**Comment by sunjayBhatia** [comment]
For security/slimming down the image, the Contour container image is a single binary in the Docker "scratch/empty" layer so there are no other tools or programs (e.g. no `sh`) available.

The Contour binary itself does not proxy requests/responses, you might have better luck looking at the Envoy daemonset logs and looking at Contour logs to see if there is anything about your Ingress resource/services that is misconfigured. If you provide an example of your Ingress configuration yaml we may be able to help with little more detail.

> Side question: have you made contour working with Knative on KinD local cluster?

knative-serving has an option to use Contour if you would like to: https://knative.dev/docs/install/knative-with-operators/#installing-the-knative-serving-component-with-different-network-layers

**Comment by JCzz** [comment]
Thanks @sunjayBhatia

I would like to follow my side question, let me know if you want me to create a new issue and if I should create it on Knative repo?

Thanks if you are still reading :-)

I have literally tried for years from time to time, and I have newer had success getting Knative running on a KinD cluster tried all network layers.

And I have just now tried using the [operator](https://knative.dev/docs/install/knative-with-operators/#installing-the-knative-serving-component-with-different-network-layers) as you suggested using contour network - normally I installed using the yaml description on Knative site.

Have you or do you know any one, who have actually got it working - please forward me if you dont know you self, thanks?

Also FYI, if I do `docker run --rm -p 8080:80 <image>` on the same server I can hit that docker container - just to let you know the conneection to the server from domain etc. is working.

I keep running into errors - just now it is:
```
curl http://helloworld-go.default.<mydomain>.dev
curl: (7) Failed to connect to helloworld-go.default.<mydomain>.dev port 80: Connection refused
```
Port 80 Connection refused, see extraPortMappings in the following script.

I can see the port is open `sudo lsof -i -P -n | grep LISTEN`

I have run the following script, and if you have KinD(Note I have 6 CPUs and 6GB) installed you should be able to just run this:

```
#!/bin/sh

# KinD Cluster
cat <<EOF | kind create cluster --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "127.0.0.1"
name: kind
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
            node-labels: "my-label1=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
EOF

# Knative

# Installing the latest release
kubectl apply -f https://github.com/knative/operator/releases/download/v0.23.0/operator.yaml

# Verify your installation
kubectl get deployment knative-operator

# Installing the Knative Serving component
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
 name: knative-serving
---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
EOF

kubectl get deployment -n knative-serving
kubectl get KnativeServing knative-serving -n knative-serving

# Contour
kubectl apply --filename https://github.com/knative/net-contour/releases/download/v0.23.0/contour.yaml

cat <<-EOF | kubectl apply -f -
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  ingress:
    contour:
      enabled: true
  config:
    network:
      ingress.class: "contour.ingress.networking.knative.dev"
EOF

kubectl --namespace contour-external get service envoy

# Configure DNS

kubectl patch configmap/config-domain \
  --namespace knative-serving \
  --type merge \
  --patch '{"data":{"<mydomain>.dev":""}}'
```
