### ISSUE TITLE
Add initial-delay parameter to shutdown-manager

### ISSUE THREAD

**Issue by r0bj** [projectcontour/contour#3897]
In my setup there is external load-balancer in front of the contour/envoy ingress controller.
```
   ┌─────────────┐       ┌─────────────┐
───| external LB |───────|envoy ingress|───── kubernetes pods
   └─────────────┘       └─────────────┘
    heatlh check (10s) ->
```
External load-balancer sends health checks (e.g. every 10s) to envoy (running as DaemonSet) and reads its readinessProbe status to determine node health.
During upgrade envoy pod needs to be restarted. After envoy pod termination is started, envoy starts draining existing connections, sets readinessProbe to fail and immediately stops from accepting new connections. So there is a period of time when envoy is not accepting new connections anymore but external load-balancer is still sending connections to this instance of envoy (because it didn't yet get response from failed envoy readinessProbe). This time period means application downtime (5xx response).

My proposition is to add `initial-delay` parameter to shutdown-manager so it could allow envoy (via its llifecycle.preStop.httpGet) still accepting new connections for another period of time (during failed readinessProbe state). Typically `initial-delay` would be set to >= external load balancer health check interval.

In this case adding `initial-delay` 10s would cause envoy to still accept new connections for another 10s and it would allow external load-balancer to notice failed backend (envoy) and remove it from the pool of healthy backends. In this way we would avoid application downtime.

What do you think? Is there any other way to achieve zero downtime upgrade of envoy?

**Comment by r0bj** [comment]
Even without external load-balancer use case described above, `initial-delay` parameter would also help with envoy graceful upgrades/restarts due to known issue with pod termination described here:
https://github.com/kubernetes/kubernetes/issues/43576
https://blog.gruntwork.io/delaying-shutdown-to-wait-for-pod-deletion-propagation-445f779a8304
https://github.com/kubernetes/ingress-nginx/issues/322
https://github.com/istio/istio/issues/7136
https://github.com/hashicorp/consul-helm/issues/866

AFAIK shutdown-manager purpose is to cleanly draining envoy, which is not to wait for pod termination propagates across kubernetes cluster network (endpoints update on nodes), am I right?

**Comment by r0bj** [comment]
As a workaround I changed preStop hook definition in envoy container from:
```
        lifecycle:
          preStop:
            httpGet:
              path: /shutdown
              port: 8090
              scheme: HTTP
```
to:
```
        lifecycle:
          preStop:
            exec:
              command:
              - bash
              - -c
              - --
              - sleep 10
              - echo
              - -ne
              - "GET /shutdown HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n"
              - '>/dev/tcp/localhost/8090'

```
It adds 10s delay (sleep) before sending `/shutdown` HTTP GET to shutdown-manager while still accepting new connections from external load-balancer. It's the time needed for an external load-balancer to notice that particular envoy instance is unhealthy (pod in termination state) and remove it from the pool.
