### ISSUE TITLE
The server header is not removed in the response headers by responseHeadersPolicy

### ISSUE THREAD

**Issue by ehdieunguyen** [projectcontour/contour#3962]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I am following the guide at https://projectcontour.io/docs/v1.18.0/config/request-rewriting/ to config responseHeaderPolicy

```
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: petstore
  namespace: application
spec:
  virtualhost:
    fqdn: petstore.contour
    tls:
      secretName: petstore
  ...
  routes:
    - conditions:
      - prefix: /
      services:
        - name: petstore
          port: 8080
          responseHeadersPolicy:
            remove:
              - x-envoy-upstream-service-time
              - server
```
![2021-08-24-175656_1229x1184_scrot](https://user-images.githubusercontent.com/39895269/130604952-b6ad63ae-9a80-410e-8124-c0328167eb88.png)

**What did you expect to happen:**

I expect that the `server` header is removed from the response headers but it was not:
![2021-08-24-175450_830x207_scrot](https://user-images.githubusercontent.com/39895269/130604698-2f784852-2c8c-48d8-ac43-120a5ec5e4c3.png)
![2021-08-24-175537_1685x515_scrot](https://user-images.githubusercontent.com/39895269/130604790-57ae1afc-adf5-4f7e-9fda-c700a3fc1415.png)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: 1.18.0
- Kubernetes version: (use `kubectl version`): 
```
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version: `minikube: v1.18.1`
- Cloud provider or hardware configuration: 
- OS (e.g. from `/etc/os-release`):
