### ISSUE TITLE
Namespace inclusion and prefix results in 404 error

### ISSUE THREAD

**Issue by Rob19999** [projectcontour/contour#4009]
Goodday,

I created a inclusion to a namespace with the prefix /test. Within that namespace a WCF application is deployed that requires all traffic to come into the root off the IIS website. I created the rewritepolicy and the api shows.  Now the moment I call a service I get a 404.

- Browse (or call from postman)
- https://<>/test/ 
- This give a http200. 
- Now I want to call a resource in a subfolder or the root https://<>/test/v10/interest.svc
- This result in a 404 error. The reason for this is that the the path it tries to find the interest.svc doesn't include the prefix and tries to find the resource in https://<>/V10/ and drops the prefix /test/
Now this is something you can fix in your application, but having over 200 application this is a challange. A lot of proxy servers can do this for your. For NGINX I could use  proxy_pas and it solves this issue. Does Contour have something similar to adress this issue?

Thank you for the response.

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: namespace-include-root
  namespace: contour
spec:
  virtualhost:
    fqdn: <>
  includes:
  - name: test
    namespace: test
    conditions:
    - prefix: /test
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: test
  namespace: test
spec:
  routes:
  - services:
    - name: test-service
      port: 80
    pathRewritePolicy:
      replacePrefix:
      - prefix: /test
        replacement: /
```

**Comment by stevesloka** [comment]
Hey @rob-elschot, when you call the 2nd time with `https://<>/test/v10/interest.svc`, does that app expect the `/test` to be in the path or not? The first app I'm assuming didn't which is why it worked.

**Comment by rob-elschot** [comment]
It looks like the application requires it. The application doesnt know the /test since it not part of the folder structure of the application hosted on IIS. So it returns https://<>/v10/interest.svc in the respronse and that gives a 404 since contour is adding the /test part. Is it possible I can add the prefix again in a response header like I do in the pathRewritePolicy?

**Comment by youngnick** [comment]
The header rewrite support does allow rewriting of response headers, so it seems like you should be able to rewrite the header on the way out, if you know all the details from the app.

**Comment by rob-elschot** [comment]
@youngnick For the smaller application this is doable but for the bigger monolits its not. I will discuss the issue with our dev teams. .NET core has middleware for this with the use of the X-Forwarded-Prefix header. Its the older .net Framework (WCF) applications that are giving trouble. Some other proxy's can solve this issue for you like NGINX does now. I was hoping contour could do the same and I mist it in the documentation.

**Comment by youngnick** [comment]
Hmm, I thought we had covered this sort of thing with header response rewriting, that should be able to rewrite the path if necessary. Could you point me at the nginx docs you mean?

**Comment by rob-elschot** [comment]
@youngnick I will look up the docs. In the meantime what header response do I need to add to get this to work in your opinion? If its just one or two I can have each team add them in there HTTPProxy.

**Comment by youngnick** [comment]
https://projectcontour.io/docs/v1.18.1/config/request-rewriting/#header-rewriting has some examples, but I would imagine that you'll want to add something like:
```yaml
  routes:
  - services:
    - name: test-service
      port: 80
      responseHeadersPolicy:
        set:
        - name: X-Some-Header
          value: somevalue
        remove:
        - X-Internal-Secret-Header
```

That will set those things on the _response_ rather than the _request_ (the request would use `requestHeadersPolicy` but could otherwise look the same.)
