### ISSUE TITLE
Header Rewriting/ CORS does not seem to work with https 

### ISSUE THREAD

**Issue by smith1994michael** [projectcontour/contour#4042]
I have tried to set a header - but unfortunately this is not displayed with any request. The same behaviour is also with CORS. The configuration is displayed as valid and other settings work - TLS termination/ load balancer with cookie/request limits. Everything I try does not lead to the desired result.

**Comment by youngnick** [comment]
Thanks for logging this issue @smith1994michael.

Could you please explain some more? It seems like you're having some issues with setting headers, but I am not sure if you are combining with CORS settings, and what you are expecting the result to look like.

Also, Including the confguration you're using (with private details edited out, of course), would be very helpful, if you can.

**Comment by smith1994michael** [comment]
Hi @youngnick 

thank you for the answer

we would like to restrict the allowed methods - for this we would have used a crosPolicy.
for certain applications we need a header / for security reasons we want to remove others.

Here is an example configuration of how we would have imagined it:
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: test
  namespace: <namespace>
spec:
  virtualhost:
    fqdn: <fqdn>
    rateLimitPolicy:
      local:
        requests: 100
        unit: minute
        responseStatusCode: 503 
    corsPolicy:
      allowOrigin:
        - "*" 
      allowMethods:
        - GET
        - POST
        - OPTIONS
    tls:
      secretName: <certificate>
      minimumProtocolVersion: "1.2"
  routes:
    - services:
      - name: <service name>
        port: 80
        requestHeadersPolicy:
          set:
            - name: X-Envoy-Hostname
              value: test
          remove:
            - server
      loadBalancerPolicy:
        strategy: Cookie

If there is something incorrect in the configuration, please let us know what the problem is.

**Comment by youngnick** [comment]
Thanks for that @smith1994michael, I edited your response to format the YAML a little better.

Looking at the header you're setting, I'm not sure that Envoy allows changing its own headers. I know we don't allow rewriting the Host header, but I would not be surprised if Envoy did not allow rewriting `X-Envoy-Hostname` as well. Could you see if you could set a different header?

Aside from that, this looks fine to me, I don't think I've seen this many HTTPProxy features used at once before though, this is a great test. :)

**Comment by smith1994michael** [comment]
Hi @youngnick 

I would have tried to rename the header to X-Envoy-Test, unfortunately it still does not work :(
also I just noticed that removing a header does not work either

If we already have these great features we should use them as well  :)

**Comment by youngnick** [comment]
Sorry, could you try without the X-Envoy? Maybe X-Contour instead, just to test if Envoy is doing any filtering of those? Because the header setting and removing definitely works with other headers, I'm trying to zoom in on what it could be. It's the end of my day, but I'll see if I can have a play tomorrow regardless.

**Comment by smith1994michael** [comment]
did not work with the other header name.
Could you recreate the mistakes?

**Comment by youngnick** [comment]
Hi @smith1994michael, sorry for the delay, I investigated this a bit today.

I don't have a ratelimit setup installed at the moment in my lab, but I recreated everything else - the CORS policy, the LoadBalancerPolicy, and the Request headers policy, and everything worked as expected.


```
❯ curl -X GET "https://contourtest1.youngnick.dev/headers" -H "accept: application/json" -H "server: somevalue"
{
  "headers": {
    "Accept": "application/json",
    "Host": "contourtest1.youngnick.dev",
    "User-Agent": "curl/7.64.0",
    "X-Envoy-Expected-Rq-Timeout-Ms": "15000",
    "X-Envoy-External-Address": "34.87.229.204",
    "X-Some-Header": "test"
  }
}
```

This request goes to a [httpbin](https://httpbin.org/) service that will respond with the headers it saw in the request.

You can see in the Curl command, I'm setting a `server` header to `somevalue`, and the httpbin response has had it removed. In addition, there is an `X-Some-Header` set to `test` as part of the configuration.

I'm using the following HTTPProxy:


```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: requestheaders
  namespace: default
spec:
  virtualhost:
    fqdn: contourtest1.youngnick.dev
    # rateLimitPolicy:
    #   local:
    #     requests: 100
    #     unit: minute
    #     responseStatusCode: 503 
    corsPolicy:
      allowOrigin:
        - "*" 
      allowMethods:
        - GET
        - POST
        - OPTIONS
    tls:
      secretName: contourtest1
      minimumProtocolVersion: "1.2"
  routes:
    - services:
      - name: httpbin
        port: 80
        requestHeadersPolicy:
          set:
            - name: X-Some-Header
              value: test
          remove:
            - server
      loadBalancerPolicy:
        strategy: Cookie
```

Could you try your config without the rate limit policy and see if you have any success? If you don't have problems, I'll bring up a ratelimit install and test that as well.
