### ISSUE TITLE
Contour HTTPRoute TCPServer with SNI Envoy Exiting

### ISSUE THREAD

**Issue by lou-lan** [projectcontour/contour#4127]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

server code
```go
import (
	"daoapp/pkg/tcp_server"
	"fmt"
	"os"
)

func main() {
	server := tcp_server.New(os.Getenv("ADDR"))

	server.OnNewClient(func(c *tcp_server.Client) {
		// new client connected
		// lets send some message
		c.Send("Hello")
	})
	server.OnNewMessage(func(c *tcp_server.Client, message string) {
		// new message received
		fmt.Printf("new message: %s\n", message)
	})
	server.OnClientConnectionClosed(func(c *tcp_server.Client, err error) {
		// connection with client lost
		fmt.Printf("client connection closed\n")
	})

	server.Listen()
}
```
```go
package tcp_server

import (
	"bufio"
	"crypto/tls"
	"log"
	"net"
)

// Client holds info about connection
type Client struct {
	conn   net.Conn
	Server *server
}

// TCP server
type server struct {
	address                  string // Address to open connection: localhost:9999
	config                   *tls.Config
	onNewClientCallback      func(c *Client)
	onClientConnectionClosed func(c *Client, err error)
	onNewMessage             func(c *Client, message string)
}

// Read client data from channel
func (c *Client) listen() {
	c.Server.onNewClientCallback(c)
	reader := bufio.NewReader(c.conn)
	for {
		message, err := reader.ReadString('\n')
		if err != nil {
			c.conn.Close()
			c.Server.onClientConnectionClosed(c, err)
			return
		}
		c.Server.onNewMessage(c, message)
	}
}

// Send text message to client
func (c *Client) Send(message string) error {
	return c.SendBytes([]byte(message))
}

// SendBytes send bytes to client
func (c *Client) SendBytes(b []byte) error {
	_, err := c.conn.Write(b)
	if err != nil {
		c.conn.Close()
		c.Server.onClientConnectionClosed(c, err)
	}
	return err
}

func (c *Client) Conn() net.Conn {
	return c.conn
}

func (c *Client) Close() error {
	return c.conn.Close()
}

// OnNewClient called right after server starts listening new client
func (s *server) OnNewClient(callback func(c *Client)) {
	s.onNewClientCallback = callback
}

// OnClientConnectionClosed called right after connection closed
func (s *server) OnClientConnectionClosed(callback func(c *Client, err error)) {
	s.onClientConnectionClosed = callback
}

// OnNewMessage called when Client receives new message
func (s *server) OnNewMessage(callback func(c *Client, message string)) {
	s.onNewMessage = callback
}

// Listen starts network server
func (s *server) Listen() {
	var listener net.Listener
	var err error
	if s.config == nil {
		listener, err = net.Listen("tcp", s.address)
	} else {
		listener, err = tls.Listen("tcp", s.address, s.config)
	}
	if err != nil {
		log.Fatal("Error starting TCP server.\r\n", err)
	}
	defer listener.Close()

	for {
		conn, _ := listener.Accept()
		client := &Client{
			conn:   conn,
			Server: s,
		}
		go client.listen()
	}
}

// New creates new tcpserver server instance
func New(address string) *server {
	log.Println("Creating server with address", address)
	server := &server{
		address: address,
	}

	server.OnNewClient(func(c *Client) {})
	server.OnNewMessage(func(c *Client, message string) {})
	server.OnClientConnectionClosed(func(c *Client, err error) {})

	return server
}

func NewWithTLS(address, certFile, keyFile string) *server {
	cert, err := tls.LoadX509KeyPair(certFile, keyFile)
	if err != nil {
		log.Fatal("Error loading certificate files. Unable to create TCP server with TLS functionality.\r\n", err)
	}
	config := &tls.Config{
		Certificates: []tls.Certificate{cert},
	}
	server := New(address)
	server.config = config
	return server
}

```

client code
```go
conn, err := tls.Dial("tcp", os.Getenv("SERVER"), nil)
if err != nil {
	log.Fatal("Failed to connect to test server:", err)
}

// output
2021/10/21 15:21:43 Failed to connect to test server:dial tcp 10.6.1.66:443: connect: connection refused
```
The example, cluster ip works well.

step 1: install contour
```bash
kubectl apply -f https://projectcontour.io/quickstart/contour-gateway.yaml
```

step 2: apply tls secret

step 3: deploy tcp server
```yaml
apiVersion: v1
kind: Service
metadata:
  name: daoapp-tcp
  namespace: daoapp
spec:
  selector:
    app: daoapp-tcp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daoapp-tcp
  namespace: daoapp
  labels:
    app: daoapp-tcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daoapp-tcp
  template:
    metadata:
      labels:
        app: daoapp-tcp
    spec:
      serviceAccountName: admin
      containers:
      - name: daoapp-tcp
        image: registry.cn-shanghai.aliyuncs.com/loulan-public/daoapp-tcp-server:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        command: ["/workspace/app"]
        env:
        - name: VERSION
          value: v1.0.1
        - name: ADDR
          value: ":80"
        resources:
          limits:
            cpu: 50m
            memory: 200M
```

step 3: apply httproute
```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: daoapp-tcp
  namespace: daoapp
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: contour-tcp-proxy-ingress.daoapp.loulan.me
    tls:
      secretName: "contour-tcp-proxy-ingress-daoapp-tls-secret"
  tcpproxy:
    # loadBalancerPolicy: 
    #   strategy: RoundRobin
    services:
      - name: daoapp-tcp
        port: 443
```

step3: tail envoy log with debug level

```lua
[2021-10-21 07:21:23.029][1][warning][main] [source/server/server.cc:742] caught ENVOY_SIGTERM
[2021-10-21 07:21:23.029][1][info][main] [source/server/server.cc:863] shutting down server instance
[2021-10-21 07:21:23.029][1][info][main] [source/server/server.cc:809] main dispatch loop exited
[2021-10-21 07:21:23.041][1][warning][config] [./source/common/config/grpc_stream.h:101] StreamRoutes gRPC config stream closed: 13,
[2021-10-21 07:21:23.042][1][warning][config] [./source/common/config/grpc_stream.h:101] StreamSecrets gRPC config stream closed: 13,
[2021-10-21 07:21:23.042][1][warning][config] [./source/common/config/grpc_stream.h:101] StreamRoutes gRPC config stream closed: 13,
[2021-10-21 07:21:23.042][1][warning][config] [./source/common/config/grpc_stream.h:101] StreamSecrets gRPC config stream closed: 13,
[2021-10-21 07:21:23.042][1][warning][config] [./source/common/config/grpc_stream.h:101] StreamRoutes gRPC config stream closed: 13,
[2021-10-21 07:21:23.042][1][warning][config] [./source/common/config/grpc_stream.h:101] StreamListeners gRPC config stream closed: 13,
[2021-10-21 07:21:23.042][1][info][main] [source/server/server.cc:855] exiting
```

**What did you expect to happen:**
client can connect to server use contour ingress 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version:
```
v1.19.0
```
- Kubernetes version: (use `kubectl version`):
```lua
$ ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes installer & version:
```lua
kubeadm 
kubeadm version: &version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:37:34Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
```
VMware vSphere
```
- OS (e.g. from `/etc/os-release`):
```
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```
