### ISSUE TITLE
Weight-based tcp load balancing not work

### ISSUE THREAD

**Issue by lou-lan** [projectcontour/contour#4158]
**What steps did you take and what happened:**
Weight-based tcp load balancing not work.

**What did you expect to happen:**
Weight-based tcp load balancing can work.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: daoapp-tcp
  namespace: daoapp
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: contour-tcp-proxy-ingress.daoapp.loulan.me
    tls: 
      secretName: "contour-tcp-proxy-ingress-daoapp-tls-secret"
  tcpproxy:
    # loadBalancerPolicy: 
    #   strategy: RoundRobin
    services:
      - name: daoapp-tcp-green
        port: 80
        weight: 1 # not work
      - name: daoapp-tcp-blue
        port: 80
        weight: 10 # not work
```

```lua
$ BATCH=1 SERVER=contour-tcp-proxy-ingress.daoapp.loulan.me:443 TLS=1 ./tcpclient
got green: 87
got blue: 113
$ BATCH=1 SERVER=contour-tcp-proxy-ingress.daoapp.loulan.me:443 TLS=1 ./tcpclient
got green: 92
got blue: 108
$ BATCH=1 SERVER=contour-tcp-proxy-ingress.daoapp.loulan.me:443 TLS=1 ./tcpclient
got green: 96
got blue: 104
```

If I switch to contour's gateway-api, it works well.
```yaml
apiVersion: networking.x-k8s.io/v1alpha1
kind: TLSRoute
metadata:
  name: daoapp-tcp
  namespace: daoapp
  labels:
    app: daoapp-tcp
spec:
  rules:
    - forwardTo:
        - serviceName: daoapp-tcp-green
          weight: 10 # 
          port: 80
        - serviceName: daoapp-tcp-blue
          weight: 1 # 
          port: 80
```

```lua
$ BATCH=1 SERVER=gateway-tcp-proxy-ingress.daoapp.loulan.me:443 TLS=1 ./tcpclient
got green: 185
got blue: 15
```

**Environment:**

- Contour version:
```
v1.19.0
```
- Kubernetes version: (use `kubectl version`):
```lua
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):
