### ISSUE TITLE
LB Police `Cookie` not work

### ISSUE THREAD

**Issue by lou-lan** [projectcontour/contour#4190]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

1. Deploy two version app and `Services`

```bash
$ kubectl get pod
daoapp-a-5f56687bfc-8fhcp              1/1     Running   1 (12d ago)   20d
daoapp-a-5f56687bfc-bwthz              1/1     Running   1 (12d ago)   39d

daoapp-b-5f56687bfc-cpjn7              1/1     Running   1 (12d ago)   38d
daoapp-b-5f56687bfc-dhhx8              1/1     Running   1 (12d ago)   20d
```

2. In a browser, navigate to this route: `/`:

```lua
[a-version,b-version, a-version, b-version]
```

**What did you expect to happen:**

In a browser, navigate to this route: `/`:

```lua
[a-version, a-version, a-version, a-version]
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I am check the browser, the cookie not change, but the page switches between two versions.
```bash
$ curl https://contour-http-proxy-ingress.daoapp.loulan.me/ -v | grep "set-cookie"

< set-cookie: X-Contour-Session-Affinity="1882798dacfc4c57"; Path=/; HttpOnly

```

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: daoapp
  namespace: daoapp
spec:
  ingressClassName: contour
  routes:
  - conditions:
    - prefix: /
    loadBalancerPolicy:
      strategy: Cookie   # set loadBalancerPolicy to Cookie
    services:
    - mirror: false
      name: daoapp-a-version
      port: 443
      weight: 1
    - name: daoapp-b-version
      port: 443
      weight: 1
  virtualhost:
    fqdn: contour-http-proxy-ingress.daoapp.loulan.me
    tls:
      secretName: contour-http-proxy-ingress-daoapp-tls-secret
status:
  conditions:
  - lastTransitionTime: "2021-11-21T07:58:00Z"
    message: Valid HTTPProxy
    observedGeneration: 15
    reason: Valid
    status: "True"
    type: Valid
  currentStatus: valid
  description: Valid HTTPProxy
  loadBalancer:
    ingress:
    - ip: 10.6.1.66
```

**Environment:**

- Contour version:
```
v1.19.0
```
- Kubernetes version: (use `kubectl version`):
```lua
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):
