### ISSUE TITLE
Broken HTTP health check when using h2 protocol

### ISSUE THREAD

**Issue by jerome-quere** [projectcontour/contour#4213]
**What steps did you take and what happened:**
Enabling an HTTP Proxy like
```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: analyzer
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "labels" . | indent 4 }}
spec:
  virtualhost:
    fqdn: {{ .Values.private_ingress_hostname }}
    tls:
      secretName: analyzer-ingress-tls
      clientValidation:
        skipClientCertValidation: true
  routes:
    - conditions:
        - prefix: /
      healthCheckPolicy:
        path: /healthz
      services:
        - name: analyzer
          port: {{ .Values.analyzer_port }}
          protocol: h2
          validation:
            caSecret: contour/internal-ca
            subjectName: {{ .Values.analyzer_hostname }}
```

That generate an envoy config like
```json
  {
     "version_info": "6",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "analyzer/analyzer/8080/2fdb943f10",
      "type": "STRICT_DNS",
      "connect_timeout": "0.250s",
      "health_checks": [
       {
        "timeout": "2s",
        "interval": "10s",
        "unhealthy_threshold": 3,
        "healthy_threshold": 2,
        "http_health_check": {
         "host": "contour-envoy-healthcheck",
         "path": "/healthz"
        }
       }
      ],
      "dns_lookup_family": "V4_ONLY",
      "transport_socket": {
       "name": "envoy.transport_sockets.tls",
       "typed_config": {
        "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext",
        "common_tls_context": {
         "validation_context": {
          "trusted_ca": {
           "inline_bytes": "*************"
          },
          "match_subject_alt_names": [
           {
            "exact": "*******************"
           }
          ]
         },
         "alpn_protocols": [
          "h2"
         ],
         "tls_certificate_sds_secret_configs": [
          {
           "name": "contour/client-certificate/71c54aac07",
           "sds_config": {
            "api_config_source": {
             "api_type": "GRPC",
             "grpc_services": [
              {
               "envoy_grpc": {
                "cluster_name": "contour"
               }
              }
             ],
             "transport_api_version": "V3"
            },
            "resource_api_version": "V3"
           }
          }
         ]
        },
        "sni": "*******************"
       }
      },
      "common_lb_config": {
       "healthy_panic_threshold": {}
      },
      "alt_stat_name": "analyzer_analyzer_8080",
      "ignore_health_on_host_removal": true,
      "load_assignment": {
       "cluster_name": "analyzer/analyzer/http",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "*******************",
              "port_value": 8080
             }
            }
           }
          }
         ]
        }
       ]
      },
      "typed_extension_protocol_options": {
       "envoy.extensions.upstreams.http.v3.HttpProtocolOptions": {
        "@type": "type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions",
        "explicit_http_config": {
         "http2_protocol_options": {}
        }
       }
      }
     },
     "last_updated": "2021-12-06T10:11:43.831Z"
    }
```

The active Health Check fail on the cluster. This is probably because the TLS `h2` alpn option open an HTTP/2 connection but the HC is send using HTTP1.

**What did you expect to happen:**

The flag `codec_client_type` should probably be set to HTTP2 when ` protocol: h2[c]`  is used on the `HTTPProxy` CRD.

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/health_check.proto#config-core-v3-healthcheck-httphealthcheck

**Environment:**

- Contour version: v1.19.1
