### ISSUE TITLE
Load blancer sourceIP based tls tcpproxy does not work

### ISSUE THREAD

**Issue by lou-lan** [projectcontour/contour#4223]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: daoapp-tcp
  namespace: app
spec:
  ingressClassName: contour
  tcpproxy:
    loadBalancerPolicy:
      requestHashPolicies:
        - hashSourceIP: true
      strategy: RequestHash
    services:
      - name: app-tcp-blue
        port: 80
        weight: 1
  virtualhost:
    fqdn: contour-tcp-proxy-ingress.daoapp.loulan.me
    tls:
      secretName: contour-tcp-proxy-ingress-daoapp-tls-secret
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version:
```
ghcr.io/projectcontour/contour:main
```

- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):
