### ISSUE TITLE
Add ability for condition in HTTPProxy services to refer to downstream protocol.

### ISSUE THREAD

**Issue by GrahamDumpleton** [projectcontour/contour#4226]
**Please describe the problem you have**

I want to use Contour as a more traditional proxy where HTTP and HTTPS connections for the same virtual host can be proxied end to end rather than Contour forcing the upstream connection to be either HTTP or HTTPS. This would be used where needing to proxy through to another ingress router.

The analogous setup in something like Apache httpd server would be:

```
<VirtualHost *:80>
ServerName example.com
ServerAlias *.example.com
ProxyPass "http://backend.example.com/"
</VirtualHost>

<VirtualHost *:443>
ServerName example.com
ServerAlias *.example.com
ProxyPass "https://backend.example.com/"
</VirtualHost>
```

The ability to do this would be useful in a few circumstances.

* Where you want to deploy multiple Contour instances in the one cluster. The secondary Contour instances would use distinct ingress classes and would not use a load balancer service or hostPort, but be deployed to have the Envoy use a ClusterIP service with the frontend Contour directing traffic for some wildcard subdomain through to the secondary Contour. This arrangement would be useful for testing where one cannot create additional load balancer services, but also where an application stack (eg. as TAP was originally doing) wanted its own ingress class and didn't want to use the default ingress controller.

* Where the Kubernetes cluster is being used to deploy virtual clusters (eg., https://github.com/loft-sh/vcluster) and where each virtual cluster would have its own Contour instance so users in the virtual cluster can use Contour specific custom resource types. For this case standard Contour with load balancer service and hostPort couldn't be used as would clash with 80/443 port usage between ingress controller instances but also with many virtual clusters being created, it wouldn't be practical for all to use load balancer services because of cost.

* Where using Contour as proxy for routing traffic to ingress controllers of other separate complete Kubernetes clusters. Sort of similar to what Gimbal was doing, although it worked a bit differently by replicating Services in the front end cluster which used an externalName.

In both cases, through the frontend Contour instance being able to preserve HTTP and HTTPS connections all the way to a secondary Contour instance, it allows a user of the second Contour instance to use both HTTP and HTTPS as they see fit, rather than being forced to only being able to use either HTTP or HTTPS in Ingress/HTTPProxy for the inbound connection part from the front end Contour, which would complicate things or even prevent certain applications from working.

The possible mechanism by which this could be implemented would be to add additional condition checks on HTTPProxy for services which can check for the protocol used from the downstream (inbound) connection. Eg:

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: ports
spec:
  virtualhost:
    fqdn: *.example.com
    tls:
      secretName: xxx
  routes:
  - services:
    - name: upstream-envoy
      port: 80
    conditions:
    - prefix: /
    - protocol: HTTP
  - services:
    - name: upstream-envoy
      port: 443
    conditions:
    - prefix: /
    - protocol: HTTPS
```

Note that `protocol: HTTP` would need to imply `permitInsecure: true`.

The only alternative would be to not use Contour as the initial edge ingress controller and deploy Envoy directly and use a custom xDS server to provide dynamic routing config. In other words, reinventing what Contour already does. :-)
