### ISSUE TITLE
Problem adding timeout setting to route with multiple conditions

### ISSUE THREAD

**Issue by stumueller** [projectcontour/contour#4272]
This is our current httpproxy yaml:
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: frontend
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: localhost
  routes:
    - conditions:
      - prefix: /
      services:
        - name: web
          port: 80
    - conditions:
      - prefix: /toggle
      services:
        - name: flagr
          port: 80
    - conditions:
      - prefix: /matsweb
      services:
        - name: matsweb
          port: 80
```
Which works fine - but I can't figure out how to add
```
    - timeoutPolicy:
        response: "2m"
```
I thought it was as follows:
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: frontend
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: localhost
  routes:
    - timeoutPolicy:
        response: "2m"
    - conditions:
      - prefix: /
      services:
        - name: web
          port: 80
    - conditions:
      - prefix: /toggle
      services:
        - name: flagr
          port: 80
    - conditions:
      - prefix: /matsweb
      services:
        - name: matsweb
          port: 80
```

However this results in the following error:
error: error validating "STDIN": error validating data: ValidationError(HTTPProxy.spec.routes[0]): missing required field "services" in io.projectcontour.v1.HTTPProxy.spec.routes; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by sunjayBhatia** [comment]
I think it should look something like this (`timeoutPolicy` is a field within the `Route` object, it should be adjacent to the `conditions` field):
```
...
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: localhost
  routes:
    - timeoutPolicy:
        response: "2m"
      conditions:
      - prefix: /
      services:
        - name: web
          port: 80
...
```

**Comment by stumueller** [comment]
so how would my next condition go?
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: frontend
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: localhost
  routes:
    - timeoutPolicy:
        response: "2m"
      conditions:
      - prefix: /
      services:
        - name: web
          port: 80
    - timeoutPolicy:
        response: "2m"
      conditions:
      - prefix: /toggle
      services:
        - name: flagr
          port: 80
    - timeoutPolicy:
        response: "2m"
      conditions:
      - prefix: /matsweb
      services:
        - name: matsweb
          port: 80
```
Therefore each service could potentially have a different timeout value?
