### ISSUE TITLE
global policy set headers not applied with ingress object

### ISSUE THREAD

**Issue by r0bj** [projectcontour/contour#4285]
**What steps did you take and what happened:**
Global policy set headers is not applied to ingress objects even with `applyToIngress` option enabled.

Contour config:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: contour
data:
  contour.yaml: |
    policy:
      applyToIngress: true
      request-headers:
        set:
          X-Envoy-Hostname: "%HOSTNAME%"
```

Example with `HTTPProxy`:
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: echo
spec:
  ingressClassName: external-lb-a
  virtualhost:
    fqdn: echo.example.com
  routes:
  - conditions:
    - prefix: /
    services:
    - name: echo
      port: 8080
```

Header `X-Envoy-Hostname` is added to the request:
```
"x-envoy-hostname": "envoy-1-24lv7"
```
Live envoy config dumped from administration Interface regarding our example routing confirms that:
```
       {
        "name": "echo.example.com",
        "domains": [
         "echo.example.com"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/"
          },
          "route": {
           "weighted_clusters": {
            "clusters": [
             {
              "name": "ops/echo/8080/da39a3ee5e",
              "weight": 1,
              "request_headers_to_add": [
               {
                "header": {
                 "key": "X-Envoy-Hostname",
                 "value": "%HOSTNAME%"
                },
                "append": false
               }
              ]
             }
            ],
            "total_weight": 1
           }
          }
         }
        ]
       },
```

So far so good, let's try with ingress object instead of HTTPProxy:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo
  labels:
    app.kubernetes.io/name: echo
  annotations:
    kubernetes.io/ingress.class: external-lb-a
spec:
  rules:
  - host: echo.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echo
            port:
              number: 8080
```

There is no header `X-Envoy-Hostname` added to the request.
Live envoy config dumped from administration Interface regarding our example routing also confirms that:
```
       {
        "name": "echo.example.com",
        "domains": [
         "echo.example.com"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/"
          },
          "route": {
           "cluster": "ops/echo/8080/da39a3ee5e"
          }
         }
        ]
       },
```

**What did you expect to happen:**
Global policy set headers is applied to ingress objects with `applyToIngress` option enabled.

**Environment:**

- Contour version: v1.19.1
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T17:25:43Z", GoVersion:"go1.16.13", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
