### ISSUE TITLE
Support Envoy gRPC-JSON transcoder

### ISSUE THREAD

**Issue by derekperkins** [projectcontour/contour#4291]
All our internal services are gRPC, and we would like to move the json transcoding layer out to Envoy.
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter

IMO, the best case scenario would use gRPC server reflection to configure Envoy directly. There is an open feature request in Envoy to support definitions via reflection, and while there has been some movement recently, the issue has been outstanding for 4 years now, so I wouldn't rely on it getting shipped for the Contour implementation.
https://github.com/envoyproxy/envoy/issues/1182

There is another project that Contour could reference/use/copy if reflection is the right path to take.
https://github.com/cashapp/transflect

**Comment by hq6** [comment]
@derekperkins I'm curious, are you using Envoy as a sidecar? 
If so, do your Envoys talk to their upstreams in plain text or via SSL?

**Comment by derekperkins** [comment]
Currently we run Envoy via Contour as a DaemonSet, so no, we couldn't ensure that today. There's a long running issue about k8s ensuring container startup order, but no consensus yet. https://github.com/kubernetes/kubernetes/issues/65502

There's nothing preventing us from running an Envoy sidecar to do the transcoding, but it would be preferable if it happened at the edge. We do have a few other sidecars, and we connect over localhost without SSL.

**Comment by hq6** [comment]
If you cannot ensure that your upstream starts first, I suspect the scope of my proposed change on the other thread is insufficient for your purposes. 
I'm not sure if `transflect` will solve the problem either, since IIRC they delay injecting the Envoy sidecar until they've successfully run reflection against the service and produced proto descriptors, although you should check with them since my understanding may be incomplete.

As an aside, if it's semantically valid for your Envoy to start after your upstreams (e.g your upstream does not require Envoy to be up for egress before starting), you could wrap your Envoy start with a script that first checks that the upstream is up before starting Envoy. I have no idea if that's true for you.

If my change is accepted, I may try to propose an additional change to the filter that will allow the reflection to continue to be attempted on each new ingress request until it succeeds, which will remove the requirement for the upstream to start first. 
However, I speculate that it'll be harder to get that change approved because it will be a larger refactoring rather than merely additive. 

---

With respect to transcoding-in-Envoy running at the edge vs as a sidecar, I have two thoughts, although I know nothing about how Contour works internally, so please ignore if they're not relevant:
 * If you want to do the JSON transcoding at the edge with gRPC reflection, you'd have to figure out how to pass the Channel URIs for all the gRPC clusters that you proxy to, rather than passing just a single URI to each sidecar. This might be hard based on the answer to [this question](https://github.com/envoyproxy/envoy/issues/19477#issuecomment-1010063709).
 * Depending on your expected load, doing the transcoding at the edge may impose large memory requirements on the edge Envoys compared to if they were merely routing requests, because the transcoder buffers (as far as I know). If you do the transcoding in sidecars instead, the amount of buffering would only be proportional to the traffic served by a single service instance, rather than proportional to the traffic routed by a single edge node.

**Comment by youngnick** [comment]
I can see how the automatic reflection would be very useful, but it does sound like it would be pretty involved, and I share @hq6's concern about memory - it's really easy to have Envoy use a *lot* of memory.

That said, I also agree that without automatic reflection, this is a lot of work for Contour users to maintain the definitions that Envoy needs. @derekperkins, would you be interested in the more manual way that doesn't have automatic reflection, or would you prefer to wait?

**Comment by juanpmarin** [comment]
https://github.com/tetratelabs/istio-tools/tree/master/grpc-transcoder
I think this is a good example on how to solve it without reflection

**Comment by vkarunx** [comment]
It will be great if Contour's implementation of the Envoy control plane supported gRPC-JSON transcoding as a first class concern with the ability to upsert a dynamically generated envoy filter as easily as the patch operation in https://github.com/cashapp/transflect/blob/master/istio/envoy-filter.yaml#L24 highlighted below. Without this support, deploying a custom sidecar/gateway only for transcoding or moving to a different ingress are the only options unfortunately.

```
    patch:
      operation: INSERT_BEFORE
      value:
        name: "envoy.filters.http.grpc_json_transcoder"
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
              proto_descriptor_bin: !!binary "{{.ProtosetBase64}}"
              services:
              {{- range .Services}}
              - {{. -}}
              {{end}}
              print_options:
                add_whitespace: true
                always_print_primitive_fields: true
                always_print_enums_as_ints: false
                preserve_proto_field_names: true
```
