### ISSUE TITLE
Can't configure httpproxy with service present in other namespace

### ISSUE THREAD

**Issue by prary** [projectcontour/contour#4294]
**What steps did you take and what happened:**
I have istio-ingressgateway service running in gateway namespace and a httpproxy object in user namespace. I want to direct traffic to ingressagateway service in gateway namespace, httpproxy tries to look in usernamespace even after specifiying complete service url. Following is the httpproxy configuration
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
    name: helloworld-inggateway
    namespace: usernamespace
spec:
    virtualhost:
      fqdn: hello.xxx.com
      tls:
        secretName: default-secret
    routes:
    - conditions:
      - prefix: /
      services:
      - name: istio-ingressgateway // in ingressgateway namespace
        port: 80
```
Have tried another approach creating dumby service  with ExternalName set to ingressgateway service but this also doesn't work. It throws 404 error.

```
kind: Service
apiVersion: v1
metadata:
  name: dumby
  namespace: usernamespace
spec:
  type: ExternalName
  externalName: istio-ingressgateway.ingress.svc.cluster.local
  ports:
  - port: 80
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
    name: helloworld-inggateway
    namespace: usernamespace
spec:
    virtualhost:
      fqdn: hello.xxx.com
      tls:
        secretName: default-secret
    routes:
    - conditions:
      - prefix: /
      services:
      - name: dumby // in user namespace
        port: 80

```
**What did you expect to happen:**
Httpproxy should send the traffic to service in other namespace

**Environment:**

- Contour version: 1.14.2
- Kubernetes version: (use `kubectl version`): 1.19
- Kubernetes installer & version: NA
- Cloud provider or hardware configuration: NA
- OS (e.g. from `/etc/os-release`):  NAME="Red Hat Enterprise Linux Server" VERSION="7.9 (Maipo)"
