### ISSUE TITLE
Downstream timeout errors

### ISSUE THREAD

**Issue by amkiryushkin** [projectcontour/contour#4330]
Hello.

I'm using Contour as ingress and I came across the DC timeout problem.
I set the parameters:
```
    timeouts:
       request-timeout: infinity
       connection-idle-timeout: 2700s
       stream-idle-timeout: 3000s
    #   max-connection-duration: infinity
       delayed-close-timeout: 900s
    #   connection-shutdown-grace-period: 5s
```

Also, I set the `projectcontour.io/response-timeout` in the ingress yaml.

However, I am still getting the DC statuses in the Envoy. What are my options to fix the problem as it is critical for me?

**Comment by youngnick** [comment]
Hi @amkiryushkin, when you say "Downstream" here, are you referring to the connection from Envoy to the backend? Envoy actually calls this "upstream", confusingly. If you do, #4326 may solve the problem for you, I think?

**Comment by amkiryushkin** [comment]
Hi @youngnick. Yes, it is should be `upstream`, however, according to the documentation, it is called Downstream connection:
https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage

Anyway, yes, it seems it could help. Could you please tell me when this change will be in master approximately?

**Comment by youngnick** [comment]
It's in review now, in a week or so if not earlier.

**Comment by amkiryushkin** [comment]
@youngnick  could you please tell me how to build the last version correctly or when the fresh image will be available to use?

**Comment by tsaarni** [comment]
Hi @amkiryushkin, 

There is `ghcr.io/projectcontour/contour:main` which is built from the main branch.  You can try following:

```bash
$ cat <<EOF | kubectl -n projectcontour patch deployment contour --patch-file=/dev/stdin
spec:
  template:
    spec:
      containers:
      - name: contour
        image: ghcr.io/projectcontour/contour:main
EOF
```

Edit the configuration file:

```bash
$ kubectl -n projectcontour edit configmaps contour
```
add something like following under `contour.yaml`
 
```yaml
timeouts:
    connect-timeout: 10s
```

restart Contour

```bash
$ kubectl -n projectcontour rollout restart deployment contour
```

and wait for a few seconds for Envoys to get reconfigured. 

This might potentially help if the probelm is that backend service (upstream) is taking long time to respond. However it is not 100% clear to me if this is true in your case. Good luck in any case and tell us how it goes!

**Comment by amkiryushkin** [comment]
it seems it doesn't work:

```
time="2022-02-15T14:16:43Z" level=error msg="pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.ContourConfiguration: failed to list *v1alpha1.ContourConfiguration: contourconfigurations.projectcontour.io is forbidden: User \"system:serviceaccount:projectcontour:contour\" cannot list resource \"contourconfigurations\" in API group \"projectcontour.io\" at the cluster scope\n" caller="reflector.go:138" context=kubernetes error="<nil>"
```

My old deploy works, but this don't.

**Comment by tsaarni** [comment]
Ok, I think you might have bit older Contour currenly and replacing only the image is not working.  Would it be possible for you to redeploy it completely? 

```bash
kubectl apply -f https://raw.githubusercontent.com/projectcontour/contour/main/examples/render/contour.yaml
```

**Comment by amkiryushkin** [comment]
Thank you for your help.

Unfortunately, my problem still there:
```
[2022-02-17T01:02:12.556Z] "POST /location?param=true HTTP/1.0" 0 DC 1138773 0 60084 - "10.50.100.200" "-" "2ebcbad4-9ae4-4a1d-b92e-7d3f0a955707" "mydomain.com" "10.0.1.114:80"
```

Here my timeouts:
```
    timeouts:
    #   request-timeout: infinity
       connection-idle-timeout: 45m
       stream-idle-timeout: 45m
    #   max-connection-duration: infinity
    #   delayed-close-timeout: 1s
    #   connection-shutdown-grace-period: 5s
       connect-timeout: 45m
```

Could you please tell me where I haven't set a timeout?
