### ISSUE TITLE
kubernetes dashboard secure backend bearer token httpproxy

### ISSUE THREAD

**Issue by tirelibirefe** [projectcontour/contour#4341]
Hello,
My topology is here:
![image](https://user-images.githubusercontent.com/45227339/153761179-b6b87b3e-aae3-4f68-96b3-b032bca9440e.png)

I have looked at reference designs [here ](https://projectcontour.io/docs/v1.6.1/httpproxy/) but I couldn't have succeeded writing a working configuration by using parameters "permitInsecure: true", "requestHeadersPolicy", "conditions" and "validation" etc.

My purpose is to access kubernetes dashboard which is protected by tls and a bearer token. This is not only for kubernetes dashboard, there are some other services like that. 

So I need to ask your help how to create a working httpproxy? Pleas advise...

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
spec:
  virtualhost:
    fqdn: kd.mydomain.com
  routes:
    - conditions:
      - prefix: /
      permitInsecure: true
      services:
        - name: kubernetes-dashboard
          port: 443
          validation:
            caSecret: kubernetes-dashboard-csrf
          #   subjectName: kd.mydomain.com
          requestHeadersPolicy:
            set:
              - name: Authorization
                value: "Bearer eyJhbGciOiJSUzI1Niblablab"
            remove:
              - Authorization
```

and browser says:
`Client sent an HTTP request to an HTTPS server.`

curl says:
```

$ curl -k -I https://kd.mydomain.com
HTTP/2 400
date: Sun, 13 Feb 2022 17:56:51 GMT
x-envoy-upstream-service-time: 1
vary: Accept-Encoding
server: envoy


```

(During accessing kubernetes dashboard from outside of k8s "user authentication" is the matter of another topic. I am not asking it here; I'm gonna consider it later. So pls don't tell me the design is violating existing kubernetes dashboard security.)

Thanks & Regards
