### ISSUE TITLE
upstream connect error or disconnect/reset before headers. reset reason: connection termination

### ISSUE THREAD

**Issue by tirelibirefe** [projectcontour/contour#4344]
Hello,
I am having a trouble accessing to a service (Kibana) in Kuebrnetes through Envoy/Contour; so needed to ask your help/advise:

here is my ingress config:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  namespace: eck
spec:
  rules:
    - host: kibana.mydomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kibana-kb-http
                port:
                  number: 5601
```

the services are:

```
$ k get svc -n eck
NAME                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
escluster-es-default     ClusterIP   None            <none>        9200/TCP   124d
escluster-es-http        ClusterIP   10.100.162.30   <none>        9200/TCP   124d
escluster-es-transport   ClusterIP   None            <none>        9300/TCP   124d
kibana-kb-http           ClusterIP   10.100.21.248   <none>        5601/TCP   124d
```

envoy log:

`"GET / HTTP/1.1" 503 UC 0 95 2 - "88.255.X.X,192.168.X.X" "curl/7.68.0" "860-194a-46df-a499-1419e2ccdb84" "kibana.mydomain.com" "192.168.21.220:5601"`

and this is what I get on the browser and curl output:

`upstream connect error or disconnect/reset before headers. reset reason: connection termination`

Am I doing something wrong?

Thanks & Regards
Tirelibirefe

**Comment by tirelibirefe** [comment]
I deleted ingress and put an httpproxy config there, nothing changed:

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kibana
  namespace: eck
spec:
  virtualhost:
    fqdn: kibana.mydomain.com
  routes:
    - conditions:
      - prefix: /
      services:
        - name: kibana-kb-http
          port: 5601
```
