### ISSUE TITLE
Update AWS NLB Guide with correct annotations

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#4346]
The guidance around annotations [this guide](https://projectcontour.io/guides/deploy-aws-tls-nlb/) references may be out of date with the latest versions of the AWS Load Balancer Controller. Particularly the `service.beta.kubernetes.io/aws-load-balancer-type` annotation. We should update to match the latest versions of that component

Links:
- https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/service/nlb/#configuration
- https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/service/annotations/#traffic-routing

**Comment by nnalam** [comment]
Hi, the Helm chart documentation also appears out of date:
https://github.com/bitnami/charts/blob/master/bitnami/contour/README.md#deploying-contour-with-an-aws-nlb

And how the value is used here:
https://github.com/bitnami/charts/blob/master/bitnami/contour/templates/envoy/service.yaml#L17

Also referred to here:
https://github.com/projectcontour/contour/tree/main/examples/contour#deploying-with-host-networking-enabled-for-envoy

And here:
https://github.com/bitnami/charts-docs/blob/main/charts/contour/_deploy_contour_aws_nlb.md.erb

**Comment by yankay** [comment]
HI @sunjayBhatia , would you please review the fix https://github.com/projectcontour/contour/pull/4347

**Comment by brunopadz** [comment]
@yankay is your solution working?
I've just redeployed AWS Load Balancer Controller and deploy Contour following the fix proposed and the Envoy service keeps provisioning the NLB with a listerner on port 80.

![image](https://user-images.githubusercontent.com/1850071/154329647-4562e160-b561-4676-b055-ab293dc37cfd.png)

Here's my config:

```yaml
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <ARN_HERE>
```

**Comment by sunjayBhatia** [comment]
That screenshot makes it look like the AWS Load Balancer Controller isn't even picking up your service to reconcile, the SSL Certificate field is empty as well? I don't have an AWS account myself to diagnose so I'll need to procure one

**Comment by brunopadz** [comment]
Ok, I found what's going on. The example in docs gives the following example:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: projectcontour
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-2:185309785115:certificate/7610ed7d-5a81-4ea2-a18a-7ba1606cca3e"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 80
    name: http
    protocol: TCP
  selector:
    app: envoy
  type: LoadBalancer
```

It doesn't work. What I did was:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: projectcontour
  annotations:
    # This annotation puts the AWS ELB into "TCP" mode so that it does not
    # do HTTP negotiation for HTTPS connections at the ELB edge.
    # The downside of this is the remote IP address of all connections will
    # appear to be the internal address of the ELB. See docs/proxy-proto.md
    # for information about enabling the PROXY protocol on the ELB to recover
    # the original remote IP address.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <ARN_HERE>
spec:
  externalTrafficPolicy: Local
  ports:
    - port: 443
      name: https
      protocol: TCP
      targetPort: 8080
```

And it works.

**Comment by yankay** [comment]
HI, @sunjayBhatia , @brunopadz . I test the yaml in the AWS. The [brunopadz](https://github.com/brunopadz)'s test result it right.

If we want use AWS NLB without SSL. we can setup it like:
```
apiVersion: v1
kind: Service
metadata:
  name: nlb-sample-service
  namespace: nlb-sample-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: nginx
```

If we want use HTTPS, we can setup as :
```apiVersion: v1
kind: Service
metadata:
  name: nlb-sample-service
  namespace: nlb-sample-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:iam::998370865006:server-certificate/my-server-test
    service.beta.kubernetes.io/aws-load-balancer-ssl-port: "443"
spec:
  ports:
    - port: 443
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: nginx
```

The screenshot of the AWS:

![企业微信截图_16450820059483](https://user-images.githubusercontent.com/1469319/154424285-f4e5dc7e-7c58-4050-af0c-9361f9a46d36.png)

![企业微信截图_1645082013478](https://user-images.githubusercontent.com/1469319/154424299-9d48033e-7d7f-4432-9393-9fa8b649586b.png)
