### ISSUE TITLE
Upstream SNI value is not configured correctly when two HTTPProxies refer to same upstream service

### ISSUE THREAD

**Issue by tsaarni** [projectcontour/contour#4348]
One of the `dag.Cluster` fields is [`SNI`](https://github.com/projectcontour/contour/blob/aa134a2a8a9f9050191e8cdbe4bf453675935a12/internal/dag/dag.go#L668-L673). It should be used when Envoy communicates towards the upstream service with TLS.  The value is derived from `HTTProxy.spec.routes.requestHeadersPolicy` `Host` key.

When Envoy clusters are created, unique name is generated by [hashing relevant fields](https://github.com/projectcontour/contour/blob/aa134a2a8a9f9050191e8cdbe4bf453675935a12/internal/envoy/cluster.go#L27-L56
) that should identify the cluster as unique. Since `SNI` is not part of the hash, the following otherwise equal `HTTPProxies` will result in same name and end up overwriting each other. The result is that only one cluster gets configured to Envoy:

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: my-httpproxy-1
spec:
  virtualhost:
    fqdn: test-1.127-0-0-101.nip.io
  routes:
    - services:
        - name: my-backend-service
          port: 8000
          protocol: tls
          validation:
            caSecret: my-ca-secret
            subjectName: my-backend-service
      requestHeadersPolicy:
        set:
          - name: Host
            value: "my-backend-service-1"  # SNI value
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: my-httpproxy-2
spec:
  virtualhost:
    fqdn: test-2.127-0-0-101.nip.io
  routes:
    - services:
        - name:  my-backend-service
          port: 8000
          protocol: tls
          validation:
            caSecret: my-ca-secret
            subjectName: my-backend-service
      requestHeadersPolicy:
        set:
          - name: Host
            value: "my-backend-service-2"  # SNI value
```

There could be also `HTTPProxy` with no `requestHeaderPolicy` at all, which would mean no SNI. That also gets collapsed into  single cluster. What ends up in upstream TLS SNI depends on which cluster gets in first.
