### ISSUE TITLE
Resources not found under /images - error HTTP 404

### ISSUE THREAD

**Issue by cmoulliard** [projectcontour/contour#4351]
**Issue**

When a pod is created using this image `ghcr.io/halkyonio/quarkus-tap-petclinic-h2` and exposed as an external route using Contour (running on Knative Serving/Route), then the images resources created under `/images/*.png` are not available as we got a `HTTP 404 error`

```
This quarkus-app.tap-demo.10.0.76.205.nip.io page can’t be foundNo web page was found for the web address: http://quarkus-app.tap-demo.10.0.76.205.nip.io/images/rh-runtimes-logo.png
HTTP ERROR 404
```
The envoy pod reports:
```
HTTP 404 error [2022-02-17T09:24:19.062Z] "GET /images/rh-runtimes-logo.png HTTP/1.1" 404 - 0 0 5 4 "10.244.0.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWe ...
```

Screenshot
![Screenshot 2022-02-17 at 14 12 06](https://user-images.githubusercontent.com/463790/154489748-f63e950e-ce70-441b-91f1-d2cadc9fb3a0.png)

If I run a container locally, then images are well displayed at the following url `http://localhost:8080/images/rh-runtimes-logo.png`

```
docker run -d -p 8080:8080 -e PORT=8080 ghcr.io/halkyonio/quarkus-tap-petclinic-h2
```

Screenshot - local

![Screenshot 2022-02-17 at 14 16 23](https://user-images.githubusercontent.com/463790/154489598-d6f840cc-b0db-4d10-8e41-997b285fe338.png)

**Question:** Do we have to configure a parameter of the HTTPProxy object to fi this issue ?

HTTProxy spec routes
```
  routes:
  - conditions:
    - header:
        exact: override
        name: K-Network-Hash
    enableWebsockets: true
    permitInsecure: true
    requestHeadersPolicy:
      set:
      - name: K-Network-Hash
        value: 00ceb4ed8d41d3b1b7fe6358c344d46ed76f8786b8f63840b93c7af0477166fb
    retryPolicy:
      count: 2
      retryOn:
      - cancelled
      - connect-failure
      - refused-stream
      - resource-exhausted
      - retriable-status-codes
      - reset
    services:
    - name: quarkus-app-00001
      port: 80
      requestHeadersPolicy:
        set:
        - name: Knative-Serving-Namespace
          value: tap-demo
        - name: Knative-Serving-Revision
          value: quarkus-app-00001
      weight: 100
    timeoutPolicy:
      idle: infinity
      response: infinity
  - enableWebsockets: true
    permitInsecure: true
    requestHeadersPolicy: {}
    retryPolicy:
      count: 2
      retryOn:
      - cancelled
      - connect-failure
      - refused-stream
      - resource-exhausted
      - retriable-status-codes
      - reset
    services:
    - name: quarkus-app-00001
      port: 80
      requestHeadersPolicy:
        set:
        - name: Knative-Serving-Namespace
          value: tap-demo
        - name: Knative-Serving-Revision
          value: quarkus-app-00001
      weight: 100
    timeoutPolicy:
      idle: infinity
      response: infinity
```

**Resources:**
ingress and route manifest: https://gist.github.com/cmoulliard/c0ed4df944a52544ce833dbd0d1687e9
httproxy manifests: https://gist.github.com/cmoulliard/d427b4973475534e6db65cedfc961596

**Environment:**

- Contour version: 1.18.2
- Kubernetes version: (use `kubectl version`): 1.21.4
- OS (e.g. from `/etc/os-release`): CentOS Linux

**Comment by sunjayBhatia** [comment]
Hm, looks like the 404 is coming from the app itself, can you just as a sanity check port-forward to the app running in the cluster and see if a request succeeds as expected?

**Comment by cmoulliard** [comment]
I dont think that this is the app as I can access the images when I launch locally the app `docker run -d -p 8080:8080 -e PORT=8080 ghcr.io/halkyonio/quarkus-tap-petclinic-h2`

**Comment by sunjayBhatia** [comment]
The 404 is being generated by the app, since Envoy is not generating an error code (in the Envoy log line you have `GET /images/rh-runtimes-logo.png HTTP/1.1" 404 -`, the `-` would be a two character error code if Envoy could not route to the app)

**Comment by sunjayBhatia** [comment]
Now the 404 may be happening because the app is receiving a request it does not expect, caused by Contour/Envoy but it would be good to check if the app is generally working in the cluster first

**Comment by sunjayBhatia** [comment]
From that page, it looks like `/fonts/*`, `/css/*` and other things work fine, not sure why `/images/*` particularly is failing

If possible, try putting Envoy in debug logging mode and see what requests it is actually sending to the `/images/*` endpoints, to check if there is anything strange there, and how it may differ from sending requests to the app directly.

**Comment by cmoulliard** [comment]
I enabled the logging to debug and here is what I got : https://gist.github.com/cmoulliard/9b4eff96a47b328e79f1e0fe385b9982#file-gistfile0-txt-L1620

**Comment by cmoulliard** [comment]
@sunjayBhatia I created a scenario able to show that the app works when it runs as a container locally or on a kind k8s cluster running ingress nginx

## Steps to reproduce

## Locally
```
git clone https://github.com/halkyonio/quarkus-tap-petclinic.git && quarkus-tap-petclinic
./mvnw clean package

docker build -f src/main/docker/Dockerfile.fast-jar -t localhost:5000/quarkus-tap .
docker run -d -p 8080:8080 -e PORT=8080 127.0.0.1:5000/quarkus-tap
```

Check now locally using this URL nd you should see 2 pets: `http://localhost:8080/test.html`

## As a pod on kind where ingress is deployed

Replace within the ingress resource the host `quarkus.192.168.1.50.nip.io` to use your local IP address
```
kubectl delete ingress/my-pod
kubectl delete service/my-pod
kubectl delete deployment/my-pod

cat <<EOF | kubectl apply -f -
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-pod
  name: my-pod
spec:
  selector:
    matchLabels:
      app: my-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-pod
    spec:
      containers:
      - image: localhost:5000/halkyonio/quarkus-tap
        imagePullPolicy: Always
        name: quarkus-tap
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  name: my-pod
spec:
  selector:
    app: my-pod
  ports:
  - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-pod
spec:
  rules:
  - host: quarkus.192.168.1.50.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: my-pod
            port:
              number: 8080  
EOF
```

Check now locally using this URL nd you should see 2 pets: `http:quarkus.192.168.1.50.nip.io/test.html`

**Comment by cmoulliard** [comment]
Which manifests (ingress, HTTProxy) do you use when you deploy on contour ?

**Comment by tsaarni** [comment]
I derived my manifest from your example to accomodate my cluster, full manifest here https://gist.githubusercontent.com/tsaarni/5b56105f4728b7efddaf7185c7393209/raw/6c0b0af5e36f90f51a955ef7f9d64c41f0193bd7/manifest.yaml

Both `Ingress` and `HTTPProxy` alternatives worked.

**Comment by cmoulliard** [comment]
That works too for me using the following config: https://gist.github.com/cmoulliard/63b258f6b7527aa8b357a4eb1bba6f0c :-)

So, there is then an issue when project is deployed on Tanzu Application Platform v1.0 then
Question: Are you in touch with Tanzu engineers to move the ticket to them ?

**Comment by sunjayBhatia** [comment]
Just a sanity check: I see port 80 being referenced in the knative etc. HTTPProxy example but the working example exposes the service via port 8080, might be worth checking the service is set up correctly in the knative example

**Comment by cmoulliard** [comment]
> I see port 80 being referenced in the knative etc

As the application is accessible externally like the css, fonts resources, I doubt that the problem is there. I suspect an issue  with the resources mapped by ingress, ...

**Comment by cmoulliard** [comment]
I saw that but when the app is deployed using HTTProxy, Service and Deployment (see previous comment) on the same k8s cluster, that works. This is why I suspect a problem using Tanzu Application Platform v1 which is maybe related to Knative and/or ingress route

**Comment by cmoulliard** [comment]
`So Tanzu Application Platform changed something from community version 🤔 ?` They perhaps didn't change anything within the community code of contour/Knative but instead they configure the k8s manifests differently (annotations, spec) ...

**Comment by cmoulliard** [comment]
I deployed successfully on TAP the following resources that I created manually and we can see the images : http://quarkus-app.issue.94.130.111.125.nip.io/test.html

I will try to understand that is the diff between my resources and what the supply chain templates of the cartographer intsall

```
kubectl create ns issue

IP=94.130.111.125
IMAGE=ghcr.io/halkyonio/quarkus-tap

kubectl delete -n issue HTTPProxy/quarkus-app
kubectl delete -n issue services.serving.knative.dev/quarkus-app

cat <<EOF | kubectl apply -n issue -f -
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: quarkus-app
spec:
  template:
    metadata:
    spec:
      containerConcurrency: 0
      containers:
        - name: workload
          image: $IMAGE
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          securityContext:
            runAsUser: 1000
      enableServiceLinks: false
      serviceAccountName: default
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: quarkus-app
spec:
  routes:
  - enableWebsockets: true
    retryPolicy:
      count: 2
      retryOn:
      - cancelled
      - connect-failure
      - refused-stream
      - resource-exhausted
      - retriable-status-codes
      - reset
    services:
    - name: quarkus-app
      port: 8080
      requestHeadersPolicy:
        set:
        - name: Knative-Serving-Namespace
          value: issue
        - name: Knative-Serving-Revision
          value: quarkus-app
      weight: 100
    timeoutPolicy:
      idle: infinity
      response: infinity
  virtualhost:
    fqdn: quarkus.$IP.nip.io
EOF
```
