### ISSUE TITLE
Certificate delegations with HTTPProxy resource

### ISSUE THREAD

**Issue by foosinn** [projectcontour/contour#4357]
**What steps did you take and what happened:**

Create a `Secret`, a `TLSCertificateDelegation` and a `HTTPProxy` like this:

```sh
❯ k get secret apps-example-com
NAME                      TYPE                DATA   AGE
apps-example-com   kubernetes.io/tls   2      4d22h
```

```yaml
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: apps-example-com
  namespace: projectcontour
spec:
  delegations:
  - secretName: apps-example-com
    targetNamespaces:
    - '*'
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: hubble
  namespace: kube-system
spec:
  routes:
  - services:
    - name: hubble-ui
      port: 80
    timeoutPolicy:
      idle: 300s
      response: 300s
  virtualhost:
    fqdn: hubble.apps.example.com
    tls:
      secretName: apps-example-com
```

Result:

```yaml
status:
  conditions:
  - errors:
    - message: 'Spec.VirtualHost.TLS Secret "apps-example-com" is invalid:
        Secret not found'
      reason: SecretNotValid
      status: "True"
      type: TLSError
    lastTransitionTime: "2022-02-21T14:47:56Z"
    message: At least one error present, see Errors for details
    observedGeneration: 4
    reason: ErrorPresent
    status: "False"
    type: Valid
  currentStatus: invalid
```

**What did you expect to happen:**

Contour looking up the certificate from the `projectcountour` namespace.

**Anything else you would like to add:**

Thanks for your help!

**Environment:**

- Contour version: docker.io/bitnami/contour:1.19.1-debian-10-r77
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.16.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6-gke.1500", GitCommit:"7ce0f9f1939dfc1aee910732e84cba03840df91e", GitTreeState:"clean", BuildDate:"2021-11-17T09:30:26Z", GoVersion:"go1.16.9b7", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version: Helm Chart contour-7.3.4
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`): -

**Comment by foosinn** [comment]
TLSCertificateDelegation is setup as in #2488 described

**Comment by tsaarni** [comment]
Hi @foosinn, couple of things come to mind that you could check:

Which namespace you created the `Secret`?  If you want to use the delegation, the `Secret` should be in the same namespace as `TLSCertificateDelegation` i.e. in `projectcontour` in this case.

When referring to deletegated certificate from `HTTPProxy.spec.virtualHost.tls.secretName`, did you prefix the name with the namespace of the `Secret`? When using delegated cert above, then set `secretName: projectcontour/apps-example-com`. 

Check also the example [here](https://projectcontour.io/docs/v1.20.0/config/tls-delegation/).

**Comment by foosinn** [comment]
yes just saw the docs but you where faster, thought it's still only documented in the issue.

Fix was to set the namespace of the secret correctly.

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: hubble
  namespace: kube-system
spec:
  routes:
  - services:
    - name: hubble-ui
      port: 80
    timeoutPolicy:
      idle: 300s
      response: 300s
  virtualhost:
    fqdn: hubble.apps.example.com
    tls:
      secretName: projectcontour/apps-example-com
```
