### ISSUE TITLE
Examples of redirecting example.com to www.example.com

### ISSUE THREAD

**Issue by stumueller** [projectcontour/contour#4366]
I believe the HTTPRequestRedirectPolicy can be used to redirect requests to example.com to www.example.com

Are there any examples of this being implemented?

we have 
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: frontend
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: www.example.com
  routes:
    - conditions:
        - prefix: /
      services:
        - name: web
          port: 80

We would like for request to example.com to be forwarded to this virtual host

Thanks

**Comment by sunjayBhatia** [comment]
heres an example:

HTTPProxy for example.com that contains a redirect to www.example.com

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: basic
spec:
  virtualhost:
    fqdn: example.com
  routes:
    - conditions:
      - prefix: /
      requestRedirectPolicy:
        hostname: www.example.com
```

HTTPProxy for www.example.com

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: www-basic
spec:
  virtualhost:
    fqdn: www.example.com
  routes:
    - conditions:
      - prefix: /
      services:
        - name: <your service>
          port: 80
```

example requests/responses:

```
$ curl -i localhost:9080 -H 'Host: example.com'
HTTP/1.1 302 Found
location: http://www.example.com/
vary: Accept-Encoding
date: Thu, 24 Feb 2022 16:16:39 GMT
server: envoy
content-length: 0
```

```
$ curl -i localhost:9080 -H 'Host: www.example.com'
HTTP/1.1 200 OK
content-length: xxx
content-type: text/html
date: Thu, 24 Feb 2022 16:18:21 GMT
x-envoy-upstream-service-time: 0
vary: Accept-Encoding
server: envoy

...
```
