### ISSUE TITLE
SNI lost when using httpproxy as TLS, TCP reverse Proxy

### ISSUE THREAD

**Issue by Jochen-dba** [projectcontour/contour#4373]
Hello,

I'm trying to use HTTPPROY as TLS, TCP reverse Proxy for MongoDB.
This is my YAML:
```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: my-replica-set-0.externaldomain.com-httpproxy
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: my-replica-set-0.externaldomain.com
    tls:
      secretName: my-replica-set-0.externaldomain.com-cert
  tcpproxy:
    services:
      - name: my-replica-set-0-svc
        port: 27017
        protocol: tls
```

Why?:
- The Client is running outside of Kubnetes
- I am using cert-manager and ACME and http01-Challenge
- The Endpoints (MongoDB Pods) require TLS and present certificates which are only valid for `*.cluster-local`.
(ACME cannot validate *.cluster-local)
- ACME (http01-Challenge) is only able to issue certificates valid for external FQDN (`*.externaldomain.com`)

I successfully terminate TLS (certificates valid for external FQDN) using `spec.virtualhost.tls`
The TCP traffic which is encapsulated in TLS is forwarded: `spec.tcpproxy`
I use upstream TLS: `spec.tcpproxy.services.protocol`

All of this works - the only issue is: it seems like due to TLS termination SNI from the Client is not passed into the upstream TLS connection. Unfortunately the MongoDB Server requires the SNI for Split-Horizon (which is in turn required for clients outside of k8s):
https://docs.mongodb.com/kubernetes-operator/master/reference/k8s-operator-specification/#spec.connectivity.replicaSetHorizons

Using `spec.virtualhost.tls.passthrough` is unfortunately not an option, as this would present the certificates which are only valid for `*.cluster-local` to the client.

What could I do to preserve the external clients SNI while terminating TLS and using upstream TLS using HTTPPROXY?
Is there a feature to achieve this I'm not aware of?

Many, many thanks & best Regards,
Jochen
