### ISSUE TITLE
requestRedirectPolicy validation error

### ISSUE THREAD

**Issue by stumueller** [projectcontour/contour#4374]
We are using the latest bitnami chart for contour - 7.3.9

our httpproxy yaml's are as follows:
redirect.yaml
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: frontend-redirect
spec:
  virtualhost:
    fqdn: reporting.example.co.uk
    tls:
      secretName: frontend-proxy-redirect
  routes:
    - conditions:
        - prefix: /
      requestRedirectPolicy:
        hostname: www.reporting.example.co.uk
      services:
        - name: web
          port: 80
```
proxy.yaml
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: frontend
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: www.reporting.example.co.uk
    tls:
      secretName: frontend-proxy
  routes:
    - timeoutPolicy:
        response: "2m"
      conditions:
      - prefix: /
      services:
        - name: web
          port: 80
    - timeoutPolicy:
        response: "2m"
      conditions:
      - prefix: /matsweb
      services:
        - name: matsweb
          port: 80
```

after applying proxy.yaml when running ```kubectl apply -f redirect.yaml```

We get the error: 
error: error validating "redirect.yaml": error validating data: ValidationError(HTTPProxy.spec.routes[0]): unknown field "requestRedirectPolicy" in io.projectcontour.v1.HTTPProxy.spec.routes; if you choose to ignore these errors, turn validation off with --validate=false

We were previously running contour 1.19.1 but have since upgraded to 1.20.1
We have also tried moving the requestResponsePolicy above hte conditions section
```
routes:
    - requestRedirectPolicy:
        hostname: www.reporting.example.co.uk
      conditions:
        - prefix: /
      services:
        - name: web
          port: 80
```
