### ISSUE TITLE
path based routing doesn't work

### ISSUE THREAD

**Issue by tirelibirefe** [projectcontour/contour#4376]
Hello;
I don't know what I am missing.

a simple service:
```
$ k get svc
NAME                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
kubernetes           ClusterIP   172.20.0.1      <none>        443/TCP   10h
nginxhello-demoapp   ClusterIP   172.20.120.67   <none>        80/TCP    109m
```
a simple httpproxy:

```
$ k get httpproxies.projectcontour.io -A
NAMESPACE   NAME      FQDN           TLS SECRET   STATUS   STATUS DESCRIPTION
default     demoapp   u1.mydomain.com                valid    Valid HTTPProxy
```
here is the httpproxy yaml file:

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: demoapp
spec:
  virtualhost:
    fqdn: u1.mydomain.com
  routes:
    - conditions:
      - prefix: /demoapp
      services:
        - name: nginxhello-demoapp
          port: 80
```

description:

```
$ k describe httpproxies.projectcontour.io demoapp
Name:         demoapp
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  projectcontour.io/v1
Kind:         HTTPProxy
Metadata:
  Creation Timestamp:  2022-02-27T00:01:50Z
  Generation:          4
  Managed Fields:
    API Version:  projectcontour.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
          .:
          k:{"type":"Valid"}:
            .:
            f:lastTransitionTime:
            f:message:
            f:observedGeneration:
            f:reason:
            f:status:
            f:type:
        f:currentStatus:
        f:description:
        f:loadBalancer:
    Manager:      contour
    Operation:    Update
    Time:         2022-02-27T00:01:50Z
    API Version:  projectcontour.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:routes:
        f:virtualhost:
          .:
          f:fqdn:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2022-02-27T00:01:50Z
  Resource Version:  145728
  UID:               95e23b6b-8bcf-4263-9fdc-e43deda4617c
Spec:
  Routes:
    Conditions:
      Prefix:  /demoapp
    Services:
      Name:  nginxhello-demoapp
      Port:  80
  Virtualhost:
    Fqdn:  u1.mydomain.com
Status:
  Conditions:
    Last Transition Time:  2022-02-27T00:14:27Z
    Message:               Valid HTTPProxy
    Observed Generation:   4
    Reason:                Valid
    Status:                True
    Type:                  Valid
  Current Status:          valid
  Description:             Valid HTTPProxy
  Load Balancer:
Events:  <none>
```

...and the result

```
$ curl -k -I https://u1.mydomain.com/demoapp
HTTP/2 404
date: Sun, 27 Feb 2022 00:18:26 GMT
content-type: text/html
server: envoy
x-envoy-upstream-service-time: 1
vary: Accept-Encoding
```

if I set condition prefix as `/` it works.  
If prefix is not `/`, it never works.

There is no any problems with host based routing.

Could you please advise what am I missing?

Thanks & Regards

**Comment by tirelibirefe** [comment]
https://github.com/projectcontour/contour/issues/2450 I see Contour doesn't support Nginx based web servers as default. it's not practicle or possible to change nginx configuration of all third party applications used in a Kubernetes environment.

Actually Contour has path-based problems also with non-nginx based web servers .

I tried kubernetes-dashboard, it doesn't work.
httpbin doesn't work.
kuard doesn't work.
Prometheus, AlertManager sometimes works sometimes not.

Shortly, may we say "Contour is an ingress controller which doesn't support path based routing" ?

Thanks & Regards

**Comment by tsaarni** [comment]
When running `curl https://u1.mydomain.com/demoapp` the proxy will forward the exact request to the application. Application will see request to path `/demoapp` and responds with `404` since it is not valid request from the application perspective. 

It is possible to use [request rewriting](https://projectcontour.io/docs/v1.20.1/config/request-rewriting/) to map external path prefix `/demoapp` to path `/` towards the application:

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: demoapp
spec:
  virtualhost:
    fqdn: u1.mydomain.com
  routes:
    - conditions:
      - prefix: /demoapp
      services:
        - name: nginxhello-demoapp
          port: 80
      pathRewritePolicy:
        replacePrefix:
          - replacement: /
```

That still might not work since application might return a web page to browser which refers to other resources without the prefix that the application is served under. For example `kuard` front page refers to `/static/css/bootstrap.min.css`. Browser gets `404` for the `.css` and fails to render the page since. It should have requested for `/demoapp/static/css/bootstrap.min.css`. Some applications are prepared to be served under route prefix and provide a config switch to set the prefix to use for its own resource paths.
