### ISSUE TITLE
unknown field "exact"

### ISSUE THREAD

**Issue by tirelibirefe** [projectcontour/contour#4377]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

https://projectcontour.io/docs/v1.20.1/config/ingress/#ingress-rules
https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: demoapp
spec:
  virtualhost:
    fqdn: u1.mydomain.com
  routes:
    - conditions:
      - exact: /demoapp
      services:
        - name: nginxhello-demoapp
          port: 80
```

```
$ k apply -f demoapp-httpproxy.yaml 
error: error validating "demoapp-httpproxy.yaml": error validating data: ValidationError(HTTPProxy.spec.routes[0].conditions[0]): unknown field "exact" in io.projectcontour.v1.HTTPProxy.spec.routes.conditions; if you choose to ignore these errors, turn validation off with --validate=false
```

**What did you expect to happen:**

I expect path based routing works

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: 1.20.1
- Kubernetes version: (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```

- Kubernetes installer & version:

EKS  K8s 1.21 via eksctl

- Cloud provider or hardware configuration:

ami

- OS (e.g. from `/etc/os-release`):
linux ami
