### ISSUE TITLE
include doesn't work too.

### ISSUE THREAD

**Issue by tirelibirefe** [projectcontour/contour#4378]
Hello,
Probably as Contour doesn't support "path based routing", "include" doesn't work too.

Surprisingly only echo-server works.

```
$ curl -I -X GET -k https://u1.mydomain.com/httpbin
HTTP/2 404
date: Sun, 27 Feb 2022 18:48:30 GMT
content-type: text/html
content-length: 233
server: envoy
access-control-allow-origin: *
access-control-allow-credentials: true
x-envoy-upstream-service-time: 2
vary: Accept-Encoding

$ curl -I -X GET -k https://u1.mydomain.com/kuard
HTTP/2 404
date: Sun, 27 Feb 2022 18:49:07 GMT
content-type: text/plain; charset=utf-8
content-length: 19
x-content-type-options: nosniff
x-envoy-upstream-service-time: 0
server: envoy

$ curl -I -X GET -k https://u1.mydomain.com/echo
HTTP/2 200
date: Sun, 27 Feb 2022 18:49:17 GMT
content-type: text/plain; charset=utf-8
content-length: 525
x-envoy-upstream-service-time: 0
vary: Accept-Encoding
server: envoy

$ curl -I -X GET -k https://u1.mydomain.com/monitoring
HTTP/2 404
date: Sun, 27 Feb 2022 18:51:25 GMT
content-length: 0
vary: Accept-Encoding
server: envoy
```

root httpproxy

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: root
  namespace: default
spec:
  virtualhost:
    fqdn: u1.mydomain.com
  routes:
    - conditions:
      - prefix: /kuard
      services:
        - name: kuard
          port: 80
    - conditions:
      - prefix: /httpbin
      services:
        - name: httpbin
          port: 80
    - conditions:
      - prefix: /echo
      services:
        - name: echo
          port: 80
  includes:
  - name: kubernetes-dashboard
    namespace: kubernetes-dashboard
    conditions:
      - prefix: /monitoring
```
dashboard httpproxy:

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
spec:
  routes:
  - match:
    conditions:
    - prefix: /
    permitInsecure: true
    services:
      - name: kubernetes-dashboard
        port: 443
        protocol: tls
```

echo 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: stevesloka/echo-server
        command: ["echo-server"]
        args:
          - --echotext=This is the default app site!
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo
  name: echo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: echo
  type: ClusterIP
```

httpbin

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
        - image: docker.io/kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          name: httpbin
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: httpbin
  type: ClusterIP
```

kuard

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kuard
  name: kuard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:1
        name: kuard
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuard
  name: kuard
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard
  sessionAffinity: None
  type: ClusterIP
```

and services:

```
$k get svc 
NAME         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE 
echo         ClusterIP   172.20.208.191   <none>        80/TCP    177m
httpbin      ClusterIP   172.20.207.171   <none>        80/TCP    3h8m
kuard        ClusterIP   172.20.224.232   <none>        80/TCP    3h2m
kubernetes   ClusterIP   172.20.0.1       <none>        443/TCP   29h 

$ k get svc -n kubernetes-dashboard
NAME                        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
dashboard-metrics-scraper   ClusterIP   172.20.202.54   <none>        8000/TCP   27h
kubernetes-dashboard        ClusterIP   172.20.78.84    <none>        443/TCP    27h

```

Thankx & Regards
