### ISSUE TITLE
contour tcpproxy not work

### ISSUE THREAD

**Issue by liuflylove666** [projectcontour/contour#4389]
How to use TCP proxy correctly?

**Comment by sunjayBhatia** [comment]
Can you give some more detail about what is not working for you? With example YAML and error messages

**Comment by Jochen-dba** [comment]
Hello @liuflylove666

this is a working example from our site - but depending on what you're planning to do you need to customise it:

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: your-httpproxy
  namespace: default #put your namespace here
spec:
  ingressClassName: contour #use the class of your controller or check the annotation for ingressClass
  virtualhost:
    fqdn: somehost.com #the hostname your client uses
    tls: #set to terminate TLS
      secretName: yourTLS-cert #type: kubernetes.io/tls
  tcpproxy: #use this to forward TCP traffic
    services:
      - name: some-svc #TCP traffic is forwarded to this service
        port: 27017 #TCP traffic is forwarded to this port
```

Best Regards,
Jochen
