### ISSUE TITLE
Requests shouldn't be reevaluated after path rewrite

### ISSUE THREAD

**Issue by rodrigo14miguel** [projectcontour/contour#4390]
## Problem

Path rewrite reevaluates HTTPProxy's conditions after the rewrite, instead of delivering the request directly to the service.
The request URL path should be rewritten and delivered to the service without addition condition evaluation.

## Reproduce

I have two deployments, **deploy1** served by service **svc1** and **deploy2** served by service **svc2**.
Both deployments are exposing their website with prefix **/** in the container.
Expose both services under the same FQDN with one HTTPproxy:

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: myapp-httpproxy
spec:
  virtualhost:
    fqdn: myapp.example.com
    tls:
      secretName: server-tls
  routes:
  - services:
    - name: svc1
      port: 80
    conditions: #condition svc1
    - prefix: /
  - services:
    - name: svc2
      port: 80
    conditions: #condition svc2
    - prefix: /secondsvc
    pathRewritePolicy:
      replacePrefix:
      - prefix: /secondsvc
        replacement: /
```

## Expected behavior

When accessing **myapp.example.com/** I should reach **svc1/**. 
When accessing **myapp.example.com/secondsvc** I should reach **svc2/** (the request prefix **/secondsvc** should be rewritten as **/** and delivered directly to **svc2** without any additional condition reevaluation). 

## Actual behavior

When accessing **myapp.example.com/** I reach **svc1/**. 
When accessing **myapp.example.com/secondsvc** I reach **svc1/**. 
The **/secondsvc** prefix is being rewritten to **/** and then there is some kind of reevaluation against the HTTPproxy conditions. Because there is only one condition with prefix **/** and it belongs to **svc1**, the request is delivered to **svc1** instead of **svc2**.

**Note:** I know that the stated example will never work with the current behavior of contour. Because the rewritten request is reevaluated against the available conditions and **svc2** does not have any prefix **/** exposed, the rewritten request will never reach **svc2**. But I can't just have two conditions with the same **/** prefix, each pointing to different services, this creates a conflict.  

## Use case

Exposing multiple apps under the same FQDN when all the apps are using the same prefix internally.

**Comment by rodrigo14miguel** [comment]
Just noticed that the documentation https://projectcontour.io/docs/v1.20.1/config/api/ states "This rewriting takes place after a request is routed and has no subsequent effects on the proxy’s routing decision" in the PathRewritePolicy section. This issue should be labeled as bug.

**Comment by rodrigo14miguel** [comment]
I'm using contour 1.20.1 but I have found the problem.
After checking you tests, I tried my example again but with the following config:

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: myapp-httpproxy
spec:
  virtualhost:
    fqdn: myapp.example.com
    tls:
      secretName: server-tls
  routes:
  - services:
    - name: svc2
      port: 80
    conditions: #condition svc2
    - prefix: /secondsvc
    pathRewritePolicy:
      replacePrefix:
      - prefix: /secondsvc
        replacement: /
```

I noticed that with a curl I also get 200 response but when opening in the browser I get a blank page.
By inspecting the web page, there are some GETs for assets and favicon in root path **/** (thus landing on **svc1/** in the original example).
From what I have searched it is possible to href this but it is an app issue, external to contour.

I'm closing this issue.
@sunjayBhatia, thank you, your test helped me get there!
