### ISSUE TITLE
Configuring request timeouts for contour

### ISSUE THREAD

**Issue by VIPHercules** [projectcontour/contour#4408]
I have a general question on how to configure the request-timeout field for contour in kubernetes.

I have a project contour deployment running with envoy daemonset using the default rendered yaml configuration, I need to update this so the request-timeout field for contour is 30s. I'm possibly missing something with this, but I can't find any examples of an edited config map to verify what I am doing is correct.

This is how I have edited the config map

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contour
  namespace: projectcontour
data:
  contour.yaml: |
    timeouts:
      request-timeout: 30s
```

I am then running kubectl apply -f ./contour to apply the rendered yaml, however I have no way of validating that this change has taken effect or been propagated to the envoy pods as well.

If there are any examples of an edited config map or any further docs on how verify deployed configuration or the required process for updating the config map or config of a running contour deployment that would be really useful.

Thanks
