### ISSUE TITLE
flesh out ContourDeployment spec

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4427]
The definition of `ContourDeployment` that we have in repo is minimal:

```yaml
kind: ContourDeployment
apiVersion: projectcontour.io/v1alpha1
metadata:
  namespace: projectcontour
  name: example
spec:
  replicas: 2
  config:
    ...
```

The structure of the rest of the spec needs to be fleshed out.

One key decision to make here: originally in the [ContourConfiguration/ContourDeployment design](https://github.com/projectcontour/contour/blob/main/design/configuration-crd.md), since the `contour serve` command was going to manage Envoy, any details of the Envoy installation went in `ContourConfiguration`. However, with the current plans around the Gateway provisioner, I think it would make more sense for these Envoy details to go directly under `ContourDeployment` for the provisioner to use. One thing we could do is collect all Envoy-related options under a top-level `envoy` field, so if/when we did decide to move Envoy management into `contour serve`, we could pick that section of `ContourDeployment` up and move it into `ContourConfiguration` wholesale. A rough sketch of what that could look like, including many of the fields we know we want to support:

```yaml
kind: ContourDeployment
apiVersion: projectcontour.io/v1alpha1
metadata:
  namespace: projectcontour
  name: example
spec:
  # Settings for the Contour part of the installation.
  contour:
    replicas: 2
    nodePlacement:
      nodeSelector:
        foo: bar
      tolerations: []
  # Settings for the Envoy part of the installation.
  envoy:
    workloadType: Deployment
    networkPublishing:
      type: LoadBalancerService
      serviceAnnotations:
        foo: bar
    nodePlacement:
      nodeSelector:
        foo: bar
      tolerations: []
  # The ContourConfigurationSpec. Arguably could move under contour.
  config:
    enableExternalNameService: true    
```
