### ISSUE TITLE
provisioner: fix reconciliations to only update fields that should change over time

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4473]
With Gateway API, parameters defined by the GatewayClass should apply at the time of Gateway instantiation, but subsequent updates to those parameters should not flow through to already instantiated resources. The provisioner is doing this partly correctly, and partly incorrectly, since it was based on existing code that did ~full reconciliation on updates. We need to go through each resource's "Ensure" function and make sure that only expected updates are flowing through to provisioned resources (e.g. listeners, addresses).

**Comment by Rycieos** [comment]
This just bit me hard. I was following the docs on proxy-proto (https://projectcontour.io/docs/main/guides/proxy-proto/), and added these values to my `ContourDeployment`:

```yaml
spec:
  runtimeSettings:
    envoy:
      listener:
        useProxyProtocol: true
  envoy:
    networkPublishing:
      serviceAnnotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
```

As I had read in [the GatewayClass guide](https://projectcontour.io/docs/main/config/gateway-api/#customizing-a-gatewayclass):
> Contour follows the recommended behavior, meaning changes to a GatewayClass and its parameters are not propagated down to existing Gateways.

I expected none of those changes to propagate to my current Gateways. While the `runtimeSettings` did not, after a few minutes the `serviceAnnotations` did, at which point AWS started speaking PROXY protocol, and envoy did not know how to handle it, breaking all connections.

I get that a full dig through the project for places this expectation is broken is a difficult task, so maybe changing the quoted section of the docs to add some warning would be a good interim solution.
