### ISSUE TITLE
gateway provisioner: when using a NodePortService, Gateway's port numbers should define nodeport numbers

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4499]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
- Installed the provisioner: 
  ```bash
  kubectl apply -f examples/gateway-provisioner/
  ```
- Created a GatewayClass with the envoy network publishing type set to `NodePortService`:
  ```yaml
  ---
  kind: GatewayClass
  apiVersion: gateway.networking.k8s.io/v1alpha2
  metadata:
    name: contour
  spec:
    controllerName: projectcontour.io/gateway-controller
    parametersRef:
      group: projectcontour.io
      kind: ContourDeployment
      namespace: projectcontour
      name: contour-params
  ---
  kind: ContourDeployment
  apiVersion: projectcontour.io/v1alpha1
  metadata:
    namespace: projectcontour
    name: contour-params
  spec:
    envoy:
      networkPublishing:
        type: NodePortService
  ```
- created a Gateway using that GatewayClass:
  ```yaml
  kind: Gateway
  apiVersion: gateway.networking.k8s.io/v1alpha2
  metadata:
    name: gateway-1
    namespace: projectcontour
  spec:
    gatewayClassName: contour
    listeners:
      - name: http
        protocol: HTTP
        port: 30080
        allowedRoutes:
          namespaces:
            from: All
  ```
- observed that the provisioned Envoy service does *not* have a NodePort value of `30080`, instead it's used for the service port value:
  ```bash
  kubectl -n projectcontour get service/envoy-gateway-1 -o yaml
  ```

**What did you expect to happen:**
When a GatewayClass is parameterized to provision envoy services of type NodePort, I think it's logical that the Gateway's port values should be used for NodePort values.

In this scenario, it probably makes sense to default the service port values to 80/443.

I guess one challenge with this approach is that, because port numbers are required on Gateway listeners, this means you can't get auto-allocated NodePort values, which might be undesirable for some users. There is an open issue upstream (https://github.com/kubernetes-sigs/gateway-api/issues/1061) to allow port numbers to be optional, which would be the best of both worlds here.

Perhaps we should hold changing this until that issue has landed.
