### ISSUE TITLE
only one of requestRedirectPolicy and service can exist

### ISSUE THREAD

**Issue by yangyy93** [projectcontour/contour#4520]
**What question do you have?:**
In the httpproxy configuration, the service and requestRedirectPolicy configurations [should not be configured at the same time.](https://www.envoyproxy.io/docs/envoy/v1.22.0/api-v3/config/route/v3/route_components.proto.html?highlight=routes#config-route-v3-route) However, when the dag is generated, [two can exist at the same time.](https://github.com/projectcontour/contour/blob/main/internal/dag/builder_test.go#L10136-L10193) After the configuration is delivered to envoy, only the requestRedirectPolicy exists. 
**this is my httpproxy file，I think It is invalid, but in fact I can send the configuration normally**
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: route-redirect
  namespace: envoy-system
spec:
  virtualhost:
    fqdn: io.daocloud
  routes:
    - conditions:
        - prefix: /prefix
      requestRedirectPolicy:
        hostname: www.envoyproxy.com
        path: /
        port: 443
        scheme: https
        statusCode: 302
      services:
        - name: httpbin
          port: 80
```

**this is envoy route**
```
{
    "virtual_hosts":[
        {
            "name":"io.daocloud",
            "domains":[
                "io.daocloud"
            ],
            "routes":[
                {
                    "match":{
                        "prefix":"/prefix"
                    },
                    "redirect":{
                        "host_redirect":"www.envoyproxy.com",
                        "path_redirect":"/",
                        "response_code":"FOUND",
                        "scheme_redirect":"https",
                        "port_redirect":443
                    }
                }
            ]
        }
    ]
}
```

I think this is a place that needs to be optimized and should return an error and say that both cannot exist at the same time.
