### ISSUE TITLE
Need to support HTTP and HTTPS both without redirect

### ISSUE THREAD

**Issue by kartik-moolya** [projectcontour/contour#4524]
**What question do you have?:**
I have a `httproxy` deployed in my k8s cluster which currently proxies request to a kubernetes service. This kubernetes service is an `ExternalName` type service and points to a loadbalancer in GCP.
it works fine when I hit the `https` endpoint of the `httpproxy` but gives a `405` when I do it with `http`.
My requirement is such that I need both `http` and `https` requests to work without ssl-redirects.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I have tried using `tls.passthrough: true` but that redirects the http request to https, which is not something that we want.
I want the originating http request to go as a http request through the proxy

Below is the httproxy k8s object yaml

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: xyz-weighted
  namespace: backend
spec:
  virtualhost:
    fqdn: xyz-weighted.abc.com
    tls:
      passthrough: true
      secretName: xyz-tls
  routes:
    - conditions:
      - prefix: /
      services:
        - name: xyz-external
          port: 80
          weight: 100
```

**Environment:**

- Contour version: docker.io/projectcontour/contour:v1.8.2
- Kubernetes version: (use `kubectl version`):  v1.21.10-gke.2000
- Kubernetes installer & version: install using helm
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`):
