### ISSUE TITLE
Server is still serving the expired TLS certificate periodically even after renewing the cert

### ISSUE THREAD

**Issue by jinnypark9393** [projectcontour/contour#4539]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I'm using Contour HTTPproxy in Tanzu Kubernetes Grid.
Since current TLS certificate is about to expire(will be expired on May 31, 2022),
I created new secret with new TLS certificate(whill be expired on May 27, 2023) and updated tls.secretName with new one on HTTPProxy YAML as below(I changed some info due to security reason i.e. hostname).
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: web-app
  namespace: app
  selfLink: /apis/projectcontour.io/v1/namespaces/app/httpproxies/web-app
status:
  conditions:
    - lastTransitionTime: '2022-05-19T04:40:49Z'
      message: Valid HTTPProxy
      observedGeneration: 1
      reason: Valid
      status: 'True'
      type: Valid
  currentStatus: valid
  description: Valid HTTPProxy
  loadBalancer:
    ingress:
      - hostname: >-
          blahblahblah.elb.ap-northeast-1.amazonaws.com
spec:
  routes:
    - conditions:
        - prefix: /
      loadBalancerPolicy:
        strategy: Cookie
      services:
        - name: web-app1
          port: 8080
  virtualhost:
    fqdn: foo-bar.net
    tls:
      secretName: web-app-secret-new
```

However, when I check on the browser, server is serving expired TLS certificate periodically(not always. Sometime it shows old one and sometime it shows new one).

This happens even after I deleted all cache files.
(Also I tried access with Chrome, IE, Edge but It happens in all browsers)

Could you help me to find way to fix this issue?

**What did you expect to happen:**
Uses new TLS certificate but it doesn't.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I tried above with NGINX and NGINX's ingress doesn't have this issue.

**Environment:**

Contour version: v1.12.0
Kubernetes version: (use kubectl version): v1.20.5–vmware.2
Cloud provider or hardware configuration: AWS with Tanzu Kubernetes Grid
Envoy version: v1.17.3
