### ISSUE TITLE
CORS Access-Control-Allow-Private-Network

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [projectcontour/contour#4553]
## Feature Request
Add a new `allowPrivateNetwork` option to `corsPolicy` of `HTTPProxy` that will make Contour respond requests with the header `Access-Control-Allow-Private-Network: true` when the header `Access-Control-Request-Private-Network: true` is present on OPTIONS requests.

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
spec:
  virtualhost:
    corsPolicy:
        allowPrivateNetwork: true
```

## Context

> Chrome is deprecating direct access to private network endpoints from public websites as part of the [Private Network Access](https://wicg.github.io/private-network-access/) (PNA) specification.
> 
> Chrome will start sending a CORS preflight request ahead of any [private network request](https://developer.chrome.com/blog/private-network-access-preflight/#what-is-private-network-access) for a subresource, which asks for explicit permission from the target server. This preflight request will carry a new header, Access-Control-Request-Private-Network: true, and the response to it must carry a corresponding header, Access-Control-Allow-Private-Network: true.

Source: https://developer.chrome.com/blog/private-network-access-preflight/
