### ISSUE TITLE
Unable to use contour for typical wildcard TLS setup: `IngressSpec.tls.secretName` seems to be required, proxy protocol support is not working

### ISSUE THREAD

**Issue by artiommocrenco** [projectcontour/contour#4556]
**What steps did you take and what happened:**
Not willing to use contour CRDs.

Using the same `networking.k8s.io/v1` Ingress resources that worked with nginx-ingress. Expected them to work with contour.

I am testing out bitnami/contour chart with the following helm values:
```yaml
contour:
  extraArgs:
    - --use-proxy-protocol
configInline:
  network:
    num-trusted-hops: 1
  tls:
    fallback-certificate:
      name: wildcard-tls
      namespace: contour
```

where `wildcard-tls` secret is created by cert-manager for `*.example.com`

I have Ingress with similar IngressSpec:

```
rules:
- host: app.example.com
  http:
    paths:
    - backend:
        service:
          name: app-ui
          port:
            name: http
      path: /
      pathType: Prefix
tls:
- hosts:
  - app.example.com
```

This produces the following:

1. `unresolved secret reference` contour error

```
time="2022-06-06T12:06:34Z" level=error msg="unresolved secret reference" context=IngressProcessor error="Secret not found" name=app-ui namespace=app secret=app/
```

2. `envoy.http.original_ip_detection.xff` envoy error

```
[2022-06-06 11:51:46.111][1][warning][config] [source/common/config/grpc_subscription_impl.cc:126] gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) ingress_http: Didn't find a registered implementation for name: 'envoy.http.original_ip_detection.xff'
```

3. Envoy HTTPS endpoints are not starting at all, only HTTP endpoints do (and only if I remove `configInline.network.num-trusted-hops` setting)

**What did you expect to happen:**

1. Not specifying `IngressSpec.tls.secretName` should not produce a log message of type `error`. `IngressSpec.tls.secretName` is optional as per [Kubernetes API Reference](https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/#IngressSpec). 
2. There should not be any `envoy.http.original_ip_detection.xff` envoy-related errors
3. Envoy HTTPS endpoints must be functional and use the configured wildcard certificate as per `fallback-certificate`
4. App must then be available both via `http://app.example.com/` and `https://app.example.com/`

**Environment:**

- Contour version: 
```
contour-7.10.1              	1.20.1     
```
- Kubernetes version: (use `kubectl version`): 1.24
