### ISSUE TITLE
Add "append" to responseHeadersPolicy

### ISSUE THREAD

**Issue by inductor** [projectcontour/contour#4564]
**Please describe the problem you have**

Hi! I'm trying to find out way to *append* params to a response header using Contour (Specifically adding Secure and SameSite param on Set-Cookies)

When I tried the following it didn't append but just set and actually override the param and my app's cookie has gone.

```yaml
      responseHeadersPolicy:
        set:
          - name: Set-Cookie
            value: Secure; SameSite=Lax;
```

This type of change should be supported by Ingress layer.
