### ISSUE TITLE
Httpproxy routes to services in different namespaces

### ISSUE THREAD

**Issue by yangyy93** [projectcontour/contour#4574]
**Please describe the problem you have**
[A clear, concise, description of the problem you are facing. What is the _problem_ that feature X would solve for you?]
In httpproxy, .spec.routes.service only contains the name of the service, and can only route to services in the same namespace as Httpproxy. How about adding a namespace option that allows specifying routes to services on other namespaces. There is a ReferenceGrant in the Gateway to allow this kind of operation.
If I have a requirement to route half of the traffic to service A and half of the traffic to service B, service A is in namespace C and service B is in namespace D.Now it is not possible to achieve it using httpproxy
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: route-diffnamespace
  namespace: testb
spec:
  virtualhost:
    fqdn: example.com
  routes:
    - conditions:
        - prefix: /test
      services:
        - name: httpbin
          port: 80
          namespace: testb
        - name: httpbin
          port: 80
          namespace: testa
```
