### ISSUE TITLE
Make configurable Envoy listener socketOptions to allow DSCP marking for QoS purposes

### ISSUE THREAD

**Issue by egerkke** [projectcontour/contour#4605]
Hi Ladies and Gents,

DSCP (differentiated services code point) is a mechanism used for classifying/prioritizing network traffic on IP networks [DSCP_wiki](https://en.wikipedia.org/wiki/Differentiated_services). Since Contour is used as O&M external interface provider for microservices at our customer, request arrived to support DSCP marking. Therefore all microservice O&M HTTP interface DSCP marking can be done in a unified place.

DiffServ uses 6-bit differentiated services code point (DSCP) in the 8-bit differentiated services field (DS field) in the IP header for packet classification purposes (last 2 bits are reserved - CU). Please see picture with details:

![image2021-11-24_14-39-42](https://user-images.githubusercontent.com/96073071/176655816-8b71a15a-4b1a-41f0-96f3-8f301963667d.png)

Example Envoy IPv4 listener configuration to set CS2 selection via Envoy [Socket Option](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/socket_option.proto)

```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 100.109.96.4, port_value: 10000 }
    socket_options:
    - level: 0           #  0 for IPPROTO_IP
      name: 1            #  1 for IP_TOS
      int_value: 64
      state: STATE_LISTENING
```
int_value 64 will be converted into 8 bits: 0 1 0 0 0 0 0 0 and used to fill the given IP header section of DS according to the picture.
Since the last 2 bits are reserved, this will end up in configuring 0 1 0 0 0 0  as Class Selector that is CS2 according to [Class Selector mapping](https://www.ccexpert.us/traffic-shaping-2/the-class-selector-phb-and-dscp-values.html)

This Class Selector can also be captured in IP packets received from Envoy:
![wireshark](https://user-images.githubusercontent.com/96073071/176666685-6e207bc8-3c44-4c7d-ab66-4e9d8dd6506b.png)

Captured packets:
[dscp_CS2_settings.pcapng.tar.gz](https://github.com/projectcontour/contour/files/9019120/dscp_CS2_settings.pcapng.tar.gz)

Example Envoy IPv6 listener configuration:
```
        socket_options:   #  this values need to be double checked!
        - level: 41        #  41 for IPPROTO_IPv6
          name: 67         #  67 for IPV6_TCLASS
          int_value: 32 
          state: STATE_LISTENING 
```

Example to configure both IPv4 and IPv6 with different DSCP values:
```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: "::", port_value: 10000, ipv4_compat: true }
    socket_options:
    - level: 0
      name: 1
      int_value: 32
      state: STATE_LISTENING
    - level: 41
      name: 67
      int_value: 64
      state: STATE_LISTENING
```

**Reproduction steps (for Ubuntu):**
For reproduction purposes the following configuration of Envoy can be used:
[base_envoy_config_socket_options_CS2.txt](https://github.com/projectcontour/contour/files/9018977/base_envoy_config_socket_options_CS2.txt)

Create a kind network:
```
docker network create -d=bridge -o com.docker.network.bridge.enable_ip_masquerade=true -o com.docker.network.driver.mtu=1400 --opt com.docker.network.bridge.name=docker1 --subnet 100.109.100.0/20 kind
```

Start Envoy container:
```
docker run -it --network kind --ip 100.109.96.4 --mount type=bind,source=<PLACEOFTHECONFIGURATIONFILE>base_envoy_config_socket_options_CS2.txt,target=/config.yaml envoyproxy/envoy-dev:latest /usr/local/bin/envoy -c config.yaml --service-cluster front-proxy
```
Copy go, [myserver.go.tar.gz](https://github.com/projectcontour/contour/files/9019199/myserver.go.tar.gz) (simple echo application) into container, install tcpdump and start myserver.go:
```
export ENVOY_CONTAINER=$(docker container ls -l -q)
docker cp /usr/local/go $ENVOY_CONTAINER:/usr/local/
docker cp myserver.go $ENVOY_CONTAINER:/tmp
docker exec -it $ENVOY_CONTAINER bash
export PATH=$PATH:/usr/local/go/bin
cd /tmp
apt-get update
apt-get install -y tcpdump
go run myserver.go
```
Start tcpdump in another shell:
```
export ENVOY_CONTAINER=$(docker container ls -l -q)
docker exec -it $ENVOY_CONTAINER bash
cd /tmp
tcpdump -i any -w dscp
```
Create direct entry in /etc/hosts file that targets the Envoy container:
```
100.109.96.4   primary.com
```
In another shell execute curl command:
```
curl primary.com:10000
```
Results can be copied and analyzed:
```
export ENVOY_CONTAINER=$(docker container ls -l -q)
docker cp $ENVOY_CONTAINER:/tmp/dscp .
```

Other notes:
- Request would be to make configurable int_value via Contour for IPv4 and IPv6 use cases as well
- Different Class Selectors shall be able to be configured on the same listener for IPv4 and IPv6
- Configurability for specific Class Selectors (e.g.: only to support CS1, CS2 and CS3) shall not be limited, since the Class Selectors can be changed in the future.
- Configuring int_value 32 ended up in 0 0 1 0 0 0 as DSCP value that verified to be Class Selector 1 by tcpdump file
- IPv6 listener configuration parameters haven't been verified yet. Once this feature request accepted, can be tried out as well.
- TCP KeepAlive is also implemented via socketOption: [2638](https://github.com/projectcontour/contour/pull/2638), might be interesting to have some general function to configure socket options
