### ISSUE TITLE
Path based routing is not working on contour

### ISSUE THREAD

**Issue by rshiva777** [projectcontour/contour#4628]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Deployed multiple nginx applications and tried to access it using httpproxy with path based routing

**What did you expect to happen:**
Path based routing should work

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I tried to configure multiple apps, one with the root prefix, and the other one with /blog prefix. The root prefix seems to be working fine, but the /blog prefix is not working.

**Envoy log:**
**when i access the / prefix:**
[2022-07-20T11:05:21.955Z] "GET / HTTP/1.1" 304 - 0 0 1 1 "10.96.4.1" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" "7bd0e9b1-a441-4f50-975f-5eb2f2afv557" "nginx.test.com" "10.96.0.31:80"

**when i access the /blog prefix:**
[2022-07-20T11:05:27.032Z] "GET /grafana/api/live/ws HTTP/1.1" 403 - 0 0 0 - "10.96.4.1" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" "c5s4049c-49c4-4137-8ae9-43d4t6caecaa" "nginx.test.com" "-"

**Httpproxy yaml:**
`apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: multiple-paths
  namespace: default
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: nginx
      port: 80
  - conditions:
    - prefix: /blog
    services:
    - name: nginxnew
      port: 80
  virtualhost:
    fqdn: nginx.test.com
`
**Environment:**

- Contour version: v1.12.0
- Kubernetes version: (use `kubectl version`): 1.21
- Kubernetes installer & version: 1.21
- Cloud provider or hardware configuration: vmware
- OS (e.g. from `/etc/os-release`): ubuntu

**Comment by youngnick** [comment]
Hi @rshiva777, did you check that your app is configured to accept requests at `/blog`? Contour does not strip the matched path, so the requests that arrive at the backend pods will be `http://nginx.test.com/blog/<path>`, not `http://nginx.test.com/<path>`.

If you are wanting the latter, you will probably need to configure path rewriting to remove the matched path, see https://projectcontour.io/docs/v1.21.1/config/request-rewriting/#path-rewriting for more details.

**Comment by rshiva777** [comment]
@youngnick  Thanks for the inputs.
I am able to get succeed by adding the below ingress:

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: nginx
  namespace: default
spec:
  routes:
  - conditions:
    - prefix: /nginx01
    pathRewritePolicy:
      replacePrefix:
      - prefix: /nginx01
        replacement: /
    services:
    - name: nginx01
      port: 80
  virtualhost:
    fqdn: nginxr.aqa-rat-tst-1.rat.gks.vodafone.com
```

However if i deleted the httpproxy resource, still i am able to reach the service from fqdn. Not sure why this is happening.
Could you please update on this. Moreover i dont see any logs on envoy
