### ISSUE TITLE
Contour supports using different ports for service health check

### ISSUE THREAD

**Issue by yangyy93** [projectcontour/contour#4655]
**Please describe the problem you have**
[A clear, concise, description of the problem you are facing. What is the _problem_ that feature X would solve for you?]
 I use httpproxy to route to port 8080 of a service, but my health check port is 8998. I checked the relevant documentation of envoy, envoy supports the use of a different port than upstream services for health check,https://www.envoyproxy.io/docs/envoy/v1.23.0/api-v3/config/endpoint/v3/endpoint_components.proto#envoy-v3-api-msg-config-endpoint-v3-endpoint-healthcheckconfig. Can contour support this configuration?
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: example
  namespace: contour
spec:
  virtualhost:
    fqdn: example.com
  routes:
    - conditions:
        - prefix: /test
      healthCheckPolicy:
        path: /
        port: 8998
      services:
        - name: httpbin
          port: 8080
```
