### ISSUE TITLE
Support using placeholders in rewrite-target

### ISSUE THREAD

**Issue by pingsutw** [projectcontour/contour#4671]
Support using placeholder $2 in rewrite-target.

Refer to https://kubernetes.github.io/ingress-nginx/examples/rewrite/#rewrite-target
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: rewrite
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: rewrite.bar.com
    http:
      paths:
      - path: /something(/|$)(.*)
        pathType: Prefix
```
