### ISSUE TITLE
Add Authentication using `ExtensionRef` to Gateway API

### ISSUE THREAD

**Issue by joda01** [projectcontour/contour#4675]
As a user of contour I want to configure external authentication backend using `Gateway API` similar to the `HTTProxy API` as described in [external-authorization](https://projectcontour.io/guides/external-authorization/) .  As described in [Gateway API specification](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1alpha2.HTTPRouteFilter) `extensionRef` filters should be used to implement such mechanisms like authentication.  

I want to keep the implementation as similar to  `HTTProxy API`  as possible.

- One proposal would be to use the existing `ExtensionService` CRD and select the custom filter function using the specified `group` field of the `ExtensionRef` object of the Gateway API specification.   
  - **Disadvantage** is that there is no way in the actual CRD to specify additional settings needed by the auth server like `context` fields, `FailOpen ` option, `timeout` field, and `requested` body.  
  -  **Advantage** easy to switch from `HTTProxy` to `API Gateway` since the `ExtensionService` deployment keeps the same. Fast to implement.
- An other way could be to define a new CRD `ExtensionRefAuth` to handle this extension.   
  - **Disadvantage** A new processor and CRD definition is needed. Not backward compatible to `HTTProxy API`.   
  - **Advantage**: All configurations needed for auth can be added to the newly defined CRD.

I created a working example implementation using proposal 1 just to keep it simple.
You can have a look at branch https://github.com/fronius-sed/contour/tree/add-custom-filter-to-gateway

---

*Service of the auth backend*
```
apiVersion: v1
kind: Service
metadata:
  name: contourauthservice
spec:
  ports:
  - name: h2c
    port: 9443
```

*Extension Reference*
```
apiVersion: projectcontour.io/v1alpha1
kind: ExtensionService
metadata:
  name: contourauth
spec:
  protocol: h2
  services:
  - name: contourauthservice
    port: 9443
```

*HTTPRoute example*
```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: nginx-web-server
spec:
  parentRefs:
  - name: parent-gateway
  rules:
  - matches:
    - path:
        value: /
        type: PathPrefix
    filters:
    - type: ExtensionRef
      extensionRef:
       kind: ExtensionService
       group: authorization
       name: contourauth
    backendRefs:
    - name: nginx-web-server-service
      port: 8080
```
