### ISSUE TITLE
I have a question about contour + Gateway API

### ISSUE THREAD

**Issue by kahirokunn** [projectcontour/contour#4728]
**What question do you have?:**

https://projectcontour.io/guides/gateway-api/

I am working on this `Option #2: Dynamically provisioned` material.

The LoadBalancer Service is created when the Gateway is created.

Q1: Is there any way to give annotations when this LoadBalancer Service is created?
Example of annotations to be added: hogehoge

Q2: Is there any way to have Ingress with annotations created instead of LoadBalancer Service? For example, we need it for an ALB + WAF configuration.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: v1.22.1
- Kubernetes version: (use `kubectl version`): eks1.23
- Kubernetes installer & version: EKS
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): amazon linux 2

**Comment by skriss** [comment]
> Q1: Is there any way to give annotations when this LoadBalancer Service is created?

Yes, there is -- https://projectcontour.io/guides/gateway-api/#next-steps describes generally how to attach parameters to your `GatewayClass` to customize the Gateways that are provisioned. Specifically, in your `ContourDeployment`, you'd want to set `spec.envoy.networkPublishing.serviceAnnotations` (see [API documentation](https://projectcontour.io/docs/main/config/api/#projectcontour.io/v1alpha1.NetworkPublishing).

> Q2: Is there any way to have Ingress with annotations created instead of LoadBalancer Service? For example, we need it for an ALB + WAF configuration.

No, the Gateway provisioner does not create Ingresses, however you could provision a Gateway with either a NodePort or ClusterIP service using a similar approach as for the above, and setting `spec.envoy.networkPublishing.type`, and then doing something out-of-band to get traffic to it.

**Comment by kahirokunn** [comment]
That's just what I was looking for! Thank you!

**Comment by kahirokunn** [comment]
@skriss Thx!
I have written the following ContourDeployment as you advised.

```yaml
apiVersion: projectcontour.io/v1alpha1
kind: ContourDeployment
metadata:
  labels:
    argocd.argoproj.io/instance: contour-gateway-example
  name: contour-internal
  namespace: projectcontour
spec:
  envoy:
    networkPublishing:
      type: ClusterIPService
```

As a result, the following ClusterIPService was created.

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    projectcontour.io/owning-gateway-name: contour-internal-gateway
  name: envoy-contour-internal-gateway
  namespace: projectcontour
spec:
  clusterIP: 172.20.46.218
  clusterIPs:
  - 172.20.46.218
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: envoy-contour-internal-gateway
  sessionAffinity: None
  type: ClusterIP
```

envoy is placed on all nodes in Daemonset.
When `internalTrafficPolicy: Cluster` is set, north-south traffic occurs. 
https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/2086-service-internal-traffic-policy/README.md

I think I need to set `internalTrafficPolicy: Local` to deal with the north-south traffic problem, how can I do that?
Also, if I am mistaken, I would appreciate it if you could point this out to me.
