### ISSUE TITLE
Enable PROXY protocol on AWS，AWS NLB all target group is unhealthy.

### ISSUE THREAD

**Issue by kinnylee** [projectcontour/contour#4833]
**What steps did you take and what happened:**

we want to envoy support client source address。
https://projectcontour.io/guides/proxy-proto/ 

1. contour deployment add "--use-proxy-protocol" args
2. envoy service add annotation:
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /ready
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8002"
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: http
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"

then, install contour, all  pod is running。

aws-loadbalancer-controller:  amazon/aws-alb-ingress-controller:v2.3.1

at aws console, loadbalancer target is pod ip, but is not healthy。

**What did you expect to happen:**
AWS NLB all target group is healthy。

--use-proxy-protocol only add envoy.filters.listener.proxy_protocol to envoy listener_filters on listener 8080,
we hope to add envoy.filters.listener.proxy_protocol to envoy listener_filters on listener 8002, then, aws loadbalancer health
check can be healthy.

in addition, we run this command is ok: 
grpcurl -d '{ "name": "world" }'\  -authority <grpc-fqdn> -plaintext <nlb address>:80 helloword.Greeter/SayHello

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: 1.19.1
- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-6d3986b", GitCommit:"8877a3e28d597e1184c15e4b5d543d5dc36b083b", GitTreeState:"clean", BuildDate:"2022-07-20T22:05:32Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version: 1.21

- Cloud provider or hardware configuration: 

- OS (e.g. from `/etc/os-release`): 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

- AWS load balancer controller:
 ```bash
    kubectl -n kube-system get deploy  aws-load-balancer-controller -oyaml |grep image:
        image: amazon/aws-alb-ingress-controller:v2.3.1
 ```

**Comment by skriss** [comment]
One note here is that Contour/Envoy don't actually open Listeners on ports 80/443 until there is some configuration in place (and Ingress, HTTPProxy or Gateway/HTTPRoute), which could be causing your NLB health checks to fail - have you configured any routing yet?

xref. #4643

**Comment by sunjayBhatia** [comment]
also the port and path you have configured there to healthcheck Envoy are not exposed by the Envoy Pod Spec or Service so they are not available outside the worker node Envoy is running on

**Comment by kinnylee** [comment]
> One note here is that Contour/Envoy don't actually open Listeners on ports 80/443 until there is some configuration in place (and Ingress, HTTPProxy or Gateway/HTTPRoute), which could be causing your NLB health checks to fail - have you configured any routing yet?
> 
> xref. #4643



> One note here is that Contour/Envoy don't actually open Listeners on ports 80/443 until there is some configuration in place (and Ingress, HTTPProxy or Gateway/HTTPRoute), which could be causing your NLB health checks to fail - have you configured any routing yet?
> 
> xref. #4643

I have configured NLB health annotation is 8001 port & /ready path，not 80/443
and  HTTPProxy like this:
```bash
kubectl get httpproxy -n test my-grpc-service
NAME              FQDN                      TLS SECRET   STATUS   STATUS DESCRIPTION
my-grpc-service   my-grpc-service.foo.com                valid    Valid HTTPProxy
```
and generate envoy config:
# kubectl -n contour exec -it contour-envoy-6bbcf449bc-pmjl7 -- sh
Defaulted container "shutdown-manager" out of: shutdown-manager, envoy, envoy-initconfig (init)
$ curl 127.0.0.1:9001/config_dump?include_eds
```yaml
{
        "name": "my-grpc-service.foo.com",
        "domains": [
         "my-grpc-service.foo.com"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/yages.Echo/Ping"
          },
          "route": {
           "cluster": "test/grpc-echo/9000/da39a3ee5e"
          }
         },
"endpoint_config": {
      "@type": "type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment",
      "cluster_name": "test/grpc-echo",
      "endpoints": [
       {
        "locality": {},
        "lb_endpoints": [
         {
          "endpoint": {
           "address": {
            "socket_address": {
             "address": "10.110.124.150",
             "port_value": 9000
            }
           },
           "health_check_config": {}
          },
          "health_status": "HEALTHY",
          "load_balancing_weight": 1
         },
```
