### ISSUE TITLE
In the configuration Ingress (ingressClass alb) -> NodePort Service -> envoy, `Status.LoadBalancer` is empty.

### ISSUE THREAD

**Issue by kahirokunn** [projectcontour/contour#4951]
**What question do you have?:**

I use ALB instead of LoadBalancer Service because I want to use AWS WAF.
I am using contour with the following configuration.
Ingress (ingressClass alb) -> NodePort Service -> envoy.

However, there is nothing in the HTTPProxy `Status.LoadBalancer`.

I am using External DNS and would like to have Ingress's `Status.LoadBalancer` inserted in `Status.LoadBalancer`.

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    argocd.argoproj.io/instance: argocd
  name: argocd.example.com
  namespace: argocd
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: argocd-server
      port: 80
  virtualhost:
    fqdn: argocd.example.com
status:
  conditions:
  - lastTransitionTime: "2022-12-29T06:36:02Z"
    message: Valid HTTPProxy
    observedGeneration: 1
    reason: Valid
    status: "True"
    type: Valid
  currentStatus: valid
  description: Valid HTTPProxy
  loadBalancer: {}
```

I tried my best to read the code and documentation, but I couldn't quite figure out how to do it.
Thx.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: v1.23.2
- Kubernetes version: 1.24:
- Kubernetes installer & version: EKS
- Cloud provider or hardware configuration: aws
- OS (e.g. from `/etc/os-release`): bottlerocket
