### ISSUE TITLE
Support for external auth with HTTP virtual hosts

### ISSUE THREAD

**Issue by claytonig** [projectcontour/contour#4954]
**Please describe the problem you have**
I am evaluating contour as a potential candidate for our ingress across our tech stack. We terminate TLS at the cloud provider level, which is a requirement. The cloud provider load balancers do not forward the SNI information if TLS is terminated at the load balancer.  

External authorization requires a virtual host to have HTTPS enabled, which doesn't work with the above mentioned constraints. 

**Current setup**
Cloud provider: AWS 
Helm chart: [Bitnami](https://github.com/bitnami/charts/tree/main/bitnami/contour)

I tried the setup both with an NLB and an ELB. Listing the annotations of the `LoadBalancer` service as rest of the chart was pretty much default. 

ELB
```
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:xxx
```

NLB
```
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-type: nlb
     service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
     service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
     service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:xxx"
     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
```

In both cases i got the following response `curl: (52) Empty reply from server`

**Comment by sunjayBhatia** [comment]
one solution, which the community would need to indicate if it is acceptable could be to have a globally configured ExtAuth Service that all HTTP vhosts would use and could be the default for all non-HTTP vhosts but overridable in HTTPS vhosts only

this would need some careful documentation etc. (and some more validation) to make sure people understand how it works

**Comment by claytonig** [comment]
Yeah, I was also thinking along the same lines. Here's what I had in mind. 


GlobalHttpExtAuth dial on the contour configuration. 

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: contour
  namespace: projectcontour
data:
  contour.yaml: |
    GlobalHttpExtAuth:
      # extensionService is the <namespace>/<name>
      # of the ExtensionService we created in the
      # previous step.
      extensionService: projectcontour/externalAuth
      # failOpen is whether to allow requests through
      # if there's an error.
      failOpen: false
      # Context is a set of key/value pairs that are sent to the authentication server in the check request.
      context:
	  	- header1: value1
	  	- header2: value2
       # ResponseTimeout configures maximum time to wait for a check response from the authorization server
      responseTimeout: 1s
```

This would configure external auth across all HTTPProxies on the HTTP Listener. 


For a scenario where both, GlobalHttpExtAuth and ExtAuth on an HTTPProxy are configured I was in two minds: 

###### Option 1
Leave it as it is, since HTTPProxy will do a 301 to the HTTPS listener. 

###### Option 2

This is the one which I don't like a lot since it's not as explicit, Short circuit all of the GlobalHttpExtAuth. So, defining a ExtAuth on an httpProxy overrides the all of the GlobalHttpExtAuth.
