### ISSUE TITLE
How many requests and limits are appropriate for the resources of the envoy in Contour in the production environment?

### ISSUE THREAD

**Issue by kahirokunn** [projectcontour/contour#4979]
I am using a 3AZ configuration on AWS (EKS). I am trying to deploy one Envoy per zone. What are the appropriate requests and limits for the Envoy resources in the production environment for Contour? 👀 

```yaml
resources:
  requests:
    cpu: ???m
    memory: ???Mi
  limits:
    cpu: ???m
    memory: ???Mi
```
