### ISSUE TITLE
HTTPProxy `include` validation recently became too tight

### ISSUE THREAD

**Issue by ecordell** [projectcontour/contour#5014]
**What steps did you take and what happened:**
Prior to https://github.com/projectcontour/contour/pull/4931, this worked:

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: frontdoor
  namespace: example
spec:
  includes:
  - name: serviceA
    namespace: example
  - name: serviceB
    namespace: example
  virtualhost:
    fqdn: frontdoor.example.com
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
  name: serviceA
  namespace: example
spec:
  routes:
  - conditions:
    - prefix: /graphql
    services:
    - name: serviceA
      port: 5000
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: serviceB
  namespace: example
spec:
  routes:
  - conditions:
    - prefix: ""
    services:
    - name: serviceB
      port: 3000
```

But after the recent change, the top-level `HTTPProxy` now reports:
```
  conditions:
  - errors:
    - message: duplicate conditions defined on an include
      reason: DuplicateMatchConditions
      status: "True"
      type: IncludeError
    lastTransitionTime: "2023-01-26T12:09:47Z"
    message: At least one error present, see Errors for details
    observedGeneration: 1
    reason: ErrorPresent
    status: "False"
    type: Valid
```

Technically, the `includes` do have equal match conditions (nothing) - but they resolve to different fully resolved paths once the delegated HTTPProxy's paths is considered.

**What did you expect to happen:**

I expected this to be a valid config - from previous versions of contour, I know that this configuration used to create the envoy configuration that I expected (both services were routed properly). It seems like it reduces the value of the `includes` feature if I have to replicate the paths on the top-level object.

**Environment:**

- Contour version: v1.24.0-rc.1
