### ISSUE TITLE
HTTPProxy include processing: Configure 502 if include references another root

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#5016]
**Please describe the problem you have**
To be consistent with the logic when an Include references a nonexistent HTTPProxy (see here: https://github.com/projectcontour/contour/blob/7722ead11204b8253bcbc9cc5a71ed18add19417/internal/dag/httpproxy_processor.go#L647-L660) we should consider return a 502 when the include conditions are valid but the referenced HTTPProxy in the include is invalid.

This seems like the same type of behavior as the logic where we return a 502 when the referenced child HTTPProxy doesn't exist. We don't want requests that match the correctly configured match condition to fall through to different route, rather we should notify the user through 502s that the server configuration is incorrect.

**Comment by theVJagrawal** [comment]
Hi @sunjayBhatia  I want to work on this issue so can you please assign it to me

**Comment by sunjayBhatia** [comment]
@theVJagrawal let us know if you need any pointers!

**Comment by liangyuanpeng** [comment]
@sunjayBhatia 

>  the include conditions are valid but the referenced HTTPProxy in the include is invalid.

Could you provide some config for it?

> Set 502 response when include was not found but include condition was valid. 

I can see the config of it is like :

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: httpbin
spec:
  includes:
    - name: httpbin3  # Not exist
      conditions:
      -  prefix: /ip
  ingressClassName: contour
  virtualhost:
    fqdn: local.projectcontour.io
  routes:
    - conditions:
        - prefix: /status
      services:
        - name: httpbin
          port: 80
```
