### ISSUE TITLE
Add ability to specify default LB strategy and health check

### ISSUE THREAD

**Issue by alexbrand** [projectcontour/contour#515]
The IngressRoute specification supports providing an overall LB strategy and health check that applies to all services found inside the given IngressRoute:

```
apiVersion: contour.heptio.com/v1alpha1
kind: IngressRoute
metadata:
  name: google
  namespace: prod
spec:
  virtualhost:
    fqdn: www.google.com
  strategy: RoundRobin # (Optional) LB Algorithm to apply to all services, defaults for all services
  healthCheck (Optional):
    [....] 
  routes:
    [....]
```
