### ISSUE TITLE
websocket-route with a wildcard path?

### ISSUE THREAD

**Issue by majusmisiak** [projectcontour/contour#5193]
**What question do you have?:**

Contour documentation mentions `projectcontour.io/websocket-routes` annotation to enable websockets on path basis. 
Right now I am working with an application, that does not have single static websocket endpoint, but multiple dynamic ones.

For websocket to work, I am simply enabling websocket on *all paths* by specifying  `projectcontour.io/websocket-routes: "/"` in Ingress configuration.

 Is it possible to enable websocket on certain wildcard paths?

If it is not possible, are there any implications (performance and security wise) that I should aware of, when enabling websocket on all paths? (All - including plain http paths)

**Anything else you would like to add:**

Example use case - Atlantis(1) project exposes websocket endpoints on multiple dynamic urls - `/jobs/{uuid}/ws` - which could be matched with a wildcard path `/jobs/*/ws`

**Environment:**

(1) https://github.com/runatlantis/atlantis

**Comment by skriss** [comment]
Hey @majusmisiak - you should be able to accomplish this by defining one or more regex path matches in the Ingress itself (see https://projectcontour.io/docs/1.24/config/ingress/#ingress-rules - you'd want an `ImplementationSpecific` match type), and then referencing the value(s) of the `path` field in the `projectcontour.io/websocket-routes` annotation. Basically, the comma-separated values in the annotation need to correspond to a `path` value in the Ingress rules.

**Comment by majusmisiak** [comment]
Hey @skriss - I just tested and it works, as long as the wildcard path is configured *both* in the annotation *and* in a list of http paths.

Just providing the annotation and single path ( `path: /` ) is not enough.

Full working example:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    projectcontour.io/websocket-routes: /jobs/.*/ws
  name: atlantis
  namespace: atlantis
spec:
  rules:
  - host: atlantis.home.lan
    http:
      paths:
      - backend:
          service:
            name: atlantis
            port:
              number: 80
        path: /jobs/.*/ws
        pathType: ImplementationSpecific
      - backend:
          service:
            name: atlantis
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - atlantis.home.lan
    secretName: atlantis-tls

```

Thanks a lot for help, closing the issue.
