### ISSUE TITLE
[provisioner] envoy should expose the metrics port.

### ISSUE THREAD

**Issue by Jean-Daniel** [projectcontour/contour#5232]
**What steps did you take and what happened:**

When deploying Envoy with the contour provisioner, the generated pods expose a single port:

```yaml
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
```

It should also expose the metric port, as it is required to monitor the envoy pods using a `PodMonitor` or a `ServiceMonitor`.

```yaml
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    - containerPort: 8002
      name: metrics
      protocol: TCP
```

The port number should be derived from `ContourDeployment.spec.runtimeSettings.envoy.metrics.port`

**What did you expect to happen:**

Deploy envoy using contour provisioner and gateway, and be able to monitor Envoy using a PodMonitor, which required that the monitoring port be exposed by the target pod.

**Environment:**

- Contour version: 1.24.2
