### ISSUE TITLE
How to set up `GRPCRoute` for any method and service?

### ISSUE THREAD

**Issue by kandeshvari** [projectcontour/contour#5374]
How to set up `GRPCRoute` for any methods and services?

If I omit this section, I get the error:

```
GRPCRoute.Spec.Rules.Matches.Method: Both Service and Method need be configured.
```

My manifest:

```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  name: tempo-grpc
  namespace: tempo
spec:
  hostnames:
    - tempo-otlp.k8s.local
  parentRefs:
    - name: tempo-grpc
      group: gateway.networking.k8s.io
      kind: Gateway
      namespace: tempo
  rules:
    - backendRefs:
        - name: tempo-distributor
          port: 4317
```          

**Environment:**

- Contour version: 1.25
- Kubernetes version: 1.26
