### ISSUE TITLE
Ingress configuration while using Contour Gateway Provisionner

### ISSUE THREAD

**Issue by davinkevin** [projectcontour/contour#5382]
**Context**

I'm currently using contour, as an IngressController using only `Ingress` objects. 
To start the transition to `GatewayAPI`, I would like to migrate my apps "one by one", then I would like to use the Contour-Gateway-Provisionner as a solution for this. The documentation states:

> Note that although the provisioning request itself is made via a Gateway API resource (Gateway), this method of installation still allows you to use any of the supported APIs for defining virtual hosts and routes: Ingress, HTTPProxy, or Gateway API’s HTTPRoute and TLSRoute

So it looks like the best solution for me. 

However, I have a specific setup with 3 IPs provided by MetalLB attached to multiple networks, and some `Ingress` should listen on one, some on others…

I've simulated my migration path and reach a point where I don't know how to configure `Ingress` object to use one Gateway(class) or another. 

**What question do you have?:**

Is it possible to instrument an `ingress` object to be selected by one specific `ContourDeployment` configuration, to use a specific Ip in my case? 

In the current situation, I feel like the configuration "available" is selected. I've even seen the `Address` field in the Ingress changed without any reason, like if the reconciliation phase generated a conflict.

**Anything else you would like to add:**

Contour is a wonderful project, I really like it… but I don't think it helps 😅. 

All files used in this sandbox are available here: https://gitlab.com/davinkevin.fr/home-server/-/commit/599b0163d2f316cfd037af889ab498e6b7896f7a

**Environment:**

- Contour version: 1.25.0, using Contour Gateway Provisioner
- Kubernetes version: (use `kubectl version`): 1.26
- Kubernetes installer & version: k3s
- Cloud provider or hardware configuration: bare-metal
- OS (e.g. from `/etc/os-release`): Debian

**Comment by davinkevin** [comment]
I think I've found the answer for it: https://projectcontour.io/docs/1.25/deploy-options/#using-the-gateway-provisioner

I had to create a ContourDeployment configuration like this: 

```yaml
kind: ContourDeployment
apiVersion: projectcontour.io/v1alpha1
metadata:
  namespace: projectcontour
  name: internal
spec:
  runtimeSettings:
    ingress:
      classNames:
        - internal
  contour:
    deployment:
      replicas: 1
  envoy:
    networkPublishing:
      serviceAnnotations:
        metallb.universe.tf/address-pool: internal
```

and use the `ingressClassName: internal` in the `ingress` object. 

This example could be an external link provided in the official documentation for [`IngressConfig`](https://projectcontour.io/docs/1.25/config/api/#projectcontour.io/v1alpha1.IngressConfig), it could have helped me on this.
