### ISSUE TITLE
Ingress `spec.rules.*.http.paths.*.backend.service.port.name` doesn't work with Contour Gateway provisioner

### ISSUE THREAD

**Issue by davinkevin** [projectcontour/contour#5383]
**What steps did you take and what happened:**

First, I've deployed the following set of YAMLs: 

* [Gateway Provisioner](https://raw.githubusercontent.com/projectcontour/contour/release-1.25/examples/render/contour-gateway-provisioner.yaml)
* The following Gateway, GatewayClass and ContourDeployment configuration in `projectcontour` namepsace: 

```
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: legacy
spec:
  controllerName: projectcontour.io/gateway-controller
  parametersRef:
    kind: ContourDeployment
    group: projectcontour.io
    name: legacy
    namespace: projectcontour
---
kind: ContourDeployment
apiVersion: projectcontour.io/v1alpha1
metadata:
  namespace: projectcontour
  name: legacy
spec:
  contour:
    deployment:
      replicas: 1
  envoy:
    networkPublishing:
      serviceAnnotations:
        metallb.universe.tf/address-pool: legacy
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: legacy
  namespace: projectcontour
spec:
  gatewayClassName: legacy
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
```

And I've deployed `httpbin` Deployment & Service in `httpbin` namespace, using this YAML: 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpbin
  name: httpbin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        name: httpbin
        ports:
          - containerPort: 80
            name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpbin
  name: httpbin
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: httpbin
  sessionAffinity: None
  type: ClusterIP
```

To expose the `httpbin`, I've deployed the following ingress:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  rules:
    - host: httpbin.192.168.74.203.nip.io
      http:
        paths:
          - backend:
              service:
                name: httpbin
                port:
                  name: http
            pathType: Prefix
            path: /
```

If I try to connect to the app, I have this error: 

```shell
$ curl http://httpbin.192.168.74.203.nip.io/
curl: (7) Failed to connect to httpbin.192.168.74.203.nip.io port 80 after 178 ms: Couldn't connect to server
```

If I change the `ingress` definition, to use `port.number` instead of `port.name`, like this: 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  rules:
    - host: httpbin.192.168.74.203.nip.io
      http:
        paths:
          - backend:
              service:
                name: httpbin
                port:
                  number: 80 # <- only change
            pathType: Prefix
            path: /
```

The result is different, the app is available: 

```
$ curl http://httpbin.192.168.74.203.nip.io/
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>httpbin.org
…
```

**What did you expect to happen:**

I expect the Contour Gateway Provisioner to support `ingress` with the same set of feature than the original Contour installation type. 

In this specific case, I should be able to configure ingress with `port.name` or `port.number` indifferently. 

**Anything else you would like to add:**

Contour is a really good project, thank you for it ❤️

**Environment:**

- Contour version: 1.25
- Kubernetes version: (use `kubectl version`): 1.26
- Kubernetes installer & version: k3s-1.26
- Cloud provider or hardware configuration: BareMetal
- OS (e.g. from `/etc/os-release`): Debian
