### ISSUE TITLE
Unable to force envoy to always generate request ids

### ISSUE THREAD

**Issue by tailrecur** [projectcontour/contour#5385]
**What steps did you take and what happened:**
I’m running Contour as an ingress controller. Some clients pass in a `X-Request-Id` header in the call but don’t always ensure this is globally unique which leads to issues during debugging. I’d like to rewrite the client-provided `X-Request-Id` to `Client-Request-Id` header and then force envoy to always generate an internal `X-Request-Id` header. However, I see that Contour configures envoy to always [preserve external headers](https://github.com/projectcontour/contour/blob/6efb36626993e12ee5a75089d24af4ecc667763b/internal/envoy/v3/listener.go#L486) so the internal request id is not generated.
I tried adding a remove section to the global policy but that leads to the `X-Request-Id` being completely dropped (both external and internal one) so no request id appears in the access logs.
```
    policy:
      request-headers:
        set:
          Client-Request-Id: "%REQ(X-REQUEST-ID)%"
        remove:
          - X-Request-Id
```
Any suggestions on how to achieve this?

**What did you expect to happen:**
Envoy overrides external `X-Request-Id` header with internal generated one

**Environment:**

- Contour version: 1.25.0
