### ISSUE TITLE
prefix replacements should be allowed when using exact match

### ISSUE THREAD

**Issue by Jean-Daniel** [projectcontour/contour#5387]
**What steps did you take and what happened:**

Create a `Route` with as single exact match condition.

Add a `PathRewritePolicy` with a single `replacePrefix` entry.

The HTTPProxy status is `invalid`.

 ```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: my-api
spec:
  routes:
  - conditions:
    - exact: /v1/myservice
    pathRewritePolicy:
      replacePrefix:
      - replacement: /api/v1/myservice
    services:
    - name: api
      port: 8080
status:
  conditions:
  - errors:
    - message: cannot specify prefix replacements without a prefix condition
      reason: MustHavePrefix
      status: "True"
      type: PrefixReplaceError
    message: At least one error present, see Errors for details
    reason: ErrorPresent
    status: "False"
    type: Valid
  currentStatus: invalid
  description: At least one error present, see Errors for details
  loadBalancer: {}
```

**What did you expect to happen:**

When matching an `exact` prefix, contour should allow to specify `PathRewritePolicy` to rewrite the matched path.

**Environment:**

- Contour version: 1.25.0
