### ISSUE TITLE
error calculating structured merge diff: error building typed value from config resource: .spec.virtualhost.authorization.globalExtAuthDisabled: field not declared in schema

### ISSUE THREAD

**Issue by kahirokunn** [projectcontour/contour#5418]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

The CRD of the HTTPProxy in contour does not contain globalExtAuthDisabled.

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: xxx.example.com
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: xxx
          port: 80
  virtualhost:
    authorization:
      globalExtAuthDisabled: true
    fqdn: xxx.example.com
```

```
error calculating structured merge diff: error building typed value from config resource: .spec.virtualhost.authorization.globalExtAuthDisabled: field not declared in schema
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version:
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):
