### ISSUE TITLE
How do I enable websockets support in native Ingress resource 

### ISSUE THREAD

**Issue by edtshuma** [projectcontour/contour#5443]
I have a Contour deployment and currently I use Ingress resource and Contour's HTTPProxy for my one my backend services that implements a notifications feature. I am looking for a way to either :

1.  Annotate the native K8s Ingress resource with something that will "enable" websockets. By native K8s Ingress resource I mean resources under  `apiVersion: networking.k8s.io/v1` . This way I will avoid having a separate resource for  Contour's HTTPProxy  and I only have to maintain a single Ingress resource like this :

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    ingress.kubernetes.io/tls-minimum-version: "1.2"
spec:
  ingressClassName: contour
  tls:
  - hosts:
      - mydomain.com
    secretName: mydomain.com-tls
  rules:
  - host: mydomain.com
    http:
      paths:       
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: my-service
            port:
              number: 80  
```

2.  Annotate Contour's IngressRoute resource  with something that will "enable" websockets. My assumption is that I should also do away with maintaining HTTPProxy resource. However I am not sure if this IngressRoute will be able to work as a native K8S Ingress resource  - routing normal K8S traffic.

I have noticed the IngressRoute resource uses annotation `apiVersion: projectcontour.io/v1` . Btw I have already looked at the [this](https://github.com/projectcontour/contour/issues/595) issue  and I have noted the annotation that I should be using (at least for now).

My issue on this approach is that it seems IngressRoute does not handle normal Kubernetes traffic and cannot act as a drop-in replacement for Ingress out of the box    - is there a way I can combine combine IngressRoute and Ingress , and come up with (posssibly) a single resource that also enables websockkets?

This is what I have for now ;

```
apiVersion: projectcontour.io/v1
kind: IngressRoute
metadata:
  name: my-ingressroute
spec:
  virtualhost:
    fqdn: mydomain.com
  tls:
    secretName: mydomain.com-tls
  routes:
    - match: /api
      services:
        - name: my-service
          port: 80
```
