### ISSUE TITLE
Support Termination mode for TLS listener protocol (TLSRoutes, TCPRoutes)

### ISSUE THREAD

**Issue by Rycieos** [projectcontour/contour#5461]
This is an enhancement request, but it could also be considered a bug, as the Kubernetes Gateway API _might_ require this support (see @skriss's [comment](https://github.com/projectcontour/contour/pull/5160#issuecomment-1585096213)).

### Description
A `Gateway` object with a `Listener` that accepts `TLSRoute`s should support `mode: Terminate` as detailed in the [GatewayTLSConfig](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.GatewayTLSConfig) spec.

### User story
I have an application that speaks a nonstandard application protocol over TCP. I want the traffic wrapped in TLS. And since I want my application to be as simple as possible, I want the Gateway to terminate the TLS tunnel.

This can be specified with this example Gateway Spec:
```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
spec:
  listeners:
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TLSRoute
    name: tls
    port: 5000
    protocol: TLS
    tls:
      mode: Terminate
      certificateRefs:
      - name: my-secret
```
And a TLSRoute like:
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
spec:
  hostnames:
    - example.com
  rules:
    - backendRefs:
      - kind: Service
        name: example
        port: 3102
```

### Issue
Currently, if this Gateway is created, Contour returns an error on the Gateway object with the message:
> Listener.TLS.Mode must be "Passthrough" when protocol is "TLS".
