### ISSUE TITLE
Support of minimumProtocolVersion when Envoy acts as client

### ISSUE THREAD

**Issue by egerkke** [projectcontour/contour#5501]
Hi Ladies and Gents,

With this feature request I would ask for supporting to configure TLS 1.3 when Envoy acts as client towards upstream server.
As far as we observed, it supports only TLS 1.2 currently, and when upstream forces to use the TLS 1.3, the session initiation ends up in TLS protocol version alert.

Similar functionality is already supported in TLS termination when Envoy acts as server: spec.virtualhost.tls.minimumProtocolVersion.

**- 1. -**
Please note that there is an issue with Envoy when it acts as client and TLS 1.3 is configured by default:
https://github.com/envoyproxy/envoy/issues/9300
The edge case is not detailed about what behavior will be observed in Envoy, just mentioning that can happen when Envoy configured to use client certificate as well.
Therefore it can happen that the combination of these features will not work.

**- 2. -**
Also based on the above ticket, both tls_maximum_protocol_version and tls_minimum_protocol_version proposed to be configured:
```
            '@type': type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext
            common_tls_context:
              tls_params:
                tls_maximum_protocol_version: TLSv1_3
                tls_minimum_protocol_version: TLSv1_3
```

Many thanks in advance!

BR.
Gergo
