### ISSUE TITLE
FYI: KinD cluster ingress example not working

### ISSUE THREAD

**Issue by JCzz** [projectcontour/contour#5519]
Following KinD example:
https://kind.sigs.k8s.io/docs/user/ingress/#using-ingress

Using the ingress :
1. `kubectl apply -f https://kind.sigs.k8s.io/examples/ingress/usage.yaml`
2. `curl localhost/foo/hostname`

returns nothing

**Comment by skriss** [comment]
@JCzz thanks for the report, can confirm this. It looks like Contour deploys fine, but the issue is some of the config in the example `Ingress` resource is nginx-specific (`nginx.ingress.kubernetes.io/rewrite-target`, perhaps the combo of a regex path along with `pathType: Prefix`) which Contour doesn't support. Let me take a look at the best way to adjust those docs. In the mean time, if you use the following simplified `Ingress`, you'll at least get routing to `foo-service` to work:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: foo-service
            port:
              number: 8080
        path: /
        pathType: Prefix
```

now `curl localhost/hostname` should return `foo-app`.

For more on path rewriting in Contour's CRD (HTTPProxy), see https://projectcontour.io/docs/1.25/config/request-rewriting/#path-rewriting.
