### ISSUE TITLE
Allow HTTPProxy to specify multiple SubjectNames for Upstream TLS Validation

### ISSUE THREAD

**Issue by KauzClay** [projectcontour/contour#5520]
**Please describe the problem you have**
I am trying to secure the data path for a request when using Contour with Knative. The implementation for securing the data path in Knative is still evolving, but one of difficulties comes from Knative's ways of managing scale-to-zero. For a given Knative service, the endpoints of the corresponding K8s service to either point to the user-container pod, or the Knative Activator pod (when the user-container pod is scaled to zero). There is no indication on the K8s service whether it is in one state or the other.

This means that in order to secure and validate traffic to the backend (a la [Upstream TLS](https://projectcontour.io/docs/v1.18.0/config/upstream-tls/)), we would need Contour to accept either the subjectName for the user-container pod OR the subjectName for the Activator.

We currently get around this by keeping the Activator in the request path always, so that we only need to provide one subjectName. But that is not an ideal end state for the feature.

The current API for this is:
```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: example
spec:
  virtualhost:
    fqdn: www.example.com
  routes:
  - services:
    - name: secure-backend
      port: 8443
      validation:
        caSecret: my-certificate-authority
        subjectName: backend.example.com
```

It would be nice if we could expand it to something like:
```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: example
spec:
  virtualhost:
    fqdn: www.example.com
  routes:
  - services:
    - name: secure-backend
      port: 8443
      validation:
        caSecret: my-certificate-authority
        subjectName: backend.example.com
        subjectNames:
        - backend.example.com
        - activator.knative.internal
```

Envoy itself has this capability, but I realize the HTTPProxy spec is in v1, so it may not be so easy to add.

Either way, I'm curious how others feel about this. I'm happy to work on a contribution if we are able to come to agreement on a way forward.
