### ISSUE TITLE
migrate to new mockery config

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#5564]
https://vektra.github.io/mockery/v2.31/migrating_to_packages/

**Comment by harshil1973** [comment]
Is this isuue begineer freindly? I may want to work on this

**Comment by skriss** [comment]
@harshil1973 yes, I think so -- I'll assign the issue to you. I would check out the link above, and let us know if you have any questions. The goal is really to keep the generated mocks the same, while switching to the new configuration mechanism.

**Comment by harshil1973** [comment]
@skriss How can I set the directory path for the newly generated mock files from .mockery.yaml, previously it was generated in the separated mock directory from where the //go: generate called.

**Comment by sunjayBhatia** [comment]
just a quick try and I got it working for one of the mock packages with this:

```
with-expecter: false
mockname: "{{.InterfaceName}}"
filename: "{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
dir: '{{trimPrefix .PackagePath "github.com/projectcontour/contour/" }}/mocks'
packages:
    github.com/projectcontour/contour/internal/debug:
        interfaces:
            DagBuilder:
```

might not work for all the mocks since we do mock things outside of projectcontour/contour but should be a good starting place

looked at the docs on Layouts and template functions: https://vektra.github.io/mockery/v2.31/configuration/#layouts
