### ISSUE TITLE
[provisioner] Gateway.status.addresses is truncated to the first address only.

### ISSUE THREAD

**Issue by Jean-Daniel** [projectcontour/contour#5650]
**What steps did you take and what happened:**

Unlike `HttpProxy.status` which is populated with all public addresses, the `Gateway.status.addresses` field is only populated with the first address.

HttpProxy.status:
```yaml
    loadBalancer:
      ingress:
      - ip: 192.168.1.2
      - ip: 2a0c:abcd:ef01::1
``` 

Gateway.status:
```yaml
    addresses:
    - type: IPAddress
      value: 192.168.1.2
```

**What did you expect to happen:**

That the `Gateway` object is updated to expose all IPs declared on the envoy service, like `HttpProxy` does.

**Anything else you would like to add:**

Status update is done here:

https://github.com/projectcontour/contour/blob/d60959ec98d46df61de6127464677fa571fd2dae/internal/k8s/statusaddress.go#L187-L195

**Environment:**

- Contour version: 1.26.0-rc.1
