### ISSUE TITLE
RequestHeadersPolicy dynamic headers does not work for host header.

### ISSUE THREAD

**Issue by clayton-gonsalves** [projectcontour/contour#5673]
## Background 

```
requestHeadersPolicy:
      set:
      - name: host
        value: '%REQ(X-FORWARDED-HOST)%'
```
the above setting does not work and results in %REQ(X-FORWARDED-HOST)% being set literally. 

## Potential fix 

for such usecases we should use [host_rewrite_header](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-host-rewrite-header)
