### ISSUE TITLE
Should we sort routes produced by `HTTPPRoxy`

### ISSUE THREAD

**Issue by davinci26** [projectcontour/contour#5773]
## Abstract

Since Envoy is greedy matching path routes, order is important. Contour decides to sort the routes in a way that is not really intuitive and can lead to suprises. In particular with the sorter.go we choose to sort the routing table based on heuristics. This approach can lead to confusion since sorting is low-level implementation primitive of Contour and most users will not know about.

## Personas

There are two main personas in question are:

- Cluster Administrator: A cluster administrator is responsible for providing core functionality to a k8s cluster. For the purposes of this document the cluster administrator installs Contour to the cluster and exposes to the internet. The administrator is responsible for the health of the Contour services.

- ResourceOwner: Someone who manages an HTTPProxy resource inside the Kubernetes cluster configuring the Route/Service combination to allow users of the application to access. A resource owner might not be familiar with Envoy, doesn't have access to the Envoy admin interface and has surface level understanding of how the the HTPProxy Routes are enforced.

## Problem

Imagine the following scenario where you have an HTTPProxy that looks like the following

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: foo
spec:
  ingressClassName: foo
  - authPolicy:
      disabled: true
    conditions:
    - regex: /(?i).foo2.*
    - name: service-foo
      port: 80
  - authPolicy:
      disabled: true
    conditions:
    - regex: /(?i).foo2bar.*
    services:
    - name: service-bar
      port: 80
```

The `HTTPProxy` above will generate a route where the route matching `/(?i).foo2bar.*` will be before the route matching `/(?i).foo2.*`. This is due to the [sorter.go](https://github.com/projectcontour/contour/blob/main/internal/sorter/sorter.go) implementation. The behaviour of the sorter is problematic for the following cases:

* HTTPProxy is written/maintained/debugged by `ResourceOwner` which are not familiar with the internals of Contour and the sorting. If a routing rule doesn't behave as expected the `Cluster Administrator` (or some tooling) would need to verify that the order is correct and there is no other issue.
* Both `Cluster Administrator` and `ResourceOwner` have a hard time reasoning about the order through pure code inspection. This makes debugging issues more complicated.
* It is hard to write tooling/abstractions on top of `HTTPProxy` without leaking this implementation detail to the users.

In more generic terms the sorter is too magical and it can work in unexpected ways.

## What do you want the project to decide?
It is the opinion of the author that we should not be sorting the routes provided in `HTTProxy`. Instead we should create the Envoy routes in the exact same order that we get them from the user for each Virtual Host.

See draft PR to get a sense of the code change: https://github.com/projectcontour/contour/pull/5772
