### ISSUE TITLE
GatewayAPI and WebSocket generates 403 errors

### ISSUE THREAD

**Issue by davinkevin** [projectcontour/contour#5775]
I've migrated an application (`minio`) from `Ingress` to `GatewayAPI`, and I'm in a situation where I don't know what to do to debug this problem… reason why I open this issue. 

**What steps did you take and what happened:**

My contour configuration is:
* contour-gateway-provisioner with two Gateway
  * `internal` for applications using `GatewayAPI`
  * `legacy` for applications using `Ingress

You can find the full gitops configuration [here](https://gitlab.com/davinkevin.fr/home-server/-/blob/9ab34ae62cb9ab4de283bdea65c6264a1cc47a50/projectcontour/overlays/k8s-server/kustomization.yaml)

I had an application (`minio`) deployed with `ingress`, [using the following configuration](https://gitlab.com/davinkevin.fr/home-server/-/blob/a6961f8bb095cbc72c32d01521dc6ee055d178cf/nas/overlays/k8s-server/minio/minio.yaml):

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: v1.bucket.davinkevin.fr
  annotations:
    projectcontour.io/websocket-routes: "/"
    cert-manager.io/cluster-issuer: letsencrypt-production
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - console.v1.bucket.davinkevin.fr
        - v1.bucket.davinkevin.fr
      secretName: v1.bucket.davinkevin.fr
  rules:
    - host: console.v1.bucket.davinkevin.fr
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: minio-proxy
                port:
                  name: http-console
    - host: v1.bucket.davinkevin.fr
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: minio-proxy
                port:
                  name: http
---
apiVersion: v1
kind: Service
metadata:
  name: minio-proxy
  labels:
    app.kubernetes.io/name: nas
    app.kubernetes.io/component: minio-proxy
spec:
  ports:
    - port: 9901
      name: http-console
      targetPort: 9901
    - port: 9900
      name: http
      targetPort: 9900
---
kind: Endpoints
apiVersion: v1
metadata:
  name: minio-proxy
subsets:
  - addresses:
      - ip: 192.168.100.5
    ports:
      - port: 9901
        name: http-console
      - port: 9900
        name: http
```

Everything was ok, and the console was able to use `wss://` without any problems. 

Then, I've migrated this definition to `GatewayAPI`, replacing the previous manifest [by this](https://gitlab.com/davinkevin.fr/home-server/-/blob/e01d758a7fdb8d3ccf8c8ec11cae7a1bdabbf53c/nas/overlays/k8s-server/minio/minio.yaml):

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: v1.bucket.davinkevin.fr
spec:
  parentRefs:
    - name: internal
  hostnames:
    - v1.bucket.davinkevin.fr
  rules:
    - matches:
        - path:
            value: "/"
      backendRefs:
        - name: minio-proxy
          port: 9900
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: console.v1.bucket.davinkevin.fr
spec:
  parentRefs:
    - name: internal
  hostnames:
    - console.v1.bucket.davinkevin.fr
  rules:
    - matches:
        - path:
            value: "/"
      backendRefs:
        - name: minio-proxy
          port: 9901
---
apiVersion: v1
kind: Service
metadata:
  name: minio-proxy
  labels:
    app.kubernetes.io/name: nas
    app.kubernetes.io/component: minio-proxy
spec:
  ports:
    - port: 9901
      name: http-console
      targetPort: 9901
    - port: 9900
      name: http
      targetPort: 9900
---
kind: Endpoints
apiVersion: v1
metadata:
  name: minio-proxy
subsets:
  - addresses:
      - ip: 192.168.100.5
    ports:
      - port: 9901
        name: http-console
      - port: 9900
        name: http
```

The application is available, but as soon as the UI tries to connect over web-socket, using `wss://` protocol, I got this:

<img width="771" alt="image" src="https://github.com/projectcontour/contour/assets/1970922/93ee527f-8ff1-40d2-b8ac-468ccdcaec98">

<img width="1227" alt="image" src="https://github.com/projectcontour/contour/assets/1970922/fbcd62c4-7e3f-4ba0-a489-d336c72cda72">

And if I check envoy logs, I have the following:

```
envoy [2023-09-23T14:44:04.450Z] "GET /ws/objectManager HTTP/1.1" 403 - 0 0 0 - "192.168.100.134" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" "eeea52ff-ad32-4452-a777-a6a66fbb8322" "console.v1.bucket.davinkevin.fr" "-"
envoy [2023-09-23T14:44:08.442Z] "GET /ws/objectManager HTTP/1.1" 403 - 0 0 0 - "192.168.100.134" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" "c3a5e839-aab7-4e30-91fd-54afe13ea05c" "console.v1.bucket.davinkevin.fr" "-"
envoy [2023-09-23T14:44:12.466Z] "GET /ws/objectManager HTTP/1.1" 403 - 0 0 0 - "192.168.100.134" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" "789727a1-d6db-4902-9758-adda415fb37f" "console.v1.bucket.davinkevin.fr" "-"
envoy [2023-09-23T14:44:16.478Z] "GET /ws/objectManager HTTP/1.1" 403 - 0 0 0 - "192.168.100.134" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" "aa9d617c-b325-41f7-85ea-98df5f5d295a" "console.v1.bucket.davinkevin.fr" "-"
envoy [2023-09-23T14:44:20.493Z] "GET /ws/objectManager HTTP/1.1" 403 - 0 0 0 - "192.168.100.134" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" "5c0fa608-ef34-40b4-9f90-5b35326d7bf6" "console.v1.bucket.davinkevin.fr" "-"
```

Which is surprising, with a `403` reported… But this was working perfectly with `ingress` attached to the exact same `gateway`. 

When in `Ingress` mode, I have the following log in the `legacy` gateway:

```
envoy [2023-09-23T14:55:25.187Z] "GET /ws/objectManager HTTP/1.1" 101 DC 405 438 12966 - "192.168.100.134" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" "640250ec-d1f8-49fc-b218-20ccab802df2" "console.v1.bucket.davinkevin.fr" "192.168.100.5:9901"
```

**What did you expect to happen:**

I expect it to be compatible with things supported previously by the `Ingress` object

**Anything else you would like to add:**

I've add a lot of links to the configuration and gitops repository, feel free to ask if you have any question. 

NOTE: It's a gitops repository, and because I need access to the UI, I will revert the modification, but the configuration will stay, just not on `HEAD`, so be sure to follow permalink.

**Environment:**

- Contour version: 1.25.2
- Kubernetes version: (use `kubectl version`): v1.27.4+k3s1
- Kubernetes installer & version: k3s
- Cloud provider or hardware configuration: None, bare metal cluster
- OS (e.g. from `/etc/os-release`): Debian 11
