### ISSUE TITLE
HTTProxy returns error about `config.enableExternalNameService` when used with GatewayAPI configuration

### ISSUE THREAD

**Issue by davinkevin** [projectcontour/contour#5776]
**What steps did you take and what happened:**

My contour configuration is:
* contour-gateway-provisioner with two Gateway
  * `internal` for applications using `GatewayAPI`
  * `legacy` for applications using `Ingress` and `HTTPProxy`

You can find the full gitops configuration [here](https://gitlab.com/davinkevin.fr/home-server/-/blob/main/projectcontour/overlays/k8s-server/kustomization.yaml)

The configuration of the Legacy Gateway look like this: 

```yaml
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: legacy
spec:
  controllerName: projectcontour.io/gateway-controller
  parametersRef:
    kind: ContourDeployment
    group: projectcontour.io
    name: legacy
    namespace: projectcontour
---
kind: ContourDeployment
apiVersion: projectcontour.io/v1alpha1
metadata:
  name: legacy
spec:
  runtimeSettings:
    enableExternalNameService: true
  contour:
    deployment:
      replicas: 1
  envoy:
    networkPublishing:
      serviceAnnotations:
        metallb.universe.tf/address-pool: legacy
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: legacy
spec:
  gatewayClassName: legacy
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: projectcontour.io/https
      port: 443
      allowedRoutes:
        namespaces:
          from: All
```

When I deploy the following `yaml`, I have some errors:

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: unifi.davinkevin.fr
spec:
  virtualhost:
    fqdn: unifi.davinkevin.fr
  routes:
    - conditions:
        - prefix: /
      services:
        - name: unifi-proxy
          port: 443
          protocol: tls
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-proxy
  annotations:
    projectcontour.io/upstream-protocol.tls: 443,https
  labels:
    app.kubernetes.io/name: unifi
    app.kubernetes.io/component: unifi-proxy
spec:
  type: ExternalName
  externalName: unifi.davinkevin.lan
  ports:
    - port: 443
      name: https
      protocol: TCP
      targetPort: 443
```

I have the following state in the object status:

```
Name:         unifi.davinkevin.fr
Namespace:    unifi
Labels:       kustomize.toolkit.fluxcd.io/name=unifi
              kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:  <none>
API Version:  projectcontour.io/v1
Kind:         HTTPProxy
Metadata:
  Creation Timestamp:  2023-09-23T16:11:17Z
  Generation:          1
  Resource Version:    114950990
  UID:                 f26fcfaf-6f34-45e9-8a92-aadcd5148174
Spec:
  Routes:
    Conditions:
      Prefix:  /
    Services:
      Name:      unifi-proxy
      Port:      443
      Protocol:  tls
  Virtualhost:
    Fqdn:  unifi.davinkevin.fr
Status:
  Conditions:
    Errors:
      Message:             Spec.Routes unresolved service reference: unifi/unifi-proxy is an ExternalName service, these are not currently enabled. See the config.enableExternalNameService config file setting
      Reason:              ServiceUnresolvedReference
      Status:              True
      Type:                ServiceError
    Last Transition Time:  2023-09-23T16:11:17Z
    Message:               At least one error present, see Errors for details
    Observed Generation:   1
    Reason:                ErrorPresent
    Status:                False
    Type:                  Valid
  Current Status:          invalid
  Description:             At least one error present, see Errors for details
  Load Balancer:
    Ingress:
      Ip:  192.168.100.10
Events:    <none>
```

The IP used is the one associated with the `legacy` gateway.

**What did you expect to happen:**

I don't expect the error to be reported because the configuration is correctly set. 

I've add a lot of links to the configuration and gitops repository, feel free to ask if you have any question.

NOTE: It's a [gitops](https://gitlab.com/davinkevin.fr/home-server) repository, so you have the full configuration there.

**Environment:**

- Contour version: 1.26.0
- Kubernetes version: (use `kubectl version`): v1.27.4+k3s1
- Kubernetes installer & version: k3s
- Cloud provider or hardware configuration: None, bare metal cluster
- OS (e.g. from `/etc/os-release`): Debian 11

**Comment by skriss** [comment]
My initial hunch is that the two different Gateways are both processing the HTTPProxy. This could be avoided by specifying an ingress class for one or the other, and specifying it on the HTTPProxy as well. Haven't had a chance to actually experiment/repro yet though.

**Comment by davinkevin** [comment]
I'll try that when possible, but I doubt both tried to process it because the IP was always the default one, eg 192.168.100.10. 

And I even tried with `enableExternalNameService: true` set for GatewayAPI config, same result.

**Comment by davinkevin** [comment]
FYI, I've tried this using `HTTPRoute` attached to a gateway with the `enableExternalNameService: true`, I have the following result:

```
Status:
  Parents:
    Conditions:
      Last Transition Time:  2023-09-30T13:23:53Z
      Message:               service "mafreebox" is invalid: freebox/mafreebox is an ExternalName service, these are not currently
enabled. See the config.enableExternalNameService config file setting, service "mafreebox" is invalid: freebox/mafreebox is an Exte
rnalName service, these are not currently enabled. See the config.enableExternalNameService config file setting
      Observed Generation:   1
      Reason:                BackendNotFound
      Status:                False
      Type:                  ResolvedRefs
      Last Transition Time:  2023-09-30T13:23:53Z
      Message:               Accepted HTTPRoute
      Observed Generation:   1
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
    Controller Name:         projectcontour.io/gateway-controller
    Parent Ref:
      Group:  gateway.networking.k8s.io
      Kind:   Gateway
      Name:   internal
```

With the following `ContourDeployment`:

```
apiVersion: projectcontour.io/v1alpha1
kind: ContourDeployment
metadata:
  creationTimestamp: "2023-08-26T09:56:57Z"
  generation: 2
  labels:
    kustomize.toolkit.fluxcd.io/name: projectcontour
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: internal
  namespace: projectcontour
  resourceVersion: "114951623"
  uid: dd4f4bce-ad1c-49b1-9369-ade72ee8a4f9
spec:
  contour:
    deployment:
      replicas: 1
  envoy:
    networkPublishing:
      serviceAnnotations:
        metallb.universe.tf/address-pool: internal
  runtimeSettings:
    enableExternalNameService: true
    ingress:
      classNames:
      - internal
```

Using an `HTTPProxy`, I have the following status: 

```
Status:
  Conditions:
    Errors:
      Message:             Spec.Routes unresolved service reference: freebox/mafreebox is an ExternalName service, these are not cu
rrently enabled. See the config.enableExternalNameService config file setting
      Reason:              ServiceUnresolvedReference
      Status:              True
      Type:                ServiceError
    Last Transition Time:  2023-09-30T13:28:56Z
    Message:               At least one error present, see Errors for details
    Observed Generation:   1
    Reason:                ErrorPresent
    Status:                False
    Type:                  Valid
  Current Status:          invalid
  Description:             At least one error present, see Errors for details
  Load Balancer:
    Ingress:
      Ip:  192.168.120.1
```

And this time, with an `ingressClassName`: 

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: mafreebox.davinkevin.fr
spec:
  ingressClassName: internal
  virtualhost:
    fqdn: mafreebox.davinkevin.fr
  routes:
    - conditions:
        - prefix: /
      services:
        - name: mafreebox
          port: 443
          protocol: tls
```

**Comment by skriss** [comment]
The other possibility is that the actual `ContourConfiguration` CRD does not have `enableExternalNameService: true`. This could happen if, when the Gateway was created, the GatewayClass's parameters did not include this setting, and it was only updated after the Gateway was created to specify this setting (ref https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.GatewayClass).

You can look at `kubectl -n projectcontour get contourconfigurations -o yaml` to see if this might be the case. If so, you can always edit them manually, and then restart the corresponding contour control planes.

Otherwise, I haven't fully reproduced your scenario, but I can confirm that at least for the simpler case of one Gateway, when the GatewayClass's parameters contain `enableExternalNameService: true`, that both HTTPProxy and HTTPRoute work correctly with externalname services.

**Comment by davinkevin** [comment]
I think you got it! 

```yaml
apiVersion: v1
items:
- apiVersion: projectcontour.io/v1alpha1
  kind: ContourConfiguration
  metadata:
    creationTimestamp: "2023-08-18T20:07:41Z"
    generation: 1
    labels:
      projectcontour.io/owning-gateway-name: legacy
    name: contourconfig-legacy
    namespace: projectcontour
    resourceVersion: "105031962"
    uid: fb95892c-bb11-46e0-8560-336cc90eafe0
  spec:
    envoy:
      service:
        name: envoy-legacy
        namespace: projectcontour
    gateway:
      gatewayRef:
        name: legacy
        namespace: projectcontour
- apiVersion: projectcontour.io/v1alpha1
  kind: ContourConfiguration
  metadata:
    creationTimestamp: "2023-08-26T09:56:57Z"
    generation: 1
    labels:
      projectcontour.io/owning-gateway-name: internal
    name: contourconfig-internal
    namespace: projectcontour
    resourceVersion: "106881549"
    uid: dc91a661-edb5-4ec7-85d2-dc3b039e7d79
  spec:
    envoy:
      service:
        name: envoy-internal
        namespace: projectcontour
    gateway:
      gatewayRef:
        name: internal
        namespace: projectcontour
    ingress:
      classNames:
      - internal
kind: List
metadata:
  resourceVersion: ""
```

Doing the edition is one thing, but I would like to have a reproducible solution (`gitops` way…). Is there a way to trigger the full recreation of the object? If I delete and recreate something?

**Comment by skriss** [comment]
If you delete the ContourConfiguration CR it should be recreated the next time the Gateway is reconciled (on change, on provisioner restart, etc), but per the Gateway API spec it's not intended to be continuously reconciled for changes.

**Comment by davinkevin** [comment]
So I proceeded like you mentioned:

* deletion of the ContourConfiguration
* `rollout restart` of the deployment `contour-gateway-provisioner`

I confirm the `contourconfig-internal` has been recreated with the required field defined:

```yaml
apiVersion: projectcontour.io/v1alpha1
kind: ContourConfiguration
metadata:
  creationTimestamp: "2023-11-11T09:43:11Z"
  generation: 1
  labels:
    projectcontour.io/owning-gateway-name: internal
  name: contourconfig-internal
  namespace: projectcontour
  resourceVersion: "129173293"
  uid: c5d90e9c-8011-4a89-8318-2d48632d35c5
spec:
  enableExternalNameService: true
  envoy:
    service:
      name: envoy-internal
      namespace: projectcontour
  gateway:
    gatewayRef:
      name: internal
      namespace: projectcontour
  ingress:
    classNames:
    - internal
```

Then I've created the following `HTTPRoute`:

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: unifi.davinkevin.fr
spec:
  parentRefs:
    - name: internal
  hostnames:
    - unifi.davinkevin.fr
  rules:
    - matches:
        - path:
            value: "/"
      backendRefs:
        - name: unifi-proxy
          port: 443
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-proxy
  annotations:
    projectcontour.io/upstream-protocol.tls: 443,https
  labels:
    app.kubernetes.io/name: unifi
    app.kubernetes.io/component: unifi-proxy
spec:
  type: ExternalName
  externalName: unifi.davinkevin.lan
  ports:
    - port: 443
      name: https
      protocol: TCP
      targetPort: 443
```

But the result is the same as described at the beginning, with the same error in the status of this `HTTPRoute`: 

```
Name:         unifi.davinkevin.fr
Namespace:    unifi
Labels:       kustomize.toolkit.fluxcd.io/name=unifi
              kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:  <none>
API Version:  gateway.networking.k8s.io/v1beta1
Kind:         HTTPRoute
Metadata:
  Creation Timestamp:  2023-11-11T09:53:18Z
  Generation:          1
  Resource Version:    129175403
  UID:                 229391e5-9d52-4a3e-b71b-740185d41ad7
Spec:
  Hostnames:
    unifi.davinkevin.fr
  Parent Refs:
    Group:  gateway.networking.k8s.io
    Kind:   Gateway
    Name:   internal
  Rules:
    Backend Refs:
      Group:   
      Kind:    Service
      Name:    unifi-proxy
      Port:    443
      Weight:  1
    Matches:
      Path:
        Type:   PathPrefix
        Value:  /
Status:
  Parents:
    Conditions:
      Last Transition Time:  2023-11-11T09:53:18Z
      Message:               service "unifi-proxy" is invalid: unifi/unifi-proxy is an ExternalName service, these are not currently enabled. See the config.enableExternalNameService config file setting
      Observed Generation:   1
      Reason:                BackendNotFound
      Status:                False
      Type:                  ResolvedRefs
      Last Transition Time:  2023-11-11T09:53:18Z
      Message:               Accepted HTTPRoute
      Observed Generation:   1
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
    Controller Name:         projectcontour.io/gateway-controller
    Parent Ref:
      Group:  gateway.networking.k8s.io
      Kind:   Gateway
      Name:   internal
Events:       <none>
```

I'll give it a try with the `HTTPProxy`, but my main goal is to use the GatewayAPI for this.
