### ISSUE TITLE
Problem with Contour Envoy in hostnetworking mode

### ISSUE THREAD

**Issue by themkarimi** [projectcontour/contour#5782]
I have installed Contour in my in-prem Kubernetes cluster with having host-networking enabled for envoy daemonset but contour-envoy pods are always not ready and specified ports are not exposed on the Kubernetes nodes.

here is my helm chart values:

```
contour:
  enabled: true  
  replicaCount: 2  
  ingressClass:
    name: "contour"
    create: true
    default: false  
  logFormat: json    
envoy:
  enabled: true
  hostNetwork: true  

 
  hostPorts:
    http: 8888
    https: 4443
    metrics: 8002
  containerPorts:
    http: 8888
    https: 4443
    metrics: 8002 
  useHostIP: true         


metrics:
  serviceMonitor:
    enabled: true  
  prometheusRule:
    enabled: true   
```   

update:
so I have envoy pods ready and running but still no 8888 or 4443 are in the listening phase on my nodes.

Environment:

- Contour version: 1.26.0
- Kubernetes version: (use `kubectl version`):
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.5
- Cloud provider or hardware configuration: On-Prem
- OS (e.g. from `/etc/os-release`): Ubutnu Server 20.04
