### ISSUE TITLE
Httpproxy error reporting when global authentication is configured

### ISSUE THREAD

**Issue by yangyy93** [projectcontour/contour#5820]
**What steps did you take and what happened:**
After I enabled global authentication, I configured context in rootHTTPProxy. If `.spec.virtualhost.tls` is empty, httproxy is normal. but if I enable tls, I will get an error of `Spec.Virtualhost.Authorization.ServiceRef extension service "skoala-yang/ " not found`. I think global authentication should specify a default extensionService regardless of whether tls is empty or not.

This is part of the configuration of my contour：
```
......
spec:
    globalExtAuth:
    authPolicy:
      context:
        gateway-name: test-gateway 
    extensionRef:
      apiVersion: projectcontour.io/v1alpha1
      name: plugin-yangyang-local-5lekbogf5f-auth
      namespace: skoala-yang
    responseTimeout: 5s
    withRequestBody:
      allowPartialMessage: true
      maxRequestBytes: 1024
      packAsBytes: true
......
```

This is my tls-httpproxy content,is's invalid:
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata: 
    name: test-auth
    namespace: skoala-yang
spec:
  ingressClassName: gateway-yang-up
  routes:
    - conditions:
        - prefix: /test-auth
      pathRewritePolicy:
        replacePrefix:
          - replacement: /
      services:
        - name: daoshop
          port: 8080
          weight: 100
  virtualhost:
    authorization:
      authPolicy:
        context:
          api-name: foo
    fqdn: example.com
    tls:
      minimumProtocolVersion: '1.2'
      secretName: skoala-yang/mysecret
```
This is my notls-httpproxy content,is's valid:
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata: 
    name: test-auth
    namespace: skoala-yang 
spec:
  ingressClassName: gateway-yang-up
  routes:
    - conditions:
        - prefix: /test-auth
      pathRewritePolicy:
        replacePrefix:
          - replacement: /
      services:
        - name: daoshop
          port: 8080
          weight: 100
  virtualhost:
    authorization:
      authPolicy:
        context:
          api-name: foo
    fqdn: example.com
```
**Environment:**

- Contour version: 1.26.0
- Kubernetes version: v1.26.5

In addition, there is another question. After I configured auth-context in httpproxy, the context(gateway-name: test-gateway) I configured in contour's global authentication was overwritten. Is this an expected process?
