### ISSUE TITLE
Unable to set multiple set-cookie headers

### ISSUE THREAD

**Issue by dnbn** [projectcontour/contour#5855]
**What steps did you take and what happened:**
RFC [actually allows the server to send multiples "set-cookie" header if they don't have the same name](https://datatracker.ietf.org/doc/html/rfc6265#section-4.1). Unfortunately contour overwrite the header and only keep the last one.
From [this code](https://github.com/projectcontour/contour/blob/main/internal/envoy/v3/route.go#L137), it seems there are cases where envoy can already make an append instead of a set. See [here](https://github.com/projectcontour/contour/blob/main/internal/envoy/v3/route.go#L592).

```
responseHeadersPolicy:
  set:
    - name: set-Cookie
      value: Cookie1=cookie1
    - name: set-Cookie
      value: Cookie2=cookie2
```

**What did you expect to happen:**
When multiple set-cookie headers are set in the same httpproxy, all should be kept and appended to the header list.

**Anything else you would like to add:**
Another approach could be to add the ability of "append header" instead of "set" header. This has already been suggested [here ](https://github.com/projectcontour/contour/issues/4564)

**Environment:**

- Contour version: 1.26.0

Thanks in advance
