### ISSUE TITLE
How to setup TCPRoute in static configuration

### ISSUE THREAD

**Issue by walleliu1016** [projectcontour/contour#5865]
**What question do you have?:**
I want to use Contour as a route to zookeeper in the kubernetes, but got some problem in setup the TCPRoute,  the Gateway and TCPRoute
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gw01
  namespace: gws
spec:
  gatewayClassName: contour-gw01
  listeners:
  - name: zk-32181
    protocol: TCP
    port: 32181
    allowedRoutes:
      namespaces:
        from: All
--
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: gw01
  namespace: gwns
spec:
  parentRefs:
  - name: zk-32181
    namespace: gwns
    sectionName: zk-32181
  rules:
  - backendRefs:
    - name: zk-client
      port: 2181
--
apiVersion: v1
kind: Service
metadata:
  name: envoy-gw01
  namespace: gwns
  annotations:
    # This annotation puts the AWS ELB into "TCP" mode so that it does not
    # do HTTP negotiation for HTTPS connections at the ELB edge.
    # The downside of this is the remote IP address of all connections will
    # appear to be the internal address of the ELB. See docs/proxy-proto.md
    # for information about enabling the PROXY protocol on the ELB to recover
    # the original remote IP address.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 32181
    name: zk
    protocol: TCP
    targetPort: 32181
  selector:
    app: envoy-gw01
  type: LoadBalancer
```
after deploy the gateway and tcproute into kubernetes, 
i try to find the port 32181 enabled in envoy pods, but not found, 
and cannot find any configuration about 32181 in the /config/envoy.json 
no useful log in envoy or contour logs
```
kubectl logs contour-pods
time="2023-10-18T10:03:31Z" level=info msg="reconciling gateway" context=gateway-controller name=gw01 namespace=gwns
time="2023-10-18T10:03:31Z" level=info msg="assigning gateway to DAG" context=gateway-controller name=gw01 namespace=gwns
time="2023-10-18T10:03:31Z" level=info msg="performing delayed update" context=contourEventHandler last_update=113.478259ms outstanding=1
time="2023-10-18T10:03:31Z" level=debug msg="cluster load assignments did not change" context=endpointstranslator
time="2023-10-18T10:03:31Z" level=debug msg="received a status update" context=StatusUpdateHandler name=gw01 namespace=gwns
time="2023-10-18T10:03:31Z" level=debug msg="update was a no-op" context=StatusUpdateHandler kind=Gateway name=gw01 namespace=gwns
time="2023-10-18T10:03:31Z" level=debug msg="handling v3 xDS resource request" connection=4 context=xds node_id=ContourCLI resource_names="[]" response_nonce=4 type_url=type.googleapis.com/envoy.config.listener.v3.Listener version_info=4
time="2023-10-18T10:03:31Z" level=debug msg="handling v3 xDS resource request" connection=2 context=xds node_id=envoy-gw01-d5c749b68-cxwz5 node_version=v1.27.0 resource_names="[]" response_nonce=4 type_url=type.googleapis.com/envoy.config.cluster.v3.Cluster version_info=4
time="2023-10-18T10:03:31Z" level=debug msg="handling v3 xDS resource request" connection=1 context=xds node_id=envoy-gw01-d5c749b68-cxwz5 node_version=v1.27.0 resource_names="[]" response_nonce=4 type_url=type.googleapis.com/envoy.config.listener.v3.Listener version_info=4
```
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version:1.26
- Kubernetes version: (use `kubectl version`):1.24.16
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):
