### ISSUE TITLE
Missing X-Forwarded-* in request

### ISSUE THREAD

**Issue by bartwitkowski** [projectcontour/contour#5948]
**My network:**

I'm using Azure Application Gateway as a edge proxy which terminates HTTPS traffic.
Then, there is Contour ingress controller in Azure Kubernetes Service.
Then, there is application pod with HTTP endpoint.
Traffic between AGW and AKS/Contour ingress is HTTPS encrypted.
AGW by default adds X-Forwarded-For and X-Forwarded-Proto headers.

Those 2 headers are missing when request is reaching application.
Why?
What I'm missing?

Please help, because I'm loosing faith in Contour :-(.

**What I did/check:**
- on AGW I've set custom HTTP header and it is visible when reaching application
- on AGW I've set explicit X-Forwarded-For (and -Proto) but it is not visible when reaching application
- in Contour I've set custom HTTP header and it is visible when reaching application
- on Contour I've set explicit X-Forwarded-For (and -Proto) but it is not visible when reaching application
- I've set num-trusted-hops = 1, it didn't helped
- I've checked on Envoy that this is set: "use_remote_address": true, "xff_num_trusted_hops": 1,
- on Envoy pod there is a XFF log: "GET /headers HTTP/1.1" 200 - 0 541 2 1 "a.b.c.d:59720,10.1.0.148"

**Environment:**

- Contour version: contour:1.24.3-debian-11-r0
- Kubernetes version: AKS v1.27.3
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): Node OS is ubuntu

**Comment by skriss** [comment]
Hey @bartwitkowski, I'm unable to reproduce this issue - the X-Forwarded-* headers are reaching the backend fine in my Azure setup.

Could you try deploying this simple echoserver and sending some traffic to it, and showing me the responses?

```yaml
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: default
spec:
  selector:
    app: echoserver
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: stevesloka/echo-server
        imagePullPolicy: Always
        name: echoserver
        command:
          - "echo-server"
        args:
          - --echotext=hello from echoserver 1!
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: echoserver
spec:
  virtualhost:
    fqdn: <insert hostname here>
  routes:
    - conditions:
      - prefix: /
      services:
      - name: echoserver
        port: 80     
```
