### ISSUE TITLE
Support `X-Forwarded-Port` header

### ISSUE THREAD

**Issue by PSanetra** [projectcontour/contour#5996]
I tried to overwrite the `X-Forwarded-Port` header in a policy, but it seems like envoy ignores this policy. Therefore it would be nice to allow enabling the envoy `append_x_forwarded_port` option explicitly. Also see the envoy documentation: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-port

My contour configuration:
```yaml
policy:
  request-headers:
    set:
      X-Forwarded-Port: "443"
```

**Environment:**

- Contour version: 1.27.0
