### ISSUE TITLE
IpAllowPolicy is not applied when using passthrough mode and tcpproxy

### ISSUE THREAD

**Issue by therealak12** [projectcontour/contour#6076]
**What steps did you take and what happened:**

Create an `httpproxy ` with `passthrough: true` and `tcpproxy` set. Then try to access the host (`example.com` here) from an IP not included in the `ipAllowPolicy`. It's still accessible.

An example of such httpproxy:

```yml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: example.com
  namespace: playground
spec:
  tcpproxy:
    services:
    - name: sample-server
      port: 8000
      weight: 100
  virtualhost:
    fqdn: example.com
    ipAllowPolicy:
    - cidr: 10.20.16.0/22
      source: Peer
    tls:
      passthrough: true
```

**What did you expect to happen:**
The host should only be accessible from the source IPs specified in the `ipAllowPolicy` list.

**Anything else you would like to add:**
This might be the cause:

- Contour correctly processes and [sets](https://github.com/projectcontour/contour/blob/main/internal/dag/httpproxy_processor.go#L574) the `ipAllowFilterPolicy` configured on the virtual host.
- However, it doesn't call the `VirtualHostsAndRoutes` function (which calls the [`ipFilterConfig`](https://github.com/projectcontour/contour/blob/main/internal/envoy/v3/route.go#L209)).
- It's because the VirtualHosts without routes are [ignored in the loop](https://github.com/projectcontour/contour/blob/main/internal/xdscache/v3/route.go#L127-L129).

I was wondering **what's the reasoning behind this `continue` statement**. Omitting this `continue` statement might resolve the issue.

**Environment:**

- Contour version: v1.25
- Kubernetes version: (use `kubectl version`): 1.23.3
- Kubernetes installer & version: Openshift installer
- Cloud provider or hardware configuration: hp g9 & g10 
- OS (e.g. from `/etc/os-release`): [fcos](https://fedoraproject.org/coreos/)
