### ISSUE TITLE
Support setting response headers for DirectResponsePolicy Routes

### ISSUE THREAD

**Issue by flawedmatrix** [projectcontour/contour#6213]
I noticed that when I was trying to use a `directResponsePolicy` in a route, the `responseHeadersPolicy` would not actually take effect:

```yaml
 routes:
  - conditions:
    - exact: /foo
    directResponsePolicy:
      statusCode: 200
    responseHeadersPolicy:
      set:
      - name: "Header-To-Add"
        value: "val"
```

```
$ curl -v https://example.site.com/foo
> GET /foo HTTP/2
> Host: example.site.com
> user-agent: curl/7.81.0
> accept: */*
...
< HTTP/2 200
< vary: Accept-Encoding
< date: Tue, 20 Feb 2024 23:43:58 GMT
< server: envoy
```

According to the Envoy docs, Direct Responses will include any headers specified in `response_headers_to_add`.

Perhaps this is a feature not yet added to Contour as `response_headers_to_add` is not populated in the case of a `DirectResponse`:

https://github.com/projectcontour/contour/blob/94e591fc8fab76c74a83d367b03e256062834ca5/internal/envoy/v3/route.go#L124-L125
