### ISSUE TITLE
ExternalName service health check port does not take effect

### ISSUE THREAD

**Issue by yangyy93** [projectcontour/contour#6229]
In the service where httpproxy sets routing, if the service type is externalName, the `healthPort` is not delivered to envoy.
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: test1
spec:
  routes:
    - conditions:
        - header:
            name: ':method'
            regex: GET
          prefix: /extservice
      healthCheckPolicy:
        path: /
      services:
        - name: demo-externalname-service
          port: 8080
          healthPort: 8998
```
```
apiVersion: v1
kind: Service
metadata:
  name: aksk-demo-externalname
spec:
  ports:
    - name: '8080'
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: '8998'
      protocol: TCP
      port: 8998
      targetPort: 8998
  type: ExternalName
  externalName: foo.test.svc.cluster.local

```

The health check port should be 8998, but it does not take effect.
