### ISSUE TITLE
/.well-known/caldav and /.well-known/carddav

### ISSUE THREAD

**Issue by musklor** [projectcontour/contour#6232]
Hi, I have to setup a rewrite rule for nextcloud.
I use a httpproxy, I don't know how to achieve that with contour.
Example :
RewriteRule ^\.well-known/carddav /remote.php/dav/ [R=301,L]
  RewriteRule ^\.well-known/caldav /remote.php/dav/ [R=301,L]

**Comment by tsaarni** [comment]
Those look like rules for Apache HTTP Server [`mod_rewrite`](https://httpd.apache.org/docs/2.4/mod/mod_rewrite.html#rewriterule) that respond with `301 Moved Permanently` to the two URL prefixes.  You could try adding something like following to `HTTPProxy`:

```yaml
spec:
  routes:
  - conditions:
    - prefix: /.well-known/carddav
    requestRedirectPolicy:
      path: /remote.php/dav
      statusCode: 301
  - conditions:
    - prefix: /.well-known/caldav
    requestRedirectPolicy:
      path: /remote.php/dav
      statusCode: 301
```
