### ISSUE TITLE
Custom domain names do not work in gateway api

### ISSUE THREAD

**Issue by Bryce-huang** [projectcontour/contour#6248]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: url-test
spec:
  hostnames:
  - api.test.stgxxx
  - api.test.stgxxx.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway1
    namespace: default
  rules:
  - backendRefs:
    - filters:
      - requestHeaderModifier:
          add:
          - name: Host
            value: service1
        type: RequestHeaderModifier
      group: ""
      kind: Service
      name: serving1
      namespace: default
      port: 80
      weight: 100
    matches:
    - path:
        type: PathPrefix
        value: /test
```

Reuqest the domain `api.test.stgxxx` return 404,but request api.test.stgxxx.com ,it work well.

I also see the log of envoy print the host is `api.test.stgxxx`

**What did you expect to happen:**

The domain is  `api.test.stgxxx` should work well.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: 1.26
- Kubernetes version: (use `kubectl version`): 1.24
- Kubernetes installer & version: 
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):
