### ISSUE TITLE
Status.LoadBalancer is empty when using service port other than 80

### ISSUE THREAD

**Issue by luong-komorebi** [projectcontour/contour#6559]
**What steps did you take and what happened:**

Given a httpproxy 

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: example-service
  namespace: example-service
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: example-service
      port: 3000
  virtualhost:
    fqdn: example-service.mydomain.com
    tls:
      secretName: example-service-tls
```
and an example service that runs on port 3000

the status that I receive is 

```yaml
status:
  conditions:
  - lastTransitionTime: "2024-07-16T18:27:53Z"
    message: Valid HTTPProxy
    observedGeneration: 1
    reason: Valid
    status: "True"
    type: Valid
  currentStatus: valid
  description: Valid HTTPProxy
  loadBalancer: {}
```

Compared it to other services that listens on port 80 and was routed to by another virtualhost, I can see the status is:
```yaml
status:
  conditions:
  - lastTransitionTime: "2024-07-16T18:27:53Z"
    message: Valid HTTPProxy
    observedGeneration: 9
    reason: Valid
    status: "True"
    type: Valid
  currentStatus: valid
  description: Valid HTTPProxy
  loadBalancer:
    ingress:
    - hostname: k8s-ingressc-contoure-[stripped].amazonaws.com
 ```

**What did you expect to happen:**

I expect the status to be populated with ingress hostname as usual. Without which other automation are also affected, such as external-dns that operates on contour-httpproxy as sources

This discussion is probably related https://github.com/projectcontour/contour/issues/661 but at the end of the day I was unable to figure out how to support other ports than 80 and 443 for virtualhost. I have tried to search the documentation but found no clear information or disclaimer about this. If there is one, please link me there and excuse me for filing this issue 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: 1.29.1
- Kubernetes version: (use `kubectl version`):  v1.30.0-eks-036c24b
- Kubernetes installer & version: Amazon EKS
- Cloud provider or hardware configuration: Amazon
- OS (e.g. from `/etc/os-release`): AWS Bottlerocket
