### ISSUE TITLE
Gateway-API: InvalidCertificateRef error if certificateRefs.group is set to "core"

### ISSUE THREAD

**Issue by kghost** [projectcontour/contour#6567]
**What steps did you take and what happened:**

Set up a gateway with a following listener:

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: contour 
  namespace: projectcontour
spec:
  listeners:
    - name: https-xxx
      hostname: xxx.example.com  
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - group: core
            kind: Secret
            name: xxx-tls
      allowedRoutes:
        namespaces:
          from: All
```

> note: this is suggested by cert-manager here https://cert-manager.io/docs/usage/gateway/

**What did you expect to happen:**

I expect the listener is successfuly setup, but got this error:

```
    - lastTransitionTime: "2024-07-18T11:47:37Z"
      message: Spec.VirtualHost.TLS.CertificateRefs "xxx-tls" must contain a reference to a core.Secret
      observedGeneration: 26
      reason: InvalidCertificateRef
      status: "False"
      type: ResolvedRefs
```

**Anything else you would like to add:**

When I removed `group: core`, everything works fine.

**Environment:**

- Contour version: 1.29.1
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):
