### ISSUE TITLE
Can not disable Global External Authorization by default using authPolicy.disabled

### ISSUE THREAD

**Issue by SamMHD** [projectcontour/contour#6617]
**What steps did you take and what happened:**
We have been trying to setup `GlobalExtAuth` in our Contour deployment and we wanted to disabled it on all routes by default and ask our clients to enable it if they need to use it on their HTTPProxies.

But, when we configured `globalExtAuth` and set `globalExtAuth.authPolicy.disabled` to `true` the External Authorization is still applied to all HTTPProxies even though they didn't asked for it.

**What did you expect to happen:**
We expected (according to contour [GlobalAuthorizationPolicy API Specification](https://github.com/projectcontour/contour/blob/f9b6f6fdfdd83d3639f6e8c55836401d749c19e1/pkg/config/parameters.go#L814)) that when we set `globalExtAuth.authPolicy.disabled` to `true` the external authorization is not applied to any routes unless it is specifically configured to be used by either `virtualhost.authorization.authPolicy.disabled` or `route.authPolicy.disabled`.

**Environment:**

- Contour version: 1.29
- Kubernetes version: (use `kubectl version`): 1.27

**How to replicate this:**
Use the following configs:

in `ContourConfiguration`: 
```yaml
apiVersion: projectcontour.io/v1alpha1
kind: ContourConfiguration
metadata:
  ...
  name: contour-config
  namespace: contour
spec:
  ...
  globalExtAuth:
    authPolicy:
      disabled: true
    extensionRef:
      name: cerberus-auth
      namespace: cerberus-operator-system
    failOpen: false
    responseTimeout: 1s
  ...
```

in sample `HTTPProxy`:
```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: test-proxy
spec:
  routes:
  - conditions:
    - exact: /
    permitInsecure: true
    services:
    - name: echo
      port: 80
      weight: 100
  virtualhost:
    fqdn: test-route.example.com
    tls:
      minimumProtocolVersion: "1.2"
      secretName: <certificate-secret>
```
then if you call `test-route.example.com` envoy will try to authorize using the authorization service specified in `ContourConfiguration`
