### ISSUE TITLE
How to customize envoy access log

### ISSUE THREAD

**Issue by shenshanyoumu** [projectcontour/contour#6676]
**What question do you have?:**
I follow docs: [https://projectcontour.io/getting-started/] with Option 3: Contour Gateway Provisioner to install contour in projectcontour namespace it works well;

but when I follow below docs to customized envoy access logs, where is config file I can found?
https://projectcontour.io/docs/main/config/access-logging/#customizing-access-log-format

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: 1.30
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by tsaarni** [comment]
When using a gateway provisioner, Contour can be configured through `ContourDeployment`

```yaml
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: mygatewayclass
spec:
  controllerName: projectcontour.io/gateway-controller
  parametersRef:
    kind: ContourDeployment
    group: projectcontour.io
    name: contour-with-envoy-deployment-params
    namespace: projectcontour
---
kind: ContourDeployment
apiVersion: projectcontour.io/v1alpha1
metadata:
  namespace: projectcontour
  name: contour-with-envoy-deployment-params
spec:
  runtimeSettings:
    envoy:
      logging:
        accessLogFormat: json
```

For more information, refer to:

* https://projectcontour.io/docs/1.30/config/gateway-api/#customizing-a-gatewayclass
* https://projectcontour.io/docs/main/config/api/#projectcontour.io/v1alpha1.ContourDeployment
