### ISSUE TITLE
 status.loadBalancer field in Ingress-resource stays empty if more than one envoy service exists 

### ISSUE THREAD

**Issue by 3deep5me** [projectcontour/contour#6679]
**What steps did you take and what happened:**
We lately did a update to the newest contour Version (v1.30) (We are using the bitnami helm-chart)
After some time we recognized in argocd that ingress objects never get ready. 
The reason is probably that the `status.loadBalancer` stays empty.

We are using this feature https://github.com/bitnami/charts/pull/21994.
It allows us to create multiple envoy-services, e.g. in every AZ. 
This is needed when your cloud-provider do not a provide a multi AZ LB solution. E.g. Hetzner & Scaleway

If we delete 2 of the 3 services, the field gets filled. 

**What did you expect to happen:**
Like in versions before the field should look like this:
```
  status:
    loadBalancer:
      ingress:
      - hostname: 54-158-xxx-xxx.lb.fancy.cloud
 ```
Or even better like this:
```
  status:
    loadBalancer:
      ingress:
      - hostname: 54-158-xxx-xx1.lb.fancy.cloud
      - hostname: 54-158-xxx-xx2.lb.fancy.cloud
      - hostname: 54-158-xxx-xx3.lb.fancy.cloud
 ```

**Anything else you would like to add:**
The Ingress-Object works even the status-filed is not set. 

**Environment:**

- Contour version: 1.30.0
- Kubernetes version: (use `kubectl version`): 1.30.2
- Kubernetes installer & version: Scaleway-Kubernetes
- Cloud provider or hardware configuration: Scaleway
- OS (e.g. from `/etc/os-release`): Debian
