### ISSUE TITLE
Support regex with "?!" in HTTPProxy

### ISSUE THREAD

**Issue by jadefr** [projectcontour/contour#6746]
I get the following error when creating HTTPProxy with "?!":
```
  - errors:
    - message: 'route: supplied regex: /lorem/(?!.*\/ipsum)(.*) invalid. error: error
        parsing regexp: invalid or unsupported Perl syntax: `(?!`'
      reason: PathMatchConditionsNotValid
      status: "True"
      type: RouteError
```

**Steps to reproduce:**

Deploy yaml:
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: basic
spec:
  virtualhost:
    fqdn: foo-basic.bar.com
  routes:
    - conditions:
      - regex: /lorem/(?!.*\/ipsum)(.*)
      services:
        - name: s1
          port: 80
```

I believe using package regexp2 would solve the issue.
As an example, the following PR was done in NGINX Virtual Server: https://github.com/nginxinc/kubernetes-ingress/pull/4465
