### ISSUE TITLE
Using special characters in Contour HTTPProxy

### ISSUE THREAD

**Issue by Neekoy** [projectcontour/contour#6762]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

We have an HTTPProxy configured that works properly, however when we add a condition that contains special characters, the proxy doesn't work.

Example:

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/target: url.cloudfront.net
  creationTimestamp: '2024-05-07T15:46:41Z'
  labels:
    argocd.argoproj.io/instance: web-server
  name: web-server
  namespace: product
  spec:
    routes:
      - conditions:
          - prefix: /gr/Βιολογία-vres-kathigiti
        services:
          - name: upstream-service
            port: 3000
```

**What did you expect to happen:**
When I visit mydomain.com/gr/Βιολογία-vres-kathigiti I should be proxied to the upstream-service.

**Environment:**

- Contour version: 1.23.2
- Kubernetes version: (use `kubectl version`): 1.29
- Kubernetes installer & version: 
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Ubnutu

Any help is appreciated, thanks in advance!
