### ISSUE TITLE
Cannot change globalExtAuth timeout

### ISSUE THREAD

**Issue by kncesarini** [projectcontour/contour#6820]
**What steps did you take and what happened:**

We are experiencing a 200ms timeout on all authorization requests (if they happen to take more than 200ms, which happens on rare occasions), leading to 403 responses.

We have configured global external authentication like this in the configmap (as per https://github.com/projectcontour/contour/blob/main/examples/global-external-auth/03-contour-config.yaml):
```
apiVersion: v1
data:
  contour.yaml: >
    globalExtAuth:
      extensionService: auth-server/auth-server
      failOpen: false
      responseTimeout: 2s
      ...
```

And our extension service is configured like this:
```
spec:
...
  timeoutPolicy:
    response: 2000ms
```

**What did you expect to happen:**
I expect a 2 second timeout for authorization requests.

**Anything else you would like to add:**
not at this time

**Environment:**

- Contour version: v1.30.0
- Kubernetes version: 1.31
- Kubernetes installer & version: EKS
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): bottlerocket
