### ISSUE TITLE
Regression in Contour v1.30.1

### ISSUE THREAD

**Issue by dprotaso** [projectcontour/contour#6829]
**What steps did you take and what happened:**
Knative has tests against Contour and when upgrading to v1.30.1 they fail

https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-extensions_net-contour/1149/integration-tests_net-contour_main/1870316455489179648

It seems like path based routing has stopped working?

**What did you expect to happen:**
Knative Contour tests Pass

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: v1.30.1
- Kubernetes version: (use `kubectl version`): v1.30.x
- Kubernetes installer & version: kind
- Cloud provider or hardware configuration: kind
- OS (e.g. from `/etc/os-release`):

**Comment by tsaarni** [comment]
It's challenging to pinpoint the issue from your test case logs without expertise in Knative and your test suite. Have you already checked the Gateway API related changes mentioned in the [1.30.0 release notes](https://github.com/projectcontour/contour/releases/tag/v1.30.0) to see if they impact Knative?

**Comment by dprotaso** [comment]
Those tests use httpproxy resources

**Comment by dprotaso** [comment]
I found the trivial example that demonstrates the failure

Install the contour-external and contour-internal files from my PR - https://github.com/knative-extensions/net-contour/pull/1149

This creates two deployments of contour on the cluster - one is private (clusterIp)  the other has a public load balancer.

Then install the following resources

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: fancy
  namespace: serving-tests
spec:
  externalName: envoy.contour-internal.svc.cluster.local
  ports:
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: workload
  namespace: serving-tests
  labels:
    app: workload
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: workload
  namespace: serving-tests
spec:
  selector:
    app: workload
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    projectcontour.io/ingress.class: contour-internal
  name: workload-internal
  namespace: serving-tests
spec:
  routes:
  - enableWebsockets: true
    permitInsecure: true
    requestHeadersPolicy: {}
    retryPolicy:
      count: 2
      retryOn:
      - cancelled
      - connect-failure
      - refused-stream
      - resource-exhausted
      - retriable-status-codes
      - reset
    services:
    - name: workload
      port: 80
      weight: 100
    timeoutPolicy:
      idle: infinity
      response: infinity
  virtualhost:
    fqdn: fancy.serving-tests.svc
---
apiVersion: v1
kind: Pod
metadata:
  name: proxy
  namespace: serving-tests
  labels:
    app: proxy
spec:
  containers:
  - name: proxy
    image: dprotaso/httpproxy-c117a6cb786f23513c0d819bd4449b1e
    ports:
    - containerPort: 8080
    env:
    - name: TARGET_HOST
      value: fancy.serving-tests.svc
    - name: PORT
      value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: serving-tests
spec:
  selector:
    app: proxy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    projectcontour.io/ingress.class: contour-external
  name: proxy
  namespace: serving-tests
spec:
  routes:
  - enableWebsockets: true
    permitInsecure: true
    requestHeadersPolicy: {}
    retryPolicy:
      count: 2
      retryOn:
      - cancelled
      - connect-failure
      - refused-stream
      - resource-exhausted
      - retriable-status-codes
      - reset
    services:
    - name: proxy
      port: 80
      weight: 100
    timeoutPolicy:
      idle: infinity
      response: infinity
  virtualhost:
    fqdn: blah.example.com
---

```

Curl the public ip using the host `blah.example.com`  and it will fail. What happens exactly is 

1. Contour-External will make a request to the backend `proxy` pod. 
2. Proxy Pod will then makes a request to `fancy.serving-tests.svc` (external name k8s service that fronts contour internal envoy svc)
3. Request fails at the internal envoy proxy pod


This worked prior to v1.30 - prior we were testing with 1.29.1 - install files for that are here

https://github.com/knative-extensions/net-contour/tree/7f0ee7377c46767e6e393c738e28f5a4b635f0dc/config/contour
