### ISSUE TITLE
Support basic host rewriting

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#69]
Support, probably via an annotation, an Ingress object which exists to redirect www.example.com to example.com (or vice versa)

This might look like, in yaml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: foo
  annotations:
    kubernetes.io/ingress.host-rewrite "example.com"
spec:
  rules:
    - host: www.example.com
            backend:
              serviceName: foo // ignored
              servicePort: http // ignored
```
