### ISSUE TITLE
How to print custom header in envoy logs

### ISSUE THREAD

**Issue by shenshanyoumu** [projectcontour/contour#6940]
**What question do you have?:**
I have follow wiki: https://projectcontour.io/docs/1.29/config/access-logging/ to print custom header using ""%REQ(x-iops-runbook-id)%\", but not works

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: 1.30.0
- Kubernetes version: (use `kubectl version`): 1.29
- Kubernetes installer & version: 1.29
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): linux

**Comment by tsaarni** [comment]
Can you show the configuration that failed?


Example config file:

```
$ cat contour.yaml
accesslog-format-string: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" \"%REQ(x-iops-runbook-id)%\"\n"
```

Apply the configuration and restart contour for the new configuration to take effect

```console
$ kubectl` -n projectcontour create configmap contour --from-file=contour.yaml --dry-run=client -o yaml | kubectl apply -f -
$ kubectl -n projectcontour delete pod -l app=contour --force
```

Make request with custom header

```console
$ http -v echoserver.127-0-0-101.nip.io x-iops-runbook-id:foo
GET / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Host: echoserver.127-0-0-101.nip.io
User-Agent: HTTPie/3.2.2
x-iops-runbook-id: foo

...
```

Check the access log from Envoy pod

```console
$ kubectl -n projectcontour logs -l app=envoy -c envoy -f
...
[2025-03-11T07:11:48.556Z] "GET / HTTP/1.1" 200 - 0 489 0 0 "172.20.0.1" "HTTPie/3.2.2" "e0888559-e25d-49b5-bf52-8742502385d8" "echoserver.127-0-0-101.nip.io" "10.244.1.6:8080" "foo"
```

**Comment by shenshanyoumu** [comment]
> Can you show the configuration that failed?
> 
> Example config file:
> 
> ```
> $ cat contour.yaml
> accesslog-format-string: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" \"%REQ(x-iops-runbook-id)%\"\n"
> ```
> 
> Apply the configuration and restart contour for the new configuration to take effect
> 
> $ kubectl -n projectcontour create configmap contour --from-file=contour.yaml --dry-run=client -o yaml | kubectl apply -f -
> $ kubectl -n projectcontour delete pod -l app=contour --force
> Make request with custom header
> 
> $ http -v echoserver.127-0-0-101.nip.io x-iops-runbook-id:foo
> GET / HTTP/1.1
> Accept: */*
> Accept-Encoding: gzip, deflate, br
> Connection: keep-alive
> Host: echoserver.127-0-0-101.nip.io
> User-Agent: HTTPie/3.2.2
> x-iops-runbook-id: foo
> 
> ...
> Check the access log from Envoy pod
> 
> $ kubectl -n projectcontour logs -l app=envoy -c envoy -f
> ...
> [2025-03-11T07:11:48.556Z] "GET / HTTP/1.1" 200 - 0 489 0 0 "172.20.0.1" "HTTPie/3.2.2" "e0888559-e25d-49b5-bf52-8742502385d8" "echoserver.127-0-0-101.nip.io" "10.244.1.6:8080" "foo"



below is my configMap:
```yaml
apiVersion: v1
data:
  contour.yaml: |-
    accesslog-format: envoy
    accesslog-format-string: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(x-iops-job-id)%\" \"%REQ(x-iops-runbook-id)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\"\n"
    disablePermitInsecure: false
    tls:
      fallback-certificate: {}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: contour
    app.kubernetes.io/instance: contour
    app.kubernetes.io/managed-by: contour-gateway-provisioner
    app.kubernetes.io/name: contour
    app.kubernetes.io/version: 1.30.0
  name: iopsv2-contour
  namespace: projectcontour
```

I restart contour deployment and envoy daemonset both, then I check logs not include two field "x-iops-job-id" and "x-iops-runbook-id"

**Comment by tsaarni** [comment]
Hmm the config seems to work for me 🤔 

I tried to apply the above config with minor modifications, but not touching the format string:

```console
$ kubectl apply -f - <<EOF
apiVersion: v1
data:
  contour.yaml: |-
    accesslog-format: envoy
    accesslog-format-string: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(x-iops-job-id)%\" \"%REQ(x-iops-runbook-id)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\"\n"
    disablePermitInsecure: false
    tls:
      fallback-certificate: {}
kind: ConfigMap
metadata:
  name: contour
  namespace: projectcontour
EOF
```

Restarted contour pods (restarting Envoys is not necessary)

```console
$ kubectl -n projectcontour delete pod -l app=contour --force
```

Then made a request with both headers

```console
$ http -v echoserver.127-0-0-101.nip.io x-iops-job-id:"my job id" x-iops-runbook-id:"my runbook id"
GET / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Host: echoserver.127-0-0-101.nip.io
User-Agent: HTTPie/3.2.2
x-iops-job-id: my job id
x-iops-runbook-id: my runbook id
```

And I did get "my job id" and "my runbook id" logged

```console
$ kubectl -n projectcontour logs -l app=envoy -c envoy -f
...
[2025-03-11T07:42:23.631Z] "GET / HTTP/1.1" 200 - 0 505 2 0 "172.20.0.1" "HTTPie/3.2.2" "c7364ea6-caeb-4c12-a341-4b141986ceaa" "my job id" "my runbook id" "echoserver.127-0-0-101.nip.io" "10.244.1.6:8080"
```

**Comment by shenshanyoumu** [comment]
> Hmm the config seems to work for me 🤔
> 
> I tried to apply the above config with minor modifications, but not touching the format string:
> 
> $ kubectl apply -f - <<EOF
> apiVersion: v1
> data:
>   contour.yaml: |-
>     accesslog-format: envoy
>     accesslog-format-string: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(x-iops-job-id)%\" \"%REQ(x-iops-runbook-id)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\"\n"
>     disablePermitInsecure: false
>     tls:
>       fallback-certificate: {}
> kind: ConfigMap
> metadata:
>   name: contour
>   namespace: projectcontour
> EOF
> Restarted contour pods (restarting Envoys is not necessary)
> 
> $ kubectl -n projectcontour delete pod -l app=contour --force
> Then made a request with both headers
> 
> $ http -v echoserver.127-0-0-101.nip.io x-iops-job-id:"my job id" x-iops-runbook-id:"my runbook id"
> GET / HTTP/1.1
> Accept: */*
> Accept-Encoding: gzip, deflate, br
> Connection: keep-alive
> Host: echoserver.127-0-0-101.nip.io
> User-Agent: HTTPie/3.2.2
> x-iops-job-id: my job id
> x-iops-runbook-id: my runbook id
> And I did get "my job id" and "my runbook id" logged
> 
> $ kubectl -n projectcontour logs -l app=envoy -c envoy -f
> ...
> [2025-03-11T07:42:23.631Z] "GET / HTTP/1.1" 200 - 0 505 2 0 "172.20.0.1" "HTTPie/3.2.2" "c7364ea6-caeb-4c12-a341-4b141986ceaa" "my job id" "my runbook id" "echoserver.127-0-0-101.nip.io" "10.244.1.6:8080"


ohh, anyway thanks for your double-confirm, I will check again

**Comment by shenshanyoumu** [comment]
> Hmm the config seems to work for me 🤔
> 
> I tried to apply the above config with minor modifications, but not touching the format string:
> 
> $ kubectl apply -f - <<EOF
> apiVersion: v1
> data:
>   contour.yaml: |-
>     accesslog-format: envoy
>     accesslog-format-string: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(x-iops-job-id)%\" \"%REQ(x-iops-runbook-id)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\"\n"
>     disablePermitInsecure: false
>     tls:
>       fallback-certificate: {}
> kind: ConfigMap
> metadata:
>   name: contour
>   namespace: projectcontour
> EOF
> Restarted contour pods (restarting Envoys is not necessary)
> 
> $ kubectl -n projectcontour delete pod -l app=contour --force
> Then made a request with both headers
> 
> $ http -v echoserver.127-0-0-101.nip.io x-iops-job-id:"my job id" x-iops-runbook-id:"my runbook id"
> GET / HTTP/1.1
> Accept: */*
> Accept-Encoding: gzip, deflate, br
> Connection: keep-alive
> Host: echoserver.127-0-0-101.nip.io
> User-Agent: HTTPie/3.2.2
> x-iops-job-id: my job id
> x-iops-runbook-id: my runbook id
> And I did get "my job id" and "my runbook id" logged
> 
> $ kubectl -n projectcontour logs -l app=envoy -c envoy -f
> ...
> [2025-03-11T07:42:23.631Z] "GET / HTTP/1.1" 200 - 0 505 2 0 "172.20.0.1" "HTTPie/3.2.2" "c7364ea6-caeb-4c12-a341-4b141986ceaa" "my job id" "my runbook id" "echoserver.127-0-0-101.nip.io" "10.244.1.6:8080"


it works if I install contour using helm, but not works using contour-gateway-provisioner as wiki mentioned: https://projectcontour.io/getting-started/

**Comment by tsaarni** [comment]
With gateway provisioner Contour is not configured via config file (in ConfigMap) anymore.  Here is an example how to use it:

```yaml
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: mygatewayclass
spec:
  controllerName: projectcontour.io/gateway-controller
  parametersRef:
    group: projectcontour.io
    kind: ContourDeployment
    namespace: projectcontour
    name: contour
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: mygateway
  namespace: projectcontour
spec:
  gatewayClassName: mygatewayclass
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
---
kind: ContourDeployment
apiVersion: projectcontour.io/v1alpha1
metadata:
  namespace: projectcontour
  name: contour
spec:
  envoy:
    networkPublishing:
      type: NodePortService
  runtimeSettings:
    envoy:
      logging:
        accessLogFormatString: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(x-iops-job-id)%\" \"%REQ(x-iops-runbook-id)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\"\n"
```

You can see how this impacts the `ContourConfig` CRD created by the provisioner:

```
$ kubectl -n projectcontour get contourconfig contourconfig-mygateway -o yaml
apiVersion: projectcontour.io/v1alpha1
kind: ContourConfiguration
metadata:
  creationTimestamp: "2025-03-11T10:18:39Z"
  generation: 1
  labels:
    gateway.networking.k8s.io/gateway-name: mygateway
    projectcontour.io/owning-gateway-name: mygateway
  name: contourconfig-mygateway
  namespace: projectcontour
  resourceVersion: "1549"
  uid: 13dd0bae-2330-4ef0-94ad-6362e27c066d
spec:
  envoy:
    logging:
      accessLogFormatString: |
        [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(x-iops-job-id)%" "%REQ(x-iops-runbook-id)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%"
    service:
      name: envoy-mygateway
      namespace: projectcontour
  gateway:
    gatewayRef:
      name: mygateway
      namespace: projectcontour
```

And that provisioner has configured Contour to read this CRD

```
$ kubectl -n projectcontour describe deployments.apps contour-mygateway
...
    Command:
      contour
    Args:
      serve
      ...
      --contour-config-name=contourconfig-mygateway
...
```

https://projectcontour.io/docs/1.30/config/api/#projectcontour.io/v1alpha1.ContourDeployment
https://projectcontour.io/docs/1.30/config/api/#projectcontour.io/v1alpha1.ContourConfigurationSpec
