### ISSUE TITLE
Enabling Upgrade: derp HTTP header with annotations

### ISSUE THREAD

**Issue by santurini** [projectcontour/contour#6942]
I am using a service in my Kubernetes cluster which requires DERP upgrades to establish a connection with the server, otherwise it will fall back to websockets ([link](https://coder.com/docs/@v2.19.0/admin/monitoring/health-check#derp)).

It would be nice to be able to allow DERP upgrades via annotations the same as it is for websockets, for instance something like this:
```YAML
annotations:
  projectcontour.io/websocket-routes: "/"
  projectcontour.io/derp-routes: "/"
```

Is this already implemented? Is it possible in case to implement it? I'm not much an expert, therefore I'm asking.
