### ISSUE TITLE
replacePrefix applies to non-matching paths unexpectedly

### ISSUE THREAD

**Issue by danchulee** [projectcontour/contour#6981]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
We set up a root HTTPProxy that delegates requests matching a specific prefix to a child HTTPProxy, where pathRewritePolicy.replacePrefix is configured.

Root
``` yaml
includes:
  - conditions:
      - prefix: /app/v1/docs/
    name: docs-backend-delegate
    namespace: default
routes:
  - conditions:
      - prefix: /
    services:
      - name: frontend-service
        port: 80
```

Child
``` yaml
routes:
  - services:
      - name: docs-backend-service
        port: 80
    pathRewritePolicy:
      replacePrefix:
        - prefix: /app/v1/docs/
          replacement: /v1/
```

With this setup:
	•	A request to /app/v1/docs/page is correctly delegated and rewritten to /v1/page.
	•	Unexpectedly, a request to /app/v1/docsXyz/page is also delegated and rewritten to /v1Xyz/page.

The second request should not match the prefix /app/v1/docs/, but it is being rewritten as if it did.

**What did you expect to happen:**

Only requests that exactly match the configured prefix /app/v1/docs/ should be rewritten.
Requests like /app/v1/docsXyz/page should not trigger delegation or path rewriting.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: 1.24.4
- Kubernetes version: (use `kubectl version`): 1.30
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):
