### ISSUE TITLE
Support adding / removing headers

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#70]
Add support for adding / removing headers at the Ingress, namespace, and default level

**Comment by drobinson123** [comment]
I'm interested in implementing ingress level support. Is this annotation format acceptable?

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example
  annotations:
    contour.heptio.com/response-headers-to-add: |
      Strict-Transport-Security "max-age=31536000; includeSubDomains"
      Public-Key-Pins: max-age=2592000; pin-sha256="E9CZ9INDbd+2eRQozYqqbQ2yXLVKB9+xcprMF+44U1g="
    contour.heptio.com/response-headers-to-remove: |
      X-Powered-By
spec:
  ...
```

**Comment by davecheney** [comment]
Thanks for offering to work on this. My initial reaction to the annotation syntax is it’s pretty ugly, yaml embedded in annotations is quite verbose and not something people are going to get right first time. 

One way around this might be to encode the header name in the annotation key, ie

contour.heptio.com/add-header-max-age: “...”

Where add-header- is a known prefix and there is a form for converting the suffix into a http header. This should work as http headers are not case sensitive. 

The other question is should this be per ingress or per route. I can see an argument for per route.

**Comment by drobinson123** [comment]
Encoding the header in the annotation will do, I have no preference.

Headers are appended to requests/responses in [a specific order](https://www.envoyproxy.io/docs/envoy/v1.6.0/configuration/http_conn_man/headers#config-http-conn-man-headers-custom-request-headers), so we may be able to do both ingress and route. I'll experiment and see how it could work.

One other question, I assume we only care about response headers? I don't have any use-cases for adding headers to requests.

**Comment by davecheney** [comment]
I see the need for this, but tbh I’m turned off by how ugly this will be to fit into the ingress object.

**Comment by zxvdr** [comment]
@davecheney, can you please provide some guidance regarding the annotation format? Unless I'm mistaken, the format I used in https://github.com/heptio/contour/pull/408 is the format [you suggested](https://github.com/heptio/contour/issues/70#issuecomment-387575336).

**Comment by kunickiaj** [comment]
If you're using contour for TLS termination x-forwarded-proto is needed in many cases -- couldn't find a way to set that.

**Comment by kellyaa** [comment]
+1 on wanting to see this happen. Right now I have a need to customize the `Host` header for route when proxying a request.

**Comment by davecheney** [comment]
Here's a design I'm thinking of
```
spec:
  routes:
    prefix: /foo
      headers:
        add:
        - name: "x-request-id"
           value: "fixed value"
        - name: "x-something"
           value: "another fixed value"
       remove:
       - name: "Date"
       - name: "ETag"
```
