### ISSUE TITLE
Support selectors as a way to identify backend services in IngressRoute

### ISSUE THREAD

**Issue by alexbrand** [projectcontour/contour#788]
Most resources in Kubernetes use selectors to establish a relationship/ownership. For example, services use selectors to determine which Pods are part of the service. Deployments, ReplicaSets, DaemonSets, etc also use selectors.

Given that this pattern exists in Kubernetes, I am wondering if it makes sense to support selectors in the IngressRoute resource to identify backend services:

```
# ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic
spec:
  rules:
  - host: foo-basic.bar.com
    http:
      paths:
      - backend:
          serviceSelector: ## <--- selector here
            app: my-app
            tier: frontend
          servicePort: 80
```

One use case that comes to mind is gimbal. Instead of having to list all the services across all the backends discovered, I could use a label selector to specify my backends using the labels that are automatically added by the gimbal discovery system.
