### ISSUE TITLE
prefixRewrite includes does not strip slash from prefix

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#899]
Report from Slack, 
```
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata: 
  labels:
    app: test
  name: test
  namespace: default
spec: 
  virtualhost:
    fqdn: test.local
  routes: 
    - match: /routeapp
      prefixRewrite: "/"
      services: 
        - name: routeapp
          port: 80
```
Requests to `/routeapp/test` get rewritten as `//test` not `/test`

**Comment by neeseius** [comment]
I brought this to attention. Looks like changing "/routeapp" to "/routeapp/" fixes the issue.

**Comment by davecheney** [comment]
I'm not able to reproduce the problem you reported. Without a way to reproduce this, I cannot verify that I have fixed the bug.

**Comment by gaelleacas** [comment]
Hi :) 

I would like to add an exemple that reproduce this issue with prefix path : 
I use  nodejs app with express routing:
  - expose my app to http://main.local/myapp 
  - A route is set to http://main.local/myapp/myroute

```
const express = require('express');
const app = express();
app.get('/', (req, res) => {
  res.setHeader("Content-Type", "text/html");
  res.status(200).send('Hello World from root');
});

app.get('/myroute', (req, res) => {
  res.setHeader('Content-Type', 'text/plain');
  res.status(200).send('Hello World from route /myroute');
});
app.listen(process.env.PORT || 8080);
```

Deploy & service: 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynodeapp
  labels:
    app: mynodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynodeapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: mynodeapp
    spec:
      containers:
      - name: mynodeapp
        image: docker.io/khaly/mynodeapp:v1
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mynodeapp
  labels:
    app: mynodeap
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: mynodeapp
```
Ingressroute with prefixRewrite :

```
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: myingress
  labels:
    app: myingress
spec:
  virtualhost:
    fqdn: main.local
  routes:
  - match: /myapp
    prefixRewrite: "/"
    services:
    - name: mynodeapp
      port: 80
```

With this config if I curl http://main.local/myapp/myroute I have :
 ```
$ curl http://main.local/myapp/myroute

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET //myroute</pre>
</body>
</html>
```
If I change the ingressroute  route match config
- match: /myapp -> - match: /myapp/ like this :
```
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: myingress
  labels:
    app: myingress
spec:
  virtualhost:
    fqdn: main.local
  routes:
  - match: /myapp/ 
    prefixRewrite: "/"
    services:
    - name: mynodeapp
      port: 80
```
It work : 
```
$ curl http://main.local/myapp/myroute
Hello World from route /myroute
```

You can find the code of my app [here](https://github.com/gaelleacas/contour-prefix)

Hope it will help you to solve :)
